<?php
    $_h = array(
        'title'   => 'about',
        'vars'    => array('user'  => $me,
                           'guest' => $guest,
                           'feed'  => array('type' => null, 'id' => null, 'inside' => 0), 
                           'events' => $events ? $events : array()
                            ),
        'guest'   => $guest);
    include(HEADER);
?>
    
    <div id="content">
        <div class="text">
            <p class="callout">We’re a bunch of guys who wanted a new way to do social communication.</p>
            <p>We know that there are a lot of solutions available today, but the problem with them is that they’re either too limited, too complex or too slow. Plus, they also rely on weird metaphors that don’t really fit in real life situations.</p>

            <p>We wanted a real-time solution that isn’t overly complex. We have lots of friends to catch up on, and a lot of people to communicate with—and we bet that you do to!.</p>
            <p>So we decided to build Tap: a fast, real-time communication tool that’s simple enough for everyone to use.</p>

            <h2>Team</h2>

            <p>Taso Du Val (taso) - Founder</p>

            <p>Andrew Korzhuev (andrew) - Lead Back-End Engineer / Front-End Engineer</p>
            
            <p>Leandro Ardissone (leandro) - Back-End Engineer / Front-End Engineer</p>

            <p>Juani Ruiz Echazu (juani) - Creative Director / Designer</p>
        </div>
    </div><!--content-->

<?php
    include(FOOTER);
?>
