<?php
$res = $_t['edit_profile'];
$fname = $res['fname'];
$lname = $res['lname'];
$uname = $_SESSION['uname'];
$email = $res['email'];
$pic = $res['pic_180'];
$country = $res['country'];
$state = $res['state'];
$region = $res['region'];
$town = $res['town'];
$lang = $res['lang'];

$stat = $_t['stats'];
$message_count = $stat['message_count'];
$response_count = $stat['response_count'];
$group_count = $stat['group_count'];
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11153159-1");
pageTracker._trackPageview();
} catch(err) {}</script>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>tap - alpha</title>

<link rel="stylesheet" href="/views/style_sheets/group_manage.css" type="text/css" >
<link rel="stylesheet" href="/views/style_sheets/profile.css" type="text/css" >


<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="icon" href="images/favicon.ico" type="image/x-icon" />

<!--[if lt IE 7]>
        <script type="text/javascript" src="js/unitpngfix.js"></script>
<![endif]-->

<script src="/views/javascript/mootools-1.2.3-core-yc.js" type="text/javascript"></script>
<script src="/views/javascript/mootools-1.2.3.1-more.js" type="text/javascript" charset="utf-8"></script>
<script src="/views/javascript/mootools-tap.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="/views/javascript/mpmetrics.js"></script>
<script type="text/javascript">try { mpmetrics.init('<?= METRIC_KEY ?>');} catch(err) { alert(err) }</script>
<script type="text/javascript">
Tap = window.Tap || {};
Tap.Vars = {
	country: "<?= $country ?>",
	region: "<?= $region ?>",
	state: "<?= $state ?>",
	town: "<?= $town ?>",
	lang: "<?= $lang ?>"
};
</script>
<script type="text/javascript" charset="utf-8">
Tap.Profile = {

	init: function(){
		var self = this;
		var body = $(document.body);
		$('gr-create-success').set('tween', {duration: 3000}).fade('hide');
		$('flagger').setStyle('display', 'none').addEvent('load', function(){
			this.setStyle('display', 'block');
		});

		var account_data = {
			fname: body.getElement('input[name="fname"]').store('passed', true),
			lname: body.getElement('input[name="lname"]').store('passed', true),
			email: body.getElement('input[name="email"]').store('passed', true),
			lang: body.getElement('select[name="language"]').store('passed', true),
			country: body.getElement('select[name="country"]').store('passed', true)
			/*
			state: body.getElement('select[name="state"]').store('passed', true),
			region: body.getElement('select[name="region"]').store('passed', true),
			town: body.getElement('select[name="town"]').store('passed', true)
			*/
		};

		account_data.fname.addEvent('blur', this.checkFname.toHandler(this));
		account_data.lname.addEvent('blur', this.checkLname.toHandler(this));
		account_data.email.addEvent('blur', this.checkEmail.toHandler(this));
		// account_data.zip.addEvent('blur', this.checkZip.toHandler(this));

		var pass_data = {
			current: body.getElement('input[name="current"]'),
			newpass: body.getElement('input[name="newpass"]'),
			repeat: body.getElement('input[name="newpass_repeat"]')
		};

		pass_data.current.addEvent('blur', this.checkCurrent.toHandler(this));
		pass_data.newpass.addEvent('blur', this.checkNew.toHandler(this));
		pass_data.repeat.addEvent('blur', this.checkRepeat.toHandler(this));

		var tabs = body.getElements('.tab');
		var panels = body.getElements('.panel');
		tabs.addEvent('click', function(){
			panels.filter('.selected').removeClass('selected');
			tabs.filter('.on').removeClass('on');
			this.addClass('on');

			if (this.get('id') === 'account') {
				$('youraccount').addClass('selected');
				self.data = account_data;
			} else {
				$('passchange').addClass('selected');
				self.data = pass_data;
			}
		});
		tabs[0].fireEvent('click');

		$('saveprofile').addEvent('click', this.onProfileSave.toHandler(this));
		$('savepassword').addEvent('click', this.onPasswordSave.toHandler(this));
		$('pic-uploader').addEvent('change', this.uploadPic.toHandler(this));
		window.addEvent('uploaded', this.displayPic.bind(this));

		var country = account_data.country;
		/*
			state = account_data.state,
			region = account_data.region,
			town = account_data.town;
			state.getParent('h2').hide(); region.getParent('h2').hide(); town.getParent('h2').hide();
		*/
		country.addEvent('change', function(a, e){
			$('flagger').set('src', 'images/geo_pics/gif/' + this.get('value') + '.gif');
			/*
			state.empty().getParent('h2').hide();
			region.empty().getParent('h2').hide();
			town.empty().getParent('h2').hide();
			self.geo({
				type: 'state',
				key: this.get('value'),
				callback: (!e) ? null : function(select){
					if (Tap.Vars.state) {
						select.getElement('option[value="'+Tap.Vars.state+'"]').set('selected', 'selected');
						select.fireEvent('change', [{}, true]);
					}
				}
			});
			*/
		});
		/*
		state.addEvent('change', function(a, e){
			region.empty().getParent('h2').hide();
			town.empty().getParent('h2').hide();
			self.geo({
				type: 'region',
				key: this.get('value'),
				callback: (!e) ? null : function(select){
					if (Tap.Vars.region) {
						select.getElement('option[value="'+Tap.Vars.region+'"]').set('selected', 'selected');
						select.fireEvent('change', [{}, true]);
					}
				}
			});
		});
		region.addEvent('change', function(a, e){
			town.empty().getParent('h2').hide();
			self.geo({
				type: 'town',
				key: this.get('value'),
				state: state.get('value'),
				callback: (!e) ? null : function(select){
					if (Tap.Vars.region) {
						select.getElement('option[value="'+Tap.Vars.region+'"]').set('selected', 'selected');
						select.fireEvent('change', [{}, true]);
					}
				}
			});
		});
		*/

		if (Tap.Vars.country) {
			country.getElement('option[value="'+Tap.Vars.country+'"]').set('selected', 'selected');
		} else {
			country.getElement('option[value="us"]').set('selected', 'selected');
		}
		country.fireEvent('change', [{}, true]);

		if (!Tap.Vars.lang.isEmpty()) account_data.lang.getElement('option[value="'+Tap.Vars.lang+'"]').set('selected', 'selected');
	},

	geo: function(options){
		var self = this;
		var loader = $('geo-loader');
		var type_code = ({
			'state': 1,
			'region': 2,
			'town': 3
		})[options.type];
		new Request({
			url: 'AJAX/geo.php',
			data: (function(){
				return $extend({
					type: type_code,
					code: options.key
				}, options.state ? { state: options.state } : {});
			})(),
			onRequest: function(){
				$('geo-loader').set('text', 'Loading ' + options.type.capitalize() + 's').setStyle('display', 'block');
			},
			onSuccess: function(){
				$('geo-loader').setStyle('display', 'none');
				var response = JSON.decode(this.response.text);
				var select = $(document.body).getElement('select[name="' + options.type + '"]');
				select.empty();
				if (response.geo) {
					select.getParent('h2').show();
					for (var x = response.geo.reverse().length; x--; ) {
						var item = response.geo[x];
						new Element('option', {
							value: item.region,
							text: item.city
						}).inject(select);
					}
					if ($type(options.callback) == 'function') options.callback.apply(self, [select]);
				} else {
					$('geo-loader').set('text', 'Location Complete!').setStyle('display', 'block');
				}
			}
		}).send();
	},

	uploadPic: function(el){
		if (!el.get('value').test(/\.(gif|png|bmp|jpeg|jpg)$/i)) {
			return this.showError(el, 'You can only upload GIFs, PNGs, BMPs or JPEGs.');
		}
		this.removeError(el);
		this.uploading = true;
		el.getParent('form').submit();
		mpmetrics.track('update-pic', {});
	},

	displayPic: function(data){
		this.uploading = false;
		var pic = $('pic-uploader');
		if (data.success) {
			$('pic-preview').empty().adopt(new Element('img', {
				'src': ['/user_pics/', data.path].join('')
			}));
			this.pic = data.path;
			this.removeError(pic);
		} else {
			this.pic = null;
			this.showError(pic, data.error);
		}
	},

	checkFname: function(el){
		if (el.isEmpty() || !el.isAlpha()) {
			return this.showError(el, 'Please enter a proper firstname');
		}
		return this.removeError(el);
	},

	checkLname: function(el){
		if (el.isEmpty() || !el.isAlpha()) {
			return this.showError(el, 'Please enter a proper lastname');
		}
		return this.removeError(el);
	},

	checkEmail: function(el){
		if (el.isEmpty() || !el.isEmail()) {
			return this.showError(el, 'Please enter a valid email address.');
		}
		return this.removeError(el);
	},

	checkZip: function(el){
		if (el.isEmpty() || !el.isNum()) {
			return this.showError(el, 'Please enter a valid zip code.');
		}
		return this.removeError(el);
	},

	checkCurrent: function(el){
		if (el.isEmpty()) {
			return this.showError(el, 'Please enter your current password.');
		}
		return this.removeError(el);
	},

	checkNew: function(el){
		if (el.isEmpty() || !el.ofLength(6, 40)) {
			return this.showError(el, 'Passwords should be from 6 to 40 characters.');
		} else if (!el.isAlphaNum()) {
			return this.showError(el, 'You have invalid characters in your password.');
		}
		return this.removeError(el);
	},

	checkRepeat: function(el){
		if (el.isEmpty() || el.get('value') !== this.data.newpass.get('value')) {
			return this.showError(el, 'Please repeat your new password.')
		}
		return this.removeError(el);
	},

	showError: function(el, msg){
		var parent = el.getParent('h2');
		el.addClass('input-err').store('passed', false);
		parent.getElement('div.error-msg').set({
			text: msg,
			style: 'display: inline;'
		});
	},

	removeError: function(el){
		var parent = el.getParent('h2');
		el.removeClass('input-err').store('passed', true);
		parent.getElement('div.error-msg').set({
			text: '',
			style: 'display: none;'
		});
	},

	noErrors: function(){
		return !$H(this.data).getValues().map(function(item){
			return !!item.retrieve('passed');
		}).contains(false);
	},

	onProfileSave: function(_, e){
		var data = this.data;
		if (this.uploading) {
			arguments.callee.delay(3000, this, [_, e]);
			return null;
		}
		var send = {
			fname: data.fname.get('value'),
			lname: data.lname.get('value'),
			email: data.email.get('value'),
			lang: data.lang.get('value')
		};
		if (this.pic) $extend(send, { old_name: this.pic });
		if (!data.country.get('value').isEmpty()) send.country = data.country.get('value');
		// if (!data.state.get('value').isEmpty()) send.state = data.state.get('value');
		// if (!data.region.get('value').isEmpty()) send.region = data.region.get('value');
		// if (!data.town.get('value').isEmpty()) send.town = data.town.get('value');
		this.onSave(send, 'edit_profile', e);
		mpmetrics.track('update-profile', {});
	},

	onPasswordSave: function(_, e){
		var data = this.data;
		var send = {
			old_pass: data.current.get('value'),
			new_pass: data.newpass.get('value')
		};
		this.onSave(send, 'password_profile', e, function(){
			$$(data.current, data.newpass, data.newpass_repeat).set('value', '');
		});
		mpmetrics.track('update-password', {});
	},

	onSave: function(send, url, e, callback){
		var self = this;
		var data = this.data;
		if (this.noErrors()) {
			var req = new Request({
				'url': 'AJAX/' + url + '.php',
				'async': false,
				'data': send,
				onSuccess: function(){
					var response = JSON.decode(this.response.text);
					if (response && response.success) {
						$('gr-create-success').set('text', 'Your changes have been saved!').fade('show').highlight().fade('out');
						if ($type(callback) == 'function') callback.apply(self);
					} else {
						$('gr-create-success').set('text', 'There was an error with your request, please try again.').fade('show').highlight('#fdebeb').fade('out');
					}
				}
			});
			req.send();
		} else {
			$$($H(this.data).getValues().filter(function(item){
				return !item.retrieve('passed');
			})).fireEvent('blur', [e]);
		}
	}
};

window.addEvent('domready', Tap.Profile.init.bind(Tap.Profile));
</script>
</head>

<body>

	<? include(NEW_HEADER); ?>

	<div id="main">
		<div id="left-col">
			<div id="profile-tab">
				<div class="tab-in">Stats</div>
			</div>
			<div class="tab-list">
				<h2><span><?= $message_count ?></span> taps from you.</h2>
				<h2><span><?= $response_count ?></span> responses received.</h2>
				<h2><span><?= $group_count ?></span> groups joined.</h2>
			</div>
		</div>

		<div id="center-col">
			<div id="profile">
				<div id="profile-header">
					<h2 class="gr-title">My Profile</h2>
					<span class="tab on" id="account">Your Account</span>
					<span class="tab" id="pass">Password</span>
				</div>

				<div class="main-frame">
					<div id="youraccount" class="panel">
						<h1>Account</h1><hr class="hr2"/>
						<h2 class="in-title">
							Username: <input type="text" name="uname" disabled="disabled" value="<?= $uname ?>" />
							<div class="error-msg"></div>
						</h2>
						<h2 class="in-title">
							Email: <input type="text" name="email" value="<?= $email ?>" />
							<div class="error-msg"></div>
						</h2>
						<h2 class="in-title">
							Firstname: <input type="text" name="fname" value="<?= $fname ?>" />
							<div class="error-msg"></div>
						</h2>
						<h2 class="in-title">
							Lastname: <input type="text" name="lname" value="<?= $lname ?>" />
							<div class="error-msg"></div>
						</h2>
						<h2 class="in-title">
							Primary Language:
							<select name="language" style="margin-right:140px">
								<option value="English">English</option>
								<option value="Afrikaans">Afrikaans</option>
								<option value="Albanian">Albanian</option>
								<option value="Aragonese">Aragonese</option>
								<option value="Asturian">Asturian</option>
								<option value="Azeri">Azeri</option>
								<option value="Basque">Basque</option>
								<option value="Belarusian">Belarusian</option>
								<option value="Breton">Breton</option>
								<option value="Catalan">Catalan</option>
								<option value="Cebuano">Cebuano</option>
								<option value="Cornish">Cornish</option>
								<option value="Corsican">Corsican</option>
								<option value="Croatian">Croatian</option>
								<option value="Czech">Czech</option>
								<option value="Danish">Danish</option>
								<option value="Dutch">Dutch</option>
								<option value="English">English</option>
								<option value="Esperanto">Esperanto</option>
								<option value="Estonian">Estonian</option>
								<option value="Faroese">Faroese</option>
								<option value="Finnish">Finnish</option>
								<option value="French">French</option>
								<option value="Frisian">Frisian</option>
								<option value="Friulian">Friulian</option>
								<option value="Fula (Pulaar)">Fula (Pulaar)</option>
								<option value="Gaelic (Scottish)">Gaelic (Scottish)</option>
								<option value="Galician">Galician</option>
								<option value="German">German</option>
								<option value="Gikuyu">Gikuyu</option>
								<option value="Guaraní">Guaraní</option>
								<option value="Hausa">Hausa</option>
								<option value="Hawai'ian">Hawai'ian</option>
								<option value="Hungarian">Hungarian</option>
								<option value="Icelandic">Icelandic</option>
								<option value="Ido">Ido</option>
								<option value="Igbo">Igbo</option>
								<option value="Indonesian">Indonesian</option>
								<option value="Insubric">Insubric</option>
								<option value="Interlingua">Interlingua</option>
								<option value="Irish">Irish</option>
								<option value="Italian">Italian</option>
								<option value="Javanese">Javanese</option>
								<option value="Kikongo">Kikongo</option>
								<option value="Kinyarwanda">Kinyarwanda</option>
								<option value="Kirundi">Kirundi</option>
								<option value="Latin">Latin</option>
								<option value="Latvian">Latvian</option>
								<option value="Lingala">Lingala</option>
								<option value="Lithuanian">Lithuanian</option>
								<option value="Luganda">Luganda</option>
								<option value="Luxembourgish">Luxembourgish</option>
								<option value="Maori">Maori</option>
								<option value="Malay">Malay</option>
								<option value="Maltese">Maltese</option>
								<option value="Manx">Manx</option>
								<option value="Moldovan">Moldovan</option>
								<option value="Nahuatl (post Spanish Conquest)">Nahuatl (post Spanish Conquest)</option>
								<option value="Navaho or Navajo">Navaho or Navajo</option>
								<option value="Ndebele">Ndebele</option>
								<option value="Norwegian">Norwegian</option>
								<option value="Occitan">Occitan</option>
								<option value="Orobic">Orobic</option>
								<option value="Oromo">Oromo</option>
								<option value="Polish">Polish</option>
								<option value="Portuguese">Portuguese</option>
								<option value="Quechua">Quechua</option>
								<option value="Romanian">Romanian</option>
								<option value="Samoan">Samoan</option>
								<option value="Scots">Scots</option>
								<option value="Serbian">Serbian</option>
								<option value="Shona">Shona</option>
								<option value="Slovak">Slovak</option>
								<option value="Slovenian">Slovenian</option>
								<option value="Somali">Somali</option>
								<option value="Spanish">Spanish</option>
								<option value="Swahili">Swahili</option>
								<option value="Swedish">Swedish</option>
								<option value="Tagalog/Filipino">Tagalog/Filipino</option>
								<option value="Tahitian">Tahitian</option>
								<option value="Tatar">Tatar</option>
								<option value="Tongan">Tongan</option>
								<option value="Tswana">Tswana</option>
								<option value="Turkish">Turkish</option>
								<option value="Turoyo">Turoyo</option>
								<option value="Vietnamese">Vietnamese</option>
								<option value="Võro">Võro</option>
								<option value="Walloon">Walloon</option>
								<option value="Welsh">Welsh</option>
								<option value="Wolof">Wolof</option>
								<option value="Xhosa">Xhosa</option>
								<option value="Yoruba">Yoruba</option>
								<option value="Zulu">Zulu</option>
							</select>
							<div class="error-msg"></div>
						</h2>
						<br /><br />
						<h1>Location </h1><hr class="hr2"/>
						<h2 class="in-title">Country:
							<select name="country" style="margin-right:140px">
								<? foreach ( $_t['init_geo_data'] as $item): ?>
								<option
									value="<?= $item['abbr2'] ?>"
									style="background: url(images/geo_pics/gif/<?= strtolower($item['abbr2']) ?>.gif) no-repeat 3% center; padding: 5px; padding-left: 30px;">
									<?= $item['name'] ?>
								</option>
								<? endforeach; ?>
							</select>
							<img id="flagger" src="images/geo_pics/gif/<?= empty($item['country']) ? $item['country'] : 'af' ?>.gif" style="float:right; margin-top: 5px" />
						</h2>
						<!--
						<h2 class="in-title">State:
							<select name="state" style="margin-right:140px">
							</select>
						</h2>
						<h2 class="in-title">Region:
							<select name="region" style="margin-right:140px">
							</select>
						</h2>
						<h2 class="in-title">Town:
							<select name="town" style="margin-right:140px">
							</select>
						</h2>
						<h2 id="geo-loader" class="loader">Loading Next</h2>
						-->

						<h1>Picture </h1><hr class="hr2"/>
						<form enctype="multipart/form-data" action="/AJAX/profile_picture_upload.php" method="post" target="picture">
							<h2 class="in-title">
								<div id="pic-preview" style="display:inline; float:left; margin-right:20px">
									<img src="/user_pics/<?= $pic ?>" />
								</div>
								Change: <input id="pic-uploader" type="file" name="you-pic" value="" style="height: 22px" />
								<div class="error-msg"></div>
							</h2>
							<iframe
								name="picture"
								style="display:none;">
							</iframe>
						</form>

						<p id="profile-btns"><a href="#" id="saveprofile" class="save-btn"></a></p><br />

					</div>
					<div id="passchange" class="panel">
						<h1>Change your password</h1><hr class="hr1"/>
						<h2 class="in-title">
							Current password: <input type="password" name="current" maxlength="40" value="" />
							<div class="error-msg"></div>
						</h2>
						<h2 class="in-title">
							New password: <input type="password" name="newpass" maxlength="40" value="" />
							<div class="error-msg"></div>
						</h2>
						<h2 class="in-title">
							Repeat password: <input type="password" name="newpass_repeat" maxlength="40" value="" />
							<div class="error-msg"></div>
						</h2>

						<p id="profile-btns"><a href="#" id="savepassword" class="save-btn"></a></p><br />

					</div>
					<p id="gr-create-success" class="input-descr">Loading...</p>
					<div style="clear:both"></div>
				</div>
				<div class="main-frame-bottom"></div>
			</div>
		</div>

		<div id="right-col">
			<h1>Help and Tips</h1>
			<h2>Set your account info correctly.</h2>
			<p>Your account information is not only required, but it's also useful for your friends and contacts to locate you on tap. So make sure to input correct information.</p>
			<h2>Keep your password safe.</h2>
			<p>Weak passwords could easily be sniffed using special tools, so make sure you use stronger passwords. Mix letters and numbers, and add a few symbols from your keyboard.</p>

		</div>
	</div>

	<div id="footer"></div>

</body>
</html>
