<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Chatapist - Profile</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css" media="all">@import "views/style_sheets/home.css";</style>
</head>

<body>

<div id="container">
	
	<?php include(HEADER);?>
		
	<?php include(LEFT);?>
	
	<div id="account">
	
		<div id="account_header">Account Options</div>
	
		<div id="account_intro">
		
			<p>
			Welcome to your account options.  Here you can easily
			add, withdraw, or transfer money to other chatapists from your account.
			For any questoin, please visit the <a href="##">FAQ</a> that will be posted shortly. Enjoy.
			</p>
		
		</div>
		
		<div id="account_go_away"><a href="#">Click to not display this message.</a></div>
		
		<div id="account_balance">
			
			<span>Current Account Balance:</span> $100.00 USD
			
			<ul>
				<li><p><span class="note">Note:</span> You owe Diego24 $18.00 for help w/ Travel.  Click <a href="##">here</a> to pay this person now.</p></li>
				<li><p><span class="note">Note:</span> You owe Garman2 $1.00 for help w/ Music.  Click <a href="##">here</a> to pay this person now.</p></li>
				<li><p><span class="note">Note:</span> You owe aKa $10.00 for help w/ PHP.  Click <a href="##">here</a> to pay this person now.</p></li>
			</ul>

		</div>
		
		<div id="account_info">
		
		<h4>Please select one of the following:</h4>
		
		<ul>	
			<li><a href="##">Add money to account</a></li>
			<li><a href="##">Pay someone (Transfer money to another account)</a></li>
			<li><a href="##">Withdraw money from your account</a></li>
			<li>Manage credit cards (comming soon!)</li>
		</ul>
		
		</div>
	
	</div>
	
</div>

	<?php include(FOOTER);?>

</body>
</html>