<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Chatapist - Profile</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css" media="all">@import "views/style_sheets/home.css";</style>
</head>

<body>

<div id="container">
	
	<?php include(HEADER);?>
		
	<?php include(LEFT);?>
	
	<div id="personal_settings">
	
	
		<div id="personal_settings_header">Personal Settings</div>
	
			<div id="personal_settings_intro">
		
			<p>
			Welcome to your Personal Settings.  Your personal settings allow you to customize your privacy, your alerts, and
			your thresh-hold level.  Your thresh-hold level is the property that determines how credible a person must be
			in order for them to alert you.  (.i.e. Personal Thresh-Hold: 10, means the person must have a ranking of 10
			in order for you to get alerted.  Network Thresh-Hold: 10 means the persons Network Credibility Rating must be 10
			for you to receive alerts from them. This feature, unique to chatapist, are so new users who sign up don't spam you.
			</p>
		
		</div>
		
		<div id="rel_go_away"><a href="#">Click to not display this message.</a></div>

		<div id="personal_settings_form">
		
			<form action="_self" method="post">	
				<fieldset>
				<legend>Thresh-Hold Settings</legend>
				
					<ul id="thresh_hold_list">
						
						<li>
							<label for="personal_thresh_hold">Personal Ranking Thresh-Hold:</label>
							<input type="text" maxlength="3" value="9.2" id="personal_thresh_hold"></input>
						</li>
						
						<li>
							<label for="network_thresh_hold">Network Ranking Thresh-Hold:</label>
							<input type="text" maxlength="3" value="9.4" id="network_thresh_hold"></input>
						</li>
					
					</ul>
				
				</fieldset>
				
				
					
	<fieldset id="global_rel_settings">
	<legend>Global Relevancy Settings</legend>

		<ul>
			<li> <label for="name">Name:</label><input  type="text" class="textbox"  id="name" value="Give me pizza postings!"></input></li>
			<li> <label for="keywords">Keywords:</label><input  type="text" class="textbox" id="keywords" value="(i.e. Pizza,Sauce,Cook)"></input></li>
			<li> <label for="category">Category:</label><select id="category"><option></option></select></li>
			<li> <label for="language">Language:</label> <select id="language"><option></option></select></li>
			<li> <label for="country">Country:</label> <select id="country"><option></option></select></li>
			<li> <label for="state">State:</label> <select id="state"><option></option></select></li>
			<li> <label for="zipcode">Zipcode:</label><input type="text" class="textbox" id="zipcode" value="(i.e. 10522)"></input></li>
			<li> <label for="group">Group:</label> <select id="group"><option title="All">All</option></select></li>
			<li><a href="####" ><button id="global_rel_button" onclick="return false;" ><span id="button_content">Add Setting</span></button></a></li>
		</ul>
		
		
	
	</fieldset>
					
				
				<fieldset>
				<legend>Privacy Settings</legend>
				
					<ul id="privacy_settings">
					
						<li>
							<label id="make_private">Make Private:</label>
							
								<ul>
									<li> 
										<label>Account Information</label>
										<input type="checkbox" class="privacy_settings"></input>
									</li>
									 
									<li> 
										<label>You</label>
										<input type="checkbox" class="privacy_settings"></input>
									</li>
									
									<li> 
										<label>Personal Information</label>
										<input type="checkbox" class="privacy_settings"></input>
									</li>
									
									<li> 
										<label>Network</label>
										<input type="checkbox" class="privacy_settings"></input>
									</li>
									
								</ul>
								
						</li>
					
						
					</ul>
				
			
				</fieldset>
			
				
				<fieldset>
				<legend>Alert Settings</legend>
				
					<ul id="alert_settings">
					
						<li>
							<label id="alerts_enabled">Enabled Alerts:</label>
							
								<ul>
									<li> 
										<label>MSN</label>
										<input type="checkbox" class="privacy_settings"></input>
									</li>
									 
									<li> 
										<label>AIM</label>
										<input type="checkbox" class="privacy_settings"></input>
									</li>
									
									<li> 
										<label>Gtalk</label>
										<input type="checkbox" class="privacy_settings"></input>
									</li>
									
									<li> 
										<label>Yahoo! Messanger</label>
										<input type="checkbox" class="privacy_settings"></input>
									</li>
									
									<li> 
										<label>IRC (Freenode)</label>
										<input type="checkbox" class="privacy_settings"></input>
									</li>
									
								</ul>
								
						</li>
					
						
					</ul>
								
				</fieldset>
				
				<fieldset id="personal_submit_fieldset">
					<button id="personal_submit_button"><span id="personal_submit_span">Submit</span></button>
				</fieldset>

				
			</form>
		
		</div>
		
		
		
	</div>		
		
</div>

	<?php include(FOOTER);?>

</body>
</html>