<?php
    $_h = array(
        'title'   => $group['name'],
        'scripts' => array('tap.js', 'search.js', 'modal.js'),
        'styles'  => array('roar.css', 'modal.css'),
        'vars'    => array('user' => $me),
        'guest'   => $guest);
    include(HEADER);
?>    
    <div id="content">
    	
        <div id="left">
            <?php
                $_f = array(
                    'feed'       => $feed,
                    'name'       => $group['name'],
                    'show_reply' => !$guest,
                    'hide_group_icon' => true
                );
                include(FEED);
            ?>        
        </div><!--left-->

        <?php
            $_s = array(
                'circle'  => $circle,
                'members' => $members
            );
            include(SIDEBAR);
        ?>
        
    </div><!--content-->
    
<?php
    include(FOOTER);
?>
