<?php
    $_h = array(
        'title'   => $circle['name'],
        'scripts' => array('main.js', 'push.js', 'search.js', 'modal.js', 'feed.js'),
        'styles'  => array('roar.css', 'modal.css'),
        'vars'    => array('user'  => $me,
                           'guest' => $guest,
                           'feed'  => array('type' => 'group', 'id' => $circle['id'], 'inside' => 1),
                           'comet' => array('groups' => array($circle['id']))),
        'guest'   => $guest);
    include(HEADER);
?>    
    <div id="content">
    	
        <div id="left">
            <?php
                $_f = array(
                    'feed'       => $feed,
                    'name'       => $circle['name'],
                    'show_reply' => !$guest,
                    'hide_group_icon' => true,
                    'show_inside' => true,
                    'status'     => $circle['status']
                );
                include(FEED);
            ?>        
        </div><!--left-->

        <?php
            $_s = array(
                'circle'  => $circle,
                'members' => $members,
                'state'   => $state,
                'moderator' => $moderator
            );
            include(SIDEBAR);
        ?>
        
    </div><!--content-->
    
<?php
    include(FOOTER);
?>
