<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Content-Language" content="en-us" />
	<meta name="robots" content="noodp" />
	<meta name="image-toolbar" content="no" />
	<meta name="copyright" content="Copyright (c) 2009 TAP" />
	<meta name="description" content="TAP communication platform" />
	<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />
	<title>tap</title>
	<link rel="stylesheet" href="/views/styles/global.css" type="text/css" />
	<link rel="stylesheet" href="/views/styles/public.css" type="text/css" />
	<script type="text/javascript" src="/views/scripts/mootools-core.js"></script>
	<script type="text/javascript" src="/views/scripts/mootools-more.js"></script>
	<script type="text/javascript" src="/views/scripts/login.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
	<script type="text/javascript" src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/FeatureLoader.js.php"></script>
        <script src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/XdCommReceiver.js" type="text/javascript"></script>
</head>
<body>
	<div id="wrapper">

		<?include(HEADER_LOGOUT)?>

		<div id="main">

			<div id="sidebar">
				
				<div id="inviter" class="section container">
					<h2>Want to start tapping?</h2>
					<p>Tap is invite only right now. If you want to be one of our early tappers, <a href="/">signup for an invite</a>.</p>
				</div>
				<?include(LOGIN);?>	
			</div>

			<div id="content">
				
				<div class="section">
					<div class="header">
						<h2 class="header-title">
							<span class="title">:)</span>
						</h2>
						contact us
					</div>
					<div class="body">
						<div class="full info">
							<p class="callout">Want to tell us what you think about tap? Want to share some ideas or suggestions? Got some questions that need to be answered? Then send us a message!</p>

							<h2>Tap Us!</h2>
							<p>If you're on Tap, you could send us a tap at <strong>Support</strong>, for any questions, comments or suggestions.</p>

							<h2>Email Us</h2>
							<p>If you're an old-fashioned email kind of person, then don't hesitate to send us one at our official address: <strong>info-nospm@tap.info</strong> (just make sure to take out the 'nospm' part).</p>
						</div>
					</div>
				</div>
			</div>

		</div>
		
		<div class="clarity"></div>
		
		<div id="footer">
			<strong>tap &copy; 2010.</strong>
			<span class="nav">
				<a href="/" class="current">home</a>
				<a href="/what">what's tap?</a>
				<a href="/about">about us</a>
				<a href="/devs">developers</a>
				<a href="/contact">contact</a>
			</span>
		</div>
	</div>
	
	<?include(JAVASCRIPT_TEMPLATES)?>

<script type="text/javascript">
var _gaq = _gaq || [];
 _gaq.push(['_setAccount', 'UA-11153159-1']);
 _gaq.push(['_trackPageview']);

 (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
 })();
</script>
		<?include(FBCONNECT_BOTTOM)?>
</body>
</html>
