<!doctype html>
<html>
<head>
	<? $tpl_title = "Contact";
	include(OK_HEADER) ?>
	<script type="text/javascript" src="/views/scripts/tap.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
</head>
<body>
	<div id="wrapper">

		<?include(OK_TOPBAR)?>

		<div id="main">

			<? include(OK_SIDEBAR) ?>
	
			<div id="content">
				
				<div class="section">
					<div class="header header-non">
						<h2 class="header-title">
							<span class="title">:)</span>
						</h2>
						contact us
					</div>
					<div class="body">
						<div class="full info">
							<p class="callout">Want to tell us what you think about tap? Want to share some ideas or suggestions? Got some questions that need to be answered? Then send us a message!</p>

							<h2>Tap Us!</h2>
							<p>If you're on Tap, you could send us a tap at <strong>Support</strong>, for any questions, comments or suggestions.</p>

							<h2>Email Us</h2>
							<p>If you're an old-fashioned email kind of person, then don't hesitate to send us one at our official address: <strong>info-nospm@tap.info</strong> (just make sure to take out the 'nospm' part).</p>
						</div>
					</div>
				</div>
			</div>

		</div>
		
		<div class="clarity"></div>

			<?include(OK_FOOTER)?>		

	</div>
	
	<?include(JAVASCRIPT_TEMPLATES)?>

<script type="text/javascript">
var _gaq = _gaq || [];
 _gaq.push(['_setAccount', 'UA-11153159-1']);
 _gaq.push(['_trackPageview']);

 (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
 })();
</script>
		<?include(FBCONNECT_BOTTOM)?>
</body>
</html>
