<?php
$logged = (!empty($_SESSION['uid']));
?>
<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Content-Language" content="en-us" />
	<meta name="robots" content="noodp" />
	<meta name="image-toolbar" content="no" />
	<meta name="copyright" content="Copyright (c) 2009 TAP" />
	<meta name="description" content="TAP communication platform" />
	<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />
	<meta name="uid" content="<?= $_t['pcid'] ?>" />
	<meta name="uname" content="<?= $_SESSION['uname'] ?>" />
	<title>tap</title>
	<link rel="stylesheet" href="/views/styles/global.css" type="text/css" />
	<script type="text/javascript" src="/views/scripts/mootools-core.js"></script>
	<script type="text/javascript" src="/views/scripts/mootools-more.js"></script>
	<script type="text/javascript" src="/views/scripts/tap.js"></script>
	<script type="text/javascript" src="/views/scripts/creategroup.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
</head>
<body>
	<div id="wrapper">

		<?include(HEADER)?>

		<div id="main">

			<div id="sidebar">

				<?php if ($logged): ?>
	                                <?include(YOU)?>
				<?php endif; ?>				
			</div>

			<div id="content">
				
				<div class="section">
					<div class="header">
						<a id="newtaps" href="" class="floater"></a>
						<h2 class="header-title">
							<img src="/images/flat/loader.gif" />
							<span class="title">groups</span>
						</h2>
						<span class="stream-name">Create a Group <a href="/groups">back to your groups</a></span>
					</div>
					<div class="body">
						<div id="create-group" class="form">
							<p>Fill in all the details below and then hit done to create a new group. Don't forget to invite your contacts after creating your group!</p>
							<label for="name">
								name 
								<span class="help">the name of your group</span>
								<span class="error"></span>
							</label>
							<input name="name" type="text" class="basic full" />
							
							<label for="symbol">
								symbol 
								<span class="help">this will be used to identify your group</span>
								<span class="error"></span>
							</label>
							<input name="symbol" type="text" class="basic full" />
							
							<label for="focus">
								focus 
								<span class="help">the areas of interest of your group; at least 3, separated by commas</span>
								<span class="error"></span>
							</label>
							<input name="focus" type="text" class="basic full" />
							
							<label for="desc">
								description 
								<span class="help">what's your group about? describe it in 20 to 240 characters</span>
								<span class="error"></span>
							</label>
							<input name="desc" type="text" class="basic full" />
							
							<form name="picuploader" action="/AJAX/group_picture_upload.php" enctype="multipart/form-data" method="post" target="picture">
								<label for="file">
									picture 
									<span class="help">upload a picture for your group</span>
									<span class="error"></span>
								</label>
								<input id="group-pic" name="gr-pic" type="file" class="basic full"/>
								<img id="preview" src="" class="blank" />
								<iframe name="picture" style="display:none;"> </iframe>
							</form>
							
							<div class="buttons">
								<button class="action">create your group</button> or <a href="/groups">cancel</a>
							</div>
						</div>
					</div>
				</div>

			</div>

		</div>

		<div class="clarity"></div>

		<div id="footer">
			<strong>tap &copy; 2010.</strong>
			<span class="nav">
				<a href="/">home</a>
				<a href="/groups">groups</a>
				<a href="/people">people</a>
				<a href="/settings">settings</a>
				<a href="/?logout=true">logout</a>
			</span>
		</div>
		
	</div>
	<?include(JAVASCRIPT_TEMPLATES)?>	
</body>
</html>
