<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Content-Language" content="en-us" />
	<meta name="robots" content="noodp" />
	<meta name="image-toolbar" content="no" />
	<meta name="copyright" content="Copyright (c) 2009 TAP" />
	<meta name="description" content="TAP communication platform" />
	<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />
	<title>tap</title>
	<link rel="stylesheet" href="/views/styles/global.css" type="text/css" />
	<link rel="stylesheet" href="/views/styles/public.css" type="text/css" />
	<script type="text/javascript" src="/views/scripts/mootools-core.js"></script>
	<script type="text/javascript" src="/views/scripts/mootools-more.js"></script>
	<script type="text/javascript" src="/views/scripts/login.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
</head>
<body>
	<div id="wrapper">

		<?include(HEADER_LOGOUT)?>

		<div id="main">

			<div id="sidebar">
				
				<div id="inviter" class="section container">
					<h2>Want to start tapping?</h2>
					<p>Tap is invite only right now. If you want to be one of our early tappers, <a href="/">signup for an invite</a>.</p>
				</div>
				<?include(LOGIN);?>	
			</div>

			<div id="content">
				
				<div class="section">
					<div class="header">
						<h2 class="header-title">
							<span class="title">&lt;/&gt;</span>
						</h2>
						developers
					</div>
					<div class="body">
						<div class="full info">
							<p class="callout">Hey, we're developers too, and we know just how exciting it is to integrate new technologies!</p>
							<p>That's why we're planning to launch an API for Tap in the near future, so that other developers could also join in on the fun, and change the way we communicate.</p>
							<p>Right now our focus is getting the basics up and running so we'll all be sure that everyone's apps run just fine. But eventually, we'll open Tap to third-party developers via an API so that you'll be able to make your own apps that could integrate with our application.</p>
							<p>If you're interested in developing for or integrating Tap, then don't hesitate to drop us a message!</p>
						</div>
					</div>
				</div>
			</div>

		</div>
		
		<div class="clarity"></div>
		
		<div id="footer">
			<strong>tap &copy; 2010.</strong>
			<span class="nav">
				<a href="/" class="current">home</a>
				<a href="/what">what's tap?</a>
				<a href="/about">about us</a>
				<a href="/devs">developers</a>
				<a href="/contact">contact</a>
			</span>
		</div>
	</div>
	
	<?include(JAVASCRIPT_TEMPLATES)?>
<script type="text/javascript">
var _gaq = _gaq || [];
 _gaq.push(['_setAccount', 'UA-11153159-1']);
 _gaq.push(['_trackPageview']);

 (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
 })();
</script>
</body>
</html>
