<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11153159-1");
pageTracker._trackPageview();
} catch(err) {}</script>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>tap - alpha</title>

<link rel="shortcut icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="views/style_sheets/group_manage.css" type="text/css" />
<link rel="stylesheet" href="views/style_sheets/homepage.css" type="text/css" />
<script type="text/javascript" src="views/javascript/mootools-1.2.3-core-yc.js"></script>
<script type="text/javascript" src="views/javascript/mootools-1.2.3.1-more.js"></script>
<script type="text/javascript" src="views/javascript/mootools-tap.js"></script>
<script type="text/javascript" src="http://mark.tap.info:8000/static/Orbited.js"></script>
<script type="text/javascript" src="views/javascript/tap.main.js"></script>
<style type="text/css">
div.section-body div.info {
	margin-left: 2px;
	margin-bottom: -1px;
	padding: 20px;
	font-size: 12px;
	border: 1px solid #D8D8D8;
}

div.info h1, div.info h2, div.info p, div.info ul {
	font-size: 12px;
	margin-bottom: 10px; }

div.info p.callout {
	font-size: 14px;
	font-weight: bold;
	margin-bottom: 20px;
}

div.info ul { 
	margin-bottom: 20px; }
	
div.info h1 { 
	color: #4F9CDF;
	font-size: 16px;
	font-weight: bold; }

div.info h2 { 
	font-size: 14px;
	margin-top: 20px;
	font-weight: bold; }
</style>


</head>

<body>

	<?php include(LOGOUT_HEADER); ?>

	<div id="main">

		<div id="right-col">
			<h1>What's This?</h1>
			<p>Tap allows you to connect with people around you and stay informed about topics you're interested in.  Use Tap to see what you and your friends are doing, what people around you are doing, and connect with link-minded individuals. Join Tap today!</p>
		</div>

		<div id="center-col">
			<div class="section">
				<div class="section-head">
					<h1>
						<span id="tap-feed-name">For Developers</span>
					</h1>
				</div>
				<div class="section-body">
					<div class="info">
						<p class="callout">Hey, we're developers too, and we know just how exciting it is to integrate new technologies!</p>
						<p>That's why we're planning to launch an API for Tap in the near future, so that other developers could also join in on the fun, and change the way we communicate.</p>
						<p>Right now our focus is getting the basics up and running so we'll all be sure that everyone's apps run just fine. But eventually, we'll open Tap to third-party developers via an API so that you'll be able to make your own apps that could integrate with our application.</p>
						<p>If you're interested in developing for or integrating Tap, then don't hesitate to drop us a message!</p>
					</div>
				</div>
			</div>
		</div>

		<div id="left-col">
			<div id="groups-tab">
				<div class="tab-in" style="color:#fff">Log in</div>
			</div>
			<div class="tab-list">
				<form id="login" action="<?=ROOT?>" method="POST">
					<label>Username</label>
						<input type="text" id="uname" name="uname" class="text" />
					<label>Password</label>
						<input type="password" id="pass" name="pass" class="text" />
					<br/>
					<input type="checkbox" checked="true" id="auto_login" name="auto_login" />
					<label class="in-form">Keep Me Logged In</label>
					<input type="submit" id="signin-submit" value="Sign In" />
				</form>
			</div>

			<div id="signup-tab">Sign-up
				<div id="signup-title">Its very easy<br />and it wont take you<br />more than 45 seconds.</div>
			</div>
			<div id="signup-form">
				<label>Username</label>
					<input type="text" name="user" class="text"/>
					<div class="guide"></div>
				<label>Full Name</label>
					<input type="text" name="name" class="text"/>
					<div class="guide"></div>
				<label>E-mail</label>
					<input type="text" name="email" class="text"/>
					<div class="guide"></div>
				<label>Password</label>
					<input type="password" name="pass" class="text"/>
					<div class="guide"></div>
				<label>Retype Password</label>
					<input type="password" name="passrepeat" class="text"/>
					<div class="guide"></div>
				<input type="submit" id="signup-submit" value="Sign me up!" />
			</div>
		</div>

	</div>

	<div id="footer">

	</div>

</body>
</html>
