<!doctype html>
<html>
<head>
	<? $tpl_title = "Developers";
	include(OK_HEADER); ?>
	<script type="text/javascript" src="/views/scripts/login.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
	<script type="text/javascript" src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/FeatureLoader.js.php"></script>
        <script src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/XdCommReceiver.js" type="text/javascript"></script>
</head>
<body>
	<div id="wrapper">

		<?include(OK_TOPBAR)?>

		<div id="main">

			<?include(OK_SIDEBAR)?>

			<div id="content">
				
				<div class="section">
					<div class="header header-non">
						<h2 class="header-title">
							<span class="title">&lt;/&gt;</span>
						</h2>
						developers
					</div>
					<div class="body">
						<div class="full info">
							<p class="callout">Hey, we're developers too, and we know just how exciting it is to integrate new technologies!</p>
							<p>That's why we're planning to launch an API for Tap in the near future, so that other developers could also join in on the fun, and change the way we communicate.</p>
							<p>Right now our focus is getting the basics up and running so we'll all be sure that everyone's apps run just fine. But eventually, we'll open Tap to third-party developers via an API so that you'll be able to make your own apps that could integrate with our application.</p>
							<p>If you're interested in developing for or integrating Tap, then don't hesitate to drop us a message!</p>
						</div>
					</div>
				</div>
			</div>

		</div>
		
		<div class="clarity"></div>
		
		<?include(OK_FOOTER)?>	
	

	</div>
	
	<?include(JAVASCRIPT_TEMPLATES)?>
<script type="text/javascript">
var _gaq = _gaq || [];
 _gaq.push(['_setAccount', 'UA-11153159-1']);
 _gaq.push(['_trackPageview']);

 (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
 })();
</script>
		<?include(FBCONNECT_BOTTOM)?>
</body>
</html>
