<!doctype html>
<html>
<head>

	<? $tpl_title ="Facebook suggestions";
	include(OK_HEADER)?>
	<script type="text/javascript" src="/views/scripts/tap.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>

</head>
<body>
	<div id="wrapper">

		<?include(OK_TOPBAR)?>

		<div id="main">

			<?include(OK_SIDEBAR)?>

			<div id="content">
				
				<div class="section">
					<div class="header header-non">
						<h2 class="header-title">
							<span class="title">F</span>
						</h2>
						Facebook
					</div>
					<div class="body">
						<div class="full info">
							 <?php var_dump($_t['fb']->getInterests()); ?>
                             <?php //echo $_t['fb']->logoutUrl; ?>
						</div>
					</div>
				</div>
			</div>

		</div>
		
		<div class="clarity"></div>
		<?include(OK_FOOTER)?>	
	

	</div>
	
	<?include(JAVASCRIPT_TEMPLATES)?>

<script type="text/javascript">
var _gaq = _gaq || [];
 _gaq.push(['_setAccount', 'UA-11153159-1']);
 _gaq.push(['_trackPageview']);

 (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
 })();
</script>
		<? // include(FBCONNECT_BOTTOM) ?>
</body>
</html>
