<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title><?=TITLE?> - Profile</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css" media="all">@import "views/style_sheets/home.css";</style>
<script type="text/javascript" src="views/javascript/tap_friend.js"></script>
</head>

<body>

<div id="container">
	
	<?php include(HEADER);?>
		
	<?php include(LEFT);?>
	
		<div id="friends">
		
			<div id="friends_header">Friends</div>
	<!--				<div id="friends_top_left_container">
			
			<div id="friends_top_contiainer">
					
							<span id="change_organize">Change Organization:</span>
							
							<div id="friends_show_organize">
								<h4>How you would like your friends organized?:</h4>
								
								<ul>
									<li><a href="#">Alphabetical Order</a></li>
									<li><a href="#####">Overall Ranking Order</a></li>
								</ul>
								
								<ul>
									<li><a href="####">Catagory Ranking Order</a></li>
									<li><a href="#####">Closest Vicinity Order</a></li>
								</ul>
								
							</div>
					</div>
			
					
			<div id="network_status">
			
				<ul>
					<li>Ranking: 9.8</li>
					<li>Network Ranking: 9.4</li>
					<li>Friends: 28</li>
					<li>Highest: 10</li>
				</ul>
			
			</div>
			
			</div>
	-->		

		<div class="friend_category">People who you have tap'd</div>

		<div>
		<? if($_t['html_0'] && $_t['html_0'] != '')foreach($_t['html_0'] as $v){echo $v;} else { echo "You have nobody on tap click <a href='people_search'>here</a> to find people to tap";}?>
		</div>

		<div class="friend_category">People who have you tap'd</div>
		<div>
		<? if($_t['html_1'] && $_t['html_1'] != '')foreach($_t['html_1'] as $v){echo $v;} else { echo "Have someone do something for me you";} ?>
		</div>
			

	
		
</div>

	<?php include(FOOTER);?>

</body>
</html>
