<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Chatapist - Profile</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css" media="all">@import "views/style_sheets/home.css";</style>
</head>

<body>

<div id="container">
	
	<?php include(HEADER);?>
		
	<?php include(LEFT);?>
	
	<div id="friends">
	
		<div id="friends_header">Friends</div>
	
		<div id="friends_organize">
		<h4>How you would like your friends organized:</h4>
		
		<ul>
			<li><a href="##*">Alphabetical Order</a></li>
			<li><a href="##*">Overall Ranking Order</a></li>
		</ul>
		
		<ul>
			<li><a href="##*">Catagory Ranking Order</a></li>
			<li><a href="##*">Closest Vicinity Order</a></li>
		</ul>
		
		</div>
		
		<div id="friends_intro">
		
			<p>
			Please chose a way to organize your friends list.  Whichever way you chose to organize them will be your default setting.
			You will be able to change them with ease by clicking on "Change Organization".
			</p>
			
		<div id="account_go_away"><a href="#">Click to not display this message.</a></div>
		</div>
	
</div>

	<?php include(FOOTER);?>

</body>
</html>