<?php
    $_h = array(
        'title'   => $circle['name'],
        'scripts' => array('validators.js', 'main.js', 'push.js', 'search.js', 'modal.js', 'feed.js', 'group_edit.js'),
        'styles'  => array('roar.css', 'modal.css'),
        'vars'    => array('user'  => $me,
                           'guest' => $guest,
                           'feed'  => array(),
                           'comet' => array()),
        'guest'   => $guest);
    include(HEADER);
?>    
    <div id="content">
    	
        <h1 class="wide">Manage circle</h1>
        
        <? if (!empty($pending)): ?>
        	<div id="add">
            	<label>pending members <small>these members need to be aproved before they can start browsing the circle</small></label>
                
                <ul>
                <? foreach ($pending as $u): ?>
                	<li>
                        <span><input type="checkbox" /></span>
                        <img
                            width="40"
                            src="<?=USER_PIC_REL?>medium_<?=$u['id']?>.jpg"
                            data-tiptitle="<?=$u['fname']?> <?=$u['lname']?>"
                            data-tipid="tip-pending-<?=$u['id']?>"
                        />
                        <a href="/user/<?=$u['uname']?>" class="view">view</a>
                    </li>
                <? endforeach; ?>
                    <div class="clear"></div>
                </ul>

                <input type="submit" class="accept" value="Accept members" />
                <input type="submit" class="reject" value="Reject members" />
                <div class="clear"></div>
            </div><!--add-->
        <? endif; ?>
    	
        <form id="edit">
        
        <div id="left">
        
			<label>title   <small>what will your circle be called?</small></label>
            <input type="text"
                   name="title" 
                   value="<?=$circle['name']?>"
                   class="required"
                   data-tipid="tip-input-title"
            />
            
            <label>symbol   <small>leave it for robots</small></label>
            <input type="text" disabled=""
                   name="symbol"
                   value="<?=$circle['symbol']?>"
                   class="groupDoesNotExists oldSymbol:'<?=$circle['symbol']?>'"
                   data-tipid="tip-input-symbol"
            />
            
            <label>description   <small>a brief explaination what this circle stands for</small></label>
            <textarea name="descr" 
                      class="maxLength:250"
                      data-tipid="tip-input-descr"
            /><?=$circle['descr']?></textarea>
                       
            <input type="submit" class="load" value="If you click that, you can not go back" />
                
        </div><!--left-->
        
        <div id="sidebar">
        	<label>circle type</label>
            <select name="type">
                <? foreach ($types as $val => $t): ?>
                    <option value="<?=$val?>" <?=($t == $circle['type'] ? ' selected' : '')?>><?=$t?></option>
                <? endforeach; ?>
            </select>
            
            <label>authentication type</label>
            <select name="auth">
                <? foreach ($auths as $val => $t): ?>
                    <option value="<?=$val?>" <?=($t == $circle['auth'] ? ' selected' : '')?>><?=$t?></option>
                <? endforeach; ?>
            </select>
            
            <span>secret <input type="checkbox" name="secret" <?=($circle['secret'] ? ' checked' : '')?>/></span>
                    
        </div><!--sidebar-->
        
        <div class="clear"></div>
        
        </form>
        
    </div><!--content-->
    
<?php
    include(FOOTER);
?>
