<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11153159-1");
pageTracker._trackPageview();
} catch(err) {}</script>

<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title><?=TITLE?> - Profile</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css" media="all">@import "<?=ROOT?>/views/style_sheets/home.css";</style>
    <script type="text/javascript">var ggid = <?php echo $_t['gid']; ?></script>
    <script type="text/javascript" src="..//views/javascript/edit_group.js"></script>
    
</head>

<body>

<div id="container">
	
	<?php include(HEADER);?>
		
	<?php include(LEFT);?>

	<?php
	
	$group_admins_result = $_t['group_admins_results'];
	$group_info_result = $_t['group_info_results'];

	 while($res = $group_info_result->fetch_assoc() ){
                        $gname = $res['gname'];
                        $focus = $res['focus'];
                        $descr = $res['descr'];
                        $pic_180_2 = $res['pic_180'];
                        $invite_only = $res['invite_only'];
                        $invite_priv = $res['invite_priv'];
                        $private = $res['private'];
                }

	?>	
	<div id="edit_profile">
	
		<div id="edit_profile_header">Edit Group</div>
	
		<div id="edit_profile_intro">
		
			<p>
			Here you can edit your profile!  Enjoy!
			</p>
		
		</div>
		
		<div id="account_go_away"><a href="#">Click to not display this message.</a></div>
		
		
		<div id="edit_profile_forms">
		
			<div id="edit_profile_left">
			<div id="active_edit">you</div>
			
			<ul id="profile_nav">
				<li><a href="#" onclick="show_edit('you'); return false;">Group Info</a></li>	
				<li><a href="#" onclick="show_edit('personal'); return false;">Admins</a></li>	
				<li><a href="#" onclick="show_edit('pic'); return false;">Picture</a></li>	
				<li><a href="#" onclick="show_edit('alerts'); return false;">Group Settings</a></li>	
			</ul>
			
		</div>
			
			<div id="edit_profile_right">
	
			
			<div id="div_edit_you">
			<div id="you_updated"></div>	
			<form id="edit_you_form" action="profile_edit" method="POST">
			<fieldset>
			<legend>You</legend>
			
				<ul>
					<li><label for="gname_input">Group Name</label><input type="text" id="gname_input" name="gname_input" value="<?=$gname?>" ></input></li>
					<li><label for="focus_input">Focus</label><input type="text" id="focus_input" name="focus_input" value="<?=$focus?>"></input></li>
					<li><label for="descr_input">Description</label><textarea type="text" id="descr_input" name="descr_input"><?=$descr?></textarea></li>
					<li><button type="submit" id="edit_submit_you" name="edit_submit_you" onclick="send_update('you'); return false;">Update Group Info</button></li>
				</ul>
			
			</fieldset>
			</form>
			</div>

			<div id="div_edit_alerts">
			<div id="alerts_updated"></div>	
			<form action="profile_edit" method="POST">
			<fieldset>
			<legend>Alerts</legend>
				<ul>
				
					<li><button type="submit" id="edit_submit_alerts" name="edit_submit_alerts" value="edit_submit">Update Alerts</button></li>
					
				</ul>
			
			</fieldset>
			</form>
			</div>


			<div id="div_edit_personal">
			<div id="personal_updated"></div>	
			<form action="profile_edit" method="POST">
			<form action="profile_edit" method="POST">
			<fieldset>
			<legend>Admins</legend>
			
				<ul>
					<li><label for="you_love">Search for an Admin to Add:</label><input type="text" id="you_love" name="you_love"></input></li>
					<span>Note: Only people who are apart of this group will show up as able to be added as an admin</span>
					<li><button type="submit" id="edit_submit_alerts" name="edit_submit_alerts" value="edit_submit">Search</button></li>
				</ul>

				<ul>
					<li>Current Admins:</li>
					<?
					foreach($_t['html_admin'] as $v)
						echo $v;

					?>
				</ul>
			
			</fieldset>
			</form>
			</div>
			
			<div id="div_edit_pic">
			<div id="pic_updated"></div>

			<form  action="<?=$PHP_SELF?>" target="upload_iframe" method="post" enctype="multipart/form-data">
			<ul>
					<li><input type="hidden" name="fileframe" value="true"></li>
					<li><label for="group_image">Picture Of You</label>
					<input type="file" id="group_image" name="group_image"></input></li>
			</ul>
			</form>
			<iframe name="upload_iframe" style="width: 400px; height: 100px; display:none;"></iframe>
			
			<form actoin="" method="POST">
			<fieldset>
			<legend>Picture</legend>
			
				<ul>
					<li><span id="upload_status"></span></li>
				        <li><span id="pic_format_error"></span></li>
					<li>
						<span id="edit_profile_picture"><img src="..<?=D_GROUP_PIC_REL?><?=$pic_180_2?>" alt='group_picture' /></span>
					</li>
					<li id="default_pic_msg">
								<?php if( $pic_180_2 == '180h_default_group.jpg')
								echo "You're using the default groupp pic, please upload a new picture of you! :)";
					?>
					</li>
					<li><button type="submit" id="edit_submit_pic" name="edit_submit_pic" onclick="jsUpload(document.getElementById('group_image')); return false;" value="edit_submit">Update Picture</button></li>
				
				</ul>
			
			</fieldset>
			</form>
			</div>
			
			</div>
		</div>
		
		
	</div>
	
</div>

	<?php include(FOOTER);?>

</body>                                                                                                                                                                                                                                                                                                                  
</html>
