<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title><?=TITLE?> - Profile</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css" media="all">@import "/views/style_sheets/home.css";</style>
<script type="text/javascript" src="/views/javascript/group_add.js"></script> 
</head>

<body>
<span id="create_group_errors"></span>

<div id="container">

	<?php include(HEADER);?>
		
	<?php include(LEFT);?>
	
	<div id="create_group">
	
		<div id="create_group_header">Create a Group</div>
	
			<div id="create_group_intro">
		
			<p>
			Welcome to Create Group.  Here you can create a group and invite your friends to the group
			that you create.  There are many options for creating a group, and each option affects who is able
			to be invited, the information that is shared within the group, and the credibility of the group.
			</p>
			
			<div id="create_group_go_away"><a href="#">Click to not display this message.</a></div>
		
		</div>

		<div id="create_group_form">
		
		<form action="<?=ROOT?>create_group" method="POST" enctype="multipart/form-data">
		<fieldset>
		<legend>Group Creation Form</legend>
			
			<ul id="main_create_form">
			
				<li><label for="create_group_name">Group Name </label><input type="text" name="gname" id="create_group_name" onblur="group(this.value);" ></input></li>
				<li><label for="create_group_symbol">Symbol </label><input type="text" name="symbol" id="create_group_symbol" onblur="group(this.value);" ></input></li>
				<span class="group_explinations">Symbols are how people reference your group</span>
				<span id="ajax_rel_groups"><ul id="ajax_rel_list"></ul></span>

				<li><label id="group_descr_label" for="create_group_desc">Group Description </label><textarea rows="4" cols="16" name="descr" id="create_group_desc" onblur="check_descr(this.value);"></textarea></li>
				<span id="descr_error"></span>
			

				<li>
					<label for="create_group_why">Groups Focus(es):</label><span class="group_explinations">Seperated by commas</span>
					<li><input type="text" name="focus" id="create_group_focus"></input></li>
			
				</li>
				
				
				<li><span class="style_bold">Prerequiests:</span>

					<ul id="prereq_check_list">
						<li>
							<label>E-mail Suffix of.. </label>
							<input type="checkbox" id="reveal_email_input" onclick="document.getElementById('email_suffix').style.display = this.checked ? 'inline' : 'none'"></input>
								<input type="text" id="email_suffix" name="email_suffix" class="hidden_text_form" onblur=""></input>
						</li>
						
					</ul>
				</li>

				<li>
					<label>Make Private</label>
					<input type="checkbox" id="private" name="private" value="1"></input>
					<span class="group_explinations">(This will not publicize your group in "Related Groups" or in search results)</span>
					
				</li>
				
				<li>
					<label>Invite Only</label>
					<input type="checkbox" id="invite" name="invite" value="1"></input>
					<span class="group_explinations">(By making a group Invite Only, only memebers invited will be able to join.)</span>
				</li>
			
<br/>	
				<li>
					<label>Who is allowed to invite new group members?</label>
					<ul id="prereq_check_list">
						<li>
							<label>Owner/Administrators </label>
							<input type="radio" id="owner" name="invite_priv" value="0" checked="true"> </input>
						</li>
						
						<li>
							<label>Everyone </label>
							<input type="radio" id="all" name="invite_priv" value="1"></input>
						</li>
						
					</ul>
				</li>
				</li>
								
				<li>
					<label for="invite_friends">Invite People From Your Network/Groups</label>
						<select id="group_invite_list" name="group_invite">
						<option value="null">--- Nobody ---</option>
						<?
						if(is_object($_t['your_groups'])){
						while($search_people_results = $_t['your_groups']->fetch_assoc())
                                                echo <<<EOF
                                                <option value="{$search_people_results['gid']}">{$search_people_results['gname']}</option>
EOF;
						} else {
						echo '<option value="NULL">Join a network/group to invite people</option>';
						}
                                                ?>
						</select>
				</li>
								

				<li><input type="submit" name="submit_create" id="submit_create" value="Submit" onclick="return check_all();" ></input></li>
				<span id="all_errors"></span>
			</ul>
		
		</fieldset>
		</form>
		
		</div>
	
	</div>
	
</div>

	<?php include(FOOTER);?>

</body>
<script type="text/javascript">document.getElementById('create_group_name').focus()</script>
</html>
