<?php
$res = $_t['edit_profile'];
$fname = $res['fname'];
$lname = $res['lname'];
$uname = $_COOKIE['uname'];
$email = $res['email'];
$pic = $res['pic_180'];
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
		
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11153159-1");
pageTracker._trackPageview();
} catch(err) {}</script>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>tap - alpha</title>

<link rel="stylesheet" href="views/style_sheets/group_manage.css" type="text/css" ></link>
<link rel="stylesheet" href="views/style_sheets/profile.css" type="text/css" ></link>


<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="icon" href="images/favicon.ico" type="image/x-icon" />

<!--[if lt IE 7]>
        <script type="text/javascript" src="js/unitpngfix.js"></script>
<![endif]-->

<script src="views/javascript/mootools-1.2.3-core-yc.js" type="text/javascript"></script>
<script src="views/javascript/mootools-1.2.3.1-more.js" type="text/javascript" charset="utf-8"></script>
<script src="views/javascript/mootools-tap.js" type="text/javascript" charset="utf-8"></script>
<style type="text/css" media="screen">
#help-header { 
	height: 41px; width: 553px;
	margin-top: -1px;
	color: white;
	background: url(/images/cimages/main_bar_grey.gif); }

#help-tab {
	height: 31px; width: 194px;
	background-image: url(/images/cimages/tab_grey.gif); }

div.help { 
	margin: 0 20px; }
	
div.help h1, div.help h2, div.help p, div.help ul {
	font-size: 12px;
	margin-bottom: 10px; }

div.help ul { 
	margin-bottom: 20px; }
	
div.help h1 { 
	color: #4F9CDF;
	font-size: 16px;
	font-weight: bold; }

div.help h2 { 
	font-size: 14px;
	font-weight: bold; }
</style>


</head>

<body>
	
	<? include(NEW_HEADER); ?>
	
	<div id="main">
		<div id="left-col">
			<div id="help-tab">
				<div class="tab-in">Topics</div>
			</div>
			<div class="tab-list">
				<ul>
					<li><a href="#quick">Quick Answers</a></li>
					<li><a href="#basics">The Basics</a></li>
					<li><a href="#convos">Conversations</a></li>
					<li><a href="#groups">Groups</a></li>
				</ul>
			</div>
		</div>
		
		<div id="center-col">
			<div id="profile">
				<div id="help-header">
					<h2 class="gr-title">Help</h2>
				</div>

				<div class="main-frame" style="padding: 10px 0">
					<div class="help">
						<h1>Help Topics</h1>
						<ul>
							<li><a href="#quick">Quick Answers</a></li>
							<li><a href="#basics">The Basics</a></li>
							<li><a href="#convos">Conversations</a></li>
							<li><a href="#groups">Groups</a></li>
						</ul>
						
						<h1 id="quick">Quick Answers</h1>

						<h2>What is Tap?</h2>

						<p>Tap is a new social-communication tool that gives you real-time connection to individuals, groups and even geographical areas, without the burden of memorizing any special usernames or address. With Tap, you can send messages to anyone in the world, even if you don&#8217;t know where they are or how to address you messages.</p>

						<p>Everything in Tap works in real-time: send a tap and it instantly appears on other people&#8217;s feeds. Conversations are also instantaneous: you&#8217;ll be able to respond to taps and see the responses from other people in real time.</p>

						<h2>How Does it Work?</h2>

						<p>It&#8217;s simple: all you have to do is compose your message, called a &#8220;tap,&#8221; and select the individuals or groups you&#8217;re sending to. You can add as many individuals or groups you want to get the tap. Hit send and your tap is automatically sent to their feeds.</p>

						<p>You can also respond directly to any taps in your feed, turning it into an active conversation.</p>

						<h2>Who Created Tap?</h2>

						<p>We&#8217;re a bunch of guys who wanted a new way to do social communication. We know that there are a lot of solutions available today, but the problem with them is that they&#8217;re either too limited, too complex or too slow. Plus, they also rely on weird metaphors that don&#8217;t really fit in real life situations.</p>

						<p>We wanted a real-time solution that isn&#8217;t overly complex. We have lots of friends to catch up on, and a lot of people to communicate with&#8212;and we bet that you do to! So we decided to build Tap: a fast, real-time communication tool that&#8217;s simple enough for everyone to use.</p>

						<h1 id="basics">The Basics</h1>

						<h2>How do I send a tap?</h2>

						<p>It&#8217;s easy as pie: go to the <strong>Interface</strong> and compose a message on the message-area. You could then select who will see your taps: type in a few letters of the name of an individual or group and then select the group from the dropdown list. You can add as many recipients as you like, so it&#8217;s easy to send a tap to multiple groups or individuals. Optionally, you could also leave the box blank and it&#8217;ll be viewable by everyone in your feed.</p>

						<h2>How do I view a tap?</h2>

						<p>In the <strong>Interface</strong>, you have a <em>Feed</em> section, where all your taps are displayed. When you first load this page, you&#8217;ll see the taps from all your groups, but you could also click on one of the groups you belong to on the list on the right side of the page to show only taps from that particular group.</p>

						<p>As new taps come in, you&#8217;ll be notified on whether you want to view these new taps. Since everything happens in real time, the moment someone sends a tap to you or a group you belong in, it will automatically be sent to your feed.</p>

						<h2>How do I search for a tap?</h2>

						<p>On the top of your Feed view, there&#8217;s a small box marked &#8220;Search through feed.&#8221; Enter a keyword and hit <strong>enter</strong> and it&#8217;ll display all taps matching your keyword.</p>

						<p>Searching is based on the group feed you&#8217;re viewing. If you&#8217;re viewing your &#8220;All Groups&#8221; feed, it will search through the taps of all your groups. Changing to another groups feed will also change your search results.</p>

						<h1 id="convos">Conversations</h1>

						<h2>What are conversations?</h2>

						<p>While taps are messages, conversations are a way to discuss a particular tap. When someone sends a tap to you, you can turn it into a conversation by responding to the tap. This will turn the tap into an &#8220;active conversation,&#8221; that enables you to talk with others in real time.</p>

						<h2>How do I start conversations?</h2>

						<p>When you see a tap that you&#8217;d like to discuss, simply click on the &#8220;Respond&#8221; button and the tap will be turned into an active conversation. You can then enter your response to the tap. You&#8217;ll also be able to see other responses to the tap,</p>

						<p>Because Tap is always in real-time, your responses and responses from other people are automatically loaded into the conversation. Think of it as a very cool chatroom where you can converse and discuss about the original tap.</p>

						<h1 id="groups">Groups</h1>

						<h2>What are groups?</h2>

						<p>We&#8217;re part of many groups in real life: families, friends, co-workers, schools&#8212;the list could go on. This grouping is also applied to Tap, where you could join several groups that connect you to different people.</p>

						<p>There are two kinds of groups in Tap: official groups and user created groups. <em>Official Groups</em> are groups that represent actual institutions like colleges, businesses and other organizations. <em>User Created Groups</em> are the ones created by different individuals who&#8217;d like to form a community, usually around a specific topic, specialty or demographic.</p>

						<h2>How do I join a group?</h2>

						<p>First, go to the <strong>Groups</strong> page. This is where you&#8217;ll manage all your groups. You&#8217;ll then be able to search for a group you&#8217;d like to join. Enter a keyword or a name then hit search. A list of results will be displayed, and you&#8217;ll be able to join them.</p>

						<p>For user created groups, you&#8217;ll be able to join instantly by clicking the join button. For official groups, you&#8217;ll have to enter a valid email address from that group to be able to join. A confirmation email will be sent to the email address with a link that will confirm that you&#8217;re part of the organization. Once you click the link, you&#8217;ll be included in the group.</p>

						<h2>How do I see a tap from a group?</h2>

						<p>Taps to all groups you&#8217;re a part of will automatically be displayed on the Interface. To view taps to a particular group, just click on the name of the group on the sidebar on the right of the page and your feed will display only taps to that group.</p>

						<h2>How do I send a tap to a group?</h2>

						<p>Sending a tap to a group is just like sending a normal tap: enter your message then select the group you&#8217;d like to send the tap to and hit send.</p>

						<h2>Can I send a tap to a group I don&#8217;t belong to?</h2>

						<p>Yes. Taps sent by people who are not members of a group are called &#8220;outside taps.&#8221; They&#8217;re usually filtered out from the group&#8217;s feed, but users can turn on their outside taps toggle to view taps from non-members.</p>
						
						
					</div>
				</div>
				<div class="main-frame-bottom"></div>
			</div>
		</div>

		<div id="right-col">
			<h1>Help and Tips</h1>
			<h2>Got any more questions?</h2>
			<p>If you have any questions or concerns, or if you wanna drop us a line, send a tap to <strong>tapsupport</strong> and we'll do our best to respond as soon as possible.</p>
		</div>
	</div>
	
	<div id="footer"></div>

</body>
</html>
