<?php
    $_h = array(
        'title'   => 'homepage',
        'scripts' => array('tap.js', 'search.js', 'modal.js'),
        'styles'  => array('roar.css', 'modal.css'),
        'vars'    => array('user' => $me),
        'guest'   => $guest);
    include(HEADER);
?>
    
    <div id="content">
    	
        <div id="left">
            <?php
                $_f = array(
                    'feed' => $feed,
                    'name' => $feed_name
                );
                include(FEED);
            ?>        
        </div><!--left-->
        
        <?php
            $_s = array(
                'circles'  => $circles,
                'show_nav' => true
            );
            include(SIDEBAR);
        ?>
        
    </div><!--content-->

<?php
    include(FOOTER);
?>
