<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Tap</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<!-- <link href="main.css" rel="stylesheet" type="text/css" media="screen" /> -->
<style type="text/css" media="all">@import "views/style_sheets/main.css";</style>
<script type="text/javascript" src="views/javascript/sign_up.js?fid=<?=$_GET['fid']?>"></script>
<script type="text/javascript" src="views/javascript/inform_users.js"></script>
<script type="text/javascript" src="views/javascript/mootools-1.2.3-core-yc.js"></script>

<script type="text/javascript">

      
window.addEvent('domready', function() { 
         
        $('repass_pass').addEvent('focus',function(){
                Cookie.write('profile_edit',1,{duration:999})
                Cookie.write('rel_settings',1,{duration:999})
                Cookie.write('groups',1,{duration:999})
                Cookie.write('new_user',1,{duration:999})
        });

});
        
</script>
</head>

<body>

<span id="errors_show"></span>
<span id="currently_showing">main_forms</span>


<div id="login_form">
		<fieldset id="login_field">
		<form action="<?=ROOT?>" method="POST">
		<ul>
		<li><label>Username</label> <input type="text" id="uname" name="uname"></input></li>
		<li><label>Password</label> <input type="password" id="pass" name="pass"></input></li>
		<li><label>Keep Me Logged In</label> <input type="checkbox" checked="true" id="auto_login" name="auto_login"></input></li>
		<li><input type="submit" id="signin_submit" value="Sign In"></input></li>
		</ul>
		</form>

		</fieldset>
	</div>

<div id="top_container">
	<div id="top">How it works. &nbsp;&nbsp;&nbsp;&nbsp; Why it works. &nbsp;&nbsp;&nbsp;&nbsp; What it is. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <?php print $_t['signup'] ?></div>

	
</div>


<div id="container_logged_out">

<?php include(SIGNUP);?>

	<div id="top_logo"><img id="click_main_forms" src="images/tap_logo.gif" alt="logo" onclick="window_swapper(this); return false;" /></div>
<?php echo $_t['errors']; ?>
	
	<div id="info">
	<!--
		<div id="video">Featured Video:
		
		<object width="225" height="250"><param name="movie" value="http://www.youtube.com/v/lUGyxi_Z8ks"></param><param name="wmode" value="transparent"></param><embed src="http://www.youtube.com/v/lUGyxi_Z8ks" type="application/x-shockwave-flash" wmode="transparent" width="225" height="250"></embed></object>
		
		</div>
	-->
		<ul id="info_list">
			<li class="post" id="click_you_ask">Tap the Connected</li>
		</ul>
	
	</div>
	
	<div id="forms">

						<div id="inform_container">
						
							<div id="you_ask" style="display:block;">
								<span class="inform_header">Connect.</span>
								
								<p>
								tap allows you to connect with people around you and stay informed about topics you're interested in.  Use tap to see what you and your friends are doing, what people around you are doing, and connect with link-minded individuals.  Join tap today.<br/><br/> <a style="margin-left:170px;color:blue;text-align:middle;" class="style_bold" href="#" onclick="sign_up(); return false;">Sign Up</a></span><br/><br/>

								</p>
								
								<p>
								</p>

							
							</div>
							
							<div id="we_find">
									<span class="inform_header">We Find Them.</span>
									
									<img id="inform_pic_2" src="images/inform/inform22.gif" alt="logo"/>
									<p>
										After you ask your question or shout to the world, tap finds all of the people who are interested in what you've said, and alerts them, instantly.
										We are able to do this through an advanced algorithem that allows us to find users on our site and alert them.
									</p>
									
									<p>
									After signing up for tap, you'll be able to setup Relevancy Settings, which are settings that let you receive alerts based on what you're interested in, knowledgeable in, and more.
									</p>
								
								
							</div>
							
							<div id="they_connect">
								<span class="inform_header">The World Connects.</span>

								<img id="inform_pic_3" src="images/inform/inform3.gif" alt="logo"/>
								<p>
									After a person is alerted, they decide wither or not to connect with you.
									Ulike any service that currently exists, tap can alert thousands of people
									instantly who know exactly what you want.  This which is what makes tap so revelotionary.
								</p>
								
								<a class="style_bold" href="#" onclick="sign_up(); return false;">Sign Up!</a></span>
								
							</div>
							
						</div>
						



		<div id="forms">
			<!--
                <form action="<?=ROOT?>" method="post" >
                                <fieldset>
                                        <div id="core">
                                        <ul id="directions">
                                        </ul>

                                        <ul id="top_form">
                                                <li><textarea class="gray_text" rows="2" cols="15" id="question" >Tap allow you to connect with people in your life in real-time</textarea></li>
                                                <li id="outter_button"><span id="inner_button">

                                                </span></li>
                                        </ul>

					</div>
				</fieldset> -->

		</div>	

	</div>

	<br/>

	<!-- <a id="main_signup" class="style_bold" href="#" onclick="sign_up(); return false;">Sign Up</a> -->
	</span>

	
	<div id="footer">

<?php include(FOOTER);?>
	
	</div>
	
</div>

</div>

</body>
</html>
