<!doctype html>
<html>
<head>
	<? 
	$tpl_title = "Invite Friends";
	include(OK_HEADER);
	?>
	<script type="text/javascript" src="/views/scripts/tap.js"></script>
	<script type="text/javascript">
		window._vars = {type: null};
	</script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>

</head>
<body>
	<div id="wrapper">
	<? include(OK_TOPBAR); ?> 

	<div id="main">

		<? include(OK_SIDEBAR); ?>

			<div id="content">
				
				<div class="section">
					<div class="header header-non">
						<a id="newtaps" href="" class="floater"></a>
						<h2 class="header-title">
							<img src="/images/flat/loader.gif" />
							<span class="title">invite</span>
						</h2>
						<span class="stream-name">Invite Your Friends</span>
					</div>
					<div class="body">
						<div id="invites" class="form">
							<p>Why don't you invite your friends to join tap?</p>
							<label for="current">
								name 
								<span class="help">your friend's name</span>
								<span class="error"></span>
							</label>
							<input name="name" type="text" class="basic full" />
							
							<label for="new">
								email
								<span class="help">your friend's email address</span>
								<span class="error"></span>
							</label>
							<input name="email" type="text" class="basic full" />
							
							<label for="about">
								message 
								<span class="help">a short message for your friend</span>
								<span class="error"></span>
							</label>
							<input name="message" type="text" class="basic full" 
								value="Hey, it's <?= $_SESSION['uname'] ?>! Join me on tap!" />
							
							<div class="buttons">
								<button class="action">send invite</button> or <a href="/">cancel</a>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
    <?include(OK_FOOTER)?>
</body>
</html>
