<!doctype html>
<html>
<head>
	<? 
	$tpl_title = "Login";
	include(OK_HEADER);
	?>
	<script type="text/javascript" src="/views/scripts/tap.js"></script>
	<script type="text/javascript" src="/views/scripts/login.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
</head>
<body>

<?php if (!$ok_user || TRUE): ?>
    <? include(MODAL_SIGNUP); ?>
    <script type="text/javascript" src="/views/scripts/modal_signup.js"></script>
<?php endif; ?>

	<div id="wrapper">

	<? include(OK_TOPBAR); ?> 

	<div id="main">

		<? include(OK_SIDEBAR); ?>

			<div id="content">
				
				<div class="section">
					<div class="header header-non">
						<h2 class="header-title">
							<span class="title">?</span>
						</h2>
						Join the conversation!
					</div>
					<div class="body">
						<div class="full info">
						<?
                            $u = $_SERVER['REQUEST_URI'];
                            $u = explode('/',$u);
                            if($u[1] == 'group')
                                $type = '?type=group';
                            if($u[1] == 'user')
                                $type = '?type=user';
                            if($type)
                                $value = '&value='.$u[2];
                        ?>
                        <div id="login" class="section container">
                            <table>
                                <tr>
                                    <td>
                                        <form id="taplogin" action="/" method="POST">
                                        <input name="fb_login" type="hidden" value="">
                                            <ul>
                                                <li>
                                                    <label class="inblock">username</label>
                                                        <p class="body">
                                                            <input name="uname" type="text" class="basic" value="<?= $_POST['uname'] ?>" />
                                                        </p>
                                                </li>
                                                <li>
                                                    <label class="inblock">password</label>
                                                    <p class="body">
                                                    <input name="pass" type="password" class="basic" value="<?= $_POST['pass'] ?>" />
                                                    </p>
                                                </li>
                                                <li class="action">
                                                    <button id="login-button" type="submit">login</button>
                                                </li>
                                            </ul>
                                        </form>
                                    </td>
                                    <td style="width: 40px; padding-right: 10px; text-align: center;">
                                        OR
                                    </td>
                                    <td>
                                        <fb:login-button show-faces="true" width="300" perms="user_about_me,email,read_friendlists,user_groups"></fb:login-button>
                                    </td>
                                </tr>
                            </table>
                        </div>    
                        </div>
					</div>
				</div>
			</div>

		</div>
	</div>
	
    <?include(OK_FOOTER)?>
	<?include(JAVASCRIPT_TEMPLATES)?>

<script type="text/javascript">
var _gaq = _gaq || [];
 _gaq.push(['_setAccount', 'UA-11153159-1']);
 _gaq.push(['_trackPageview']);

 (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
 })();
</script>
		<?include(FBCONNECT_BOTTOM)?>
</body>
</html>
