<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Content-Language" content="en-us" />
	<meta name="robots" content="noodp" />
	<meta name="image-toolbar" content="no" />
	<meta name="copyright" content="Copyright (c) 2009 TAP" />
	<meta name="description" content="TAP communication platform" />
	<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />
	<title>tap</title>
	<link rel="stylesheet" href="/views/styles/global.css" type="text/css" />
	<link rel="stylesheet" href="/views/styles/public.css" type="text/css" />
	<script type="text/javascript" src="/views/scripts/mootools-core.js"></script>
	<script type="text/javascript" src="/views/scripts/mootools-more.js"></script>
	<script type="text/javascript" src="/views/scripts/login.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
	<script type="text/javascript" src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/FeatureLoader.js.php"></script>
        <script src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/XdCommReceiver.js" type="text/javascript"></script>
</head>
<body>
	<div id="wrapper">

			<?php if ($logged): ?>
				<?include(HEADER)?>
			<?php else: ?>
				<?include(HEADER_LOGOUT)?>
			<?php endif; ?>


		<div id="main">

			<div id="sidebar">
				
				<div id="inviter" class="section container">
					<h2>Want to start tapping?</h2>
					<p>Tap is invite only right now. If you want to be one of our early tappers, <a href="/">signup for an invite</a>.</p>
				</div>
				<?php //include(LOGIN);?>	
			</div>

			<div id="content">
				
				<div class="section">
					<div class="header header-non">
						<h2 class="header-title">
							<span class="title">?</span>
						</h2>
						Join the conversation!
					</div>
					<div class="body">
						<div class="full info">
						<?
                            $u = $_SERVER['REQUEST_URI'];
                            $u = explode('/',$u);
                            if($u[1] == 'group')
                                $type = '?type=group';
                            if($u[1] == 'user')
                                $type = '?type=user';
                            if($type)
                                $value = '&value='.$u[2];
                        ?>
                        <div id="login" class="section container">
                            <form id="taplogin" action="/" method="POST">
                                <ul>
                                    <li>
                                        <label class="inblock">username</label>
                                            <p class="body">
                                                <input name="uname" type="text" class="basic" value="<?= $_POST['uname'] ?>" />
                                            </p>
                                    </li>
                                    <li>
                                        <label class="inblock">password</label>
                                        <p class="body">
                                        <input name="pass" type="password" class="basic" value="<?= $_POST['pass'] ?>" />
                                        </p>
                                    </li>
                                    <li class="action">
                                        <button type="submit">login</button>
                                    </li>
                                    <li id="login-status"></li>
                                </ul>
                            </form>
                        </div>    
                        </div>
					</div>
				</div>
			</div>

		</div>
		
		<div class="clarity"></div>
		
		<div id="footer">
			<strong>tap &copy; 2010.</strong>
			<span class="nav">
				<a href="/" class="current">home</a>
				<a href="/what">what's tap?</a>
				<a href="/about">about us</a>
				<a href="/devs">developers</a>
				<a href="/contact">contact</a>
			</span>
		</div>
	</div>
	
	<?include(JAVASCRIPT_TEMPLATES)?>

<script type="text/javascript">
var _gaq = _gaq || [];
 _gaq.push(['_setAccount', 'UA-11153159-1']);
 _gaq.push(['_trackPageview']);

 (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
 })();
</script>
		<?include(FBCONNECT_BOTTOM)?>
</body>
</html>
