<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title><?=TITLE?> - Profile</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css" media="all">@import "views/style_sheets/home.css";</style>
</head>

<body>

<div id="container">
	
	<?php include(HEADER);?>
		
	<?php include(LEFT);?>
	
	<div id="logs">
	
		<div id="logs_header">Logs</div>
	
			<div id="logs_intro">
		
			<p>
			Welcome to your logs.  These are logs of conversations that you've had in the past with other users.  Everytime
			you engage in a conversation with someone on chatapist, your conversations are automatically logged and organized,
			for you to then read through at a later time.  You can view a conversation by click on "view log".  
			</p>
			
			<div id="logs_go_away"><a href="#">Click to not display this message.</a></div>
		
		</div>

		<div id="log_table_div">
		
			<table id="log_table">
					
				<colgroup span="6">
					<col width="80"></col>
					<col width="360"></col>
					<col width="80"></col>
					<col width="70"></col>
					<col width="90"></col>
					<col width="50"></col>
				</colgroup>
			
				<thead id="log_head">
				<tr><td>-View Logs-</td><td>-Description-</td><td>-Category-</td><td>-Username-</td><td>-Date-</td><td>-Price-</td></tr>
				</thead>
				
				<tbody>
				
					<tr class="log_columns_white">
						<td class="log_rows"> <a href="<?=ROOT?>view_logs">View Logs</a> </td>
						<td class="table_description"> This is a description of something that happened.  I'm wondering where my kid could have gone if
						I really gave him the car keys that we were talking about doing.  This is something pretty serious.
						does anyone know how this could be possible or why something like this could happen or anything
						of the sort?  Thanks!</td>
						<td class="log_rows"> Need Help </td>
						<td class="log_rows"> No </td>
						<td class="log_rows"> 1 / 3 / 2010 </td>
						<td class="log_rows"> $33.00 </td>
					</tr>
					
					<tr class="log_columns_blue">
						<td class="log_rows"> <a href="<?=ROOT?>view_logs">View Logs</a> </td>
						<td class="table_description"> This is a description of something that happened.  I'm wondering where my kid could have gone if
						I really gave him the car keys that we were talking about doing!</td>
						<td class="log_rows"> Computer </td>
						<td class="log_rows"> Jake </td>
						<td class="log_rows"> 1 / 3 / 2010 </td>
						<td class="log_rows"> $3.00 </td>
					</tr>
					
					<tr class="log_columns_white">
						<td class="log_rows"> <a href="<?=ROOT?>view_logs">View Logs</a> </td>
						<td class="table_description">This is something pretty serious.
						does anyone know how this could be possible or why something like this could happen or anything
						of the sort?  Thanks!</td>
						<td class="log_rows"> Law Student </td>
						<td class="log_rows"> TasoDuv </td>
						<td class="log_rows"> 1 / 30 / 2010 </td>
						<td class="log_rows"> $333.00 </td>
					</tr>
					
					<tr class="log_columns_blue">
						<td class="log_rows"> <a href="<?=ROOT?>view_logs">View Logs</a> </td>
						<td class="table_description"> I'm going to take a look at this and see, but I think I have a good reason too.  This is a description of something that happened.  I'm wondering where my kid could have gone if
						I really gave him the car keys that we were talking about doing!</td>
						<td class="log_rows"> Need Personal Help </td>
						<td class="log_rows"> MikeJohn2 </td>
						<td class="log_rows"> 10 / 30 / 2010 </td>
						<td class="log_rows"> $33.00 </td>
					</tr>		
					
										<tr class="log_columns_blue">
						<td class="log_rows"> <a href="<?=ROOT?>view_logs">View Logs</a> </td>
						<td class="table_description"> I'm going to take a look at this and see, but I think I have a good reason too.  This is a description of something that happened.  I'm wondering where my kid could have gone if
						I really gave him the car keys that we were talking about doing!</td>
						<td class="log_rows"> Need Personal Help </td>
						<td class="log_rows"> MikeJohn2 </td>
						<td class="log_rows"> 10 / 30 / 2010 </td>
						<td class="log_rows"> $33.00 </td>
					</tr>		
										<tr class="log_columns_blue">
						<td class="log_rows"> <a href="<?=ROOT?>view_logs">View Logs</a> </td>
						<td class="table_description"> I'm going to take a look at this and see, but I think I have a good reason too.  This is a description of something that happened.  I'm wondering where my kid could have gone if
						I really gave him the car keys that we were talking about doing!</td>
						<td class="log_rows"> Need Personal Help </td>
						<td class="log_rows"> MikeJohn2 </td>
						<td class="log_rows"> 10 / 30 / 2010 </td>
						<td class="log_rows"> $33.00 </td>
					</tr>		
										<tr class="log_columns_blue">
						<td class="log_rows"> <a href="<?=ROOT?>view_logs">View Logs</a> </td>
						<td class="table_description"> I'm going to take a look at this and see, but I think I have a good reason too.  This is a description of something that happened.  I'm wondering where my kid could have gone if
						I really gave him the car keys that we were talking about doing!</td>
						<td class="log_rows"> Need Personal Help </td>
						<td class="log_rows"> MikeJohn2 </td>
						<td class="log_rows"> 10 / 30 / 2010 </td>
						<td class="log_rows"> $33.00 </td>
					</tr>		
										<tr class="log_columns_blue">
						<td class="log_rows"> <a href="<?=ROOT?>view_logs">View Logs</a> </td>
						<td class="table_description"> I'm going to take a look at this and see, but I think I have a good reason too.  This is a description of something that happened.  I'm wondering where my kid could have gone if
						I really gave him the car keys that we were talking about doing!</td>
						<td class="log_rows"> Need Personal Help </td>
						<td class="log_rows"> MikeJohn2 </td>
						<td class="log_rows"> 10 / 30 / 2010 </td>
						<td class="log_rows"> $33.00 </td>
					</tr>		
										<tr class="log_columns_blue">
						<td class="log_rows"> <a href="<?=ROOT?>view_logs">View Logs</a> </td>
						<td class="table_description"> I'm going to take a look at this and see, but I think I have a good reason too.  This is a description of something that happened.  I'm wondering where my kid could have gone if
						I really gave him the car keys that we were talking about doing!</td>
						<td class="log_rows"> Need Personal Help </td>
						<td class="log_rows"> MikeJohn2 </td>
						<td class="log_rows"> 10 / 30 / 2010 </td>
						<td class="log_rows"> $33.00 </td>
					</tr>		
				</tbody>
			</table>
		
		</div>
	
	</div>
	
</div>

	<?php include(FOOTER);?>

</body>
</html>