<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Chatapist - Profile</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css" media="all">@import "views/style_sheets/home.css";</style>
</head>

<body>

<div id="container">
	
	<?php include(HEADER);?>
		
	<?php include(LEFT);?>
	
	<div id="messages_view">
	
		<div id="messages_view_header">messages_view</div>
	
			<div id="messages_view_intro">
		
			<p>
			Here are your messages_view.  In your message area, you will receive messages_view from your friends.
			Click on a message in order to view your messages_view
			</p>
			
			<div id="messages_view_go_away"><a href="#">Click to not display this message.</a></div>
		
		</div>

		<div id="messages_view_table_div">
		
		<div id="message_body">
		
			<div id="message_body_container">
			
			
				<div id="message_body_left">
				
					<div class="message_pic">
					float left
					</div>
					
					<div id="sender_information">
					username
					</div>
					
				</div>

				
				<div class="message_content">
				
				<h4>Subject:</h4>
				<p> aoif jsaoif jsaoi jasoi</p>
				
				
				<h4>Message:</h4>
				<p>howhohaoafh we need to make sute thoah taoafh we need to make sute thoah taoafh we need to make sute thoah taoafh we need to make sute thoah taoafh we need to make sute thoah taoafh we need to make sute thoah this soi  fhoa aoif oi fa</p>
				
				</div>
				
				<div id="message_response_options">
				<button>Reply</button>
				</div>
				
				<div id="responding_area">
				
				<span>
				<textarea></textarea>
				</span>
				
				<span id="send_message_button">
				<button>Send</button>
				</span>
				
				</div>
				
			
			</div>
			

		</div>
		
		
		</div>
	
	</div>
	
</div>

	<?php include(FOOTER);?>

</body>
</html>