<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title><?=TITLE?> - Profile</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css" media="all">@import "/views/style_sheets/home.css";</style>
</head>

<body>

<div id="container">
	
	<?php include(HEADER);?>
		
	<?php include(LEFT);?>
	
	<div id="messages">
	
		<div id="messages_header">Messages</div>
	
			<div id="messages_intro">
		
			<p>
			Here are your messages.  In your message area, you will receive messages from your friends.
			Click on a message in order to view your messages
			</p>
			
			<div id="messages_go_away"><a href="#">Click to not display this message.</a></div>
		
		</div>

		<div id="messages_table_div">
		
		
		<div id="message_global_options">
		
			<select>
				 <option>Select All</option>
				 <option>Deselect All</option>
				 <option>Delete</option>
				 <option>Mark as New</option>
			</select>
			
		</div>
		
			<table id="messages_table">
					
				<colgroup span="5">
					<col width="48"></col>
					<col width="60"></col>
					<col width="120"></col>
					<col width="320"></col>
					<col width="80"></col>
			
				</colgroup>
			
				<thead id="messages_head">
				<tr><td>-Check-</td><td>-From-</td><td>-Subject-</td><td>-Message-</td><td>-Sent-</td></tr>
				</thead>
				
				<tbody>
				
					<tr class="messages_columns_white">
						<td class="messages_rows"> <input type="checkbox"></input> </td>
						<td class="table_description"> Username888</td>
						<td class="messages_rows"> Hey what's up?</td>
						<td class="messages_rows"> <a href="<?=ROOT?>messeges_view">Hey how are you?  I was wondering how things were going...</a> </td>
						<td class="messages_rows"> 1 / 3 / 2010 </td>

					</tr>
					
					<tr class="messages_columns_blue">
							<td class="messages_rows"> <input type="checkbox"></input> </td>
						<td class="table_description"> Username888</td>
						<td class="messages_rows"> Hey what's up?</td>
						<td class="messages_rows"> <a href="<?=ROOT?>messeges_view">Hey how are you?  I was wondering how things were going...</a></td>
						<td class="messages_rows"> 1 / 3 / 2010 </td>
					</tr>
					
				</tbody>
			</table>
		
		</div>
	
	</div>
	
</div>

	<?php include(FOOTER);?>

</body>
</html>