<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
		
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>TAP :: BETA</title>

<link rel="stylesheet" href="views/style_sheets/group_manage.css" type="text/css" ></link>
<link rel="stylesheet" href="views/style_sheets/profile.css" type="text/css" ></link>

<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="icon" href="images/favicon.ico" type="image/x-icon" />

<!--[if lt IE 7]>
        <script type="text/javascript" src="js/unitpngfix.js"></script>
<![endif]-->

</head>

<body>

	<div id="header">
		<div class="holder">
			<span id="logo"><a href="">TAP</a></span>
			<span id="main-menu">
				<a href="">Home</a> <a href="">My Profile</a> <a href="">People</a> <a href="">Groups</a> <a href="">Filters</a> <a href="">Settings</a> <a href="">Help</a>
			</span>
			<span id="login-info"><a href="">Register</a> <a href="">Sign in</a></span>
		</div>
	</div>
	
	<div id="main">
		<div id="left-col">
			<div id="profile-tab">
				<div class="tab-in">My Profile</div>
			</div>
				<div class="tab-list">
					<ul>
						<li class="list-item"><strong>TAP Account</strong></li>
						<li class="list-item"><a href="" class="item-name">About me</a></li>
						<li class="list-item"><a href="" class="item-name">TAP Stats</a></li>
					</ul>
					<p class="more-btn1"><a href="">show more &raquo;</a></p>
					<div style="clear:both"></div>
				</div>
		</div>
		
		<div id="center-col">
			<div id="profile">
				<div id="profile-header">
					<h2 class="gr-title">My Profile</h2>
					<span class="tab-on">TAP Account</span>
					<span class="tab-off"><a href="">About me</a></span>
					<span class="tab-off"><a href="">TAP Stats</a></span>
				</div>

				<div class="main-frame">
					<div id="picture-side">
						<div id="prof-pic"><img src="images/group_image.gif" alt="group logo" class="prof-image" /></div>
						<p><a href="">upload picture &raquo;</a></p>
						<p class="pic-desc">JPG / GIF / PNG / BMP format of any size (will be automatically resized &amp; cropped upon uploading)</p>
					</div>
					<div id="account-info">
						<h2 class="in-title">Username: <input type="text" name="username" value="" /></h2>
						<h2 class="in-title">Password: <input class="input-err" type="password" name="password" value="" /><div class="error-msg">password is not correct</div></h2>
						<h2 class="in-title">E-mail: <input type="text" name="email" value="" /></h2>
						<p id="profile-btns"><a href="" >Accept</a> <a href="" >cancel</a></p><br />
					</div>
					<div style="clear:both"></div>
				</div>
				<div class="main-frame-bottom"></div>
			</div>
		</div>

		<div id="right-col">
			<p></p>
		</div>
	</div>
	
	<div id="footer"></div>

</body>
</html>
