<?php
if ($_GET['logout'] == 'true') header('location: /');
?>
<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Content-Language" content="en-us" />
	<meta name="robots" content="noodp" />
	<meta name="image-toolbar" content="no" />
	<meta name="copyright" content="Copyright (c) 2009 TAP" />
	<meta name="description" content="TAP communication platform" />
	<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />
	<meta name="with-errors" content="<?= (!empty($_t['errors']) && empty($_GET['logout'])) ? 'y' : 'n'?>">
	<title>tap</title>
	<link rel="shortcut icon" href="http://mark.tap.info/group_pics/default.ico" />
	<link rel="stylesheet" href="/views/styles/global.css" type="text/css" />
	<link rel="stylesheet" href="/views/styles/public.css" type="text/css" />
	<script type="text/javascript" src="/views/scripts/mootools-core.js"></script>
	<script type="text/javascript" src="/views/scripts/mootools-more.js"></script>
	<script type="text/javascript" src="/views/scripts/login.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
</head>
<body>
	<div id="wrapper">

		<?include(HEADER_LOGOUT)?>

		<div id="main">

			<div id="sidebar">
				
				<div id="login" class="section container">
					<a id="tab-people" title="contacts" class="tab selected"></a>
					<h2>
						<span id="tab-name">ready to tap?</span>
					</h2>
					<form id="taplogin" action="/" method="POST">
						<ul>
							<li class="notice">
								login with your tap or freenode account.
							</li>
							<li>
								<label class="inblock">username</label>
								<p class="body">
									<input name="uname" type="text" class="basic" value="<?= $_POST['uname'] ?>" />
								</p>
							</li>
							<li>
								<label class="inblock">password</label>
								<p class="body">
									<input name="pass" type="password" class="basic" value="<?= $_POST['pass'] ?>" />
								</p>
							</li>
							<li class="action">
								<button type="submit">login</button>
							</li>

							<li id="login-status"></li>
							<li id="pics-galore" style="background:#111;margin-left:8px;">
							<? foreach($_t['pics_array'] as $pic): ?>
								<a href="/group/<?=$pic['symbol']?>" >
								<img class="small-pics-logout" style="height:16px;width:16px;margin:4px;" src="/group_pics/<?=$pic['pic_36']?>" title="<?=$pic['symbol']?>" />
								</a>
							<? endforeach; ?>
							</li>
						</ul>
					</form>
				</div>
				
			</div>

			<div id="content">
				
				<div class="section">
					<div class="header">
						<h2 class="header-title">
							<span class="title">tap</span>
						</h2>
						join the conversation!
					</div>
					<div class="body">
						<div style="font-size:18px;color:white;" class="description">Tap allows you to create real-time communities that are manageable, easily accessable, scaleable and stylish.  Tap is currently open to members of Freenode only, as our focus is on real-time communities for open source and software projects. </div>	
<div id="content"> 
 
 
				<div id="tapstream" class="section description"> 
					<div class="header"> 
						<a href="#" id="streamer" class="floater" alt="pause live streaming" title="pause live streaming"></a> 
						<a id="newtaps" href="" class="floater">This feed has 5 new taps! Click here to load them.</a> 
						<h2 class="header-title"> 
							<img src="/images/flat/loader.gif" /> 
							<span class="title">feed</span> 
						</h2> 
						<span class="stream-name">Tap Demo - Join today and start tap'ing!</span> 
					</div> 
					<div class="description">Below is a demo of tap in action!</div> 
					<div class="body">
						<ul id="taps" class="stream"> 
														<li id="tid_4496" class="container" 
								data-id="4496" data-uid="63" data-user=""> 
								<a href="/user/taso"> 
									<img class="avatar" alt="taso" src="/user_pics/med_bc42066667df4574522808493783794a.gif" /> 
								</a> 
								<p class="tap-from "> 
									<a href="/user/taso">Taso Duval</a>,
									<a href="/tap/4496" class="date" data-timestamp="1271190676"> 
										3 hours, 10 minutes ago									</a> 
									<a href="/group/jquery-dev " /> 
										<img class="aggr-favicons" src="/group_pics/fav_e7da889ea2d65435cf1ccccaecfc28f1.gif" title="jquery-dev " /> 
									</a> 
								</p> 
								<p class="tap-body"> 
									jQuery Dev, terrific :)								</p> 
								<p class="tap-actions"> 
									<span class="tap-resp"> 
										<span class="indicator">Someone's replying..</span> 
										<span class="last-resp"> 
											<strong></strong> 
											<span class="body ellipsis inblock"></span> 
										</span> 
									</span> 
									<a href="#" class="tap-resp-count" title="view responses"> 
										<span class="count"> 
											0										</span> 
									</a> 
									<span class="tap-view-count count" title="viewers"> 
										1									</span> 
								</p> 
								<div class="responses"> 
									<ul class="chat"> 
									</ul> 
									<input class="chatbox" type="text" /> 
									<div class="counter">240</div> 
									<div class="overlay">type in your response and press enter.</div> 
								</div> 
							</li> 
														<li id="tid_4495" class="container" 
								data-id="4495" data-uid="63" data-user=""> 
								<a href="/user/taso"> 
									<img class="avatar" alt="taso" src="/user_pics/med_bc42066667df4574522808493783794a.gif" /> 
								</a> 
								<p class="tap-from "> 
									<a href="/user/taso">Taso Duval</a>,
									<a href="/tap/4495" class="date" data-timestamp="1271190661"> 
										3 hours, 10 minutes ago									</a> 
									<a href="/group/python-dev " /> 
										<img class="aggr-favicons" src="/group_pics/fav_71f0aa010272ba2f43e46e05edd5108f.gif" title="python-dev " /> 
									</a> 
								</p> 
								<p class="tap-body"> 
									Going well?								</p> 
								<p class="tap-actions"> 
									<span class="tap-resp"> 
										<span class="indicator">Someone's replying..</span> 
										<span class="last-resp"> 
											<strong></strong> 
											<span class="body ellipsis inblock"></span> 
										</span> 
									</span> 
									<a href="#" class="tap-resp-count" title="view responses"> 
										<span class="count"> 
											0										</span> 
									</a> 
									<span class="tap-view-count count" title="viewers"> 
										1									</span> 
								</p> 
								<div class="responses"> 
									<ul class="chat"> 
									</ul> 
									<input class="chatbox" type="text" /> 
									<div class="counter">240</div> 
									<div class="overlay">type in your response and press enter.</div> 
								</div> 
							</li> 
														<li id="tid_4494" class="container" 
								data-id="4494" data-uid="63" data-user=""> 
								<a href="/user/taso"> 
									<img class="avatar" alt="taso" src="/user_pics/med_bc42066667df4574522808493783794a.gif" /> 
								</a> 
								<p class="tap-from "> 
									<a href="/user/taso">Taso Duval</a>,
									<a href="/tap/4494" class="date" data-timestamp="1271190650"> 
										3 hours, 10 minutes ago									</a> 
									<a href="/group/python-dev " /> 
										<img class="aggr-favicons" src="/group_pics/fav_71f0aa010272ba2f43e46e05edd5108f.gif" title="python-dev " /> 
									</a> 
								</p> 
								<p class="tap-body"> 
									How's Python Dev going?								</p> 
								<p class="tap-actions"> 
									<span class="tap-resp"> 
										<span class="indicator">Someone's replying..</span> 
										<span class="last-resp"> 
											<strong></strong> 
											<span class="body ellipsis inblock"></span> 
										</span> 
									</span> 
									<a href="#" class="tap-resp-count" title="view responses"> 
										<span class="count"> 
											0										</span> 
									</a> 
									<span class="tap-view-count count" title="viewers"> 
										1									</span> 
								</p> 
								<div class="responses"> 
									<ul class="chat"> 
									</ul> 
									<input class="chatbox" type="text" /> 
									<div class="counter">240</div> 
									<div class="overlay">type in your response and press enter.</div> 
								</div> 
							</li> 
								
						<!-- <div class="full info form">
							<p>Tap is invite-only for now. If you want to be one of our early beta testers, you can fill up the form below and we'll send you an exclusive invite.</p>

							<h2>email address</h2>
							<p class="center"><input type="text" class="basic stretch big" /></p>
							
							<h2>full name</h2>
							<p class="center"><input type="text" class="basic stretch big" /></p>

							<h2>where did you hear about tap?</h2>
							<p class="center"><input type="text" class="basic stretch big" /></p>
							
							<p class="buttons">
								<button type="submit" class="action">send me an invite!</button>
							</p>
						</div>
						-->

					</div>
				</div>
			</div>

		</div>
		
		<div class="clarity"></div>
		
		<div id="footer">
			<strong>tap &copy; 2010.</strong>
			<span class="nav">
				<a href="/" class="current">home</a>
				<a href="/what">what's tap?</a>
				<a href="/about">about us</a>
				<a href="/devs">developers</a>
				<a href="/contact">contact</a>
			</span>
		</div>
	</div>
	
	<?include(JAVASCRIPT_TEMPLATES)?>

<script type="text/javascript">
var _gaq = _gaq || [];
 _gaq.push(['_setAccount', 'UA-11153159-1']);
 _gaq.push(['_trackPageview']);

 (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
 })();
</script>
</body>
</html>
