<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>TAP :: BETA</title>

<link rel="shortcut icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="views/style_sheets/group_manage.css" type="text/css" />
<link rel="stylesheet" href="views/style_sheets/homepage.css" type="text/css" />
<script type="text/javascript" src="views/javascript/mootools-1.2.3-core-yc.js"></script>
<script type="text/javascript" src="views/javascript/mootools-1.2.3.1-more.js"></script>
<script type="text/javascript" src="views/javascript/mootools-tap.js"></script>
<script type="text/javascript" src="http://mark.tap.info:8000/static/Orbited.js"></script>
<script type="text/javascript" src="views/javascript/tap.main.js"></script>
<script type="text/javascript" src="views/javascript/mpmetrics.js"></script>
<script type="text/javascript"> try { mpmetrics.init('<?= METRIC_KEY ?>');} catch(err) { alert(err) } </script>
</head>

<body>

	<?php include(LOGOUT_HEADER); ?>

	<div id="main">

		<div class="left-col" style="margin-right: 20px">
			<div id="groups-tab" style="background-image:url(/images/cimages/tab_grey.gif);">
				<div class="tab-in" style="color:#fff;">What's This?</div>
			</div>
			<div class="tab-list">
				<p>Tap allows you to connect with people around you and stay informed about topics you're interested in.  Use Tap to see what you and your friends are doing, what people around you are doing, and connect with link-minded individuals. Join Tap today!</p>
			</div>
			<div id="groups-tab">
				<div class="tab-in" style="color:#fff">Trending Groups</div>
			</div>
			<div class="tab-list">
				<ul>
					<?php foreach($_t['trending_groups'] as $trending): ?>
						<li class="list-item" style="height:30px">
							<p style="height: 14px;"><span class="suggestion-item"><img src="/group_pics/<?= $trending['pic_36'] ?>" style="float:left; margin-right: 10px" /><strong><?= $trending['gname'] ?></strong> (<?= $trending['count'] ?>)</span></p>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>

		<div id="center-col">

			<?php if (!empty($_t['errors'])): ?>
			<div class="section error">
				<?= $_t['errors'] ?>
			</div>
			<?php endif; ?>

			<div id="tap-feed" class="section">
				<div class="section-head">
					<h1>
						<img id="tap-feed-icon" src="/group_pics/36wh_default_group.gif" style="float:left; margin-right:10px; height: 20px; width: 20px" />
						<span id="tap-feed-name">Look Who's Tapping!</span>
					</h1>
				</div>
				<div class="section-body">
					<ul id="main-stream" class="tap-stream">
						<?php
							if (!empty($_t['logout_bits'])):
								foreach($_t['logout_bits'] as $bit):
						?>
						<li id="tid_<?= $bit['cid'] ?>">
							<img src="/user_pics/<?= $bit['pic_100'] ?>" class="avatar" alt="<?= $bit['uname'] ?>" />
							<div class="tap-actions">
								<span class="tap-respond" style="color:#000">Responses <span class="tap-respond-count">(<?= $bit['count'] ?>)</span></span>
								<p class="tap-respond-last">
									<strong>
										<?= (!empty($bit['resp_uname'])) ? $bit['resp_uname'] . ":" : "" ?>
									</strong>
									<?= $bit['last_resp'] ?>
								</p>
							</div>
							<div class="tap-body">
								<p class="tap-info">
									<span class="tap-from"><?= $bit['fname'] . " " . $bit['lname'] ?></span>
									<span class="tap-time <?= $bit['chat_timestamp_raw'] ?>"><?= $bit['chat_timestamp'] ?></span>
									<span class="tap-typing"></span>
								</p>
								<p>
									<span class="tap-msg"><?= $bit['chat_text'] ?></span>
								</p>
							</div>
							<div class="tap-response-box clarity">
								<ul class="tap-chat">
								</ul>
								<input type="text" class="tap-response" style="width:450px" />
								<!-- <a href="#">Respond</a> or  --><a class="tap-respond-cancel" href="#">Close</a>
							</div>
							<div class="clarity"></div>
						</li>
						<?php
								endforeach;
							else:
						?>
						<li class="noresults">
							<p>This feed is too silent. Try sending a tap!</p>
						</li>
						<?php
							endif;
						?>
					</ul>
				</div>
			</div>
		</div>

		<div id="left-col">
			<div id="groups-tab">
				<div class="tab-in" style="color:#fff">Log in</div>
			</div>
			<div class="tab-list">
				<form id="login" action="<?=ROOT?>" method="POST">
					<label>Username</label>
						<input type="text" id="uname" name="uname" class="text" />
					<label>Password</label>
						<input type="password" id="pass" name="pass" class="text" />
					<br/>
					<input type="checkbox" checked="true" id="auto_login" name="auto_login" />
					<label class="in-form">Keep Me Logged In</label>
					<input type="submit" id="signin-submit" value="Sign In" />
				</form>
			</div>

			<div id="signup-tab">Sign-up
				<div id="signup-title">Its very easy<br />and it wont take you<br />more than 45 seconds.</div>
			</div>
			<div id="signup-form">
				<label>Username</label>
					<input type="text" name="user" class="text"/>
					<div class="guide"></div>
				<label>Full Name</label>
					<input type="text" name="name" class="text"/>
					<div class="guide"></div>
				<label>E-mail</label>
					<input type="text" name="email" class="text"/>
					<div class="guide"></div>
				<label>Password</label>
					<input type="password" name="pass" class="text"/>
					<div class="guide"></div>
				<label>Retype Password</label>
					<input type="password" name="passrepeat" class="text"/>
					<div class="guide"></div>
				<input type="submit" id="signup-submit" value="Sign me up!" />
			</div>
		</div>

	</div>

	<div id="footer">

	</div>

</body>
</html>
