<?php
function map_clean($func, $arr) {
	return array_filter(array_map($func, $arr));
}

// Taps
$last = (!empty($last_tap)) ? $last_tap[0] : null;

$inits = array(); $people = array();
if (is_array($groups_bits)) {
	function get_cids($bit) { return $bit['cid']; }
	$inits = map_clean("get_cids", $groups_bits);

	function get_uids($bit) { return $bit['uid']; }
	$people = map_clean("get_uids", $groups_bits);
}

$convos = array();
if (is_array($active_convos)) {
	function get_mids($bit) { return $bit['mid']; }
	$convos = map_clean("get_mids", $active_convos);
}

$groups = array(); $groups_online = array();
if (is_array($your_groups)) {
	function get_gids($bit) { return $bit['gid']; }
	//$groups = map_clean("get_gids", $your_groups);

	$count=0;
	foreach($your_groups as $k => $v){
		$groups[$count] = $k;
		$count++;
	}
	foreach ($your_groups as $group){
		$groups_online[$group['gid']] = $group['online_count'];
	}
}

$all_your_groups_topic = "Aggregate feed of all of the channels";
$public_groups_topic = "This is a place where you can discover what's being said in real-time from all channels, even if you're not apart of them";
if ($feed_type == 'all') {    
    $groups_descr = $all_your_groups_topic;
    $start_gid = "all";
    $groups_topic = "All Your Channels";
} else {
    $groups_descr = $public_groups_topic;
    $start_gid = "public";
    $groups_topic = "Discover";
}
?>
<!doctype html>
<html>
<head>
	<? 
	$tpl_title = "Home";
	include(OK_HEADER);
	?>
    <link title="" type="application/rss+xml" rel="alternate" href="http://<?=$_SERVER['SERVER_NAME']?>/rss.xml"/>

	<script type="text/javascript" src="/views/scripts/tap.js"></script>
	<script type="text/javascript">
        window._vars = {
            user: <?= json_encode($me) ?>,
            stream: <?= json_encode($inits) ?>,
            convos: <?= json_encode($convos) ?>,
            people: <?= json_encode($people) ?>,
            groups: <?= json_encode($groups) ?>,
            groupsOnline: <?= json_encode($groups_online) ?>,
            sendTo: "public:public:0:0",
            filter: {
                gid: "<?=$start_gid?>",
                info: {
                    name: "<?=$groups_topic?>"
                }
            }
        };
	</script>
	<script type="text/javascript" src="/views/scripts/push.js"></script>
	<script type="text/javascript" src="/views/scripts/public.js"></script>
	<script type="text/javascript" src="/views/scripts/sidebar.js"></script>
	<script type="text/javascript" src="/views/scripts/filter.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
	
</head>
<body>
				
<div id="wrapper">
		
	<? include(OK_TOPBAR); ?> 

	<div id="main">

		<?
		$show_lists  = true;
		$show_search = false;
		include(NEW_SIDEBAR);
		?>

			<div id="content">

				<!--
				<form id="tapbox" action="" class="section active">
					<div id="tapto">choose a channel to tap</div>
					<span class="counter">240</span>
					<input id="taptext" tabindex="1" type="text" disabled="true" style="background:gray;">
					<button id="tapsend" tabindex="3" type="submit" class="">tap!</button>
					<span id="no-group-selected"><b>You need to tap to a channel!</b> Tap to a channel by clicking on the channel tab or searching for new channels to tap</span>
				</form>
				-->


				<div id="tapstream" class="section description">
					<div class="header">
						<a id="newtaps" href="" class="floater">This feed has 5 new taps! Click here to load them.</a>
						<h2 class="header-title">
							<img src="/images/flat/loader.gif" />
							<span class="title">feed</span>
						</h2>
						<span class="stream-name"><?=$groups_topic?> <?php if(isset($facebook_loginUrl)): ?><a href="<?php echo $facebook_loginUrl; ?>">Login to facebook to see your other channels</a><?php endif; ?></span>
					</div>
					<div class="description" style="padding:15px;"><?= $groups_descr ?></div>
					<div class="body">
                        <?php
                            $_taps = $groups_bits;
                            include(TAP_STREAM);
                        ?>
					</div>
				</div>
			</div>



		</div>
	</div>

    <?include(OK_FOOTER)?>

</body>
</html>
