<?php
$last = $_t['last_tap'][0];
$inits = array();
foreach($_t['groups_bits'] as $bit) {
	array_push($inits, $bit['cid']);
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>TAP :: BETA</title>

<link rel="shortcut icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<style type="text/css" media="all">@import "views/style_sheets/TextboxList.css";</style>
<style type="text/css" media="all">@import "views/style_sheets/TextboxList.Autocomplete.css";</style>
<link rel="stylesheet" href="views/style_sheets/group_manage.css" type="text/css" />
<link rel="stylesheet" href="views/style_sheets/homepage.css" type="text/css" />
<script type="text/javascript" src="views/javascript/mootools-1.2.3-core-yc.js"></script>
<script type="text/javascript" src="views/javascript/mootools-1.2.3.1-more.js"></script>
<script type="text/javascript" src="views/javascript/textboxlist-complete.js"></script>
<script type="text/javascript" src="views/javascript/mootools-tap.js"></script>
<script type="text/javascript" src="http://mark.tap.info:8000/static/Orbited.js"></script>
<script type="text/javascript">
Tap = window.Tap || {};
Tap.Vars = {
	pcid: ("<?= $_t['pcid'] ?>" * 1),
	currentTap: ("<?= $last['cid'] ?>" * 1),
	currentStream: JSON.decode('<?= json_encode($inits) ?>')
};
</script>
<script type="text/javascript" src="views/javascript/tap.push.js"></script>
<script type="text/javascript" src="views/javascript/tap.home.js"></script>
</head>

<body>

	<?php include(NEW_HEADER); ?>
	
	<div id="tap-feed-outside-more">
		<p>
			<input type="checkbox" name="outside-show" />
			<label for="show-outside">Show Outside Taps</label>							
		</p>
		<p>
			<label>From: </label><br />
			<input type="text" name="outside-from" />				
		</p>
		<p>
			<a href="#" id="tap-feed-outside-set">Save</a>
		</p>
	</div>

	<div id="main">

		<div id="right-col">
			<h1>Help and Tips</h1>
			<h2>Find your groups faster.</h2>
			<p>You can search through your own groups by filtering them out using the filter-bar. Simply enter in a keyword and hit enter, and all corresponding groups will be displayed.</p>
			<h2>Don't overuse your memes.</h2>
			<p>It might have been funny the first time you heard it, but most memes are notorious for expiring quickly. Avoid the social awkwardness produced by using an expired meme by not using them when they near their expiry date. Common memes expire within 3 days. Celebrity memes expire with a week, and cat-related ones are good for at least a month. When in doubt, consult your local /b/.</p>
			<h2>More options for search.</h2>
			<p>When searching, you can optionally toggle the "more" link to give you the option of adding location and focus criteria to narrow down your search.</p>
			<h2>Share your groups via invites.</h2>
			<p>You can send invites to your friends who might be interested in a group you belong to. Simply click on the Invite button and write their email addresses or usernames and send.</p>
		</div>

		<div id="center-col">
			<div id="tap-box" class="section">
				<input type="text" id="tap-box-msg" alt="Tap here!" />
				<div id="tap-box-more">
					<a id="tap-box-send" href="#">Send</a>
					<input type="text" id="tap-box-people" />
				</div>
			</div>

			<div id="tap-yours" class="section">
				<div class="section-head">
					<h1>
						<span id="tap-notify"></span>
						Your Last Tap
					</h1>
				</div>
				<div class="section-body">
					<ul id="your-stream" class="tap-stream">
						<li>
							<img src="/user_pics/<?= $last['pic_100'] ?>" class="avatar" alt="<?= $last['uname'] ?>" />
							<div>
								<p class="tap-info">
									<span class="tap-from"><?= $last['fname'] . " " . $last['lname'] ?></span>
									<span class="tap-time"><?= $last['chat_timestamp'] ?></span>
								</p>
								<p class="tap-msg">
									<span><?= $last['chat_text'] ?></span>
								</p>
							</div>
							<div class="clarity"></div>
						</li>
					</ul>
				</div>
			</div>

			<div id="tap-feed" class="section">
				<div class="section-head">
					<h1>
						<span id="tap-feed-outside">Out</span>
						<input type="text" id="tap-feed-search" alt="Search through feed." />
						<span id="tap-feed-name">Groups Feed</span>
						<img src="/images/loading.gif" id="loading-indicator" style="display:none" />
					</h1>
				</div>
				<div class="section-body">
					<ul id="main-stream" class="tap-stream">
						<?php foreach($_t['groups_bits'] as $bit): ?>
						<li id="tid_<?= $bit['cid'] ?>">
							<img src="/user_pics/<?= $bit['pic_100'] ?>" class="avatar" alt="<?= $bit['uname'] ?>" />
							<div class="tap-actions">
								<a class="tap-respond" href="#">Respond</a>
							</div>
							<div class="tap-body">
								<p class="tap-info">
									<span class="tap-from"><?= $bit['fname'] . " " . $bit['lname'] ?></span>
									<span class="tap-time"><?= $bit['chat_timestamp'] ?></span>
									<span class="tap-typing"></span>
								</p>
								<p>
									<span class="tap-msg"><?= $bit['chat_text'] ?></span>
								</p>
							</div>
							<div class="tap-response-box clarity">
								<ul class="tap-chat">
								</ul>
								<textarea class="tap-response" cols="50" rows="1"></textarea>
								<!-- <a href="#">Respond</a> or  --><a class="tap-respond-cancel" href="#">Close</a>
							</div>
							<div class="clarity"></div>
						</li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>
		</div>

		<div id="left-col">
			<div id="groups-tab">
				<div class="tab-in"><a href="" class="name">My Groups</a></div>
			</div>
			<div class="tab-list">
				<ul>
					<li id="gid_all" class="group">
						<span class="counter"></span>
						<img src="/group_pics/36wh_default_group.jpg" />
						<a href="#" title="Groups Feed">All Your Groups</a>
					</li>
					<?php foreach ($_t['your_groups'] as $group): ?>
					<li id="gid_<?= $group['gid'] ?>" class="group">
						<span class="counter"></span>
						<img src="/group_pics/<?= $group['pic_36']?>" />
						<a href="#<?= $group['symbol'] ?>" title="<?= $group['gname'] ?>"><?= $group['symbol'] ?></a>
					</li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>

	</div>

	<div id="templates" style="display:none">
		<ul id="template-bit">
			<# for (var x = this.reverse().length; x--;) { var bit = this[x]; #>
			<li id="tid_<#: bit.cid #>">
				<img src="/user_pics/<#: bit.pic_100 #>" class="avatar" alt="<#: bit.uname #>" />
				<div class="tap-actions">
					<a class="tap-respond" href="#">Respond</a>
				</div>
				<div class="tap-body">
					<p class="tap-info">
						<span class="tap-from"><#: [bit.fname, bit.lname].join(" ") #></span>
						<span class="tap-time"><#: bit.chat_timestamp #></span>
						<span class="tap-typing"></span>
					</p>
					<p>
						<span class="tap-msg"><#: bit.chat_text #></span>
					</p>
				</div>
				<div class="tap-response-box clarity">
					<ul class="tap-chat">
					</ul>
					<textarea class="tap-response" cols="50" rows="1"></textarea>
					<!-- <a href="#">Respond</a> or  --><a class="tap-respond-cancel" href="#">Close</a>
				</div>
				<div class="clarity"></div>
			</li>
			<# } #>
		</ul>
		<ul>
			<li id="no-taps" class="noresults">
				<p>There doesn't seem to be anything here.</p>
			</li>
			<li id="no-results" class="noresults">
				<p>
					No taps match your search keyword.
					<a href="#" class="reset-feed">Show all taps.</a>
				</p>
			</li>
		</ul>
	</div>

	<div id="footer">

	</div>

</body>
</html>
