<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11153159-1");
pageTracker._trackPageview();
} catch(err) {}</script>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>tap - alpha</title>

<link rel="shortcut icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="views/style_sheets/group_manage.css" type="text/css" />
<link rel="stylesheet" href="views/style_sheets/homepage.css" type="text/css" />
<script type="text/javascript" src="/views/javascript/mootools-1.2.3-core-yc.js"></script>
<script type="text/javascript" src="/views/javascript/mootools-1.2.3.1-more.js"></script>
<script type="text/javascript" src="/views/javascript/mootools-tap.js"></script>
<script type="text/javascript" src="/views/javascript/tap.main.js"></script>
<script type="text/javascript" src="/views/javascript/mpmetrics.js"></script>
<script type="text/javascript"> try { mpmetrics.init('<?= METRIC_KEY ?>');} catch(err) {} </script>
<style type="text/css" media="screen">
#signup-guide {
	display: none;
	text-align: center;
	margin-top: 15px;
	margin-right: 10px;
	padding: 5px;
	background: #C9DEFB;
	border-top: 1px solid #BBD0EE;
	border-bottom: 1px solid #BBD0EE;
}

#connect-guide {
	margin-top: 5px;
	margin-bottom: 10px;
	padding: 5px;
	text-align: center;
	background: #C9DEFB;
	border-top: 1px solid #BBD0EE;
	border-bottom: 1px solid #BBD0EE;
	margin-right: 8px;
	display: none;
}

ul.pitch {
	margin-bottom: 10px;
	font-size: 16px;
	list-style: square;
	font-weight: bold;
}

ul.pitch li {
	margin-bottom: 10px;
	color: #007AE5;
	margin-left: -3px;
}

#rotator {
	height: 257px;
	background: url(/images/cimages/demo/tap123-1.gif) no-repeat center center;
}

#rotator-text {
	font-size: 14px;
	position: absolute;
	bottom: 0;
	left: 0;
	right: 0;
	padding: 5px;
	background: #F2F2F2;
	opacity: .8;
}

#rotator-text strong {
/*	font-weight: normal;*/
	color: #3F5C06;
}

#rotator-icon {
	background: url(/images/cimages/demo/4.PNG) no-repeat;
	height: 74px;
	width: 55px;
	position: absolute;
	right: 2px;
	top: 2px;
}

#fblogin img {
	margin-top: 20px;
	margin-left: 20px;
}

#curtain {
	display: none;
	position: absolute;
	background: #000;
	height: 100%;
	width: 100%;
	z-index: 1;
	top: 0;
}

#connect-signup {
	display: none;
	position: absolute;
	width: 500px;
	z-index: 2;
	background: #F2F2F2;
	top: 100px;
	left: 200px;
	border: 1px solid #ccc;
	padding: 10px;
}

#connect-signup h2 {
	border-bottom: 2px solid #ccc;
	color: #333;
	font-weight: bold;
	margin-bottom: 10px;
}

#connect-signup p {
	margin-bottom: 10px;
	font-size: 13px;
}

#connect-signup span.indicator {
	display: none;
}

#connect-signup p.forms {
	margin-top: 10px;
	padding-left: 30px;
	clear: both;
}

#connect-signup label {
	font-size: 16px;
	margin-top: 20px;
	font-weight: bold;
	color: #3088ED;
}

#connect-signup p.guide {
	display: none;
	margin-top: -5px;
	text-align: right;
	padding-right: 60px;
	margin-bottom: 10px;
	clear: both;
	color: #F12C46;
}

#connect-signup input {
	border: 1px solid #ccc;
	padding: 5px;
	float: right;
	margin-right: 50px;
	width: 300px;
	font-size: 16px;
	margin-bottom: 10px;
}

#connect-signup input.error {
	background: #FDEBEB;
}

#connect-signup input.passed {
	background: #EEFDEB;
}

#connect-signup button {
	font-size: 16px;
}
</style>
<script type="text/javascript">
window.addEvent('load', function(){
	mpmetrics.track('main-view', {'type': Tap.Vars.ref ? 'referral' : 'direct'});
});

window.addEvent('domready', function(){
var rotates = $H({
	'/images/cimages/demo/tap123-1.gif': '<strong>#1 — Join groups, schools and companies related to your life.</strong><br/> \
	#2 — Send messages to those groups, and search for others to target too!<br/> \
	#3 — Discuss whatever you\'ve said with the group in real-time, like chat!',

	'/images/cimages/demo/tap123-2.gif': '#1 — Join groups, schools and companies related to your life.<br/> \
	<strong>#2 — Send messages to those groups, and search for others to target too!</strong><br/> \
	#3 — Discuss whatever you\'ve said with the group in real-time, like chat!',

	'/images/cimages/demo/tap123-3.gif': '#1 — Join groups, schools and companies related to your life.<br/> \
	#2 — Send messages to those groups, and search for others to target too!<br/> \
	<strong>#3 — Discuss whatever you\'ve said with the group in real-time, like chat!</strong>'
});
var current = 1;
function rotate(){
	var images = rotates.getKeys();
	var text = rotates.getValues();
	$('rotator').setStyle('background-image', 'url(' + images[current] + ')');
	// $('rotator-text').set('html', text[current]);
	current = (current == 2) ? 0 : current + 1;
	arguments.callee.delay(7000);
};
rotate.delay(7000);
});
</script>

</head>

<body>

	<div id="curtain"></div>
	<div id="connect-signup">
		<h2>Just one more thing before we log you in..</h2>
		<p>We're almost there <strong><span id="connect-signup-name"></span></strong>, but first we'll need you to add a few more details to personalize your Tap experience.</p>
		<input type="text" name="name" style="display:none" />
		<p class="forms" style="margin-top:30px"><label>Username</label> <input type="text" name="uname" /></p>
		<p class="guide">This username is already taken.</p>
		<p class="forms"><label>Email</label> <input type="text" name="email" /></p>
		<p class="guide">Enter a valid email address.</p>
		<p class="forms"><label>Password</label> <input type="password" name="pass" /></p>
		<p class="guide">Passwords must be at least 4 characters.</p>
		<p style="margin-top: 50px; text-align: right; font-size: 14px; margin-right: 20px">
			<span class="indicator">
				<img src="/images/spinner.gif" /> 
				<span class="indic-msg">Signing you up...</span>
			</span> 
			<span id="connect-signup-actions">
				<button>Start Tapping!</button> or <a id="connect-cancel" href="#">close</a>
			</span>
		</p>
	</div>

	<?php include(LOGOUT_HEADER); ?>

	<div id="main">

		<div class="left-col" style="margin-right: 20px">
			<div id="groups-tab">
				<div class="tab-in" style="color:#fff">Log in</div>
			</div>
			<div class="tab-list">
				<form id="tap-login" action="<?=ROOT?>" method="POST">
					<label>Username</label>
						<input type="text" id="login-uname" name="uname" class="text" />
					<label>Password</label>
						<input type="password" id="login-pass" name="pass" class="text" />
					<br/>
					<input type="checkbox" checked="true" id="auto_login" name="auto_login" />
					<label class="in-form">Keep Me Logged In</label>
					<input type="submit" id="signin-submit" value="Sign In" />
				</form>
				<fb:login-button id="fblogin" onlogin="on_connect()" onclick="click_connect()"></fb:login-button>
			</div>
			<!--
			<div id="groups-tab">
				<div class="tab-in" style="color:#fff;">What's Tap?</div>
			</div>
			<div class="tab-list">
				<ul class="pitch">
					<li>&bull; Real-time discussions.</li>
					<li>&bull; Join groups you're interested in.</li>
					<li>&bull; Keep informed about the latest happenings.</li>
					<li>&bull; Stay connected about anything and everything</li>
				</ul>
				<p style="font-size:12px"><strong>Tap allows you to connect with people around you and stay informed about topics you're interested in.</strong></p>
			</div>
			<div id="groups-tab">
				<div class="tab-in" style="color:#fff">Trending Groups</div>
			</div>
			<div class="tab-list">
				<ul>
					<?php foreach($_t['trending_groups'] as $trending): ?>
						<li class="list-item trending" style="height:30px; cursor:pointer">
							<p style="height: 14px;"><span class="suggestion-item"><img src="/group_pics/<?= $trending['pic_36'] ?>" style="float:left; margin-right: 10px" /><strong><?= $trending['gname'] ?></strong> (<?= $trending['count'] ?>)</span></p>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
			-->
		</div>

		<div id="center-col">

			<?php if (!empty($_t['errors'])): ?>
			<div class="section error">
				<?= $_t['errors'] ?>
			</div>
			<?php endif; ?>

			<?php if ($_GET['q'] === 'swineflu'): ?>
			<div class="section info" style="text-align:center; font-size: 14px">
				Join the SwineFlu Conversation!
			</div>
			<?php endif; ?>

			<div id="rotator" class="section">

			</div>

			<!-- 			<div id="rotator-icon"></div>
						<div id="rotator-text">
							<strong>#1 — Join groups, schools and companies related to your life.</strong><br/>
							#2 — Send messages to those groups, and search for others to target too!<br/>
							#3 — Discuss whatever you've said with the group in real-time, like chat!
						</div>
			<div id="search-public" class="section">
				<span class="spiel">Go on, search for something!</span>
				<input type="text" id="search-public-keyword" />
				<input id="search-public-submit" type="submit" value="Search" />
			</div>
						 -->

			<div id="tap-feed" class="section">
				<div class="section-head">
					<h1>
						<input type="text" id="tap-feed-search" alt="Search through feed." />
						<img id="tap-feed-icon" src="/group_pics/36wh_default_group.gif" style="float:left; margin-right:10px; height: 20px; width: 20px" />
						<span id="tap-feed-name">Look Who's Tapping!</span>
						<img src="/images/loading.gif" id="loading-indicator" style="display:none" />
					</h1>
				</div>
				<div class="section-body">
					<ul id="main-stream" class="tap-stream">
						<?php
							if (!empty($_t['logout_bits'])):
								foreach($_t['logout_bits'] as $bit):
						?>
						<li id="tid_<?= $bit['cid'] ?>">
							<img src="/user_pics/<?= $bit['pic_100'] ?>" class="avatar" alt="<?= $bit['uname'] ?>" />
							<div class="tap-actions">
								<a href="#" class="tap-respond" style="color:#000">Responses <span class="tap-respond-count">(<?= $bit['count'] ?>)</span></a>
								<p class="tap-respond-last">
									<strong>
										<?= (!empty($bit['resp_uname'])) ? $bit['resp_uname'] . ":" : "" ?>
									</strong>
									<?= $bit['last_resp'] ?>
								</p>
							</div>
							<div class="tap-body">
								<p class="tap-info">
									<span class="tap-from">
										<a href="/user/<?= $bit['uname'] ?>">
										<?= $bit['fname'] . " " . $bit['lname'] ?>
										</a>
									</span>
									<a href="/tap/<?= $bit['cid'] ?>">
									<span class="tap-time <?= $bit['chat_timestamp_raw'] ?>"><?= $bit['chat_timestamp'] ?>
									</span>
									</a>
									<span class="tap-typing"></span>
								</p>
								<p>
									<span class="tap-msg"><?= $bit['chat_text'] ?></span>
								</p>
							</div>
							<div class="tap-response-box clarity">
								<ul class="tap-chat out">
								</ul>
								<input type="text" class="tap-response" disabled="disabled" style="width:440px" alt="Sign in to see responses." />
								<!-- <a href="#">Respond</a> or  --><a class="tap-respond-cancel" href="#">Close</a>
							</div>
							<div class="clarity"></div>
						</li>
						<?php
								endforeach;
							else:
						?>
						<li class="noresults">
							<p>This feed is too silent. Try sending a tap!</p>
						</li>
						<?php
							endif;
						?>
					</ul>
				</div>
			</div>
		</div>

		<div id="left-col">
			<div id="signup-tab" style="margin-top:0">Sign-up
				<div id="signup-title">Its very easy<br />and it wont take you<br />more than 45 seconds.</div>
			</div>
			<div>
				<form id="signup-form" action="#" method="post">
					<div id="connect-guide">
						<strong>FB Connect Done!</strong><br />
						We just need a little more info!
					</div>
					<label>Username</label>
						<input type="text" name="user" class="text"/>
						<div class="guide"></div>
					<label>Full Name</label>
						<input type="text" name="name" class="text"/>
						<div class="guide"></div>
					<label>E-mail</label>
						<input type="text" name="email" class="text"/>
						<div class="guide"></div>
					<label>Password</label>
						<input type="password" name="pass" class="text"/>
						<div class="guide"></div>
					<!--
					<label>Retype Password</label>
						<input type="password" name="passrepeat" class="text"/>
						<div class="guide"></div>
					-->
					<label style="display:none">Primary Language</label>
						<select name="language" class="text" style="display:none">
							<option value="English" selected="selected">English</option>
							<option value="Afrikaans">Afrikaans</option>
							<option value="Albanian">Albanian</option>
							<option value="Aragonese">Aragonese</option>
							<option value="Asturian">Asturian</option>
							<option value="Azeri">Azeri</option>
							<option value="Basque">Basque</option>
							<option value="Belarusian">Belarusian</option>
							<option value="Breton">Breton</option>
							<option value="Catalan">Catalan</option>
							<option value="Cebuano">Cebuano</option>
							<option value="Cornish">Cornish</option>
							<option value="Corsican">Corsican</option>
							<option value="Croatian">Croatian</option>
							<option value="Czech">Czech</option>
							<option value="Danish">Danish</option>
							<option value="Dutch">Dutch</option>
							<option value="English">English</option>
							<option value="Esperanto">Esperanto</option>
							<option value="Estonian">Estonian</option>
							<option value="Faroese">Faroese</option>
							<option value="Finnish">Finnish</option>
							<option value="French">French</option>
							<option value="Frisian">Frisian</option>
							<option value="Friulian">Friulian</option>
							<option value="Fula (Pulaar)">Fula (Pulaar)</option>
							<option value="Gaelic (Scottish)">Gaelic (Scottish)</option>
							<option value="Galician">Galician</option>
							<option value="German">German</option>
							<option value="Gikuyu">Gikuyu</option>
							<option value="Guaraní">Guaraní</option>
							<option value="Hausa">Hausa</option>
							<option value="Hawai'ian">Hawai'ian</option>
							<option value="Hungarian">Hungarian</option>
							<option value="Icelandic">Icelandic</option>
							<option value="Ido">Ido</option>
							<option value="Igbo">Igbo</option>
							<option value="Indonesian">Indonesian</option>
							<option value="Insubric">Insubric</option>
							<option value="Interlingua">Interlingua</option>
							<option value="Irish">Irish</option>
							<option value="Italian">Italian</option>
							<option value="Javanese">Javanese</option>
							<option value="Kikongo">Kikongo</option>
							<option value="Kinyarwanda">Kinyarwanda</option>
							<option value="Kirundi">Kirundi</option>
							<option value="Latin">Latin</option>
							<option value="Latvian">Latvian</option>
							<option value="Lingala">Lingala</option>
							<option value="Lithuanian">Lithuanian</option>
							<option value="Luganda">Luganda</option>
							<option value="Luxembourgish">Luxembourgish</option>
							<option value="Maori">Maori</option>
							<option value="Malay">Malay</option>
							<option value="Maltese">Maltese</option>
							<option value="Manx">Manx</option>
							<option value="Moldovan">Moldovan</option>
							<option value="Nahuatl (post Spanish Conquest)">Nahuatl (post Spanish Conquest)</option>
							<option value="Navaho or Navajo">Navaho or Navajo</option>
							<option value="Ndebele">Ndebele</option>
							<option value="Norwegian">Norwegian</option>
							<option value="Occitan">Occitan</option>
							<option value="Orobic">Orobic</option>
							<option value="Oromo">Oromo</option>
							<option value="Polish">Polish</option>
							<option value="Portuguese">Portuguese</option>
							<option value="Quechua">Quechua</option>
							<option value="Romanian">Romanian</option>
							<option value="Samoan">Samoan</option>
							<option value="Scots">Scots</option>
							<option value="Serbian">Serbian</option>
							<option value="Shona">Shona</option>
							<option value="Slovak">Slovak</option>
							<option value="Slovenian">Slovenian</option>
							<option value="Somali">Somali</option>
							<option value="Spanish">Spanish</option>
							<option value="Swahili">Swahili</option>
							<option value="Swedish">Swedish</option>
							<option value="Tagalog/Filipino">Tagalog/Filipino</option>
							<option value="Tahitian">Tahitian</option>
							<option value="Tatar">Tatar</option>
							<option value="Tongan">Tongan</option>
							<option value="Tswana">Tswana</option>
							<option value="Turkish">Turkish</option>
							<option value="Turoyo">Turoyo</option>
							<option value="Vietnamese">Vietnamese</option>
							<option value="Võro">Võro</option>
							<option value="Walloon">Walloon</option>
							<option value="Welsh">Welsh</option>
							<option value="Wolof">Wolof</option>
							<option value="Xhosa">Xhosa</option>
							<option value="Yoruba">Yoruba</option>
							<option value="Zulu">Zulu</option>
						</select>
						<div class="guide" style="display:none"></div>
					<input type="submit" id="signup-submit" value="Sign me up!" />
					<div id="signup-guide">Signing you up..</div>
				</form>
			</div>
		</div>

	</div>

	<div id="footer">

	</div>

	<div id="templates" style="display:none">
		<ul id="template-bit">
			<# for (var x = this.reverse().length; x--;) { var bit = this[x]; #>
			<li id="tid_<#: bit.cid #>">
				<img src="/user_pics/<#: bit.pic_100 #>" class="avatar" alt="<#: bit.uname #>" />
				<div class="tap-actions">
					<a href="#" class="tap-respond" style="color:#000">Responses <span class="tap-respond-count">(<#: bit.count #>)</span></a>
					<p class="tap-respond-last">
						<strong>
							<#: bit.resp_uname ? bit.resp_uname + ":" : "" #>
						</strong>
						<#: bit.last_resp || "" #>
					</p>
				</div>
				<div class="tap-body">
					<p class="tap-info">
						<span class="tap-from">
							<a href="/user/<#: bit.uname #>">
							<#: [bit.fname, bit.lname].join(" ") #>
							</a>
						</span>
						<a href="/tap/<#: bit.cid #>">
							<span class="tap-time <#: bit.chat_timestamp_raw #>"><#: bit.chat_timestamp #></span>
						</a>
						<span class="tap-typing"></span>
					</p>
					<p>
						<span class="tap-msg"><#: bit.chat_text #></span>
					</p>
				</div>
				<div class="tap-response-box clarity">
					<ul class="tap-chat out">
					</ul>
					<input type="text" class="tap-response" disabled="disabled" style="width:450px" alt="Sign in to see responses." />
					<!-- <a href="#">Respond</a> or  --><a class="tap-respond-cancel" href="#">Close</a>
				</div>
				<div class="clarity"></div>
			</li>
			<# } #>
		</ul>
		<ul>
			<li id="no-results" class="noresults">
				<p>
					No taps match your search keyword.
					<a href="#" class="reset-feed">Show public taps.</a>
				</p>
			</li>
		</ul>
	</div>
<script src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/FeatureLoader.js.php/en_US" type="text/javascript"></script>
<script type="text/javascript">
(function(){

var curtain = $('curtain');
var connectForm = $('connect-signup');
var indic = connectForm.getElement('span.indicator');
var indic_msg = indic.getElement('span.indic-msg');
$('connect-cancel').addEvent('click', function(e){
	e.stop();
	$$(curtain, connectForm).setStyle('display', 'none')
});
var signupData = {
	name: connectForm.getElement('input[name="name"]').store('passed', true),
	uname: connectForm.getElement('input[name="uname"]'),
	email: connectForm.getElement('input[name="email"]'),
	pass: connectForm.getElement('input[name="pass"]')
};

var showError = function(el, msg){
	el.store('passed', false).addClass('error');
	el.getParent('p').getNext('p.guide').set('text', msg).setStyle('display', 'block');
};

var removeError = function(el){
	el.store('passed', true).removeClass('err').addClass('passed');
	el.getParent('p').getNext('p.guide').setStyle('display', 'none');
};

var noErrors = function(){
	return !$H(signupData).getValues().map(function(item){
		return !!item.retrieve('passed');
	}).contains(false);
};

var checkUname = function(el){
	if (el.isEmpty() || !el.ofLength(4, 20)) {
		return showError(el, 'Username must be at least 4 characters');
	} else {
		new Request({
			url: 'AJAX/check_signup.php',
			data: {
				type: 1,
				val: el.get('value')
			},
			onSuccess: function(){
				var response = JSON.decode(this.response.text);
				if (!response.available) {
					showError(el, 'This username is already taken.');
				} else {
					removeError(el);
				}
			}
		}).send();
	}
	mpmetrics.track('username-complete', {'type': Tap.Vars.ref ? 'referral' : 'direct'});
	return removeError(el);
};

var checkEmail = function(el){
	if (el.isEmpty() || !el.isEmail()) {
		return showError(el, 'Please enter a valid email.');
	} else {
		new Request({
			url: 'AJAX/check_signup.php',
			data: {
				type: 2,
				val: el.get('value')
			},
			onSuccess: function(){
				var response = JSON.decode(this.response.text);
				if (!response.available) {
					showError(el, 'This email is already used.');
				} else {
					removeError(el);
				}
			}
		}).send();
	}
	return removeError(el);
};

var checkPass = function(el){
	if (el.isEmpty() || !el.ofLength(6, 20)) {
		return showError(el, 'Password must be at least 6 characters.');
	}
	mpmetrics.track('password-complete', {'type': Tap.Vars.ref ? 'referral' : 'direct'});
	return removeError(el);
};

signupData.uname.addEvent('blur', checkUname.toHandler(this));
signupData.email.addEvent('blur', checkEmail.toHandler(this));
signupData.pass.addEvent('blur', checkPass.toHandler(this));

connectForm.getElement('button').addEvent('click', function(e){
	var self = this;
	if (noErrors()) {
		if (!connectForm.metricked) {
			mpmetrics.track('signup-forms-finished', {'type': Tap.Vars.ref ? 'referral' : 'direct'});
			connectForm.metricked = true;
		}
		new Request({
			url: 'AJAX/ajaz_sign_up.php',
			data: {
				uname: signupData.uname.get('value'),
				fname: signupData.name.get('value'),
				email: signupData.email.get('value'),
				pass: signupData.pass.get('value'),
				lang: "English",
				fid: 0,
				signup_flag: 'signup_function();'
			},
			onRequest: function(){
				$('connect-signup-actions').setStyle('display', 'none');
				indic_msg.set('text', 'Signing you up..');
				indic.setStyle('display', 'block');
			},
			onSuccess: function(){
				indic_msg.set('text', 'Logging you in..');
				mpmetrics.track('signup', {'success' : 'true', 'type': Tap.Vars.ref ? 'referral' : 'direct'}, function(){
					window.location = window.location.toString().replace('?logout=true', '');
				});
			}
		}).send();
	} else {
		$$($H(signupData).getValues().filter(function(item){
			return !item.retrieve('passed');
		})).fireEvent('blur', [e]);
	}
});

this.on_connect = function(e){
	var api = FB.Facebook.apiClient;
	var uid = api.get_session().uid;
	api.users_getInfo(uid, 'username, name, pic_square', function(data){
		if (!data) return null;
		data = data.pop();

		$('connect-signup-name').set('text', data.name);
		signupData.name.set('value', data.name);
		if (data.username) signupData.uname.set('value', data.username).fireEvent('blur', {
			stop: $empty, 
			preventDefault: $empty,
			stopPropagation: $empty
		});

		curtain.set('styles', {
			'opacity': '.3',
			'display': 'block',
			'height': window.getSize().x,
			'width': window.getWidth()
		});
		connectForm.set('styles', {
			left: (window.getSize().x / 2) - 265,
			'display': 'block'
		});
		
		signupData.uname.focus();

		/*
		var form = $('signup-form');
		if (data.username) form.getElement('input[name="user"]').set('value', data.username);
		form.getElement('input[name="name"]').set('value', data.name);
		form.getElement('input[name="email"]').focus();
		form.fireEvent('submit');
		form.highlight();
		$('connect-guide').setStyle('display', 'block');
		*/
		mpmetrics.track('fbconnect-complete', {'type': Tap.Vars.ref ? 'referral' : 'direct'});
		// window.fbconnected = true;
	});
};

this.click_connect = function(){
	mpmetrics.track('fbconnect-click', {'type': Tap.Vars.ref ? 'referral' : 'direct'});
};

FB.init("e31fd60bbbc576ac7fd96f69215268d0", "/xd_receiver.htm");

})();
</script>
<?php if (!empty($_GET['q'])): ?>
<script type="text/javascript">
if (Tap.Vars) Tap.Vars.ref = true;
</script>
<?php endif; ?>
</body>
</html>
