<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />
<title>tap - alpha</title>
<link rel="stylesheet" href="/views/style_sheets/global.css" type="text/css" />
<link rel="stylesheet" href="/views/style_sheets/groups.css" type="text/css" />
<link rel="shortcut icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<script type="text/javascript" src="/views/javascript/mootools-1.2.3-core-yc.js"></script>
<script type="text/javascript"src="/views/javascript/mootools-1.2.3.1-more.js"></script>
<script type="text/javascript" src="/views/javascript/mootools-tap.js"></script>
<script type="text/javascript" src="/views/javascript/mpmetrics.js"></script>
<script type="text/javascript"> try { mpmetrics.init('<?= METRIC_KEY ?>');} catch(err) { alert(err) } </script>
<script type="text/javascript" src="/views/javascript/tap.groups.js"></script>
<script type="text/javascript" charset="utf-8">
// Searching
var searchkey = <?= (!empty($_GET['search'])) ? json_encode($_GET['search']) : 'null' ?>;

Tap.Groups.addEvents({
	'searchSuccess': function(keyword){
		mpmetrics.track('group-search', {'success' : 'true', 'keyword': keyword});
	},
	'searchFail': function(keyword){
		mpmetrics.track('group-search', {'success' : 'false', 'keyword': keyword});
	}
});
</script>
</head>

<body>
	
	<? include(HEADER_CLEAN); ?>
	
	<div id="main">
		
		<div id="sidebar-left" class="sidebar">
			<div id="groups" class="section">
				<div class="section-head">
					<h1>Suggested Groups</h1>
				</div>
				<div class="section-body">
					<ul class="suggested-groups">
						<?php foreach ($_t['random_group_results'] as $random): ?>
						<li class="list-item">
							<p class="name">
								<a class="suggestion-item" title="<?= $random['gname'] ?>" href="/group/<?= $random['symbol'] ?>">
								<img src="/group_pics/<?= $random['pic'] ?>">
								<?php
									$gname = $random['gname'];
									echo stripslashes((strlen($gname) < 15) ? $gname : substr($gname, 0, 15) . '...');
								?>
								</a>
							</p>
							<p class="focus"><?= $random['focus'] ?></p>
						</li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>
		</div>
		
		<div id="content">
			
			<div id="gr-search" class="section">
				<p>
					Looking for new groups? 
					<input id="search-field" type="text" name="group-search"/> 
					<a id="search-btn-more" href="">more &raquo;</a> 
					<input id="search-btn"  type="submit" value="Search">
				</p>
			</div>
			
			<div id="gr-search-more">
				<div>
					<label>Location:</label>
					<input id="search-location" type="text">
					<label>Focus:</label>
					<input id="search-focus" type="text">
				</div>
			</div>
			
			<div id="gr-list" class="section">
				
				<div id="gr-header" class="section-head big">
					<h1>
						<a href="#" id="gr-filter-btn" class="set-filter"></a>
						<input id="gr-filter" type="text" name="keywords" alt="Search your groups" />
						<a id="gr-create-btn" href="/create_group"></a>
						<span>Groups</span>
					</h1>
				</div>
				
				<div id="gr-search-header">
					<p class="gr-search-title">
						Search Results (<span id="gr-search-count">No matching groups found</span>)
						| <a href="#" class="remove-search">Show Your Groups</a>
					</p>
					<p class="gr-search-pages">
						<a href="#" id="gr-search-pages-back">&laquo; Previous</a>
						<span id="gr-search-sep" style="display:none"> | </span>
						<a href="#" id="gr-search-pages-next">Next &raquo;</a>
					</p>
				</div>
				
				<div id="gr-sort">
					<p>
						<span id="sort-logo">Logo</span>
						<span id="sort-name">Name</span>
						<span id="sort-loc">Location</span>
						<span id="sort-msgs"># Msg</span>
						<span id="sort-mmbrs">Members</span>
					</p>
				</div>
				
				<div class="section-body">
					<ul id="groups-list" class="gr-listing">
						<?php
							foreach ($_t['group_results'] as $group):
								$gid = $group['gid'];
								$gname = $group['gname'];
								$admin = $group['admin'];
								$pic = $group['pic'];
								$type = $group['type'];
								$size = $group['size'];
								$official = $group['official'];
								$focus = $group['focus'];
								$descr = $group['descr'];
								$count = $group['count'];
								$last_chat = $group['last_chat'];
								$last_user = $group['last_uname'];
								$symbol = $group['symbol'];
						?>
						<li id="gr-id_<?= $gid ?>" class="listing">
							<a href="/group/<?= $symbol ?>">
								<img src="/group_pics/<?= $pic ?>" alt="group logo" class="gr-image" />
							</a>
							<div class="gr-info">
								<p>
									<?php if ($official == "*"): ?>
									<img src="/images/cimages/star.gif" alt="official group" class="gr-offic" title="This is an offical group"/>
									<?php endif; ?>
									<strong class="gr-name">
										<a href="/group/<?= $symbol ?>"><?= $gname ?></a>
									</strong>&nbsp;&nbsp;
								</p>
								<p class="gr-desc description">
									<strong><a href="#" class="leave-group">Leave this Group</a></strong><br /><br />
									<?= $descr ?><br /><br />
									<strong>Latest Tap: <?= $last_user ?></strong>&mdash;<?= stripslashes($last_chat) ?>
								</p>
								<p class="gr-desc focus"><?= $focus ?><span><a href="" class="more-btn3">more &raquo;</a></span></p>
							</div>
							<div class="gr-numbers">
								<p><strong><?= $count ?></strong></p>
							</div>
							<div class="gr-numbers">
								<p><strong><?= $size ?></strong></p>
							</div>
							<div class="gr-btns">
								<a href="" class="gr-invite-btn"></a><br />
								<? if($admin): ?>
								<a href="/group_edit?group=<?= $gid ?>" class="gr-admin-btn"></a>
								<? endif; ?>
							</div>
						</li>
						<li class="more-invite">
							<? include('modules/OpenInviter/form.php');?>
						</li>
						<?php endforeach; ?>
					</ul>
				</div>
			
			</div>
			
		</div>
		
		<div id="sidebar-right" class="sidebar">
			<div class="section">
				<div class="section-head gray">
					<h1>Help and Tips</h1>
				</div>
				<div class="section-body info">
					<h2>Find your groups faster.</h2>
					<p>You can search through your own groups by filtering them out using the filter-bar. Simply enter in a keyword and hit enter, and all corresponding groups will be displayed.</p>
					<h2>Don't overuse your memes.</h2>
					<p>It might have been funny the first time you heard it, but most memes are notorious for expiring quickly. Avoid the social awkwardness produced by using an expired meme by not using them when they near their expiry date. Common memes expire within 3 days. Celebrity memes expire with a week, and cat-related ones are good for at least a month. When in doubt, consult your local /b/.</p>
					<h2>More options for search.</h2>
					<p>When searching, you can optionally toggle the "more" link to give you the option of adding location and focus criteria to narrow down your search.</p>
					<h2>Share your groups via invites.</h2>
					<p>You can send invites to your friends who might be interested in a group you belong to. Simply click on the Invite button and write their email addresses or usernames and send.</p>
				</div>
			</div>
		</div>
		
	</div>
	
	<div id="templates">
		<ul id="search-template">
			<# for (var x = this.reverse().length; x--;) { var data = this[x]; #>
			<li id="gr-id_<#: data.gid #>" class="listing">
				<a href="/group/<#: data.symbol #>">
					<img src="/group_pics/<#: data.pic #>" alt="group logo" class="gr-image" />
				</a>
				<div class="gr-info">
					<p>
						<# if (data.official == "*") { #>
						<img src="/images/cimages/star.gif" alt="official group" class="gr-offic" />
						<# } #>
						<strong class="gr-name">
							<a href="/group/<#: data.symbol #>"><#: data.gname #></a>
						</strong>&nbsp;&nbsp;
					</p>
						<p class="gr-desc description">
							<#: data.descr #><br /><br />
							<# if (data.last_chat) { #>
							<strong>Latest Tap: </strong><#: data.last_chat || "" #>
							<# } #>
						</p>
						<p class="gr-desc focus"><#: data.focus ? data.focus : "" #><span><a href="" class="more-btn3">more &raquo;</a></span></p>
				</div>
				<div class="gr-numbers">
					<p><strong><#: data.count #></strong></p>
				</div>
				<div class="gr-numbers">
					<p><strong><#: data.size #></strong></p>
				</div>
				<div class="gr-btns">
					<# if (data["in"] == 0) { #>
					<a href="" class="gr-join-btn"></a><br />
					<p class="status" style="display:none">Please wait..</p>
					<img src="images/icons/accept.png" class="join-ok" alt="Joined" style="display:none" />
					<# } else { #>
					<img src="images/icons/accept.png" alt="Joined" /><br/>Joined!
					<!-- <img src="images/icons/accept.png" alt="Joined" /> -->
					<# } #>
				</div>
			</li>
			<li class="more-invite">
				<div>
					<p>Please enter your official email address: <input type="text" class="invitees"> <span class="gr-domain">@<#: data.symbol #></span></p>
					<p class="status"><a href="#" class="send-join">Send confirmation</a>, or <a class="cancel-invite" href="#">cancel.</a></p>
				</div>
			</li>
			<# } #>
		</ul>
		<ul id="listing-templates">
			<li id="filter-noresults" class="info">
				<div>
					<p>Sorry, there are no groups that match your filter. <a href="#" class="remove-filter">Show All</a></p>
				</div>
			</li>
			<li id="search-noresults" class="info">
				<div>
					<p>Sorry, there are no groups that match your keywords. Try searching for the abbreviations for a school, company or group. (Example: for New York University, try "NYU."<br/>If you're tired of searching, you can go back to viewing <a href="#" class="remove-search">Your Groups</a><br/>"</p>
				</div>
			</li>
			<li id="search-loading" class="info">
				<div>
					<p>Loading search results.</p>
				</div>
			</li>
		</ul>
	</div>

	<? include(ANALYTICS); ?>
	
</body>
</html>
