<?php
$logged = (!empty($_SESSION['uid']));
?>
<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Content-Language" content="en-us" />
	<meta name="robots" content="noodp" />
	<meta name="image-toolbar" content="no" />
	<meta name="copyright" content="Copyright (c) 2009 TAP" />
	<meta name="description" content="TAP communication platform" />
	<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />
	<meta name="uid" content="<?= $_t['pcid'] ?>" />
	<meta name="uname" content="<?= $_SESSION['uname'] ?>" />
	<title>tap</title>
	<link rel="stylesheet" href="/views/styles/global.css" type="text/css" />
	<script type="text/javascript" src="/views/scripts/mootools-core.js"></script>
	<script type="text/javascript" src="/views/scripts/mootools-more.js"></script>
	<script type="text/javascript" src="/views/scripts/tap.js"></script>
	<script type="text/javascript" src="/views/scripts/groups.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
</head>
<body>
	<div id="wrapper">

		<?include(HEADER)?>

		<div id="main">

			<div id="sidebar">

				<?php if ($logged): ?>
				<div id="you" class="section container">
					<img src="/user_pics/<?= $_SESSION['upic'] ?>" class="avatar" />
					<p>hello <strong><?= $_SESSION['uname'] ?></strong>!</p>
					<p class="special">
						<a href="/invite" title="Invite your friends to tap">you have 2 invites left</a>
					</p>
					<p>
						<a href="/user/<?= $_SESSION['uname'] ?>">profile</a>
						<a href="/settings">settings</a>
						<a href="/?logout=true">logout</a>
					</p>
				</div>
				<?php endif; ?>

				<div class="sideinfo section container">
					<h2>
						<span id="tab-name">groups</span>
					</h2>
					<ul class="panel">
						<li class="panel-item" >
							<span class="count"></span>
							<a href="/create_group" class="names inblock ellipsis">create new group</a>
						</li>
						<li class="panel-item" >
							<span class="count"></span>
							<a href="/invite" class="names inblock ellipsis">invite people</a>
						</li>
					</ul>
				</div>
				
			</div>

			<div id="content">
				
				<div class="section">
					<div class="header">
						<a id="newtaps" href="" class="floater"></a>
						<h2 class="header-title">
							<img src="/images/flat/loader.gif" />
							<span class="title">groups</span>
						</h2>
						<span class="stream-name">Your Groups <a href="/create_group">create group</a></span>
					</div>
					<div class="body">
						<ul class="bodylist">
							<?php
								foreach ($_t['group_results'] as $group):
									$gid = $group['gid'];
									$gname = $group['gname'];
									$admin = $group['admin'];
									$pic = $group['pic'];
									$type = $group['type'];
									$size = $group['size'];
									$official = $group['official'];
									$focus = $group['focus'];
									$descr = $group['descr'];
									$count = $group['count'];
									$last_chat = $group['last_chat'];
									$last_user = $group['last_uname'];
									$symbol = $group['symbol'];
							?>
							<li id="gid_<?= $group['gid'] ?>" class="container" 
								data-id="<?= $group['gid'] ?>" data-symbol="<?= $group['symbol'] ?>">
								<button class="invite">invite</button>
								<img src="/group_pics/<?= $group['pic'] ?>" class="avatar" />
								<h2>
									<a href="/group/<?= $group['symbol'] ?>" title="<?= $group['gname'] ?>"><?= $group['gname'] ?></a>
									<span class="nick">
										<? if ($group['admin']): ?>
										<a href="/group_edit?group=<?= $group['symbol'] ?>">Manage</a> 
										<? endif; ?>
										<a href="#" class="leave">Leave</a>
									</span>
								</h2>
								<p class="headline">&#8220;<?= $group['descr'] ?>&#8221;</p>
								<p class="stats">
									<? if ($official == "*"): ?>
									<strong>Official Group.</strong> 
									<? endif; ?>
									<strong><?= $group['size'] ?></strong> Members joined, 
									<strong><?= $group['count'] ?></strong> Taps sent, and
									<strong>0</strong> Responses received. 
								</p>
							</li>
							<?
								endforeach;
							?>
						</ul>
					</div>
				</div>

			</div>

		</div>

		<div class="clarity"></div>

		<div id="footer">
			<strong>tap &copy; 2010.</strong>
			<span class="nav">
				<a href="/">home</a>
				<a href="/groups">groups</a>
				<a href="/people">people</a>
				<a href="/settings">settings</a>
				<a href="/?logout=true">logout</a>
			</span>
		</div>
	</div>
	<?include(JAVASCRIPT_TEMPLATES)?>	
</body>
</html>
