<?php
$logged = (!empty($_SESSION['uid']));
$res = $_t['group_info_result'];
$gid = $res['gid'];
$gname = $res['gname'];
$symbol = $res['symbol'];
$focus = $res['focus'];
$desc = $res['descr'];
$pic = $res['pic_100'];
$country = $res['country'];
$state = $res['state'];
$region = $res['region'];
$town = $res['town'];
$favicon = $res['favicon'];


$invite_only = $res['invite_only'];
$invite_priv = $res['invite_priv'];
$private = $res['private'];
?>
<!doctype html>
<html>
<head>
	<? 
	$tpl_title = "Channel Management";
	include(OK_HEADER);
	?>
	<script type="text/javascript" src="/views/scripts/tap.js"></script>
	<script type="text/javascript" src="/views/scripts/editgroup.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
</head>
<body>
	<div id="wrapper">

	<? include(OK_TOPBAR); ?> 

	<div id="main">

		<? include(OK_SIDEBAR); ?>

			<div id="content">
				
				<div class="section">
					<div class="header header-non">
						<a id="newtaps" href="" class="floater"></a>
						<h2 class="header-title">
							<img src="/images/flat/loader.gif" />
							<span class="title">channels</span>
						</h2>
						<span class="stream-name">Manage Channel <a href="/channels">back to your channels</a></span>
					</div>
					<div class="body">
						<div id="create-group" class="form" data-id="<?= $gid ?>">
							<p class="notify">Your changes have been saved</p>
                                                        <p class="error">You have errors you need to fix before you can create the channel, could you please try again?</p>

							<p>Fill in all the details below and then hit save to edit your channel.</p>
							<span id="catagory-manage-link">
								<label class="nick">
								<a style="float:left" class="follow_button" href='/catagory_add?group=<?=$symbol?>'>Manage Catagories</a>
								<span class="help">Manage sub-catagories for your tap channel</span>
								</label>
							</span>
							<label for="name">
								name 
								<span class="help">the name of your channel</span>
								<span class="error"></span>
							</label>
							<input name="name" value="<?= $gname ?>" type="text" disabled="disabled" class="basic full" />
							
							<label for="symbol">
								symbol 
								<span class="help">this will be used to identify your channel</span>
								<span class="error"></span>
							</label>
							<input name="symbol" value="<?= $symbol ?>" type="text" disabled="disabled" class="basic full" />
							
							<label for="focus">
								focus 
								<span class="help">the areas of interest of your channel; at least 3, separated by commas</span>
								<span class="error"></span>
							</label>
							<input name="focus" value="<?= $focus ?>" type="text" class="basic full" />
							
							<label for="desc">
								description 
								<span class="help">what's your channel about? describe it in 20 to 240 characters</span>
								<span class="error"></span>
							</label>
							<input name="desc" value="<?= $desc ?>" type="text" class="basic full" />
                            
                            <label for="private">
								Private?
								<span class="help">NEED more info here and styles</span>
								<span class="error"></span>
							</label>
							<input name="private" type="checkbox" <?= $private ? 'checked="checked"' : '' ?> class="basic" />
							
							<form id="picuploader" name="picuploader" action="/AJAX/group_picture_upload.php" enctype="multipart/form-data" method="post" target="picture">
								<label for="file">
									picture 
									<span class="help">upload a picture for your channel</span>
									<span class="error"></span>
								</label>
								<input id="group-pic" name="gr-pic" type="file" class="basic full"/>
								<img id="preview" src="/group_pics/<?= $pic ?>" />
								<iframe name="picture" style="display:none;"> </iframe>
							</form>

							<form id="picuploader-fav" name="picuploader-fav" action="/AJAX/group_favicon_upload.php" enctype="multipart/form-data" method="post" target="picture-fav">
								<label for="file">
									favicon
									<span class="help">upload an icon for your channel ( use a fav.ico from your website )</span>
									<span class="error"></span>
								</label>
								<input id="group-pic-fav" name="gr-pic-fav" type="file" class="basic full"/>
								<img id="preview-fav" src="/group_pics/<?= $favicon ?>" />
								<iframe name="picture-fav" style="display:none;"> </iframe>
							</form>
							
							<div class="buttons">
								<button class="action">save changes</button> or <a href="/channels">cancel</a>
							</div>
						</div>
					</div>
				</div>

			</div>

		</div>
	</div>
    <?include(OK_FOOTER)?>
	<?include(JAVASCRIPT_TEMPLATES)?>	
</body>
</html>
