<?php
$last = (!empty($_t['last_tap'])) ? $_t['last_tap'][0] : null;
$inits = array();
if (is_array($_t['groups_bits'])) {
	foreach($_t['groups_bits'] as $bit) {
		array_push($inits, $bit['cid']);
	}
}
$convos = array();
if (is_array($_t['active_convos'])) {
	foreach($_t['active_convos'] as $bit) {
		array_push($convos, $bit['mid']);
	}
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11153159-1");
pageTracker._trackPageview();
} catch(err) {}</script>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>tap - alpha</title>

<link rel="shortcut icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<style type="text/css" media="all">@import "views/style_sheets/TextboxList.css";</style>
<style type="text/css" media="all">@import "views/style_sheets/TextboxList.Autocomplete.css";</style>
<link rel="stylesheet" href="views/style_sheets/group_manage.css" type="text/css" />
<link rel="stylesheet" href="views/style_sheets/homepage.css" type="text/css" />
<script type="text/javascript" src="views/javascript/mootools-1.2.3-core-yc.js"></script>
<script type="text/javascript" src="views/javascript/mootools-1.2.3.1-more.js"></script>
<script type="text/javascript" src="views/javascript/textboxlist-complete.js"></script>
<script type="text/javascript" src="views/javascript/mootools-tap.js"></script>
<script type="text/javascript" src="http://mark.tap.info:8000/static/Orbited.js"></script>
<script type="text/javascript">
Tap = window.Tap || {};
Tap.Vars = {
	pcid: "<?= $_t['pcid'] ?>".toInt(),
	uname: "<?= $_SESSION['uname'] ?>",
	currentTap: "<?= $last['cid'] ?>".toInt(),
	currentStream: JSON.decode('<?= json_encode($inits) ?>'),
	activeConvos: JSON.decode('<?= json_encode($convos) ?>')
};
</script>
<script type="text/javascript" src="views/javascript/tap.push.js"></script>
<script type="text/javascript" src="views/javascript/tap.home.js"></script>
<script type="text/javascript" src="views/javascript/mpmetrics.js"></script>
<script type="text/javascript">
// Metrics
try { mpmetrics.init('<?= METRIC_KEY ?>');} catch(err) { alert(err) }
window.addEvent('domready', function(){
	$(document.body).addEvents({
		'click:relay(a.suggestion-item)': function(e){
			e.stop();
			var self = this;
			mpmetrics.track('trending-click', {'group': this.getElement('strong').get('text')}, function(){
				window.location = self.get('href');
			});
		},
		'click:relay(li.group a)': function(){
			var self = this;
			var id = this.get('id');
			if (!id) return;
			mpmetrics.track('feed-change', {
				'group': (function(){
					if (id === 'gid_all') return 'All Groups';
					return self.getElement('a').get('title');
				})()
			});
		}
	});

	Tap.Home.addEvents({
		'sendTap': function(number){
			mpmetrics.track('send-tap', {
				'type': number !== 0 ? 'private' : 'public',
				'groups': number
			});
		},
		'loadResponses': function(){
			mpmetrics.track('view-responses', {});
		},
		'sendResponse': function(){
			mpmetrics.track('send-responses', {});
		},
		'searchFeed': function(keyword){
			mpmetrics.track('search-feed', {'keyword': keyword});
		}
	});
});
</script>
</head>

<body>

	<?php include(NEW_HEADER); ?>

	<div id="tap-feed-outside-more">
		<p style="margin-bottom:5px">Allow messages from this groups:</p>
		<p>
			<input type="text" name="outside-from" alt="Choose sources.." />
		</p>
		<p style="clear:both;">
			<a href="#" id="tap-feed-outside-set">Save</a>
		</p>
	</div>

	<div id="main">

		<div class="left-col" style="margin-right: 20px">
			<!--
			<div id="groups-tab" style="background-image:url(/images/cimages/tab_grey.gif);">
				<div class="tab-in" style="color:#fff;">What's This?</div>
			</div>
			<div class="tab-list">
				<p>Tap allows you to connect with people around you and stay informed about topics you're interested in.  Use Tap to see what you and your friends are doing, what people around you are doing, and connect with link-minded individuals. Join Tap today!</p>
			</div>
			-->
			<div id="groups-tab">
				<div class="tab-in" style="color:#fff">Popular Groups</div>
			</div>
			<div class="tab-list">
				<ul>
					<?php foreach($_t['trending_groups'] as $trending): ?>
						<li class="list-item" style="height:30px">
							<p style="height: 14px;"><a href="/groups?search=<?= $trending['gname'] ?>" class="suggestion-item" title="<?= $trending['gname'] ?>"><img src="/group_pics/<?= $trending['pic_36'] ?>" style="float:left; margin-right: 10px" />
								<strong>
									<?php
										$gname = $trending['gname'];
										echo stripslashes((strlen($gname) < 10) ? $gname : substr($gname, 0, 10) . '...');
									?>
								</strong> (<?= $trending['count'] ?>)</a></p>
						</li>
						<!--
						<li id="gid_<?= $trending['gid'] ?>" class="group trending">
							<?= $trending['gname'] ?> (<?= $trending['count'] ?>)

						</li>
						-->
					<?php endforeach; ?>
					<li class="list-item" style="height:30px; margin-top:20px">
						<strong><a href="/groups" title="Create/Join New Groups">Create/Join New Groups</a></strong>
					</li>
				</ul>
				<div style="clear:both"></div>
			</div>
		</div>

		<div id="center-col">
			<div id="tap-box" class="section">
				<input type="text" id="tap-box-msg" alt="Start tapping by writing a message here." />
				<div id="tap-box-more">
					<input type="text" id="tap-box-people" alt="Add some groups who'll receive your tap!" />
					<a id="tap-box-send" href="#">tap!</a>
					<div style="clear:both"></div>
				</div>
			</div>

			<div id="tap-yours" class="section">
				<div class="section-head">
					<h1>
						<span id="archived-taps">Archived Taps</span>
						Your Last Tap
					</h1>
				</div>
				<div class="section-body">
					<ul id="your-stream" class="tap-stream">
						<?php if ($last == null): ?>
						<li class='welcome_tap'>
							<h1 style="font-size:14px; font-weight:bold; margin-bottom: 5px; color: #4F9CDF;">Welcome To Tap!</h1>
							<p style="margin-bottom: 10px;">Tap allows you to connect with people around you and stay informed about topics you're interested in.</p>
							<p style="margin-bottom: 10px;"></p>
							<p style="margin-bottom: 10px;">You can start by updating your <a href="/profile"><strong>profile pic</strong></a>, joining a <a href="/groups"><strong>group</strong></a>, or you can send a tap right now using the TapBox above. If you get stuck, check out the <a href="/help"><strong>Help</strong></a> section, or send a tap to <strong>Support</strong>.</p>
							<p style="margin-bottom: 10px;"><strong>Keep on tapping!</strong></p>
						</li>
						<?php else: ?>
						<li id="yid_<?= $last['cid'] ?>">
							<img src="/user_pics/<?= $last['pic_100'] ?>" class="avatar" title="<?= $last['uname'] ?>" alt="<?= $last['uname'] ?>" rel="<?= $last['uid'] ?>" />
							<div class="tap-actions">
								<span class="tap-views">Viewers: 
									<strong>
									<?= (!empty($last['viewer_count'])) ? $last['viewer_count'] : '0' ?>
									</strong>
								</span>
								<a class="tap-respond <?= empty($last['count']) ? 'noresp' : '' ?>" href="#">
									Respond <span class="tap-respond-count">(<?= $last['count'] ?>)</span>
								</a>
								<p class="tap-respond-last <?= empty($last['count']) ? 'noresp' : '' ?>">
									<strong>
										<?= (!empty($last['resp_uname'])) ? $last['resp_uname'] . ":" : "" ?>
									</strong>
									<span><?= $last['last_resp'] ?></span>
								</p>
							</div>
							<div class="tap-body">
								<p class="tap-info">
									<span class="tap-from"><?= $last['fname'] . " " . $last['lname'] ?></span>
									<span class="tap-time <?= $last['chat_timestamp_raw'] ?>"><?= $last['chat_timestamp'] ?></span>
									<span class="tap-typing"></span>
								</p>
								<p>
									<span class="tap-msg"><?= $last['chat_text'] ?></span>
								</p>
							</div>
							<div class="tap-response-box clarity">
								<ul class="tap-chat <?= empty($last['count']) ? 'noresp' : '' ?>">
								</ul>
								<input type="text" class="tap-response" style="width:360px" alt="Respond to this tap." />
								<!-- <a href="#">Respond</a> or  --><a class="tap-respond-cancel" href="#">Close</a>
							</div>
							<div class="clarity"></div>
						</li>
						<?php endif; ?>
					</ul>
				</div>
			</div>

			<div id="tap-feed" class="section">
				<div class="section-head">
					<h1>
						<input type="text" id="tap-feed-search" alt="Search through feed." />
						<!-- <span id="tap-feed-outside-drop"></span> -->
						<span id="tap-feed-outside">Outside: Off</span>
						<span id="taps-responded">Taps You've Responded To</span>
						<span style="clear:right"></span>
						<img id="tap-feed-icon" src="/group_pics/36wh_default_group.gif" style="float:left; margin-right:10px; height: 20px; width: 20px" />
						<span id="tap-feed-name">Groups Feed</span>
						<img src="/images/loading.gif" id="loading-indicator" style="display:none" />
					</h1>
				</div>
				<div class="section-body">
					<div id="tap-notify"></div>
					<ul id="main-stream" class="tap-stream">
						<?php
							if (!empty($_t['groups_bits'])):
								foreach($_t['groups_bits'] as $bit):
						?>
						<li id="tid_<?= $bit['cid'] ?>">
							<img src="/user_pics/<?= $bit['pic_100'] ?>" class="avatar" alt="<?= $bit['uname'] ?>" rel="<?= $bit['uid'] ?>" />
							<div class="tap-actions">
								<span class="tap-views">Viewers: 
									<strong>
									<?= (!empty($bit['viewer_count'])) ? $bit['viewer_count'] : '0' ?>
									</strong>
								</span>
								<a class="tap-respond <?= empty($bit['count']) ? 'noresp' : '' ?>" href="#">
									Respond <span class="tap-respond-count">(<?= $bit['count'] ?>)</span>
								</a>
								<p class="tap-respond-last <?= empty($bit['count']) ? 'noresp' : '' ?>">
									<strong>
										<?= (!empty($bit['resp_uname'])) ? $bit['resp_uname'] . ":" : "" ?>
									</strong>
									<span><?= $bit['last_resp'] ?></span>
								</p>
							</div>
							<div class="tap-body">
								<p class="tap-info">
									<span class="tap-from"><?= $bit['fname'] . " " . $bit['lname'] ?></span>
									<span class="tap-time <?= $bit['chat_timestamp_raw'] ?>"><?= $bit['chat_timestamp'] ?></span>
									<span class="tap-typing"></span>
								</p>
								<p>
									<span class="tap-msg"><?= $bit['chat_text'] ?></span>
								</p>
							</div>
							<div class="tap-response-box clarity">
								<ul class="tap-chat <?= empty($bit['count']) ? 'noresp' : '' ?>">
								</ul>
								<input type="text" class="tap-response" style="width:360px" alt="Respond to this tap." />
								<!-- <a href="#">Respond</a> or  --><a class="tap-respond-cancel" href="#">Close</a>
							</div>
							<div class="clarity"></div>
						</li>
						<?php
								endforeach;
							else:
						?>
						<li class="noresults">
							<p>This feed is too silent. Try sending a tap!</p>
						</li>
						<?php
							endif;
						?>
					</ul>
				</div>
			</div>
		</div>

		<div id="left-col">
			<div id="groups-tab">
				<div class="tab-in" style="color:#fff">My Groups</div>
			</div>
			<div class="tab-list">
				<ul>
					<li id="gid_public" class="group">
						<span class="counter"></span>
						<img src="/group_pics/36wh_default_group.gif" style="display:none" />
						<strong><a href="#" title="Public Feed">Public Taps</a></strong>
					</li>
					<li id="gid_all" class="group">
						<span class="counter"></span>
						<img src="/group_pics/36wh_default_group.gif" style="display:none" />
						<strong><a href="#" title="Groups Feed">All Your Groups <span class="unread-counter">(0)</span></a></strong>
					</li>
					<?php foreach ($_t['your_groups'] as $group): ?>
					<li id="gid_<?= $group['gid'] ?>" class="group">
						<img src="/group_pics/<?= $group['pic_36']?>" />
						<a href="#<?= $group['display_symbol'] ?>" grsymbol="<?= $group['symbol'][0] ?>" title="<?= $group['gname'] ?> (<?= $group['message_count'] ?>)"><?= $group['display_symbol'] ?> <span class="unread-counter">(0)</span></a>
						<a class="add-tap-to" grtype="<?= $group['type'] ?>" href="#" title="Tap this group!">+</a>
					</li>
					<?php endforeach; ?>
					<li class="group" style="margin-top:20px">
						<span class="counter"></span>
						<strong><a href="/groups" title="Create/Join New Groups">Create/Join New Groups</a></strong>
					</li>
				</ul>
			</div>
			<div id="groups-tab">
				<div class="tab-in" style="color:#fff">Active Conversations</div>
			</div>
			<div class="tab-list">
				<ul id="active-convos-list">
					<?php 
						if (!empty($_t['active_convos'])):
							$active_convos = array_reverse($_t['active_convos']);
							foreach ($active_convos as $convo): 
					?>
					<li id="aid_<?= $convo['mid'] ?>" class="convo">
						<strong><a href="#" class="change-convo"><?= $convo['uname'] ?></a></strong>
						<span style="font-size:10px">
						<?php
							$chat_text = $convo['chat_text'];
							echo stripslashes((strlen($chat_text) < 20) ? $chat_text : substr($chat_text, 0, 20) . '...');
						?> 
						(<span class="convo-count"><?= $convo['resp_count'] ?></span>)
						</span>
						<a href="#" class="remove-convo" title="Remove Conversation">&ndash;</a>
					</li>
					<?php 
							endforeach;
						else: 
					?>
					<li class="no-convos">
						<strong>No Active Conversations</strong>
					</li>
					<?php 
						endif; 
					?>
				</ul>
			</div>
		</div>

	</div>

	<div id="templates" style="display:none">
		<ul id="template-bit">
			<# for (var x = this.reverse().length; x--;) { var bit = this[x]; #>
			<li id="tid_<#: bit.cid #>">
				<img src="/user_pics/<#: bit.pic_100 #>" class="avatar" alt="<#: bit.uname #>" rel="<#: bit.uid #>"  />
				<div class="tap-actions">
					<span class="tap-views">Viewers: 
						<strong><#: bit.viewer_count || 0 #></strong>
					</span>
					<# if (bit.count) { #>
					<a class="tap-respond" href="#">
					<# } else { #>
					<a class="tap-respond noresp" href="#">
					<# } #>
						Respond <span class="tap-respond-count">(<#: bit.count #>)</span>
					</a>
					<# if (bit.count) { #>
					<p class="tap-respond-last">
					<# } else { #>
					<p class="tap-respond-last noresp">
					<# } #>
						<strong>
							<#: bit.resp_uname ? bit.resp_uname + ":" : "" #>
						</strong>
						<#: (bit.last_resp || "").linkify() #>
					</p>
				</div>
				<div class="tap-body">
					<p class="tap-info">
						<span class="tap-from"><#: [bit.fname, bit.lname].join(" ") #></span>
						<span class="tap-time <#: bit.chat_timestamp_raw #>"><#: bit.chat_timestamp #></span>
						<span class="tap-typing"></span>
					</p>
					<p>
						<span class="tap-msg"><#: bit.chat_text.linkify() #></span>
					</p>
				</div>
				<div class="tap-response-box clarity">
					<# if (bit.count) { #>
					<ul class="tap-chat">
					<# } else { #>
					<ul class="tap-chat noresp">
					<# } #>
					</ul>
					<input type="text" class="tap-response" style="width:360px" alt="Respond to this tap." />
					<!-- <a href="#">Respond</a> or  --><a class="tap-respond-cancel" href="#">Close</a>
				</div>
				<div class="clarity"></div>
			</li>
			<# } #>
		</ul>
		<ul>
			<li id="no-taps" class="noresults">
				<p>There doesn't seem to be anything here.</p>
			</li>
			<li id="no-results" class="noresults">
				<p>
					No taps match your search keyword.
					<a href="#" class="reset-feed">Show all taps.</a>
				</p>
			</li>
		</ul>
	</div>

	<div id="footer">

	</div>

</body>
</html>
