<?php $last = $_t['last_tap'][0]; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>tap - alpha</title>

<link rel="stylesheet" href="/views/style_sheets/group_manage.css" type="text/css" />
<link rel="shortcut icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<style type="text/css" media="all">@import "/views/style_sheets/TextboxList.css";</style>
<style type="text/css" media="all">@import "/views/style_sheets/TextboxList.Autocomplete.css";</style>
<script src="/views/javascript/mootools-1.2.3-core-yc.js" type="text/javascript"></script>
<script src="/views/javascript/mootools-1.2.3.1-more.js" type="text/javascript" charset="utf-8"></script>
<script src="/views/javascript/mootools-tap.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="/views/javascript/TextboxList.js"></script>
<script type="text/javascript" src="/views/javascript/TextboxList.Autocomplete.js"></script>
<script type="text/javascript" src="/views/javascript/GrowingInput.js"></script>
<style type="text/css" media="screen">

#center-col {
	width: 750px;
	margin-right: 20px;
}

#tap-box {
	padding: 5px;
	background: #ccc;
}

#tap-box-msg {
	width: 720px;
	padding: 3px;
	margin-bottom: 5px;
	border: 1px solid #999;
	font-size: 14px;
	padding: 7px;
	-moz-border-radius: 3px;
	-webkit-border-radius: 5px;
}

#tap-box-people {
	width: 70%;
	padding: 3px;
	border: 1px solid #999;
	-moz-border-radius: 3px;
	-webkit-border-radius: 5px;
}

.section {
	margin-bottom: 20px;
	border: 1px solid #D8D8D8;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
	-moz-box-shadow: 0px 0px 4px #D8D8D8;
	-webkit-box-shadow: 0px 0px 4px #D8D8D8;
}

.section-head {
	padding: 5px;
	background: #ccc;
}

.section-head h1 {
	font-size: 18px;
	font-weight: bold;
}

ul.tap-stream li {
	background: #EAEAEA url(/images/cimages/message_back.gif) repeat-x scroll 0 0;
	border-top: 1px solid #D8D8D8;
	padding: 10px;
	font-size: 12px;
}

ul.tap-stream li.noresults {
	height: 80px;
	background-image: none;
	text-align:center;
}

ul.tap-stream li.noresults p {
	margin-top: 30px;
	font-size: 14px;
	font-weight:bold;
	color: #666;
}

ul.tap-stream img.avatar {
	float: left;
	margin-right: 10px;
}

ul.tap-stream .floater {
	float: left;
}

ul.tap-stream .floaterdown {
	clear: left;
	float: left;
}

ul.tap-stream .clarity {
	display: block;
	clear: both;
}

ul.tap-stream .tap-info {
	margin-bottom: 3px;
}

ul.tap-stream .tap-msg {
	font-size: 13px;
}

ul.tap-stream .tap-info span {
	color: #797979;
}

ul.tap-stream .tap-from {
	font-weight: bold;
	margin-right: 5px;
}

div.textboxlist {
	background: #fff;
	width: 70%;
	padding: 3px;
	border: 1px solid #999;
	-moz-border-radius: 3px;
	-webkit-border-radius: 5px;
}

ul.textboxlist-bits {
	border: none;
}

div.textboxlist-autocomplete {
	z-index: 1;
}

#tap-feed-search {
	padding: 3px 6px;
	-moz-border-radius:8px;
	-webkit-border-radius: 8px;
	font-size: 12px;
	background: #fff;
	color: #000; float: right;
	border: none;
}

.section-head label {
	font-size: 12px;
}

#tap-notify {
	display: none;
	background:#4F9CDF;
	padding: 3px 6px;
	-moz-border-radius:8px;
	-webkit-border-radius: 8px;
	font-size: 12px;
	color: #fff; float: right;
	cursor: pointer;
}

#tap-notify:hover {
	background: #3E7AAE;
}

span.counter {
	display: none;
	float:right; background:#666; padding: 2px 5px; -moz-border-radius:6px; font-weight: bold; color:#fff;
}

</style>
<script type="text/javascript" src="http://<?= DOMAIN ?>:8080/meteor.js"></script>
<script type="text/javascript" charset="utf-8">

TextboxList.implement({
	empty: function(){
		this.list.getChildren().map(function(el){
			var bit = this.getBit(el);
			if (bit.is('editable')) return null;
			return bit.remove();
		}, this).clean();
		this.index.empty();
		return this;
	}
});

Tap = window.Tap || {};

Tap.Home = {

	feedView: 'gid_all',
	currentTap: "<?= $last['cid'] ?>".toInt(),

	pushed: {},

	tapper: {
		msg: '',
		people: []
	},

	init: function(){
		var self = this;
		var body = $(document.body);
		this.mainStream = $('main-stream');

		body.addEvents({
			'click:relay(li.group a)': this.changeFeed.toHandler(this),
			'click:relay(a.reset-feed)': this.clearSearch.toHandler(this)
		});

		var tapper = this.tapper = {
			msg: $('tap-box-msg'),
			people: new TextboxList('tap-box-people', {
				unique: true,
				plugins: {
					autocomplete: {
						minLength: 3, maxResults: 5, queryRemote: true,
						remote: { url: 'AJAX/search_assoc.php' }
					}
				}
			}),
			more: $('tap-box-more').slide('hide')
		};
		var eve = {
			'blur': this.hideTapMore.toHandler(this),
			'focus': this.showTapMore.toHandler(this)
		};
		tapper.msg.addEvents(eve); tapper.people.addEvents(eve);
		new OverText(tapper.msg, { positionOptions: { offset: {x: 6, y: 6}}}).show();
		$('tap-box-send').addEvent('click', this.sendTap.toHandler(this));

		$('tap-notify').addEvent('click', this.getPushed.toHandler(this));

		this.tapSearch = $('tap-feed-search');
		this.tapSearch.addEvent('keypress', function(e){
			if (e.key == 'enter') self.searchFeed();
		});
		new OverText(this.tapSearch, { positionOptions: { offset: {x: 6, y: 4}}}).show();
	},

	showTapMore: function(){
		var tapper = this.tapper;
		tapper.tapping = true;
		tapper.more.slide('in');
	},

	hideTapMore: function(){
		var tapper = this.tapper;
		(function(){
			if (!tapper.tapping) {
				tapper.more.slide(tapper.msg.get('value').isEmpty()
					&& tapper.people.getValues().length == 0 ? 'out' : 'in');
			}
			tapper.tapping = false;
		}).delay(500);
	},

	injectFeed: function(){

	},

	searchFeed: function(){
		var self = this;
		var keyword = this.tapSearch.get('value');
		if (!keyword.isEmpty()) {
			new Request({
				url: 'AJAX/filter_creator.php',
				data: (function(){
					return $extend((self.feedView == 'gid_all')
						? {type: 11}
						: {type: 1, id: self.feedView.remove(/gid_/)}
						, {search: keyword});
				})(),
				onRequest: function(){
					$('loading-indicator').setStyle('display', 'inline');
				},
				onComplete: function(){
					$('loading-indicator').setStyle('display', 'none');
				},
				onSuccess: function(){
					var response = JSON.decode(this.response.text);
					var items;
					if (response.results) {
						items = new Element('div', {
							html: self.parseTemplate('taps', response.data)
						});
					} else {
						items = new Element('div').adopt($('no-results').clone());
					}
					self.mainStream.empty();
					items.inject(self.mainStream, 'top').slide('hide').set('slide', {
						onComplete: function(){
							items.getElements('li').reverse().inject('main-stream', 'top');
							items.getParent('div').destroy();
						}
					}).slide('in');
				}
			}).send();
		} else {
			this.clearSearch();
		}
	},

	clearSearch: function(){
		this.tapSearch.set('value', '').fireEvent('blur');
		this.changeFeed(this.feedView, true);
		this.tapSearch.blur();
	},

	changeFeed: function(el, force){
		force = (!force || force.stop) ? false : force;
		var self = this;
		var gid = $try(function(){ return el.get('id'); }) || el;
		if (this.feedView === gid && !force) return;
		var id = (gid !== 'gid_all') ? gid.remove(/gid_/) : null;
		new Request({
			url: 'AJAX/filter_creator.php',
			data: (function(){
				return (id === null) ? {type: 11} : {type:1, id: id};
			})(),
			onRequest: function(){
				$('loading-indicator').setStyle('display', 'inline');
			},
			onComplete: function(){
				$('loading-indicator').setStyle('display', 'none');
			},
			onSuccess: function(){
				var response = JSON.decode(this.response.text);
				if (response.results) {
					self.feedView = gid;
					var key = (gid === 'gid_all') ? 'groups' : gid.replace('gid', 'group');
					if ($type(self.pushed[key]) == 'array') self.pushed[key].empty();
					if (!force) $('tap-feed-name').set('text', el.getElement('a').get('title'));
					var items = new Element('div', {
						html: self.parseTemplate('taps', response.data)
					});
					self.mainStream.empty();
					items.inject(self.mainStream, 'top').slide('hide').set('slide', {
						onComplete: function(){
							items.getElements('li').reverse().inject('main-stream', 'top');
							items.getParent('div').destroy();
						}
					}).slide('in');
					$('tap-notify').setStyle('display', 'none');
				}
			}
		}).send();
	},

	sendTap: function(_, e){
		var self = this;
		var data = this.tapper;
		var to_box = data.people.getValues().map(function(item){
			return item[1];
		});
		new Request({
			url: 'AJAX/message_handler.php',
			data: {
				msg: data.msg.get('value'),
				to_box: JSON.encode(to_box.length !== 0 ? to_box : null)
			},
			onSuccess: function(){
				var response = JSON.decode(this.response.text);
				if (response.new_msg) {
					self.currentTap = response.new_msg[0].cid.toInt();
					var items = new Element('div', {
						html: self.parseTemplate('taps', response.new_msg)
					});
					$('your-stream').empty();
					items.inject('your-stream', 'top').slide('hide').set('slide', {
						onComplete: function(){
							items.getElements('li').reverse().inject('your-stream', 'top');
							items.getParent('div').destroy();
						}
					}).slide('in');
				}
				data.people.empty();
				data.msg.set('value', '');
				data.msg.fireEvent('blur', e);
			}
		}).send();
	},

	processPushed: function(data){
		var pushed = this.pushed;
		data = JSON.decode(data);
		if (!pushed[data.type]) pushed[data.type] = [];
		var type = pushed[data.type];
		type.include(data.cid);

		var key = (this.feedView === 'gid_all') ? 'groups' : this.feedView.replace('gid', 'group');
		if (key === data.type && type.length > 0 && data.cid !== this.currentTap) {
			var length = type.length - (type.contains(this.currentTap) ? 1 : 0);
			var notify = ['You have', length, 'new', length == 1 ? 'tap' : 'taps'].join(' ');
			$('tap-notify').set({
				text: notify,
				styles: {display: 'inline'}
			}).store('type', data.type).highlight('#5AB2FF');
		} else if (data.type.contains('group') && this.feedView !== 'gid_all') {
			$((data.type == 'groups')
			  ? 'gid_all'
			  : data.type.replace('group', 'gid')
			).getElement('span.counter').set('text', type.length);
		}
	},

	getPushed: function(el){
		var self = this;
		var type = el.retrieve('type');
		var data = this.pushed[type];
		var template = $('template-bit').innerHTML.cleanup();
		new Request({
			url: 'AJAX/loader.php',
			data: {
				id_list: data.join(',')
			},
			onSuccess: function(){
				var response = JSON.decode(this.response.text);
				if (response.results) {
					data.empty();
					var items = new Element('div', {
						html: self.parseTemplate('taps', response.data)
					});
					items.inject('main-stream', 'top').slide('hide').set('slide', {
						onComplete: function(){
							items.getElements('li').reverse().inject('main-stream', 'top');
							items.getParent('div').destroy();
						}
					}).slide('in');
					el.set('styles', {display:'none'});
				}
			}
		}).send();
	},

	parseTemplate: function(type, data){
		var template = $(({
			taps: 'template-bit'
		})[type]).innerHTML.cleanup();
		if (!this.templater) this.templater = new Template();
		return this.templater.parse(template, data);
	}
};

window.addEvent('domready', Tap.Home.init.bind(Tap.Home));
</script>
</head>

<body>

	<?php include(NEW_HEADER); ?>

	<div id="main">
		<div id="center-col">
			<div id="tap-box" class="section">
				<input type="text" id="tap-box-msg" alt="Tap here!" />
				<div id="tap-box-more">
					<input type="text" id="tap-box-people" /><a id="tap-box-send" href="#">Send</a>
				</div>
			</div>

			<div id="tap-yours" class="section">
				<div class="section-head">
					<h1>
						<span id="tap-notify"></span>
						Your Last Tap
					</h1>
				</div>
				<div class="section-body">
					<ul id="your-stream" class="tap-stream">
						<li>
							<img src="/user_pics/<?= $last['pic_100'] ?>" class="avatar" alt="<?= $last['uname'] ?>" />
							<div>
								<p class="tap-info">
									<span class="tap-from"><?= $last['fname'] . " " . $last['lname'] ?></span>
									<span class="tap-time"><?= $last['chat_timestamp'] ?></span>
								</p>
								<p>
									<span class="tap-msg"><?= $last['chat_text'] ?></span>
								</p>
							</div>
							<div class="clarity"></div>
						</li>
					</ul>
				</div>
			</div>

			<div id="tap-feed" class="section">
				<div class="section-head">
					<h1>
						<input type="text" id="tap-feed-search" alt="Search through feed." />
						<span id="tap-feed-name">Groups Feed</span>
						<img src="/images/loading.gif" id="loading-indicator" style="display:none" />
					</h1>
				</div>
				<div class="section-body">
					<ul id="main-stream" class="tap-stream">
						<?php foreach($_t['groups_bits'] as $bit): ?>
						<li>
							<img src="/user_pics/<?= $bit['pic_100'] ?>" class="avatar" alt="<?= $bit['uname'] ?>" />
							<div>
								<p class="tap-info">
									<span class="tap-from"><?= $bit['fname'] . " " . $bit['lname'] ?></span>
									<span class="tap-time"><?= $bit['chat_timestamp'] ?></span>
								</p>
								<p>
									<span class="tap-msg"><?= $bit['chat_text'] ?></span>
								</p>
							</div>
							<div class="clarity"></div>
						</li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>
		</div>

		<div id="left-col">
			<div id="groups-tab">
				<div class="tab-in"><a href="" class="name">My Groups</a></div>
			</div>
			<div class="tab-list">
				<ul>
					<li id="gid_all" class="group">
						<span class="counter"></span>
						<img src="/group_pics/36wh_default_group.jpg" />
						<a href="#" title="Groups Feed">All Your Groups</a>
					</li>
					<?php foreach ($_t['your_groups'] as $group): ?>
					<li id="gid_<?= $group['gid'] ?>" class="group">
						<span class="counter"></span>
						<img src="/group_pics/<?= $group['pic_36']?>" />
						<a href="#<?= $group['symbol'] ?>" title="<?= $group['gname'] ?>"><?= $group['symbol'] ?></a>
					</li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>

	</div>

	<div id="templates" style="display:none">
		<ul id="template-bit">
			<# for (var x = this.reverse().length; x--;) { var bit = this[x]; #>
			<li>
				<img src="/user_pics/<#: bit.pic_100 #>" class="avatar" alt="<#: bit.uname #>" />
				<div>
					<p class="tap-info">
						<span class="tap-from"><#: [bit.fname, bit.lname].join(" ") #></span>
						<span class="tap-time"><#: bit.chat_timestamp #></span>
					</p>
					<p>
						<span class="tap-msg"><#: bit.chat_text #></span>
					</p>
				</div>
				<div class="clarity"></div>
			</li>
			<# } #>
		</ul>
		<ul>
			<li id="no-taps" class="noresults">
				<p>There doesn't seem to be anything here.</p>
			</li>
			<li id="no-results" class="noresults">
				<p>
					No taps match your search keyword.
					<a href="#" class="reset-feed">Show all taps.</a>
				</p>
			</li>
		</ul>
	</div>

	<div id="footer">

	</div>
<script type="text/javascript">
document.domain = "<?= DOMAIN ?>";
Meteor.hostid = '<?= $_SESSION["rand_id"] ?>';
Meteor.port = '8080';
// Meteor.debugmode = 1;

Meteor.host = location.hostname;
Meteor.registerEventCallback('process', function(data){ Tap.Home.processPushed(data); });

Meteor.joinChannel("<?=$_t['pcid'];?>", 0);
Meteor.mode = 'stream';
Meteor.connect();
</script>
</body>
</html>
