<!doctype html>
<html>
<head>
	<? 
	$tpl_title = "Password Recovery";
	include(OK_HEADER);
	?>
	<script type="text/javascript" src="/views/scripts/password_recovery.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
</head>
<body>
<?php if (!$_t['ok_user']): ?>
    <? include(MODAL_SIGNUP); ?>
    <script type="text/javascript" src="/views/scripts/modal_signup.js"></script>
<?php endif; ?>
	<div id="wrapper">

	<? include(OK_TOPBAR); ?> 

	<div id="main">

		<? include(OK_SIDEBAR); ?>
			

		<div id="content">
				
				<div class="section">
					<div class="header header-non">
						<h2 class="header-title">
							<span class="title">?</span>
						</h2>
						Lost your password? Dont worry!
					</div>
					<div class="body">
						<div class="full info">
						<?
                            $u = $_SERVER['REQUEST_URI'];
                            $u = explode('/',$u);
                            if($u[1] == 'group')
                                $type = '?type=group';
                            if($u[1] == 'user')
                                $type = '?type=user';
                            if($type)
                                $value = '&value='.$u[2];
                        ?>
				<? echo $_t['recovery_password_form_msg']; ?>
				<?php if($_t['recovery_password_form'] == 'yes'): ?>
				<div id="pwrecovery" class="section container">
                            <form id="tapnewpassform" action="/" method="POST">
                                <ul>
                                    <li>
                                        <label class="inblock">Enter your new password</label>
                                            <p class="body">
                                                <input name="pass" type="password" class="basic" value="" />
                                            </p>
                                    </li>
						<li>
                                        <label class="inblock">Retype your new password</label>
                                            <p class="body">
                                                <input name="repass" type="password" class="basic" value="" />
                                            </p>
                                    </li>
                                    <li class="action">
							<input name="hash" type="hidden" value="<?php echo $_GET['hash']; ?>" />
							<button type="submit">Send!</button>
                                    </li>
                                    <li id="pwrecovery-status"></li>
                                </ul>
                            </form>
                        </div>
				<?php else: ?>
				<div id="login" class="section container">
                            <form id="tappassrecovery" action="/" method="POST">
                                <ul>
                                    <li>
                                        <label class="inblock">Enter your email and we will send you instructions</label>
                                            <p class="body">
                                                <input name="email" type="text" class="basic" value="<?= $_POST['email'] ?>" />
                                            </p>
                                    </li>
                                    <li class="action">
                                        <button type="submit">Send!</button>
                                    </li>
                                    <li id="pwrecovery-status"></li>
                                </ul>
                            </form>
                        </div>
				<?php endif; ?>

                        </div>
					</div>
				</div>
			</div>

		</div>
	</div>
	
    <?include(OK_FOOTER)?>
	<?include(JAVASCRIPT_TEMPLATES)?>

<script type="text/javascript">
var _gaq = _gaq || [];
 _gaq.push(['_setAccount', 'UA-11153159-1']);
 _gaq.push(['_trackPageview']);

 (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
 })();
</script>
		<?include(FBCONNECT_BOTTOM)?>
</body>
</html>
