
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>tap - alpha</title>

<link rel="stylesheet" href="/views/style_sheets/global.css" type="text/css" >
<link rel="stylesheet" href="/views/style_sheets/people_manage.css" type="text/css" >
<link rel="shortcut icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<script src="/views/javascript/mootools-1.2.3-core-yc.js" type="text/javascript"></script>
<script src="/views/javascript/mootools-1.2.3.1-more.js" type="text/javascript" charset="utf-8"></script>
<script src="/views/javascript/mootools-tap.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="/views/javascript/mpmetrics.js"></script>
<script type="text/javascript"> try { mpmetrics.init('<?= METRIC_KEY ?>');} catch(err) { alert(err) } </script>
</head>

<body>

	<? include(HEADER_CLEAN); ?>

	<div id="main">

		<div id="sidebar-left" class="sidebar">
			<div id="peoples" class="section">
				<div class="section-head">
					<h1>Suggested people</h1>
				</div>
				<div class="section-body">
					<ul class="suggested-peoples"></ul>
				</div>
			</div>
		</div>

		<div id="content">
			<div id="people-search-main" class="section">
				<form method="get" action="search_people">
					 <fieldset>
						<ul>
							<li><input type="text" id="fname" class="people-search-field" name="fname"></input>
							<input type="text" id="lname" class="people-search-field" name="lname"></input></li>
							<li><input type="text" id="uname" class="people-search-field" name="uname"></input>
							<select id="group" class="people-sel-field" name="group">
							<option value=""> - - - - - - - - -</option>
							<?while($search_people_results = $_t['your_groups']->fetch_assoc()):?>
							<option value="<?=$search_people_results['gid']?>:<?=$search_people_results['connected']?>">
								<?=$search_people_results['gname']?>
							</option>
							<?endwhile;?>
							?>
							</select></li>
							<li><input id="people-search-btn" type="submit" name="people_search_button" value="Search"></input></li>
						</ul>
					</fieldset>
				</form> 	
			</div>

			<div id="people-list" class="section">

				<div id="people-header" class="section-head big">
					<h1>
						<a class="tracker" href="people?q=1"><img src="/images/cimages/tracked-icon.gif" alt="tracked users" class="track-icon" />Tracked</a>
						<a class="tracker" href="people?q=0"><img src="/images/cimages/tracking-icon.gif" alt="tracking users" class="track-icon" />Tracking </a>
						<span>People <?= empty($_GET['q']) ? "You're Tracking" : "Tracking You" ?></span>
					</h1>
				</div>


				<div id="people-sort">
					<p>
						<span id="sort-pic">Picture</span>
						<span id="sort-uname">User data</span>
						<span id="sort-lasttap">Last tap</span>
						<span id="sort-groups">Membership</span>
					</p>
				</div>

				<!-- Start of People Listing -->
				<div>
					<ul id="peoples-list" class="people-listing">
					<?php
						$q = empty($GET['q']) ? 0 : 1;
						$people = "people_$q";	
						if($_t[$people]):
						foreach ($_t[$people] as $n):
						$uid = $n['uid'];
						$uname = $n['uname'];
						$fname = $n['fname'];
						$lname = $n['lname'];
						$pic = $n['pic_100'];
						$last_tap = $n['last_chat'];
						$friend = $n['friend'];
						$groups = $n['groups'];
					?>
						<li id="people-id_<?= $uid ?>" class="listing">
							<a href="/user/<?= $uname ?>">
								<img src="/user_pics/<?= $pic ?>" alt="people logo" class="people-image" /><?=$uname?>
							</a>
							<div class="people-numbers">
							<p>
									Latest Tap: <?= $last_tap ?>&mdash;<?= stripslashes($last_chat) ?>
							</p>
							</div>
							<div class="people-numbers">
							<p>
								<? if($groups)
									foreach($groups as $g):
									$gid = $g['gid'];
									$symbol = $g['symbol'];
									$gname = $g['gname'];
										?>
									<a href="group/<?=$symbol?>"><?=$gname?></a>
							
								<? endforeach; ?>	
							</p>
							</div>
							<div class="people-btns">
								<? if($friend): ?>
								<a href="#">Untrack</a>
								<? else: ?>
								<a href="#">Track</a>
								<? endif; ?>
									
							</div>
						</li>
						<?php endforeach; else:?>
						<li id="people-id_" class="listing">
						You are tracking nobody 
						</li>
						<?php endif; ?>
					</ul>
				</div>
			</div>
		</div>

		<div id="sidebar-right" class="sidebar">
			<div class="section">
				<div class="section-head gray">
					<h1>Help and Tips</h1>
				</div>
				<div class="section-body info">
					<h2>Invite Your Friends!</h2>
					<p>Having your friends on tap allows for a much richer experience without them, so get them on tap!</p>
				</div>
			</div>
		</div>


	</div>

	<? include(ANALYTICS); ?>

</body>
</html>
