<?php
$logged = (!empty($_SESSION['uid']));

if($_SERVER['REQUEST_URI'] == '/people')
$tracker = 0;
else
$tracker = empty($_GET['q'])  ? 0 : 1;


$people_list = "people_$tracker";

?>
<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Content-Language" content="en-us" />
	<meta name="robots" content="noodp" />
	<meta name="image-toolbar" content="no" />
	<meta name="copyright" content="Copyright (c) 2009 TAP" />
	<meta name="description" content="TAP communication platform" />
	<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />
	<meta name="uid" content="<?= $_t['pcid'] ?>" />
	<meta name="uname" content="<?= $_SESSION['uname'] ?>" />
	<title>tap</title>
	<link rel="stylesheet" href="/views/styles/global.css" type="text/css" />
	<script type="text/javascript" src="/views/scripts/mootools-core.js"></script>
	<script type="text/javascript" src="/views/scripts/mootools-more.js"></script>
	<script type="text/javascript" src="/views/scripts/tap.js"></script>
	<script type="text/javascript" src="/views/scripts/people.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
</head>
<body>
	<div id="wrapper">

		<?include(HEADER)?>

		<div id="main">

			<div id="sidebar">

				<?php if ($logged): ?>
	                                <?include(YOU)?>
				<?php endif; ?>
				
				<div id="filter" class="section">
					<p class="inblock ellipsis">looking for someone? <span class="title"></span> <a href="#" class="clear">clear</a></p>
					<input id="filterkey" type="text" class="basic" />
				</div>

				<div class="sideinfo section container">
					<h2>
						<span id="tab-name">people</span>
					</h2>
					<ul class="panel">
						<li class="panel-item <?= !$tracker ? 'selected' : '' ?>">
							<span class="count"><?= $_t['tracked_count'] ?></span>
							<a href="/people?q=0" class="names inblock ellipsis">people you're tracking</a>
						</li>
						<li class="panel-item <?= $tracker ? 'selected' : '' ?>" >
							<span class="count"><?= $_t['track_count'] ?></span>
							<a href="/people?q=1" class="names inblock ellipsis">people tracking you</a>
						</li>
						<li class="panel-item" >
							<span class="count"></span>
							<a href="/invite" class="names inblock ellipsis">invite people</a>
						</li>
					</ul>
				</div>
				
			</div>

			<div id="content">
				
				<div id="people-main" class="section">
					<div class="header">
						<a id="newtaps" href="" class="floater"></a>
						<h2 class="header-title">
							<img src="/images/flat/loader.gif" />
							<span class="title">people</span>
						</h2>
						<span class="stream-name">
							People 
							<?php if ($tracker): ?>
							Tracking You (<?= $_t['track_count'] ?>)
							<?php else: ?>
							You're Tracking (<?= $_t['tracked_count'] ?>)
							<?php endif; ?>
						</span>
					</div>
					<div class="body">
						<ul class="bodylist <?= empty($_t[$people_list]) ? 'empty' : '' ?>">
							<?php 	
								if (!empty($_t[$people_list])):
									foreach ($_t[$people_list] as $person):
										$uid = $n['fuid'];
										$uname = $n['uname'];
										$fname = $n['fname'];
										$lname = $n['lname'];
										$pic = $n['pic_100'];
										$last_tap = $n['last_chat'];
										$friend = $n['friend'];
										$groups = $n['groups'];
							?>
							<li id="pid_<?= $person['fuid'] ?>" class="container list-item" 
								data-id="<?= $person['fuid'] ?>" data-uname="<?= $person['uname'] ?>">
								<?php if ($person['friend']): ?>
								<button class="untrack">untrack</button>
								<?php else: ?>
								<button class="track">track</button>
								<?php endif; ?>
								<img src="/user_pics/<?= $person['pic_100'] ?>" class="avatar" />
								<h2>
									<a href="/user/<?= $person['uname'] ?>" title="<?= $person['uname'] ?>">
										<?= $person['fname'] ?> <?= trim($person['lname']) ?></a> 
									<span class="nick"><?= $person['uname'] ?></span>
								</h2>
								<p class="headline"><?= $person['last_chat'] ?></p>
								<p class="stats">
									<strong><?= $stats['message_count'] ?></strong> Taps sent, 
									<strong><?= $stats['response_count'] ?></strong> Responses received, and
									<strong><?= $stats['group_count'] ?></strong> Groups joined.
								</p>
							</li>
							<?php
									endforeach;
								else:
							?>
							<li class="notice">
							
								<p><?php if ($tracker): ?>
								No one's tracking you.
								<?php else: ?>
								You're tracking no one.
								<?php endif; ?></p>
							</li>
							<?php
								endif;
							?>
						</ul>
					</div>
				</div>

			</div>

		</div>

		<div class="clarity"></div>

		<div id="footer">
			<strong>tap &copy; 2010.</strong>
			<span class="nav">
				<a href="/">home</a>
				<a href="/groups">groups</a>
				<a href="/people">people</a>
				<a href="/settings">settings</a>
				<a href="/?logout=true">logout</a>
			</span>
		</div>
		
	</div>
	<?include(JAVASCRIPT_TEMPLATES)?>
</body>
</html>
