<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title><?=TITLE?> - Profile</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css" media="all">@import "views/style_sheets/home.css";</style>

</head>

<!--[if lt IE 7]>
<style type="text/css">
html, body {background-color:#FF00FF;
#container {height: 100%; width: 100%; overflow: auto;}
.fixed {position: absolute;}
</style>
<![endif]-->
</head>

<body>


<div id="container">
	
	<?php include(HEADER);?>
		
	<?php include(LEFT);?>
	
	<?php 
	
	$rel_profile_data = $view_data['rel_profile'];
	$login_data = $view_data['login'];
	$last_chat_data = $view_data['last_chat'];
	
	$friend_data = $view_data['friends'];
	$posting_results = $view_data['postings'];
	$chat_results = $view_data['chat'];
	$groups_results = $view_data['groups'];
	
	?>
	
	<div id="profile">
	
		<div id="profile_header">Profile</div>
	
		<div id="picture">
			<img id="profile_pic" src="<?=PROFILE_PIC_REL?><? echo $login_data['pic_180'] ?>" alt='blank' />
			<span id="edit_profile_link"><img src="images/icons/vcard_edit.png" /> <a href="<?=ROOT?>profile_edit">Edit Profile</a></span>
		</div>
		
		<div id="basic_info">
		
			<h4>&nbsp;Account Info.</h4>
			
			<ul>
				<li>Username: <? echo $login_data['uname'] ?></li>
				<li>Friends: <?=$friend_data['count']?></li>
				<li>Taps: <?=$posting_results['count']?></li>
				<li>Responses ( in lines ): <?=$chat_results['count']?></li>
			</ul>
			
			<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You</h4>
			
			<ul>
				<li>Name: <?=$rel_profile_data['fname'].' '.$rel_profile_data['lname']?></li>
				<li>Location: <?=$rel_profile_data['state'].', '.$rel_profile_data['country']?></li>
				<li>Zip: <?=$rel_profile_data['zip']?></li>
				<li>Languages: <?=$rel_profile_data['language']?></li>
				<li></li>
			</ul>
			
		</div>
		
		<div id="specific_ranking">
		
			<h4>What your friends are saying:</h4>
		
			<ul>
				<?php
				if($last_chat_data->num_rows > 0){
				while($last_chat = $last_chat_data->fetch_assoc() ){
				echo '<li>'.$last_chat['uname'].' - '.stripslashes($last_chat['last_chat']).'</li>';
				}
				} else {
				echo "Nobody you have on tap has said anything yet...";
				}
				?>
				
			</ul>
			
		</div>
		
		
		
	<div id="groups_profile">
		
		<h4>Groups</h4>
		
		<h5>Groups You're Invovled With:</h5>
		
			<ul>
				<?php
				while($groups = $groups_results->fetch_assoc() ){
				echo '<li> <a class="profile_groups" href="group/'.$groups['gid'].'"><img class="profile_groups" src="'.D_GROUP_PIC_REL.$groups['pic_36'].'" />'.$groups['gname'].'</li></a>';
				}
				?>
			</ul>
	
	</div>
	
</div>

	<?php include(FOOTER);?>



</body>
</html>
