<?php
$logged = (!empty($_SESSION['uid']));
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11153159-1");
pageTracker._trackPageview();
} catch(err) {}</script>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>tap - alpha</title>

<link rel="shortcut icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="/views/style_sheets/global.css" type="text/css" />
<link rel="stylesheet" href="/views/style_sheets/public.css" type="text/css" />
<link rel="stylesheet" href="/views/style_sheets/TextboxList.css" type="text/css" />
<link rel="stylesheet" href="/views/style_sheets/TextboxList.Autocomplete.css" type="text/css" />
<script type="text/javascript" src="/views/javascript/mootools-1.2.3-core-yc.js"></script>
<script type="text/javascript" src="/views/javascript/mootools-1.2.3.1-more.js"></script>
<script type="text/javascript" src="/views/javascript/textboxlist-complete.js"></script>
<script type="text/javascript" src="/views/javascript/mootools-tap.js"></script>
<script type="text/javascript" src="http://mark.tap.info:8000/static/Orbited.js"></script>
<script>
Tap = window.Tap || {};
Tap.Vars = {
	pcid: "<?= $_t['pcid'] ?>".toInt(),
	logged: !!'<?= $logged ?>',
	uname: '<?= $_SESSION["uname"] ?>',
	user: '<?= $_t["uid"] ?>',
	group: '<?= $_t["gid"] ?>',
	tap: '<?= $_t["cid"] ?>'
};
</script>
<script type="text/javascript" src="/views/javascript/tap.push.js"></script>
<script type="text/javascript" src="/views/javascript/tap.public.js"></script>
<script type="text/javascript" src="/views/javascript/mpmetrics.js"></script>
<script type="text/javascript"> try { mpmetrics.init('<?= METRIC_KEY ?>');} catch(err) {} </script>
</head>

<body>

	<?php 
		include($logged ? NEW_HEADER : LOGOUT_HEADER);
	?>

	<div id="main">

		<div id="sidebar-left" class="sidebar">
			<div class="section">
				<div class="section-head">
					<h1>User Info</h1>
				</div>
				<div class="section-body">
					
				</div>
			</div>
		</div>

		<div id="content">

			<div id="tapper-info" class="section">
				<p class="icon"><img src="/user_pics/<?= $_t['user_pic_med'] ?>" /></p>
				<p class="tap-name">
					<a href="/user/<?= $_t['user'] ?>"><strong><?= $_t['user'] ?></strong></a>
					<span class="tap-typing" style="color:#518E3E; font-size:12px;"></span>
				</p>
				<?php
					if (!empty($_t['user_bits'])):
						$bit = array_shift($_t['user_bits'])
				?>
					<p class="tap" rel="<?= $bit['uid'] ?>">
						<?= $bit['chat_text'] ?><br />
						<span class="tap-info">
							<span class="tap-time <?= $bit['chat_timestamp_raw'] ?>"><?= $bit['chat_timestamp'] ?></span>
							<span class="tap-resp">Viewers: 
								<strong><?= (!empty($bit['viewer_count'])) ? $bit['viewer_count'] : '0' ?></strong>
							</span>
						</span>
					</p>
				<?php
					endif;
				?>
				<div style="clear:both;"></div>
			</div>

			<div id="tap-chat-perma" class="section">
				<div class="tap-response-box clarity" style="display: block">
					<div class="tap-response-counter">240</div>
					<ul class="tap-chat <?= empty($_t['responses']) ? 'noresp' : '' ?> <? if (!$logged) echo 'out'; ?>">
						<?php
							if (!empty($_t['responses'])):
								foreach($_t['responses'] as $resp):
						?>
						<li>
							<span class="time <?= $resp['chat_time'] ?>"><?= date('g:i A', $resp['chat_time']) ?></span>
							<strong><?= $resp['uname'] ?>:</strong>
							<?= $resp['chat_text'] ?>
						</li>
						<?php
								endforeach;
							endif;
						?>
					</ul>
					<input type="text" class="tap-response" style="width:483px" maxlength="240" 
						<?= ($logged) ? 'alt="Respond to this tap."' : 'alt="Signup to join the conversation!" disabled="disabled"' ?>
					/>
				</div>
			</div>
		</div>

		<div id="sidebar-right" class="sidebar">
			<div class="section">
				<div class="section-head">
					<h1 style="font-size: 12px">In This Conversation</h1>
				</div>
				<div class="section-body">
					<div class="stats">
						<ul id="people-list">
						<?php
							if (!empty($_t['invovled'])):
								foreach ($_t['invovled'] as $person):
						?>
						<li id="person_<?= str_replace(" ", "", $person['uname']) ?>">
							<a href="/user/<?= $person['uname'] ?>"><?= $person['uname'] ?></a>
							<span class="floater"><?= $person['count'] ?><span>
						</li>
						<?php
								endforeach;
							else:
						?>
						<li class="no-convos">
							<strong>No One Responded Yet</strong>
						</li>
						<?php
							endif;
						?>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div id="templates" style="display:none">
		<ul id="template-bit">
			<# for (var x = this.reverse().length; x--;) { var bit = this[x]; #>
			<li id="tid_<#: bit.cid #>">
				<img src="/user_pics/<#: bit.pic_100 #>" class="avatar" alt="<#: bit.uname #>" rel="<#: bit.uid #>"  />
				<div class="tap-actions">
					<span class="tap-views">Viewers:
						<strong><#: bit.viewer_count || 0 #></strong>
					</span>
					<# if (bit.count) { #>
					<a class="tap-respond" href="#">
					<# } else { #>
					<a class="tap-respond noresp" href="#">
					<# } #>
						<a href="/tap/<#: bit.cid #>">
						Respond <span class="tap-respond-count">(<#: bit.count #>)</span>
						</a>
					</a>
					<# if (bit.count) { #>
					<p class="tap-respond-last">
					<# } else { #>
					<p class="tap-respond-last noresp">
					<# } #>
						<strong>
							<#: bit.resp_uname ? bit.resp_uname + ":" : "" #>
						</strong>
						<# if (bit.last_resp) { #>
							<#: ((bit.last_resp.length < 70) ? bit.last_resp : bit.last_resp.substring(0, 70) + "...").linkify() #>
						<# } #>
					</p>
				</div>
				<div class="tap-body">
					<p class="tap-prof-info">
						<span class="tap-from">
							<a href="/user/<#: bit.uname #>">
							<#: [bit.fname, bit.lname].join(" ") #>
							</a>
						</span>
						<span class="tap-time <#: bit.chat_timestamp_raw #>"><#: bit.chat_timestamp #></span>
						<span class="tap-typing"></span>
					</p>
					<p>
						<span class="tap-msg"><#: bit.chat_text.linkify() #></span>
					</p>
				</div>
				<div class="tap-response-box clarity">
					<div class="tap-response-counter"></div>
					<# if (bit.count) { #>
					<ul class="tap-chat">
					<# } else { #>
					<ul class="tap-chat noresp">
					<# } #>
					</ul>
					<input type="text" class="tap-response" style="width:420px" maxlength="240" alt="Respond to this tap." />
					<!-- <a href="#">Respond</a> or  --><a class="tap-respond-cancel" href="#">Close</a>
				</div>
				<div class="clarity"></div>
			</li>
			<# } #>
		</ul>
		<ul>
			<li id="no-taps" class="noresults">
				<p>There doesn't seem to be anything here.</p>
			</li>
			<li id="no-results" class="noresults">
				<p>
					No taps match your search keyword.
					<a href="#" class="reset-feed">Show all taps.</a>
				</p>
			</li>
		</ul>
	</div>

	<div id="footer">

	</div>

</body>
</html>
