<?php
$logged = (!empty($_SESSION['uid']));
// if ($no_tap) header('location:/');

extract($_t, EXTR_PREFIX_SAME, '_');
?>
<!doctype html>
<html>
<head>
	<? 
	$tpl_title = "Convo with ".$user['real_name'];
	include(OK_HEADER);
	?>
	<script type="text/javascript" src="/views/scripts/tap.js"></script>
	<script type="text/javascript" src="http://<?=DOMAIN?>:8000/static/Orbited.js"></script>
	<script type="text/javascript">
		window._vars = {
			uid: "<?= $_SESSION['uid'] ?>",
            anon: <?=$ok_user ? 0 : 1?>,
            fb: <?=$_SESSION['facebook'] ? 1 : 0?>,
			uname: "<?= $_SESSION['uname'] ?>",
			stream: "<?= $cid ?>",
			convos: ["<?= $cid ?>"],
			people: ["<?= $_SESSION['uid'] ?>"],
			groups: [],
            filter: {
                gid: '0',
                cid: <?=$cid?>
            }
		};

        window.addEvent('load', function() {
            var boxes = $$('ul.chat');
            _tap.publish('stream.updated', []);
            boxes.each(function(box){
                //box.scrollTo(0, box.getScrollSize().y);
                _tap.publish('convos.loaded', [box, 0]);
            });
        });
	</script>
	<script type="text/javascript" src="/views/scripts/push.js"></script>
	<script type="text/javascript" src="/views/scripts/public.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
</head>
<body>
	<div id="wrapper">

	<? 
    include(OK_TOPBAR);
    ?> 

		<div id="main">

		<? ob_start(); ?>

			<div class="sideinfo section container">

			<h3>	
			<?php if($active_convo):?>
				<span id="tab-name" class="untrack-convo follow_button" cid="<?= $cid ?>">You are following this convo</span>
			<?php else: ?>
				<span id="tab-name" class="track-convo follow_button" cid="<?= $cid ?>">Follow this convo</span>
			<?php endif;?>
			</h3>

			<h2>
				<span id="tab-name">in this convo<?php if (isset($debug)) echo " >> ".$debug; ?></span>
			</h2>

			<ul class="panel">
			<?php 
			if (!empty($involved)):
				foreach ($involved as $person):
			?>
					<li class="panel-item" >
					<span class="count"><?= $person['count'] ?></span>	
					<img class="small-pic" src="/user_pics/<?= $person['small_pic'] ?>" />
					&nbsp;
					<a href="/user/<?= $person['uname'] ?>" class="names inblock-public ellipsis"><?= $person['uname'] ?></a>
					</li>
            <?php
				endforeach;
			else:
            ?>
				<li class="notify">
				no one's responded yet
				</li>
            <?php
			endif;
			?>
			</ul>
		</div>

		<? $add_sidebar = ob_get_clean(); ?>
		<? include(OK_SIDEBAR); ?>

			<div id="content">
				<div id="tapstream" class="section">
                    <a id="newtaps" href="" class="floater">This feed has 5 new taps! Click here to load them.</a>
					<div class="header header-non">
						<h2 class="header-title">
							<img src="/images/flat/loader.gif" />
							<span class="title">convo</span>
						</h2>
						<span class="stream-name">with <?= $user['uname'] ?>&nbsp; 
						<a href="/channel/<?=$tap['symbol']?>" /><img class="public-tap-favicon aggr-favicons" src="/group_pics/<?= $tap['favicon']?>" title="<?=$tap['gname']?>" /></a>
						</span>
					</div>
					<div class="body">
                        <?php
                            if (!empty($tap)) {
                                $_taps = array($tap);
                                $dont_show_more = true;
                                $show_responses = true;
                                include(TAP_STREAM);
                            } else {
                        ?>
                            
                        <? } ?>
					</div>
				</div>

			</div>

		</div>
	</div>
    <?include(OK_FOOTER)?>
</body>
</html>
