<?php
$logged = (!empty($_SESSION['uid']));
if ($_t['no_group']) header('location:/');

function map_clean($func, $arr) {
	return array_filter(array_map($func, $arr));
}
$inits = array();
$people = array();
if (is_array($_t['user_bits'])) {
	function get_cids($bit) { return $bit['cid']; }
	$inits = map_clean("get_cids", $_t['user_bits']);
	function get_uids($bit) { return $bit['uid']; }
	$people = map_clean("get_uids", $_t['user_bits']);
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11153159-1");
pageTracker._trackPageview();
} catch(err) {}</script>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>tap - alpha</title>

<link rel="shortcut icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="/views/style_sheets/global.css" type="text/css" />
<link rel="stylesheet" href="/views/style_sheets/public.css" type="text/css" />
<link rel="stylesheet" href="/views/style_sheets/TextboxList.css" type="text/css" />
<link rel="stylesheet" href="/views/style_sheets/TextboxList.Autocomplete.css" type="text/css" />
<script type="text/javascript" src="/views/javascript/mootools-1.2.3-core-yc.js"></script>
<script type="text/javascript" src="/views/javascript/mootools-1.2.3.1-more.js"></script>
<script type="text/javascript" src="/views/javascript/textboxlist-complete.js"></script>
<script type="text/javascript" src="/views/javascript/mootools-tap.js"></script>
<script type="text/javascript" src="http://mark.tap.info:8000/static/Orbited.js"></script>
<script>
Tap = window.Tap || {};
Tap.Vars = {
	pcid: "<?= $_t['pcid'] ?>".toInt(),
	logged: !!'<?= $logged ?>',
	uname: '<?= $_SESSION["uname"] ?>',
	user: '<?= $_t["uid"] ?>',
	username: '<?= $_t["user"] ?>',
	group: '<?= $_t["gid"] ?>',
	groupname: '<?= $_t["gname"] ?>',
	tap: '<?= $_t["cid"] ?>',
	feed: JSON.decode('<?= json_encode($inits) ?>'),
	people: JSON.decode('<?= json_encode($people) ?>')
};
</script>
<script type="text/javascript" src="/views/javascript/tap.push.js"></script>
<script type="text/javascript" src="/views/javascript/tap.public.js"></script>
<script type="text/javascript" src="/views/javascript/mpmetrics.js"></script>
<script type="text/javascript"> try { mpmetrics.init('<?= METRIC_KEY ?>');} catch(err) {} </script>
</head>

<body>

	<?php 
		include($logged ? HEADER_CLEAN : LOGOUT_HEADER);
	?>

	<div id="main">

		<div id="sidebar-left" class="sidebar">
			<div class="section">
				<div class="section-head">
					<h1>Popular Taps</h1>
				</div>
				<div class="section-body stats">
					<ul class="tap">
					<?php
						if (!empty($_t['popular_taps'])):
							foreach ($_t['popular_taps'] as $tap):
					?>
						<li>
							<a href="/tap/<?= $tap['cid'] ?>">
								<?= (strlen($tap['tap']) > 15) ? substr($tap['tap'], 0, 15) . '...' : $tap['tap'] ?>
							</a>
							<span class="floater"><?= $tap['count'] ?><span>
						</li>
					<?php
							endforeach;
						endif;
					?>
					</ul>
				</div>
			</div>
		</div>

		<div id="content">

			<div id="tapper-info" class="section">
				<p class="icon"><img src="/group_pics/<?= $_t['group_pic_med'] ?>" /></p>
				<?php if ($_t['joined']): ?>
				<span class="button selected">You're A Member!</span>
				<?php 
					else: 
						if ($logged):
				?>
				<a href="/groups?search=<?= $_t['gname'] ?>" class="button">Join Group</a>
				<?php 
						else:
				?>
				<a href="/" class="button">Signup to Tap this Group!</a>
				<?php 
						endif;
					endif; 
				?>
				<p class="tap-name"><strong><?= $_t['gname'] ?></strong></p>
				<?php
					if (!empty($_t['user_bits'])):
						$bit = array_shift($_t['user_bits'])
				?>
					<p class="tap" rel="<?= $bit['uid'] ?>">
						<a href="/user/<?= $bit['uname']?>" class="tap-from"><strong><?= $bit['uname']?>:</strong></a>
						<?= $bit['chat_text'] ?><br />
						<span class="tap-info">
							<span class="tap-time <?= $bit['chat_timestamp_raw'] ?>"><?= $bit['chat_timestamp'] ?></span>
							<span class="tap-resp"><a href="/tap/<?= $bit['cid'] ?>">Respond</a></span>
						</span>
					</p>
				<?php
					endif;
				?>
				<div class="clarity"></div>
			</div>

			<div id="tap-feed" class="section">
				<div class="section-head">
					<h1>
						<input type="text" id="tap-feed-search" alt="Search through feed." />
						<span style="clear:right"></span>
						<span id="tap-feed-name"><?= $_t['gname'] ?>'s Feed</span>
						<img src="/images/loading.gif" id="loading-indicator" style="display:none" />
					</h1>
				</div>
				<div class="section-body">
					<div id="tap-notify" style="display:none"></div>
					<ul id="main-stream" class="tap-stream">
						<?php
							if (!empty($_t['user_bits'])):
								foreach($_t['user_bits'] as $bit):
						?>
						<li id="tid_<?= $bit['cid'] ?>">
							<img src="/user_pics/<?= $bit['pic_100'] ?>" class="avatar" alt="<?= $bit['uname'] ?>" rel="<?= $bit['uid'] ?>" />
							<div class="tap-actions">
								<span class="tap-views">Viewers:
									<strong>
									<?= (!empty($bit['viewer_count'])) ? $bit['viewer_count'] : '0' ?>
									</strong>
								</span>
								<a class="tap-respond <?= empty($bit['count']) ? 'noresp' : '' ?>" href="/tap/<?= $bit['cid'] ?>">
									Respond <span class="tap-respond-count">(<?= $bit['count'] ?>)</span>
								</a>
								<p class="tap-respond-last <?= empty($bit['count']) ? 'noresp' : '' ?>">
									<strong>
										<?= (!empty($bit['resp_uname'])) ? $bit['resp_uname'] . ":" : "" ?>
									</strong>
									<span>
										<?php
											$last_rep = $bit['last_resp'];
											echo (strlen($last_rep) < 70) ? $last_rep : substr($last_rep, 0, 70) . '...';
										?>
									</span>
								</p>
							</div>
							<div class="tap-body">
								<p class="tap-info">
									<span class="tap-from">
										<a href="/user/<?= $bit['uname'] ?>" title="">
										<?= $bit['fname'] . " " . $bit['lname'] ?>
										</a>
									</span>
									<span class="tap-time <?= $bit['chat_timestamp_raw'] ?>"><?= $bit['chat_timestamp'] ?></span>
									<span class="tap-typing"></span>
								</p>
								<p>
									<span class="tap-prof-msg"><?= $bit['chat_text'] ?></span>
								</p>
							</div>
							<div class="tap-response-box clarity">
								<div class="tap-response-counter"></div>
								<ul class="tap-chat <?= empty($bit['count']) ? 'noresp' : '' ?>">
								</ul>
								<input type="text" class="tap-response" style="width:420px" maxlength="240" alt="Respond to this tap." />
								<!-- <a href="#">Respond</a> or  --><a class="tap-respond-cancel" href="#">Close</a>
							</div>
							<div class="clarity"></div>
						</li>
						<?php
								endforeach;
							else:
						?>
						<li class="noresults">
							<p>There isn't anything here yet! <a href="/">Send this group a tap</a>!</p>
						</li>
						<?php
							endif;
						?>
					</ul>
				</div>
			</div>
		</div>

		<div id="sidebar-right" class="sidebar">
			<div class="section">
				<div class="section-head">
					<h1 style="font-size:12px"><?= $_t['gname'] ?>'s Members</h1>
				</div>
				<div class="section-body">
						<p class="member-count">
							<a href="/search_people?group=<?=$_t['gid']?>:0&amp;people_search_button=1">
								This group has <?= (!empty($_t['member_count'])) ? $_t['member_count'] : 0 ?> members.
							</a>
						</p>
						<div class="group-stats stats">
							<p>Admins</p>
							<ul id="admin-list">
								<?php if($_t['admins']): foreach($_t['admins'] as $admin): ?>
									<li>
										<a href="/user/<?=$admin['uname']?>" title="<?=$admin['type']?>"><?=$admin['uname']?></a>
									</li>
								<?php endforeach; else:?>
									<li>There are currently no admins</li>
								<?php endif; ?>
							</ul>
							<p>Popular Members</p>
							<ul>
							<?php
								if (!empty($_t['popular_members'])):
									foreach ($_t['popular_members'] as $member):
							?>
							<li>
								<a href="/user/<?= $member['member'] ?>"><?= $member['member'] ?></a>
								<span class="floater"><?= $member['count'] ?><span>
							</li>
							<?php
									endforeach;
								endif;
							?>
							</ul>
						</div>
				</div>
			</div>
		</div>

	</div>

	<div id="templates" style="display:none">
		<ul id="template-bit">
			<# for (var x = this.reverse().length; x--;) { var bit = this[x]; #>
			<li id="tid_<#: bit.cid #>">
				<img src="/user_pics/<#: bit.pic_100 #>" class="avatar" alt="<#: bit.uname #>" rel="<#: bit.uid #>"  />
				<div class="tap-actions">
					<span class="tap-views">Viewers:
						<strong><#: bit.viewer_count || 0 #></strong>
					</span>
					<# if (bit.count) { #>
					<a class="tap-respond" href="/tap/<#: bit.cid #>">
					<# } else { #>
					<a class="tap-respond noresp" href="/tap/<#: bit.cid #>">
					<# } #>
						Respond <span class="tap-respond-count">(<#: bit.count #>)</span>
					</a>
					<# if (bit.count) { #>
					<p class="tap-respond-last">
					<# } else { #>
					<p class="tap-respond-last noresp">
					<# } #>
						<strong>
							<#: bit.resp_uname ? bit.resp_uname + ":" : "" #>
						</strong>
						<# if (bit.last_resp) { #>
							<#: ((bit.last_resp.length < 70) ? bit.last_resp : bit.last_resp.substring(0, 70) + "...").linkify() #>
						<# } #>
					</p>
				</div>
				<div class="tap-body">
					<p class="tap-info">
						<span class="tap-from">
							<a href="/user/<#: bit.uname #>">
							<#: [bit.fname, bit.lname].join(" ") #>
							</a>
						</span>
						<span class="tap-time <#: bit.chat_timestamp_raw #>"><#: bit.chat_timestamp #></span>
						<span class="tap-typing"></span>
					</p>
					<p>
						<span class="tap-msg"><#: bit.chat_text.linkify() #></span>
					</p>
				</div>
				<div class="tap-response-box clarity">
					<div class="tap-response-counter"></div>
					<# if (bit.count) { #>
					<ul class="tap-chat">
					<# } else { #>
					<ul class="tap-chat noresp">
					<# } #>
					</ul>
					<input type="text" class="tap-response" style="width:420px" maxlength="240" alt="Respond to this tap." />
					<!-- <a href="#">Respond</a> or  --><a class="tap-respond-cancel" href="#">Close</a>
				</div>
				<div class="clarity"></div>
			</li>
			<# } #>
		</ul>
		<ul>
			<li id="no-taps" class="noresults">
				<p>There doesn't seem to be anything here.</p>
			</li>
			<li id="no-results" class="noresults">
				<p>
					No taps match your search keyword.
					<a href="#" class="reset-feed">Show all taps.</a>
				</p>
			</li>
		</ul>
	</div>

	<div id="footer">

	</div>

</body>
</html>
