<?php
$logged = (!empty($_SESSION['uid']));
if ($_t['no_user']) header('location:/');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11153159-1");
pageTracker._trackPageview();
} catch(err) {}</script>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>tap - alpha</title>

<link rel="shortcut icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<link rel="icon" href="/images/cimages/favicon.ico" type="image/x-icon" />
<style type="text/css" media="all">@import "/views/style_sheets/TextboxList.css";</style>
<style type="text/css" media="all">@import "/views/style_sheets/TextboxList.Autocomplete.css";</style>
<link rel="stylesheet" href="/views/style_sheets/group_manage.css" type="text/css" />
<link rel="stylesheet" href="/views/style_sheets/homepage.css" type="text/css" />
<script type="text/javascript" src="/views/javascript/mootools-1.2.3-core-yc.js"></script>
<script type="text/javascript" src="/views/javascript/mootools-1.2.3.1-more.js"></script>
<script type="text/javascript" src="/views/javascript/textboxlist-complete.js"></script>
<script type="text/javascript" src="/views/javascript/mootools-tap.js"></script>
<script type="text/javascript" src="http://mark.tap.info:8000/static/Orbited.js"></script>
<script>
Tap = window.Tap || {};
Tap.Vars = {
	logged: !!'<?= $logged ?>',
	uname: '<?= $_SESSION["uname"] ?>',
	user: '<?= $_t["uid"] ?>',
	username: '<?= $_t["user"] ?>',
	group: '<?= $_t["gid"] ?>',
	groupname: '<?= $_t["gname"] ?>',
	tap: '<?= $_t["cid"] ?>'
};
</script>
<script type="text/javascript" src="/views/javascript/tap.public.js"></script>
<script type="text/javascript" src="/views/javascript/mpmetrics.js"></script>
<script type="text/javascript"> try { mpmetrics.init('<?= METRIC_KEY ?>');} catch(err) {} </script>
<style>
div.stats {
	margin-bottom: 20px;
}

div.stats h2 {
	font-size: 13px;
	color: #666;
	font-weight: normal;
	margin-bottom: 20px;
}

.tab-list p.icon {
	text-align: center;
	margin-top: 5px;
	margin-bottom: 20px;
}

.tab-list h2 {
	font-size: 20px;
	color: #333;
}

.tab-list p.actions {
	font-size: 10px;
}

div.stats h2 span {
	font-family: "Trebuchet MS", "Lucida Grande", Arial, Helvetica, sans-serif;
	font-weight: bold;
	font-size: 20px;
}

div.stats ul li {
	font-family: "Trebuchet MS", "Lucida Grande", Arial, Helvetica, sans-serif;
	color: #666;
	font-size: 12px;
	padding: 5px;
}

div.stats li span.floater {
	float: right;
	color: #666;
	font-size: 12px;
	padding: 5px;
	padding-top: 0;
}

#tapper-info {
	padding: 20px;
	margin-bottom: 20px;
	background: #F2F2F2;
	border: 1px solid #E0E0E0;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
}

#tapper-info p.tap-name {
	font-size: 18px;
}

#tapper-info a.button {
	padding: 5px;
	float: right;
	background: #ccc;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
	font-size: 12px;
}

#tapper-info a.button:hover {
	background: #84B5ED;
	text-decoration: none;
	color: #fff;
}

#tapper-info p.icon {
	float: left;
	margin-right: 30px;
}

#tapper-info p.tap {
	margin-top: 10px;
	font-size: 16px;
	padding-left: 90px;
}

#tapper-info span.tap-info {
	margin-top: 5px;
	font-size: 12px;
}

#tapper-info span.tap-resp {
	margin-left: 10px;
	font-size: 12px;
	padding-left: 10px;
	border-left: 1px solid #333;
}

#tapper-info a {
	color: #333;
}

#tap-chat-perma {
	background: #F2F2F2;
	border: 1px solid #E0E0E0;
	padding: 8px;
}

ul.tap-chat {
	height: 300px;
}

ul.tap-chat li {
	font-size: 16px;
}

input.tap-response {
	font-size: 14px;
}

div.tap-response-counter {
	right: 10px;
	color: #00B7E9;
}
</style>
</head>

<body>

	<?php 
		include($logged ? NEW_HEADER : LOGOUT_HEADER);
	?>

	<div id="main">

		<div class="left-col" style="margin-right: 20px">
			<div id="groups-tab">
				<div class="tab-in" style="color:#fff">Statistics</div>
			</div>
			<div class="tab-list">
				<div class="stats">
					<?php $stats = $_t['stats']; ?>
					<h2><span><?= $stats['message_count'] ?></span> taps sent.</h2>
					<h2><span><?= $stats['response_count'] ?></span> responses received.</h2>
					<h2><span><?= $stats['group_count'] ?></span> groups joined.</h2>
				</div>
			</div>
		</div>

		<div id="center-col">

			<div id="tapper-info" class="section">
				<p class="icon"><a href="/user/<?= $_t['user'] ?>"><img src="/user_pics/<?= $_t['user_pic_med'] ?>" /></a></p>
				<p class="tap-name">
					<a href="/user/<?= $_t['user'] ?>"><strong><?= $_t['user'] ?></strong></a>
					<span class="tap-typing" style="color:#518E3E; font-size:12px;"></span>
				</p>
				<?php
					if (!empty($_t['user_bits'])):
						$bit = array_shift($_t['user_bits'])
				?>
					<p class="tap" rel="<?= $bit['uid'] ?>">
						<?= $bit['chat_text'] ?><br />
						<span class="tap-info">
							<span class="tap-time <?= $bit['chat_timestamp_raw'] ?>"><?= $bit['chat_timestamp'] ?></span>
							<span class="tap-resp"><a href="/tap/<?= $bit['cid'] ?>">Respond</a></span>
						</span>
					</p>
				<?php
					endif;
				?>
				<div style="clear:both;"></div>
			</div>

			<div id="tap-feed" class="section">
				<div class="section-head">
					<h1>
						<input type="text" id="tap-feed-search" alt="Search through feed." />
						<span style="clear:right"></span>
						<span id="tap-feed-name"><?= $_t['user'] ?>'s Feed</span>
						<img src="/images/loading.gif" id="loading-indicator" style="display:none" />
					</h1>
				</div>
				<div class="section-body">
					<div id="tap-notify" style="display:none"></div>
					<ul id="main-stream" class="tap-stream">
						<?php
							if (!empty($_t['user_bits'])):
								foreach($_t['user_bits'] as $bit):
						?>
						<li id="tid_<?= $bit['cid'] ?>">
							<div class="tap-actions">
								<span class="tap-views">Viewers:
									<strong>
									<?= (!empty($bit['viewer_count'])) ? $bit['viewer_count'] : '0' ?>
									</strong>
								</span>
								<a class="tap-respond <?= empty($bit['count']) ? 'noresp' : '' ?>" href="/tap/<?= $bit['cid'] ?>">
									Respond <span class="tap-respond-count">(<?= $bit['count'] ?>)</span>
								</a>
								<p class="tap-respond-last <?= empty($bit['count']) ? 'noresp' : '' ?>">
									<strong>
										<?= (!empty($bit['resp_uname'])) ? $bit['resp_uname'] . ":" : "" ?>
									</strong>
									<span>
										<?php
											$last_rep = $bit['last_resp'];
											echo (strlen($last_rep) < 70) ? $last_rep : substr($last_rep, 0, 70) . '...';
										?>
									</span>
								</p>
							</div>
							<div class="tap-body">
								<p class="tap-prof-info">
									<span class="tap-time <?= $bit['chat_timestamp_raw'] ?>"><?= $bit['chat_timestamp'] ?></span>
									<span class="tap-typing"></span>
								</p>
								<p class="tap-prof-msg">
									<span class="tap-prof-msg"><?= $bit['chat_text'] ?></span>
								</p>
							</div>
							<div class="tap-response-box clarity">
								<div class="tap-response-counter"></div>
								<ul class="tap-chat <?= empty($bit['count']) ? 'noresp' : '' ?>">
								</ul>
								<input type="text" class="tap-response" style="width:420px" maxlength="240" alt="Respond to this tap." />
								<!-- <a href="#">Respond</a> or  --><a class="tap-respond-cancel" href="#">Close</a>
							</div>
							<div class="clarity" style="margin-bottom:20px"></div>
						</li>
						<?php
								endforeach;
							else:
						?>
						<li class="noresults">
							<p>There isn't anything here yet! <a href="/">Send a tap</a>!</p>
						</li>
						<?php
							endif;
						?>
					</ul>
				</div>
			</div>

		</div>

		<div id="left-col">
			<div id="groups-tab">
				<div class="tab-in" style="color:#fff"><?= $_t['user'] ?>'s Groups</div>
			</div>
			<div class="tab-list">
				<ul>
					<?php
						if (!empty($_t['your_groups'])):
							foreach ($_t['your_groups'] as $group):
					?>
					<li id="gid_<?= $group['gid'] ?>" class="group">
						<a href="/group/<?= $group['symbol'] ?>" grsymbol="<?= $group['symbol'] ?>" title="<?= $group['gname'] ?> (<?= $group['message_count'] ?>)" style="vertical-align: 0; margin-right: 5px"><img src="/group_pics/<?= $group['pic_36']?>" /></a>
						<a href="/group/<?= $group['symbol'] ?>" grsymbol="<?= $group['symbol'] ?>" title="<?= $group['gname'] ?> (<?= $group['message_count'] ?>)"><?= $group['display_symbol'] ?> <span class="unread-counter">(0)</span></a>
						<!-- <a class="add-tap-to" grtype="<?= $group['type'] ?>" href="#" title="Tap this group!">+</a> -->
					</li>
					<?php
							endforeach;
						endif;
					?>
				</ul>
			</div>
		</div>

	</div>

	<div id="templates" style="display:none">
		<ul id="template-bit">
			<# for (var x = this.reverse().length; x--;) { var bit = this[x]; #>
			<li id="tid_<#: bit.cid #>">
				<!-- <img src="/user_pics/<#: bit.pic_100 #>" class="avatar" alt="<#: bit.uname #>" rel="<#: bit.uid #>"  /> -->
				<div class="tap-actions">
					<span class="tap-views">Viewers:
						<strong><#: bit.viewer_count || 0 #></strong>
					</span>
					<# if (bit.count) { #>
					<a class="tap-respond" href="/tap/<#: bit.cid #>">
					<# } else { #>
					<a class="tap-respond noresp" href="/tap/<#: bit.cid #>">
					<# } #>
						Respond <span class="tap-respond-count">(<#: bit.count #>)</span>
					</a>
					<# if (bit.count) { #>
					<p class="tap-respond-last">
					<# } else { #>
					<p class="tap-respond-last noresp">
					<# } #>
						<strong>
							<#: bit.resp_uname ? bit.resp_uname + ":" : "" #>
						</strong>
						<# if (bit.last_resp) { #>
							<#: ((bit.last_resp.length < 70) ? bit.last_resp : bit.last_resp.substring(0, 70) + "...").linkify() #>
						<# } #>
					</p>
				</div>
				<div class="tap-body">
					<p class="tap-prof-info">
						<span class="tap-time <#: bit.chat_timestamp_raw #>"><#: bit.chat_timestamp #></span>
						<span class="tap-typing"></span>
					</p>
					<p>
						<span class="tap-prof-msg"><#: bit.chat_text.linkify() #></span>
					</p>
				</div>
				<div class="tap-response-box clarity">
					<div class="tap-response-counter"></div>
					<# if (bit.count) { #>
					<ul class="tap-chat">
					<# } else { #>
					<ul class="tap-chat noresp">
					<# } #>
					</ul>
					<input type="text" class="tap-response" style="width:420px" maxlength="240" alt="Respond to this tap." />
					<!-- <a href="#">Respond</a> or  --><a class="tap-respond-cancel" href="#">Close</a>
				</div>
				<div class="clarity" style="margin-bottom:20px"></div>
			</li>
			<# } #>
		</ul>
		<ul>
			<li id="no-taps" class="noresults">
				<p>There doesn't seem to be anything here.</p>
			</li>
			<li id="no-results" class="noresults">
				<p>
					No taps match your search keyword.
					<a href="#" class="reset-feed">Show all taps.</a>
				</p>
			</li>
		</ul>
	</div>

	<div id="footer">

	</div>

</body>
</html>
