<?php
$logged = (!empty($_SESSION['uid']));
if ($_t['no_user']) header('location:/');

function map_clean($func, $arr) {
	return array_filter(array_map($func, $arr));
}
$inits = array();
$people = array();
if (is_array($_t['user_bits'])) {
	function get_cids($bit) { return $bit['cid']; }
	$inits = map_clean("get_cids", $_t['user_bits']);
	function get_uids($bit) { return $bit['uid']; }
	$people = map_clean("get_uids", $_t['user_bits']);
}
$private = $_t['private'];
?>
<!doctype html>
<html>
<head>
	<?include(OK_HEADER)?>
	<script type="text/javascript" src="/views/scripts/tap.js"></script>
	<script type="text/javascript" src="http://<?=DOMAIN?>:8000/static/Orbited.js"></script>
	<script type="text/javascript">
		window._vars = {
			uid: "<?= $_t['pcid'] ?>",
			uname: "<?= $_SESSION['uname'] ?>",
			stream: JSON.decode('<?= json_encode($inits) ?>'),
			convos: [],
			people: JSON.decode('<?= json_encode($people) ?>'),
			groups: JSON.decode('<?= json_encode($groups) ?>'),
		};
	</script>
	<script type="text/javascript" src="/views/scripts/push.js"></script>
	<script type="text/javascript" src="/views/scripts/public.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>

</head>
<body>
	<div id="wrapper">

		<?include(OK_TOPBAR)?>

		<div id="main">

			<? ob_start(); ?>

				<div class="sideinfo section container">
					<h2>
						<span id="tab-name">groups (message stats)</span>
					</h2>
					<ul class="panel">
						<?php 
							if (!empty($_t['your_groups'])):
								foreach ($_t['your_groups'] as $group):
						?>
						<li class="panel-item" >
							<span class="count"><? if($group['admin']) echo "<span title='Moderator'>&#10070;</span>" ?></span>
							<img src="/group_pics/<?=$group['favicon']?>" title="<?$group['gname']?>" />&nbsp;
							<a href="/group/<?= $group['symbol'] ?>" class="names inblock-public ellipsis"><?= $group['gname'] ?></a>
							<span class="public-user-group-count"><?=rand(1,199)?></span>
						</li>
						<?php
								endforeach;
							else:
						?>
						<li class="notify">
							This user has no groups.
						</li>
						<?php
							endif;
						?>
					</ul>
				</div>
			<? $add_sidebar = ob_get_clean(); ?>
			<? include(OK_SIDEBAR); ?>

			<div id="content">
				
				<div id="infobox" class="pubgroup section container">
					<?php if($private):?>
						<button class="public-private-button">private account</button>
					<? else: ?>
						<?php if ($_t['user'] == $_SESSION["uname"]): ?>
						<button data-id="<?= $_t['uid'] ?>" class="you" disabled="disabled">this is you!</button>
						<?php elseif ($_t['tracked']): ?>
						<button data-id="<?= $_t['uid'] ?>" class="untrack">unfollow</button>
						<?php elseif ($logged): ?>
						<button data-id="<?= $_t['uid'] ?>" class="track">follow</button>
						<?php else: ?>
						<button data-id="<?= $_t['uid'] ?>" class="login">login to follow</button>
						<?php endif; ?>
					<? endif; ?>
					<img src="/user_pics/<?= $_t['user_pic_med'] ?>" class="avatar" />
					<h2><?= $_t['user'] ?> <span class="nick"><? if ($_t['user_online']) echo "<span class='useronline'>user online</span>"; else echo "user offline"; ?></span></h2>
					<p class="headline">&#8220;<?=$_t['about']?>&#8221;</p>
					<p class="stats">
						<?php $stats = $_t['stats']; ?>
						<strong><?= $stats['message_count'] ?></strong> Taps sent, 
						<strong><?= $stats['response_count'] ?></strong> Responses received, and
						<strong><?= $stats['group_count'] ?></strong> Groups joined.
					</p>
                                        <span style="float:right;display:block;color:lightgreen;opacity:0;" class="positive-click">Following!</span>
                                        <span style="float:right;display:block;color:red;opacity:0;" class="negative-click">Not following anymore :(</span>

				</div>

				<!-- 
				<form id="tapbox" action="" class="section active">
					<div id="tapto">
						<?= (!$logged) ? 'login to ' : '' ?>tap <?= strtolower($_t['gname']) ?>..
					</div>
					<span class="counter">240</span>
					<input id="taptext" tabindex="1" type="text">
					<button id="tapsend" tabindex="3" type="submit" <?= (!$logged) ? 'disabled="disabled" ' : '' ?>>tap!</button>
				</form>
				 -->

				<div id="tapstream" class="section">
					<div class="header header-non">
						<a href="" id="streamer" class="floater" alt="pause live streaming" title="pause live streaming"></a>
						<a id="newtaps" href="" class="floater">This feed has 5 new taps! Click here to load them.</a>
						<h2 class="header-title">
							<img src="/images/flat/loader.gif" />
							<span class="title">feed</span>
						</h2>
						<span class="stream-name"><?= $_t['user'] ?></span>
			
						<span id="public-following" >Followers ( <span class="count-one"><?=$_t['track_count']?></span> )</span>
						<span id="public-followers">Following ( <?=$_t['tracked_count']?>  )</span>

					</div>
					<div class="body">
						<ul id="taps" class="stream <?= empty($_t['user_bits']) ? "empty" : "" ?>">
							<?php if($private): ?>
							<li> <img class="private-lock" src="/images/flat/lock.png" />This user has a private account and does not share his taps outside his groups </li>
							<? else: ?>
							<?php
								if (!empty($_t['user_bits'])):
									foreach($_t['user_bits'] as $tap):
							?>
							<li id="tid_<?= $tap['cid'] ?>" class="container" 
								data-id="<?= $tap['cid'] ?>" data-uid="<?= $tap['uid'] ?>" data-user="<?= $tap['user'] ?>">
								<a href="/user/<?= $tap['uname'] ?>">
									<img class="avatar" alt="<?= $tap['uname'] ?>" src="/user_pics/<?= $tap['pic_100'] ?>" />
								</a>
								<p class="tap-from <?= ($tap['user_online'] || $tap['uname'] == $_SESSION['uname']) ? '' : 'offline' ?>">
									<a href="/user/<?= $tap['uname'] ?>"><?= trim($tap['uname'])?></a>,
									<a href="/tap/<?= $tap['cid'] ?>" class="date" data-timestamp="<?= $tap['chat_timestamp_raw'] ?>">
										<?= $tap['chat_timestamp'] ?>
									</a>
									<a href="/group/<?=$tap['symbol']?>"><img class="aggr-favicons" src="/group_pics/<?=$tap['favicon']?>" title="<?=$tap['gname']?>" /></a>
								</p>
								<p class="tap-body">
									<?= $tap['chat_text'] ?>
								</p>
								<p class="tap-actions">
									<span class="tap-resp">
										<span class="indicator">Someone's replying..</span>
										<span class="last-resp">
											<strong><?= (!empty($tap['resp_uname'])) ? $tap['resp_uname'] . ":" : "" ?></strong>
											<span class="body ellipsis inblock"><?= $tap['last_resp'] ?></span>
										</span>
									</span>
									<a href="#" class="tap-resp-count" title="view responses">
											<span class="show-resp-count"><?= $tap['count'] ?></span>
                                                                                        <span class="follow_button">Reply</span>
									</a>
								</p>
								<div class="responses">
									<ul class="chat">
									</ul>
									<input class="chatbox" type="text" />
									<div class="counter">240</div>
									<div class="overlay">type in your response and press enter.</div>
								</div>
							</li>
							<?php
									endforeach;
								else:
							?>
							<li id="no-taps-yet" class="notice">
								<p>Nothing yet! Try tapping this feed...</p>
							</li>
							<?php
								endif;
							endif;
							?>
						</ul>
					</div>
				</div>

			</div>

		</div>

		<div class="clarity"></div>
	
		<?include(OK_FOOTER)?>

	</div>
	<?include(JAVASCRIPT_TEMPLATES)?>	

        <?php if (!$logged): ?>
                <?include(FBCONNECT_BOTTOM)?>
        <?php endif; ?>

</body>
</html>
