<?php
	$logged = $ok_user;
	if ($no_user) header('location:/');

function map_clean($func, $arr) {
	return array_filter(array_map($func, $arr));
}
$inits = array();
$people = array();
if (is_array($user_bits)) {
	function get_cids($bit) { return $bit['cid']; }
	$inits = map_clean("get_cids", $user_bits);
	function get_uids($bit) { return $bit['uid']; }
	$people = map_clean("get_uids", $user_bits);
}
$private = $private;
?>
<!doctype html>
<html>
<head>
	<? $tpl_title="profile: ".$gname; ?>
	<? include(OK_HEADER); ?>
    <link title="" type="application/rss+xml" rel="alternate" href="http://<?=$_SERVER['SERVER_NAME']?>/rss_personal_<?=$user;?>.xml"/>
    <script type="text/javascript" src="http://<?=DOMAIN?>:8000/static/Orbited.js"></script>
	<script type="text/javascript">
		window._vars = {
			uid: "<?= $pcid ?>",
            anon: <?=$ok_user ? 0 : 1?>,
            fb: <?=$_SESSION['facebook'] ? 1 : 0?>,
            real_name: "<?=$_SESSION['real_name']?>",
			uname: "<?= $_SESSION['uname'] ?>",
			stream: JSON.decode('<?= json_encode($inits) ?>'),
			convos: [],
			people: JSON.decode('<?= json_encode($people) ?>'),
			groups: JSON.decode('<?= json_encode($groups) ?>'),
            filter: {
                gid: 'personal',
                uname: '<?=$user?>',
                uid: <?=$uid;?>
            }
		};
	</script>
	<script type="text/javascript" src="/views/scripts/tap.js"></script>
	<script type="text/javascript" src="/views/scripts/push.js"></script>
	<script type="text/javascript" src="/views/scripts/public.js"></script>  
	<script type="text/javascript" src="/views/scripts/filter.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
	<script type="text/javascript" src="/views/scripts/infobox.js"></script>
	<script type="text/javascript" src="/views/scripts/user.js"></script>
</head>
<body>
	<div id="wrapper">

	<? include(OK_TOPBAR) ?>

		<div id="main">
		<? ob_start(); ?>

				<div class="sideinfo section container">
					<h2>
						<span id="tab-name">channels (message stats)</span>
					</h2>
					<ul class="panel">
						<?php 
							if (!empty($your_groups)):
								foreach ($your_groups as $group):
						?>
						<li class="panel-item" >
							<span class="count"><? if($group['admin']) echo "<span title='Moderator'>&#10070;</span>" ?></span>
							<img src="/group_pics/<?=$group['favicon']?>" title="<?$group['gname']?>" />&nbsp;
							<a href="/channel/<?= $group['symbol'] ?>" class="names inblock-public ellipsis"><?= $group['gname'] ?></a>
							<span class="public-user-group-count"><?= $group['taps_count'] ?></span>
						</li>
						<?php
								endforeach;
							else:
						?>
						<li class="notify">
							This user has no groups.
						</li>
						<?php
							endif;
						?>
					</ul>
				</div>
				
		<? $add_sidebar = ob_get_clean(); ?>
		<? include(OK_SIDEBAR); ?>

			<div id="content">
				
				<div id="infobox" class="pubgroup section container">
					<?php if($private):?>
						<button class="public-private-button">private account</button>
					<? elseif (!$_SESSION['guest']): ?>
						<?php if ($user == $_SESSION["uname"]): ?>
						<button data-id="<?= $uid ?>" class="you" disabled="disabled">this is you!</button>
						<?php elseif ($tracked): ?>
						<button data-id="<?= $uid ?>" class="untrack">unfollow</button>
						<?php else: ?>
						<button data-id="<?= $uid ?>" class="track">follow</button>
						<?php endif; ?>
					<? endif; ?>
					<img src="/user_pics/<?= $user_pic_med ?>" class="avatar" />
					<h2><?= $user ?> <span class="nick"><? if ($user_online) echo "<span class='useronline'>user online</span>"; else echo "user offline"; ?></span></h2>
					<p class="headline">&#8220;<?=$about?>&#8221;</p>
					<p class="stats">
						<?php $stats = $stats;  ?>
						<strong><?= $stats['taps'] ?></strong> Taps sent, 
						<strong><?= $stats['responses'] ?></strong> Responses received, and
						<strong><?= $stats['groups'] ?></strong> Channels joined.
					</p>
                                        <span style="float:right;display:block;color:lightgreen;opacity:0;" class="positive-click">Following!</span>
                                        <span style="float:right;display:block;color:red;opacity:0;" class="negative-click">Not following anymore :(</span>

				</div>

                <form id="tapbox" action="" class="selection active <?= $pm ? '' : 'hidden' ?>">
                    <div id="tapto">
                        tap <?= strtolower($user) ?>...
                    </div>
                    <span class="counter">240</span>
                    <input id="taptext" tabindex="1" type="text">
                    <button id="tapsend" tabindex="3" type="submit">tap!</button>
                </form>

				<div id="tapstream" class="section">
					<div class="header header-non">
						<a href="" id="streamer" class="floater" alt="pause live streaming" title="pause live streaming"></a>
						<a id="newtaps" href="" class="floater">This feed has 5 new taps! Click here to load them.</a>
						<h2 class="header-title">
							<img src="/images/flat/loader.gif" />
							<span class="title">feed</span>
						</h2>
						<span class="stream-name"><?= $user ?></span>
					</div>
					<div class="body">
                        <div id="menus">
                            <a class="tab <?= !$pm ? 'selected' : '' ?>" href="#" title="<?=$user?> tapstream" data-name="tapstream">Tapstream</a>
                            <a class="tab" href="#" title="View following" data-name="following">Following (<?=$tracked_count?>)</a>
                            <a class="tab" href="#" title="View followers" data-name="followers">Followers (<?=$track_count?>)</a>
                            <a class="tab <?= $pm ? 'selected' : '' ?>" href="#" title="<?=$user?> private messages" data-name="pm">Private Messages</a>
                            <br>

                            <div id="user-tapstream" class="item selected">
                                <?
                                    if($private):
                                ?>
                                <ul id="taps" class="stream <?= empty($user_bits) ? "empty" : "" ?>">
                                    <li>
                                        <img class="private-lock" src="/images/flat/lock.png" />
                                        This user has a private account and does not share his taps outside his channels
                                    </li>
                                </ul>
                                <?
                                    else:
                                        $_taps = $user_bits;
                                        include(TAP_STREAM);
                                    endif;
                                ?>
                            </div>
                            <div id="user-following" class="item">
                                <? $people_list = $following;
                                   include(USERS_STREAM);?>
                            </div>
                            <div id="user-followers" class="item">
                                <? $people_list = $followers;
                                   include(USERS_STREAM);?>
                            </div>
                        </div>
					</div>
				</div>

			</div>

		</div>
	</div>
    <?include(OK_FOOTER)?>
</body>
</html>
