<?php
$logged = (!empty($_SESSION['uid']));
// if ($_t['no_tap']) header('location:/');

if (!empty($_t['user_bits'])) {
	$tap = array_shift($_t['user_bits']);
}
?>
<!doctype html>
<html>
<head>
	<? $tpl_title = "convo with ".$_t['user']; ?>
	<? include(OK_HEADER); ?>
	<script type="text/javascript" src="/views/scripts/tap.js"></script>
	<script type="text/javascript" src="http://<?=DOMAIN?>:8000/static/Orbited.js"></script>
	<script type="text/javascript">
		window._vars = {
			uid: "<?= $_t['pcid'] ?>",
			uname: "<?= $_SESSION['uname'] ?>",
			stream: JSON.decode('<?= json_encode($tap['cid']) ?>'),
			convos: [],
			people: JSON.decode('<?= json_encode($people) ?>'),
			groups: JSON.decode('<?= json_encode($groups) ?>')
		};
	</script>
	<script type="text/javascript" src="/views/scripts/push.js"></script>
	<script type="text/javascript" src="/views/scripts/public.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
</head>
<body>
	<div id="wrapper">

		<?include(OK_TOPBAR)?>

		<div id="main">

			<div id="sidebar">

				<?php if ($logged): ?>
	                                <?include(YOU)?>
				<?php endif; ?>

				<div class="sideinfo section container">
						
					<h3>	
						<?php if($_t['active_convo']):?>
						<span id="tab-name" class="untrack-convo follow_button" cid="<?= $tap['cid'] ?>">You are following this convo</span>
						<?php else: ?>
						<span id="tab-name" class="track-convo follow_button" cid="<?= $tap['cid'] ?>">Follow this convo</span>
						<?php endif;?>
					</h3>

					<h2>
						<span id="tab-name">in this convo</span>
					</h2>
					<ul class="panel">
						<?php 
							if (!empty($_t['invovled'])):
								foreach ($_t['invovled'] as $person):
						?>
						<li class="panel-item" >
							<span class="count"><?= $person['count'] ?></span>	
							<img class="small-pic" src="/user_pics/<?= $person['small_pic'] ?>" />
							&nbsp;
							<a href="/user/<?= $person['uname'] ?>" class="names inblock-public ellipsis"><?= $person['uname'] ?></a>
						</li>
						<?php
								endforeach;
							else:
						?>
						<li class="notify">
							no one's responded yet
						</li>
						<?php
							endif;
						?>
					</ul>
				</div>
				
			</div>

			<div id="content">
				
				<div id="infobox" class="pubgroup section container">
					<?php if (!$logged): ?>
					<button class="login">login to respond</button>
					<?php endif; ?>
					<img src="/user_pics/<?= $_t['user_pic_med'] ?>" class="avatar" />
					<h2><?= $_t['user'] ?> <span class="nick"></span></h2>
					<p class="headline">&#8220;<?=$_t['about']?>&#8221;</p>
					<p class="stats">
						<?php $stats = $_t['stats']; ?>
						<strong><?= $stats['message_count'] ?></strong> Taps sent, 
						<strong><?= $stats['response_count'] ?></strong> Responses received, and
						<strong><?= $stats['group_count'] ?></strong> Channels joined.
					</p>
				</div>

				<!-- 
				<form id="tapbox" action="" class="section active">
					<div id="tapto">
						<?= (!$logged) ? 'login to ' : '' ?>tap <?= strtolower($_t['gname']) ?>..
					</div>
					<span class="counter">240</span>
					<input id="taptext" tabindex="1" type="text">
					<button id="tapsend" tabindex="3" type="submit" <?= (!$logged) ? 'disabled="disabled" ' : '' ?>>tap!</button>
				</form>
				 -->

				<div id="tapstream" class="section">
					<div class="header header-non">
						<a id="newtaps" href="" class="floater">This feed has 5 new taps! Click here to load them.</a>
						<h2 class="header-title">
							<img src="/images/flat/loader.gif" />
							<span class="title">convo</span>
						</h2>
						<span class="stream-name">with <?= $_t['user'] ?>&nbsp; 
						<a href="/channel/<?=$tap['symbol']?>" /><img class="public-tap-favicon aggr-favicons" src="/group_pics/<?= $tap['favicon']?>" title="<?=$tap['gname']?>" />
						
                        
                        <!-- AddThis Button BEGIN -->
<a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=250&amp;username=xa-4c40ca132ba5c7bb"><img src="/images/addthis.gif" width="153" height="16" alt="Bookmark and Share" style="border:0"/></a><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=xa-4c40ca132ba5c7bb"></script>
<!-- AddThis Button END -->


                        
                        </span>
					</div>
					<div class="body">
						<ul id="taps" class="stream <?= empty($_t['user_bits']) ? "empty" : "" ?>">
							<li id="tid_<?= $tap['cid'] ?>" class="container" 
								data-id="<?= $tap['cid'] ?>" data-uid="<?= $tap['uid'] ?>" data-user="<?= $_t['user'] ?>">
								<a href="/user/<?= $tap['uname'] ?>">
									<img class="avatar" alt="<?= $tap['uname'] ?>" src="/user_pics/<?= $tap['pic_100'] ?>" />
								</a>
								<p class="tap-from <?= ($tap['user_online'] || $tap['uname'] == $_SESSION['uname']) ? '' : 'offline' ?>">
									<a href="/user/<?= $tap['uname'] ?>"><?= trim($tap['fname'] . " " . $tap['lname']) ?></a>,
									<a href="/tap/<?= $tap['cid'] ?>" class="date" data-timestamp="<?= $tap['chat_timestamp_raw'] ?>">
										<?= $tap['chat_timestamp'] ?>
									</a>
								</p>
								<p class="tap-body">
									<?= $tap['chat_text'] ?>
								</p>
								<p class="tap-actions">
									<span class="tap-resp">
										<span class="indicator">Someone's replying..</span>
										<span class="last-resp">
											<strong><?= (!empty($tap['resp_uname'])) ? $tap['resp_uname'] . ":" : "" ?></strong>
											<span class="body ellipsis inblock"><?= $tap['last_resp'] ?></span>
										</span>
									</span>
									<a href="#" class="tap-resp-count" title="view responses">
										<span class="count">
											<?= $tap['count'] ?>
										</span>
									</a>
									<span class="tap-view-count count" title="viewers">
										<?= (!empty($tap['viewer_count'])) ? $tap['viewer_count'] : '0' ?>
									</span>
								</p>
								<div class="responses perma">
									<ul class="chat chat-pub">
										<?php
											if (!empty($_t['responses'])):
												foreach($_t['responses'] as $resp):
										?>
										<li>
											<em data-timestamp="<?= $resp['chat_time'] ?>">
												<?= date('g:i A', $resp['chat_time']) ?>
											</em>
											<a href="/user/<?= $resp['uname'] ?>" class="user"><?= $resp['uname'] ?>:</a> <span><?= $resp['chat_text'] ?></span>
										</li>
										<?php
												endforeach;
											endif;
										?>
									</ul>
									<input class="chatbox" type="text" />
									<div class="counter">240</div>
									<div class="overlay">type in your response and press enter.</div>
								</div>
							</li>
						</ul>
					</div>
				</div>

			</div>

		</div>

		<div class="clarity"></div>
		<?include(OK_FOOTER)?>
	</div>
	<?include(JAVASCRIPT_TEMPLATES)?>	
</body>
</html>
