<rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	> 
 
<channel> 
	<title><?=$_t['symbol']?> Tap Channel Feed</title> 
	<atom:link href="http://tap.info/rss?symbol=<?=$_t['symbol']?>" rel="self" type="application/rss+xml" /> 
	<link>http://tap.info/about</link> 
	<description>tap - real-time communication platform</description> 
	<lastBuildDate><?=date('r');?></lastBuildDate> 
	<language>en</language> 
	<sy:updatePeriod>hourly</sy:updatePeriod> 
	<sy:updateFrequency>1</sy:updateFrequency> 

		<?php
		if (!empty($_t['user_bits'])):
			foreach($_t['user_bits'] as $tap):
		?>

		<item>
		<title><?=$tap['chat_text']?> tap</title>
		<link>http://tap.info/tap/<?=$tap['cid']?></link>
		<guid>http://tap.info/tap/<?=$tap['cid']?></guid>
		<pubDate><?=date( 'r', $tap['chat_timestamp_raw'] ) ?></pubDate>
		<description><![CDATA[<?=$tap['chat_text']?>]]></description>
		</item>
		<?php
			endforeach;
		endif;
		?>

</channel> 
</rss> 
