<?php
$res = $_t['edit_profile'];
$fname = $res['fname'];
$lname = $res['lname'];
$uname = $_SESSION['uname'];
$email = $res['email'];
$pic = $res['pic_180'];
$country = $res['country'];
$state = $res['state'];
$region = $res['region'];
$town = $res['town'];
$lang = $res['lang'];

$stat = $_t['stats'];
$message_count = $stat['message_count'];
$response_count = $stat['response_count'];
$group_count = $stat['group_count'];
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11153159-1");
pageTracker._trackPageview();
} catch(err) {}</script>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>tap - alpha</title>

<link rel="stylesheet" href="/views/style_sheets/global.css" type="text/css" >
<link rel="stylesheet" href="/views/style_sheets/settings.css" type="text/css" >


<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="icon" href="images/favicon.ico" type="image/x-icon" />

<!--[if lt IE 7]>
        <script type="text/javascript" src="js/unitpngfix.js"></script>
<![endif]-->

<script type="text/javascript" src="/views/javascript/mpmetrics.js"></script>
<script type="text/javascript">try { mpmetrics.init('<?= METRIC_KEY ?>');} catch(err) { alert(err) }</script>
<script type="text/javascript" charset="utf-8">
</script>
</head>

<body>

	<? include(HEADER_CLEAN); ?>

	<div id="main">
		<div id="sidebar-left" class="sidebar">
			<div class="section-head">
			<h1>Stats</h1>
			</div>
			<div class="section-body user-stats">
				<p><span><?= $message_count ?></span> taps from you.</p>
				<p><span><?= $response_count ?></span> responses received.</p>
				<p><span><?= $group_count ?></span> groups joined.</p>
			</div>
		</div>

		<div id="content">

			<div id="settings" class="section">

                                <div class="section-head big">
                                        <span class="tab on" id="pass">Settings</span>
                                        <h1>
                                                <span>Settings</span>
                                        </h1>
                                </div>
			<? if($_t['settings_updated']) echo "Settings successfully updated"; ?>


			<div class="section-body info">
                                        <div id="youraccount" class="panel selected">

					<form action="/settings" method="post">
						<h1>Email me when someone...</h1>
						<? foreach($_t['settings'] as $setting):
							$respond = $setting['respond'];
							$track = $setting['track'];
							$join_group = $setting['join_group'];

							$c = 'checked';
							if($respond==1) $r1_1=$c;else $r1_0=$c;
							if($track==1) $r3_1=$c;else $r3_0=$c;
							if($join_group==1) $r4_1=$c;else $r4_0=$c;
						?>
						<h2 class="in-title">
							Responds to my tap: 
							<ul class="setting_buttons">
								<li>On<input type="radio" name="respond" value="1" <?=$r1_1?> /></li>
								<li>Off<input type="radio" name="respond" value="0" <?=$r1_0?>/></li>
							</ul>
						</h2>
						<h2 class="in-title">
							Tracks me:
							<ul class="setting_buttons">
								<li>On<input type="radio" name="track" value="1" <?=$r3_1?> /></li>
								<li>Off<input type="radio" name="track" value="0" <?=$r3_0?>/></li>
							</ul>
						</h2>
						<h2 class="in-title">
							Joins a group I own/moderate:
							<ul class="setting_buttons">
								<li>On<input type="radio" name="join_group" value="1" <?=$r4_1?> /></li>
								<li>Off<input type="radio" name="join_group" value="0" <?=$r4_0?>/></li>
							</ul>

						</h2>
						<? endforeach; ?>
						<input style="height:25px;" type="submit" value="submit" name="submit" />
						</form>
					</div>
					<div class="clarity"></div>
				</div>
			</div>
		</div>

	
		<div id="sidebar-right" class="sidebar">
                        <div class="section">
                                <div class="section-head gray">
                                        <h1>Help and Tips</h1>
                                </div>
                                <div class="section-body info">
			<h2>Set your account info correctly.</h2>
			<p>Your account information is not only required, but it's also useful for your friends and contacts to locate you on tap. So make sure to input correct information.</p>
			<h2>Keep your password safe.</h2>
			<p>Weak passwords could easily be sniffed using special tools, so make sure you use stronger passwords. Mix letters and numbers, and add a few symbols from your keyboard.</p>
                                </div>
                        </div>
                </div>

	</div>

	<div id="footer"></div>

</body>
</html>
