<?php
$res = $_t['edit_profile'];
$fname = $res['fname'];
$lname = $res['lname'];
$uname = $_SESSION['uname'];
$email = $res['email'];
$pic = $res['pic_180'];
$country = $res['country'];
$state = $res['state'];
$region = $res['region'];
$town = $res['town'];
$lang = $res['lang'];

$stat = $_t['stats'];
$message_count = $stat['message_count'];
$response_count = $stat['response_count'];
$group_count = $stat['group_count'];
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-11153159-1");
pageTracker._trackPageview();
} catch(err) {}</script>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="EN" />
<meta name="ROBOTS" content="ALL" />
<meta name="Copyright" content="Copyright (c) 2009 TAP" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />

<title>tap - alpha</title>

<link rel="stylesheet" href="/views/style_sheets/group_manage.css" type="text/css" >
<link rel="stylesheet" href="/views/style_sheets/profile.css" type="text/css" >


<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="icon" href="images/favicon.ico" type="image/x-icon" />

<!--[if lt IE 7]>
        <script type="text/javascript" src="js/unitpngfix.js"></script>
<![endif]-->

<script src="/views/javascript/mootools-1.2.3-core-yc.js" type="text/javascript"></script>
<script src="/views/javascript/mootools-1.2.3.1-more.js" type="text/javascript" charset="utf-8"></script>
<script src="/views/javascript/mootools-tap.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="/views/javascript/mpmetrics.js"></script>
<script type="text/javascript">try { mpmetrics.init('<?= METRIC_KEY ?>');} catch(err) { alert(err) }</script>
<script type="text/javascript">
Tap = window.Tap || {};
Tap.Vars = {
	country: "<?= $country ?>",
	region: "<?= $region ?>",
	state: "<?= $state ?>",
	town: "<?= $town ?>",
	lang: "<?= $lang ?>"
};
</script>
<script type="text/javascript" charset="utf-8">
Tap.Profile = {

	init: function(){
		var body = document.body;
		var tabs = body.getElements('.tab');
		var panels = body.getElements('.panel');
		tabs.addEvent('click', function(){
			panels.filter('.selected').removeClass('selected');
			tabs.filter('.on').removeClass('on');
			this.addClass('on');

			if (this.get('id') === 'account') {
				$('youraccount').addClass('selected');
			}
		});
		tabs[0].fireEvent('click');

		$('saveprofile').addEvent('click', this.onProfileSave.toHandler(this));
	},



	noErrors: function(){
		return !$H(this.data).getValues().map(function(item){
			return !!item.retrieve('passed');
		}).contains(false);
	},

	onProfileSave: function(_, e){
		var data = this.data;
		if (this.uploading) {
			arguments.callee.delay(3000, this, [_, e]);
			return null;
		}
		var send = {
			fname: data.fname.get('value'),
			lname: data.lname.get('value'),
			email: data.email.get('value'),
			lang: data.lang.get('value')
		};
		if (this.pic) $extend(send, { old_name: this.pic });
		// if (!data.state.get('value').isEmpty()) send.state = data.state.get('value');
		// if (!data.region.get('value').isEmpty()) send.region = data.region.get('value');
		// if (!data.town.get('value').isEmpty()) send.town = data.town.get('value');
		this.onSave(send, 'edit_profile', e);
		mpmetrics.track('update-profile', {});
	},

	onPasswordSave: function(_, e){
		var data = this.data;
		var send = {
			old_pass: data.current.get('value'),
			new_pass: data.newpass.get('value')
		};
		this.onSave(send, 'password_profile', e, function(){
			$$(data.current, data.newpass, data.newpass_repeat).set('value', '');
		});
		mpmetrics.track('update-password', {});
	},

	onSave: function(send, url, e, callback){
		var self = this;
		var data = this.data;
		if (this.noErrors()) {
			var req = new Request({
				'url': 'AJAX/' + url + '.php',
				'async': false,
				'data': send,
				onSuccess: function(){
					var response = JSON.decode(this.response.text);
					if (response && response.success) {
						$('gr-create-success').set('text', 'Your changes have been saved!').fade('show').highlight().fade('out');
						if ($type(callback) == 'function') callback.apply(self);
					} else {
						$('gr-create-success').set('text', 'There was an error with your request, please try again.').fade('show').highlight('#fdebeb').fade('out');
					}
				}
			});
			req.send();
		} else {
			$$($H(this.data).getValues().filter(function(item){
				return !item.retrieve('passed');
			})).fireEvent('blur', [e]);
		}
	}
};

window.addEvent('domready', Tap.Profile.init.bind(Tap.Profile));
</script>
</head>

<body>

	<? include(NEW_HEADER); ?>

	<div id="main">
		<div id="left-col">
			<div id="profile-tab">
				<div class="tab-in">Stats</div>
			</div>
			<div class="tab-list">
				<h2><span><?= $message_count ?></span> taps from you.</h2>
				<h2><span><?= $response_count ?></span> responses received.</h2>
				<h2><span><?= $group_count ?></span> groups joined.</h2>
			</div>
		</div>

		<div id="center-col">
			<div id="profile">
				<div id="profile-header">
					<h2 class="gr-title">Settings</h2>
					<span class="tab on" id="account">Settings</span>
				</div>
			<? if($_t['settings_updated']) echo "Settings successfully updated"; ?>

				<div class="main-frame">
					<div id="youraccount" class="panel">
					<form action="/settings" method="post">
						<h1>Email me when someone...</h1>
						<? foreach($_t['settings'] as $setting):
							$respond = $setting['respond'];
							$track = $setting['track'];
							$join_group = $setting['join_group'];

							$c = 'checked';
							if($respond==1) $r1_1=$c;else $r1_0=$c;
							if($track==1) $r3_1=$c;else $r3_0=$c;
							if($join_group==1) $r4_1=$c;else $r4_0=$c;
						?>
						<h2 class="in-title">
							Responds to my tap: 
							<ul class="setting_buttons">
								<li>On<input type="radio" name="respond" value="1" <?=$r1_1?> /></li>
								<li>Off<input type="radio" name="respond" value="0" <?=$r1_0?>/></li>
							</ul>
						</h2>
						<h2 class="in-title">
							Tracks me:
							<ul class="setting_buttons">
								<li>On<input type="radio" name="track" value="1" <?=$r3_1?> /></li>
								<li>Off<input type="radio" name="track" value="0" <?=$r3_0?>/></li>
							</ul>
						</h2>
						<h2 class="in-title">
							Joins a group I'm in:
							<ul class="setting_buttons">
								<li>On<input type="radio" name="join_group" value="1" <?=$r4_1?> /></li>
								<li>Off<input type="radio" name="join_group" value="0" <?=$r4_0?>/></li>
							</ul>

						</h2>
						<? endforeach; ?>
						<input style="height:25px;" type="submit" value="submit" name="submit" />
						</form>
					</div>
					<div style="clear:both"></div>
				</div>
				<div class="main-frame-bottom"></div>
			</div>
		</div>

		<div id="right-col">
			<h1>Help and Tips</h1>
			<h2>Set your account info correctly.</h2>
			<p>Your account information is not only required, but it's also useful for your friends and contacts to locate you on tap. So make sure to input correct information.</p>
			<h2>Keep your password safe.</h2>
			<p>Weak passwords could easily be sniffed using special tools, so make sure you use stronger passwords. Mix letters and numbers, and add a few symbols from your keyboard.</p>

		</div>
	</div>

	<div id="footer"></div>

</body>
</html>
