<?php
    $_h = array(
        'title'   => $user['fname'].' '.$user['lname'],
        'scripts' => array('main.js', 'push.js', 'search.js', 'modal.js', 'feed.js','sidebar.js', 'Swiff.Uploader.js', 'user_edit.js'),
        'styles'  => array('roar.css', 'modal.css'),
        'vars'    => array('user'  => $me,
                           'guest' => $guest,
                           'feed'  => array('type' => 'friend', 'id' => $user['id']),
                           'comet' => array('groups' => array())),
        'guest'   => $guest);
    include(HEADER);
?>
    <div id="content">
    	
        <div id="left">
        
        	<h1 class="title profile">Circles <?=$user['fname']?> is part of 
            <? if (count($circles) >= 10): ?>
                <a class="view-all" href="#"
                   data-type="groups"
                   data-id="<?=$user['id']?>">view all...</a>
            <? endif; ?>
            </h1>
            
            <div class="user-circles" id="experience">
                <?php
                    $_cl['list'] = $circles;
                    include(CIRCLE_LIST);
                ?>
                <div class="clear"></div>
            </div><!--user-circles-->

            <?php
                $_f = array(
                    'feed' => $feed,
                    'name' => $user['fname']."'s Feed",
                    'user' => true
                );
                include(FEED);
            ?>        
        </div><!--left-->

        <?php
            $_s = array(
                'user'      => $user,
                'followers' => $followers,
                'following' => $following,
                'state'     => $state
            );
            include(SIDEBAR);
        ?>
    </div><!--content-->
<?php
    include(FOOTER);
?>
