<?php
    $_h = array(
        'title'   => $user['fname'].' '.$user['lname'],
        'scripts' => array('main.js', 'push.js', 'search.js', 'modal.js', 'feed.js'),
        'styles'  => array('roar.css', 'modal.css'),
        'vars'    => array('user'  => $me,
                           'guest' => $guest,
                           'feed'  => array('type' => 'friend', 'id' => null)),
        'guest'   => $guest);
    include(HEADER);
?>
    <div id="content">
    	
        <div id="left">
        
        	<h1 class="title profile">Circles <?=$user['fname']?> is part of <a class="view-all" href="#">view all...</a></h1>
            
            <div class="user-circles">
                <?php
                    $_cl['list'] = $circles;
                    include(CIRCLE_LIST);
                ?>
                <div class="clear"></div>
            </div><!--user-circles-->

            <?php
                $_f = array(
                    'feed' => $feed,
                    'name' => $user['fname']."'s"
                );
                include(FEED);
            ?>        
        </div><!--left-->

        <?php
            $_s = array(
                'user'      => $user,
                'followers' => $followers,
                'following' => $following
            );
            include(SIDEBAR);
        ?>
    </div><!--content-->
<?php
    include(FOOTER);
?>
