<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Content-Language" content="en-us" />
	<meta name="robots" content="noodp" />
	<meta name="image-toolbar" content="no" />
	<meta name="copyright" content="Copyright (c) 2009 TAP" />
	<meta name="description" content="TAP communication platform" />
	<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />
	<title>tap</title>
	<link rel="stylesheet" href="/views/styles/global.css" type="text/css" />
	<link rel="stylesheet" href="/views/styles/public.css" type="text/css" />
	<script type="text/javascript" src="/views/scripts/mootools-core.js"></script>
	<script type="text/javascript" src="/views/scripts/mootools-more.js"></script>
	<script type="text/javascript" src="/views/scripts/login.js"></script>
	<script type="text/javascript" src="/views/scripts/search.js"></script>
	<script type="text/javascript" src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/FeatureLoader.js.php"></script>
        <script src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/XdCommReceiver.js" type="text/javascript"></script>
</head>
<body>
	<div id="wrapper">

			<?php if ($logged): ?>
				<?include(HEADER)?>
			<?php else: ?>
				<?include(HEADER_LOGOUT)?>
			<?php endif; ?>


		<div id="main">

			<div id="sidebar">
				
				<div id="inviter" class="section container">
					<h2>Want to start tapping?</h2>
					<p>Tap is invite only right now. If you want to be one of our early tappers, <a href="/">signup for an invite</a>.</p>
				</div>
				<?include(LOGIN);?>	
			</div>

			<div id="content">
				
				<div class="section">
					<div class="header">
						<h2 class="header-title">
							<span class="title">?</span>
						</h2>
						what's tap?
					</div>
					<div class="body">
						<div class="full info">
							<p class="callout">Tap is a new social-communication tool that gives you real-time connection to individuals, groups and even geographical areas, without the burden of memorizing any special usernames or address. With Tap, you can send messages to anyone in the world, even if you don&#8217;t know where they are or how to address you messages.</p>

							<p>Everything in Tap works in real-time: send a tap and it instantly appears on other people&#8217;s feeds. Conversations are also instantaneous: you&#8217;ll be able to respond to taps and see the responses from other people in real time.</p>

							<h2>How Does it Work?</h2>

							<p>It&#8217;s simple: all you have to do is compose your message, called a &#8220;tap,&#8221; and select the individuals or groups you&#8217;re sending to. You can add as many individuals or groups you want to get the tap. Hit send and your tap is automatically sent to their feeds.</p>

							<p>You can also respond directly to any taps in your feed, turning it into an active conversation.</p>

							<h2>Why Does it Work?</h2>
							<p>Because Tap connects you to people that matter.</p>
							<p>Unlike other available social communication tools, Tap lets you focus your message to the people who you know want to receive it. Gone are the days of sending out messages in the hope of getting someone to actually reply.</p>
							<p>With Tap, you send messages to your groups. Whether it's a group of friends, a group of people you share the same interest with or even a geographical area you're in, Tap lets you communicate with people who'll be happy to read your messages.</p>

							<h2>How Do I Join?</h2>
							<p>Simple! Just fill up the signup form on your right and hit submit! Signing up is a one time process and it's totally free.</p>
							<p>After signing up, you'll automatically be logged in. Join groups, create new ones, and then tap 'em!</p>
						</div>
					</div>
				</div>
			</div>

		</div>
		
		<div class="clarity"></div>
		
		<div id="footer">
			<strong>tap &copy; 2010.</strong>
			<span class="nav">
				<a href="/" class="current">home</a>
				<a href="/what">what's tap?</a>
				<a href="/about">about us</a>
				<a href="/devs">developers</a>
				<a href="/contact">contact</a>
			</span>
		</div>
	</div>
	
	<?include(JAVASCRIPT_TEMPLATES)?>

<script type="text/javascript">
var _gaq = _gaq || [];
 _gaq.push(['_setAccount', 'UA-11153159-1']);
 _gaq.push(['_trackPageview']);

 (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
 })();
</script>
		<?include(FBCONNECT_BOTTOM)?>
</body>
</html>
