#!/bin/bash

mysql -uroot -proot -Drewrite2 -e " 

DELETE FROM TEMP_ONLINE WHERE uid = $1;
DELETE FROM settings WHERE uid = $1;
DELETE FROM group_members WHERE uid = $1;
DELETE FROM profile WHERE uid = $1;
DELETE FROM login WHERE uid = $1;
"
