<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Chatapist - Profile</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css" media="all">@import "views/style_sheets/home.css";</style>
</head>

<body>

<div id="container">
	
	<?php include(HEADER);?>
		
	<?php include(LEFT);?>
	
		<div id="friends">
		
			<div id="friends_header">Friends</div>
			
			<div id="friends_top_contiainer">
					
					<div id="friends_top_left_container">
							<span id="change_organize">Change Organization:</span>
							
							<div id="friends_show_organize">
								<h4>How you would like your friends organized?:</h4>
								
								<ul>
									<li><a href="#">Alphabetical Order</a></li>
									<li><a href="#####">Overall Ranking Order</a></li>
								</ul>
								
								<ul>
									<li><a href="####">Catagory Ranking Order</a></li>
									<li><a href="#####">Closest Vicinity Order</a></li>
								</ul>
								
							</div>
					</div>
			
			
					
			<div id="network_status">
			
				<ul>
					<li>Ranking: 9.8</li>
					<li>Network Ranking: 9.4</li>
					<li>Friends: 28</li>
					<li>Highest: 10</li>
				</ul>
			
			</div>
			
			</div>
			
			<!-- friends left container start -->
			<div id="friend_container_left">
				
				<div class="friend_category">Testing</div>
				
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					
					<div class="friend">
					
						<div class="friend_name"><span class="friend_name_span">Mike</span></div>
						
						<div class="thumbnail_friend">Test</div>
						
						<div class="friend_info">
							<ul>
								<li><span class="style_bold">Username: </span>Mike2049259258</li>
								<li><span class="style_bold">Rank: </span> 24+</li>
								<li><span class="style_bold">Groups:</span></li>
						
									<li>WCC Westchester Community College</li>
									<li>Chatapist</li>
									<li>My Friends</li>
									<li>My Friends</li>
							</ul>
								
						</div>
		
					</div>
					
					<div class="friend_category">Testing</div>
					
					<div class="friend">
					
						<div class="friend_name"><span class="friend_name_span">Mike</span></div>
						
						<div class="thumbnail_friend">Test</div>
						
						<div class="friend_info">
							<ul>
								<li><span class="style_bold">Username:</span> Mike2049259258</li>
								<li><span class="style_bold">Rank: </span> 24+</li>
								<li><span class="style_bold">Groups:</span></li>
						
									<li>WCC Westchester Community College</li>
									<li>Chatapist</li>
									<li>My Friends</li>
									<li>My Friends</li>
							</ul>
								
						</div>
		
					</div>
					
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					
					<div class="friend">
					
						<div class="friend_name"><span class="friend_name_span">Mike</span></div>
						
						<div class="thumbnail_friend">Test</div>
						
						<div class="friend_info">
							<ul>
								<li><span class="style_bold">Username:</span> Mike2049259258</li>
								<li><span class="style_bold">Rank: </span> 24+</li>
								<li><span class="style_bold">Groups:</span></li>
						
									<li>WCC Westchester Community College</li>
									<li>Chatapist</li>
									<li>My Friends</li>
									<li>My Friends</li>
							</ul>
								
						</div>
		
					</div>
					
					
					<div class="friend">
					
						<div class="friend_name"><span class="friend_name_span">Mike</span></div>
						
						<div class="thumbnail_friend">Test</div>
						
						<div class="friend_info">
							<ul>
								<li><span class="style_bold">Username:</span> Mike2049259258</li>
								<li><span class="style_bold">Rank: </span> 24+</li>
								<li><span class="style_bold">Groups:</span></li>
						
									<li>WCC Westchester Community College</li>
									<li>Chatapist</li>
									<li>My Friends</li>
									<li>My Friends</li>
							</ul>
								
						</div>
		
					</div>
						

				</div>
				<!-- end of friend left container -->
				
				
				
				<!-- start of friend right container -->
				<div id="friend_container_right">
				
				
				<div class="friend_category">Testing</div>
				
				<div class="friend_collapsed">testing</div>
				<div class="friend_collapsed">testing</div>
					<div class="friend">
					
						<div class="friend_name"><span class="friend_name_span">Mike</span></div>
						
						<div class="thumbnail_friend">Test</div>
						
						<div class="friend_info">
							<ul>
								<li><span class="style_bold">Username:</span> Mike2049259258</li>
								<li><span class="style_bold">Rank: </span> 24+</li>
								<li><span class="style_bold">Groups:</span></li>
						
									<li>WCC Westchester Community College</li>
									<li>Chatapist</li>
									<li>My Friends</li>
									<li>My Friends</li>
							</ul>
								
						</div>
		
					</div>
					
					
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					
					<div class="friend_category">Testing</div>
					
					<div class="friend_collapsed">testing</div>
					<div class="friend">
					
						<div class="friend_name"><span class="friend_name_span">Mike</span></div>
						
						<div class="thumbnail_friend">Test</div>
						
						<div class="friend_info">
							<ul>
								<li><span class="style_bold">Username:</span> Mike2049259258</li>
								<li><span class="style_bold">Rank: </span> 24+</li>
								<li><span class="style_bold">Groups:</span></li>
						
									<li>WCC Westchester Community College</li>
									<li>Chatapist</li>
									<li>My Friends</li>
									<li>My Friends</li>
							</ul>
								
						</div>
		
					</div>
					
										<div class="friend">
					
						<div class="friend_name"><span class="friend_name_span">Mike</span></div>
						
						<div class="thumbnail_friend">Test</div>
						
						<div class="friend_info">
							<ul>
								<li><span class="style_bold">Username:</span> Mike2049259258</li>
								<li><span class="style_bold">Rank: </span> 24+</li>
								<li><span class="style_bold">Groups:</span></li>
									<li>WCC Westchester Community College</li>
									<li>Chatapist</li>
									<li>My Friends</li>
									<li>My Friends</li>
							</ul>
								
						</div>
		
					</div>
					
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					<div class="friend_collapsed">testing</div>
					
					
				</div>
				
				<!-- end of friend left container -->
			
			
		</div>
		
</div>

	<?php include(FOOTER);?>

</body>
</html>