<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Chatapist - Profile</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css" media="all">@import "views/style_sheets/home.css";</style>
</head>

<body>

<div id="container">
	
	<?php include(HEADER);?>
		
	<?php include(LEFT);?>
	
	<div id="manage_groups">
	
		<div id="manage_groups_header">Manage Groups</div>
	
			<div id="manage_groups_intro">
		
			<p>
			Welcome to Manage Groups.  Here you can Add, Create, and Remoeve yourself from groups that you like.
			By adding yourself to a group, you enable yourself to message everyoone in the group and participate in receive
			updates from that group.
			</p>
			
			<div id="manage_groups_go_away"><a href="#">Click to not display this message.</a></div>
		
		</div>

		<div id="manage_groups_body">
		
			<div id="manage_groups_top">
			
				<span id="create_group_span">Create a Group&nbsp;</span>
			
			<span id="relate_groups_title">Related Groups</span>
			<div id="search_related_wrapper">
			
				<div id="search_groups">
					
					<form action="_self">
						<fieldset>
						<legend>Search Groups To Join:</legend>
						
							<ul>
										<li><label for="group_name">Name </label><input type="text" id="group_name"></input></li>
										<li><a href="#">Advanced Search</a></li>
											<li>
												<ul>
													<li><label for="search_group_name">Keywords in Description </label><input type="text" id="search_group_name"></input></li>
													<li><label for="search_group_cred">Credibility Atleast.. </label><input type="text" id="search_group_cred"></input></li>
													<li><label for="search_group_zip">Zipcode </label><input type="text" id="search_group_zip"></input></li>
													<li>
														<label for="serach_group_category">Category </label>
															<select id="serach_group_category">
																<option>test</option>
															</select>
													</li>
												</ul>
											</li>
										<li><button type="submit">Search</button></li>
							</ul>
						
						</fieldset>
					</form>
		
				</div>
				
				<div id="related_groups">
				
					<div class="related_group_wrapper">
						<span class="group_more_wrapper">
							<span class="related_group_pic">test</span>
							<span class="related_group_more"><a href="#">More Info..</a></span>
						</span>
						
							<ul class="related_group_list">
								<li class="related_group_name"><span class="style_bold">Name: </span>We love to party with Alex and holy crap!</li>
								<li class="related_group_focus"><span class="style_bold">Focus: </span>Art, Match, Scinece, Religion, Computer Science</li>
								<li class="related_group_desc"><span class="style_bold">Description: </span>Help people change the world by adding computer...</li>
							</ul>
					</div>
					
					<div class="related_group_wrapper">
						<span class="group_more_wrapper">
							<span class="related_group_pic">test</span>
							<span class="related_group_more"><a href="#">More Info..</a></span>
						</span>
						
							<ul class="related_group_list">
								<li class="related_group_name"><span class="style_bold">Name: </span>We love to party with Alex and holy crap!</li>
								<li class="related_group_focus"><span class="style_bold">Focus: </span>Art, Match, Scinece, Religion, Computer Science</li>
								<li class="related_group_desc"><span class="style_bold">Description: </span>Help people change the world by adding computer...</li>
							</ul>
					</div>	
				
				</div> <!-- End related_groups -->
				
			</div>	<!-- End search_related_wrapper -->
			
			
		</div>
			
			
			
						<span id="search_group_divider">You are currently in the following Groups:	</span>
			
			<div class="groups_your_in">
			
<!--	This is where the groups starts		-->


<!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group -->

<!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group -->

<!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group -->


				<div class="group_header">Mazarrati Delux</div>

				<div class="group_container">
				
					<div class="group_pic">test</div>
					
						<div class="group_information_left">
							<span class="group_info_title">Group Owner(s):</span>
							<span class="group_attribute">UserName888_284924</span>
							
<!--														<span class="group_border">&nbsp;</span>-->
							
							<span class="group_info_title">Group Credibility:</span>
							<span>10.10</span>
							
<!--														<span class="group_border">&nbsp;</span>-->
							
							<span class="group_info_title">Groups Focus:</span>
								<span class="group_focus">Computer Science</span>
								<span class="group_focus">Computer Law</span>
								<span class="group_focus">Law Major</span>
							
<!--														<span class="group_border">&nbsp;</span>-->
							
							<span class="group_info_title">Group Credibility:</span>
							<span>10.10</span>
							
<!--														<span class="group_border">&nbsp;</span>-->
							
							<span class="group_info_title">Group Prerequisite:</span>
								<span class="group_prereq">Email Address</span>
								<span class="group_prereq">Answer This Question</span>
								<span class="group_prereq">Be Apart of Group A</span>
								

						</div>
					
						<div class="group_information_right">
						
							<span class="group_info_title">Group Description:</span>
							<p>this group is going to do x,y,z and allow for you to be able
							to do whateer you want when you want.  The only people who will be able
							to join this group are people who understand exactly what is going on...<a href="#">click here for more.</a>
							</p>
							
														
							
							<span class="group_info_title">Why Join This Group?</span>
							<p>this group is going to do x,y,z and allow for you to be able
							to do whateer you want when you want.  The only people who will be able
							to join this group are people who understand exactly what is going on...<a href="#">click here for more.</a>
							</p>
							
						</div>
						
						
						<div class="group_options">
						
							<span class="group_info_title">Group Details</span>
							<span class="group_info_title">Leave Group</span>
							<span class="group_info_title">Message Group</span>
							
						</div>
					
				</div>
				
<!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group -->

<!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group -->
				
				
				<div class="group_header">Mazarrati Delux</div>
				
				<div class="group_container">
				
					<div class="group_pic">test</div>
					
						<div class="group_information_left">
							<span class="group_info_title">Group Owner(s):</span>
							<span class="group_attribute">UserName888_284924</span>
							
<!--														<span class="group_border">&nbsp;</span>-->
							
							<span class="group_info_title">Group Credibility:</span>
							<span>10.10</span>
							
<!--														<span class="group_border">&nbsp;</span>-->
							
							<span class="group_info_title">Groups Focus:</span>
								<span class="group_focus">Computer Science</span>
								<span class="group_focus">Computer Law</span>
								<span class="group_focus">Law Major</span>
							
<!--														<span class="group_border">&nbsp;</span>-->
							
							<span class="group_info_title">Group Credibility:</span>
							<span>10.10</span>
							
<!--														<span class="group_border">&nbsp;</span>-->
							
							<span class="group_info_title">Group Prerequisite:</span>
								<span class="group_prereq">Email Address</span>
								<span class="group_prereq">Answer This Question</span>
								<span class="group_prereq">Be Apart of Group A</span>
								

						</div>
					
						<div class="group_information_right">
						
							<span class="group_info_title">Group Description:</span>
							<p>this group is going to do x,y,z and allow for you to be able
							to do whateer you want when you want.  The only people who will be able
							to join this group are people who understand exactly what is going on...<a href="#">click here for more.</a>
							</p>
														
							
							<span class="group_info_title">Why Join This Group?</span>
							<p>this group is going to do x,y,z and allow for you to be able
							to do whateer you want when you want.  The only people who will be able
							to join this group are people who understand exactly what is going on...<a href="#">click here for more.</a>
							</p>
							
						</div>
						
						
						<div class="group_options">
						
							<span class="group_info_title">Group Details</span>
							<span class="group_info_title">Leave Group</span>
							<span class="group_info_title">Message Group</span>
							
						</div>
					
				</div>
						
					
				
				
<!--	This is where the groups end		-->
					
			</div>	
			
			<div class="groups_your_in_right">
			
			<!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group --><!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group --><!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group --><!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group --><!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group --><!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group --><!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group --><!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group -->

				<div class="group_header">Mazarrati Delux</div>
				
				<div class="group_container">
				
					<div class="group_pic">test</div>
					
						<div class="group_information_left">
							<span class="group_info_title">Group Owner(s):</span>
							<span class="group_attribute">UserName888_284924</span>
							
<!--														<span class="group_border">&nbsp;</span>-->
							
							<span class="group_info_title">Group Credibility:</span>
							<span>10.10</span>
							
<!--														<span class="group_border">&nbsp;</span>-->
							
							<span class="group_info_title">Groups Focus:</span>
								<span class="group_focus">Computer Science</span>
								<span class="group_focus">Computer Law</span>
								<span class="group_focus">Law Major</span>
							
<!--														<span class="group_border">&nbsp;</span>-->
							
							<span class="group_info_title">Group Credibility:</span>
							<span>10.10</span>
							
<!--														<span class="group_border">&nbsp;</span>-->
							
							<span class="group_info_title">Group Prerequisite:</span>
								<span class="group_prereq">Email Address</span>
								<span class="group_prereq">Answer This Question</span>
								<span class="group_prereq">Be Apart of Group A</span>
								

						</div>
					
						<div class="group_information_right">
						
							<span class="group_info_title">Group Description:</span>
							<p>this group is going to do x,y,z and allow for you to be able
							to do whateer you want when you want.  The only people who will be able
							to join this group are people who understand exactly what is going on...<a href="#">click here for more.</a>
							</p>
														
							
							<span class="group_info_title">Why Join This Group?</span>
							<p>this group is going to do x,y,z and allow for you to be able
							to do whateer you want when you want.  The only people who will be able
							to join this group are people who understand exactly what is going on...<a href="#">click here for more.</a>
							</p>
							
						</div>
						
						
						<div class="group_options">
						
							<span class="group_info_title">Group Details</span>
							<span class="group_info_title">Leave Group</span>
							<span class="group_info_title">Message Group</span>
							
						</div>
					
				</div>

<!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group --><!-- Folded Group Start -->
<div class="folded_group">
<div class="folded_group_header"><span class="folded_group_title">Westchester Commynity College hoi hfaoi hfaoihf oihfai hfaoa</span></div>
	<div class="folded_group_body">
	
		<div class="folded_group_pic">testing</div>
		
			<div class="folded_group_info">
			
				<ul>
					<li class="folded_group_focus">
					<span class="style_bold">Focus: </span>
					Computer Science, Art Therapy, Something Else, Excellent, Something Insane
					</li>
					
					<li class="folded_group_cred">
					<span class="style_bold">Credibility: </span>
					10.4
					</li>
					
					<li class="folded_group_why">
					<span class="style_bold">Owner: </span>
					Username_848928
					</li>
				
				</ul>
			
			</div>
		
	</div><!-- End folded group body -->
	
</div> <!-- End folded group -->
			
			</div>

		
		</div>
	
	</div>
	
</div>

	<?php include(FOOTER);?>

</body>
</html>