<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Chatapist Search</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<!-- <link href="main.css" rel="stylesheet" type="text/css" media="screen" /> -->
<style type="text/css" media="all">@import "views/style_sheets/main.css";</style>
</head>

<body>

<div id="top">This is the top</div>

<div id="container">

	<div id="top_logo"><img src="images/chatapist-big.gif" alt="logo" /></div>
	
	<div id="info">
	
		<ul id="info_list">
		
			<li id="welcome">Welcome Taso</li>
			<li id="number">There are currently 400 active users</li>
			<li id="post">Post your discussion here</li>
			<li id="setup"><a href="#">Setup your account now</a></li>
		
		</ul>
	
	</div>
	
	<div id="forms">
	
		<form action="_self" method="post" >
		
			<fieldset>
			
				<ul id="top_form">
					<li> <label for="title">Title:</label> <input type="text" id="title"></input> </li>
					<li> <label for="catagory">Category:</label> <select id="catagory"><option></option></select> </li>
				</ul>
				
				<ul id="bottom_form">
					<li id="q"><label for="question">Question:</label> <textarea rows="2" cols="15" id="question"></textarea></li>
					<li id="sub"><label for="sub-catagory">Sub-Category:</label><select id="sub-catagory"><option></option></select></li>
				</ul>
				
				<span><input type="submit" id="submit_button" value="Post!"></input></span>
			
			</fieldset>
		
		</form>
	
	</div>
		
	<div id="links">
	
		<ul>
		
			<li id="this1"><a href="##">Home</a></li>
			<li id="this2"><a href="###">Profile</a></li>
			<li id="this3"><a href="#####">Relevancy Settings</a></li>
			<li id="this4"><a href="######">Something</a></li>
			<li id="this5"><a href="#######">Great</a></li>
				<li id="this6"><a href="########">Home</a></li>
			<li id="this24"><a href="#########">Profile</a></li>
	
		
		</ul>
		
	
	</div>
	
	
	<div id="footer">

<?php include(FOOTER);?>
	
	</div>
	
</div>

</body>
</html>