<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Chatapist - Profile</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css" media="all">@import "views/style_sheets/home.css";</style>
</head>

<body>

<div id="container">
	
	<?php include(HEADER);?>
		
	<?php include(LEFT);?>
	
	<div id="profile">
	
		<div id="profile_header">Profile</div>
	
		<div id="picture">Testing</div>
		
		<div id="basic_info">
		
			<h4>&nbsp;Account Info.</h4>
			
			<ul>
				<li>Username:</li>
				<li>Rank:</li>
				<li>Friends: (Network Avg. Rank: )</li>
				<li>Postings:</li>
				<li>Lines Chatted:</li>
			</ul>
			
			<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You</h4>
			
			<ul>
				<li>Name:</li>
				<li>Age:</li>
				<li>Location:</li>
				<li>Zip:</li>
				<li>Education:</li>
				<li>Occupation:</li>
				<li>Languages:</li>
				<li></li>
			</ul>
			
		</div>
		
		<div id="specific_ranking">
		
			<h4>Rankings</h4>
		
			<ul>
				<li>Social Studies - 1 - [Total: 6]</li>
				<li>English - 2 - [Total: 9]</li>
				<li>Computer Science - 4 - [Total: 8]</li>
				<li>Postings - 2- [Total: 8]</li>
				<li>Customer Support - 10 - [Total: 3]</li>
			</ul>
			
		</div>
		
		<div id="personal">
		
		<h4>Personal</h4>
		
			<ul>
				<li>Interests:</li>
				<li>Favriot Foods:</li>
				<li>Places you've travels:</li>
				<li>Your reason for being on chatapist:</li>
				<li>Your weakest subjects:</li>
				<li>Your strongest subjects:</li>
				<li>What you love:</li>
			</ul>
			
		</div>
		
	<div id="border"></div>
		
	<div id="groups">
		
		<h4>Channels</h4>
		
		<h5>Channels You're Invovled With:</h5>
		
			<ul>
				<li>Westchester Community College (188 People)</li>
				<li>Johns Pizza Shop (12 People)</li>
				<li>Argentina (4 People)</li>
				<li>United States ( >Argentina )</li>
			</ul>
	
	</div>
	
</div>

	<?php include(FOOTER);?>

</body>
</html>