<?php print_r($errors)?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Chatapist - Profile</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css" media="all">@import "views/style_sheets/home.css";</style>
</head>

<body>

<div id="container">
	
	<?php include(HEADER);?>
		
	<?php include(LEFT);?>
	
	<div id="rel">
	
		<div id="rel_header">Relevancy Settings</div>
	
			<div id="rel_intro">
		
			<p>
			Welcome to your relevancy settings.  Relevancy settings are the heart and core of chatapist and allow you to 
			receive posts/questions that you may know or be interested in.  Create and add multiple relevancy settings
			that reflect your knowledge, interests, and expertise.  
			</p>
		
		</div>
		
		<div id="rel_go_away"><a href="#">Click to not display this message.</a></div>
		
	
	<div id="rel_left">
	
	<h4>Configure and Add a Relevancy Setting:</h4>
	
	<form action="_self" method="post">	
	
	<fieldset>

		<ul>
			<li> <label for="name">Name:</label><input  type="text" class="textbox"  id="name" value="Give me pizza postings!"></input></li>
			<li> <label for="keywords">Keywords:</label><input  type="text" class="textbox" id="keywords" value="(i.e. Pizza,Sauce,Cook)"></input></li>
			<li> <label for="category">Category:</label><select id="category"><option></option></select></li>
			<li> <label for="language">Language:</label> <select id="language"><option></option></select></li>
			<li> <label for="country">Country:</label> <select id="country"><option></option></select></li>
			<li> <label for="state">State:</label> <select id="State"><option></option></select></li>
			<li> <label for="zipcode">Zipcode:</label><input type="text" class="textbox" id="zipcode" value="(i.e. 10522)"></input></li>
			<li> <label for="group">Group:</label> <select id="group"><option title="All">All</option></select></li>
		</ul>
		
		<span id="rel_button"><a href="####" ><button type="submit">Add Setting</button></a></span>
	
	</fieldset>
		
		</form>
	
	</div>
	
	<div id="rel_area">
	
   		<h4 id="rel_example">Examples:</h4>
		<span class="example">
			Catagory: <span class="style_bold">Food/Cooking</span> in state <span class="style_bold">NY</span> in zipcode <span class="style_bold">10522</span> in language <span class="style_bold">English</span> Keywords: <span class="style_bold">Maple, Syrup, Pancakes, mmm</span>
			<span class="delete_rel"><a href="#">Delete</a></span>
		</span>
		
		<span class="example">
			<span class="style_bold">All Catagories</span> in zipcode <span class="style_bold">10522</span> Keywords: <span class="style_bold">Skateboarding</span>
			<span class="delete_rel"><a href="#">Delete</a></span>
		</span>
		
		<span class="example">
			<span class="style_bold">All Catagories</span> in zipcode <span class="style_bold">10522</span>
			<span class="delete_rel"><a href="#">Delete</a></span>
		</span>
		
		<span class="example">
			<span class="style_bold">All Catagories</span> in language <span class="style_bold">Italian </span>Keywords: <span class="style_bold">Pasta, Mario, Luigi, Supa Dupa Ferrari</span>
			<span class="delete_rel"><a href="#">Delete</a></span>
		</span>
		
	</div>
	
	
	<div id="border"></div>
	<div id="rel_area_used">
	
	<span class="rel_name_number">1. Crazy Jakes</span>
	<span id="active_rel">
			Catagory: <span class="style_bold">Food/Cooiahfoiafjoaifja oijfa oij oifa jaoi afoifa oioking</span> in state <span class="style_bold">NY</span> in zipcode <span class="style_bold">10522</span> in language <span class="style_bold">English</span> Keywords: <span class="style_bold">Maple, Syrup, Pancakes, mmm</span>
			<span class="delete_rel"><a href="#">Delete</a></span>
	</span>
	
	<span class="rel_name_number">2. Pancake Mixing Helper</span>
	<span id="active_rel">
			Catagory: <span class="style_bold">Food/Cooking</span> in state <span class="style_bold">NY</span> in zipcode <span class="style_bold">10522</span> in language <span class="style_bold">English</span> Keywords: <span class="style_bold">Maple, Syrup, Pancakes, mmm</span>
			<span class="delete_rel"><a href="#">Delete</a></span>
	</span>
	
	</div>
	
	</div>
	
</div>

	<?php include(FOOTER);?>

</body>
</html>