							<option value="NO">Chose a Category</option>
								<optgroup label="+School/Academic Help">
									<option value="Middle School">Middle School</option>
									<option value="High School">High School</option>
									<option value="College(BA/BS)">College(BA/BS)</option>
									<option value="College(MS/PhD)">College(MS/PhD)</option>
									<option value="Law School">Law School</option>
									<option value="Medical School">Medical School</option>
									<option value="Other">Other</option>
								
								<optgroup label="+Computer Help">
									<option value="Programming">Programming</option>
									<option value="Networking">Networking</option>
									<option value="Systems">Systems</option>
									<option value="Hardware">Hardware</option>
									<option value="Desktop/OS">Desktop/OS</option>
									<option value="Internet/Site Specific">Internet/Site Specific</option>
									<option value="Application Specific">Application Specific</option>
									
								<optgroup label="+More Help">
									<option value="Business Help/Advice">Business Help/Advice</option>
									<option value="Legal Help/Advice">Legal Help/Advice</option>
									<option value="Financial Help">Financial Help</option>
									<option value="Mechanical/Car/Vehicles">Mechanical/Car/Vehicles</option>
									<option value="Electronics/Devices">Financial Help</option>
									<option value="Food/Cooking">Food/Cooking</option>
									<option value="Other">Other</option>
								
								<optgroup label="Jobs/Chat Interviews">
									<option value="IT Jobs">IT Jobs</option>
									<option value="Marketing Jobs">Marketing Jobs</option>
									<option value="Sales Jobs">Sales Jobs</option>
									<option value="Graphic Design Jobs">Graphic Design Jobs</option>
									<option value="Physical Labor Jobs">Physical Labor Jobs</option>
									<option value="Business Jobs">Business Jobs</option>
									<option value="Need an Extra Hand">Need an Extra Hand</option>
								
								<optgroup label="+Meeting People">
									<option value="Just moved to the area">Just moved to the area</option>
									<option value="Theres a party at!...">Theres a party at!...</option>
									<option value="Bar/Club Events">Bar/Club Events</option>
									<option value="Random Meeting">Random Meeting</option>
									<option value="Flirting/Dating">Flirting/Dating</option>
									<option value="Just moved to area">Just moved to area</option>
									<option value="Event Organizing">Event Organizing</option>
								
								<optgroup label="+Chatapist">
									<option value="Deppression">Deppression</option>
									<option value="Need to talk">Need to talk</option>
									<option value="Addiction Help Chat">Addiction Help Chat</option>
									<option value="We broke up">We broke up</option>
									<option value="Im drunk, need a driver">Im drunk, need a driver</option>
									<option value="Looking to travel w/ someone">Looking to travel w/ someone</option>
								</optgroup>