<?php print_r($errors)?>
<html>
<head><style type="text/css" media="all">@import "<?=$view_data['stylesheet'];?>";</style></head>
<body>
<div id="body">
1234
<br/>This is a template of something: anything that you put in the 'home' part of the homepage you'll be good to go.<br/>
<b><?=$view_data['home'];?></b>
<br/>This is the end of the template.

<br/>
<br/>

<form method="POST" target="_self">
<label>User Name:</label><br/><input type="text" id="uname" name="uname"></input><br/>
<label>Password:</label><br/><input type="password" id="pass" name="pass"></input><br/>
<input type="submit" value="Submit" id="Submit_Home">
</form>

<?php //while($row = $view_data['users']->fetch_assoc()){ echo $row['uid'].'<br/>'; }?>
</div>
</body>
</html>