<div id="sign_up">
<span class="signup_error_count" id="uname_error_count">1</span>
<span class="signup_error_count" id="email_error_count">1</span>
<span class="signup_error_count" id="pass_error_count">1</span>

	<div id="step_1">
	<span class="sign_up_top_buttons"> &nbsp; <a href="#" onclick="close_sign_up(); return false;">close</a></span>
		<form id="sign_up_form">
			<fieldset >
			<legend>-Sign Up-</legend>
			
				<ul>
					<li><label>Username</label><input type="text" onblur="check_uname(this);" id="uname_signup"></input><span class="guide" id="uname_insert">No spaces</span></li>
					<li><label>Full Name</label><input type="text" id="fname_signup"></input></li>
					<li><label>E-mail</label><input type="text" onblur="check_email(this);" id="email_signup"></input><span class="guide" id="email_insert">Must be valid</span></li>
					<li><label>Password</label><input type="password" id="pass_signup"></input><span class="guide" id="repass_insert">6 characters or more</span></li>
					<li><label>Retype Password</label><input type="password" onblur="check_repass(this);" id="repass_pass"></input></li>
					<li><span id="signup_errors"></span></li>
				</ul>
				
				<button class="sign_up_button" id="next_1" onclick="check_all(this,1); return false;">&nbsp; Sign Up! &nbsp;</button>
				
			</fieldset>
		</form>
	</div>

	
	<div id="step_2">
	<span class="sign_up_top_buttons"><a href="#" id="back_2" onclick="show_last_step(this); return false;">back</a> &nbsp; <a href="#" onclick="close_sign_up(); return false;">close</a></span>

                <div id="people_search_results">
                        <span id="connected_group_descr">Welcome to tap. Enjoy!</span>

                </div>

	
		<button class="sign_up_button" id="next_2" onclick="show_next_step(this); return false;">&nbsp; Next &gt&gt &nbsp;<span id="elips"></span></button>

	</div>
	
	<div id="step_3">
	<span class="sign_up_top_buttons"><a href="#" id="back_3" onclick="show_last_step(this); return false;">back</a> &nbsp; <a href="#" onclick="close_sign_up(); return false;">close</a></span>
	
	<h4><span class="step_3_space">Import and invite your contacts...</span></h4>



		<?
		include('views/parts/lists/invite_list.html');
		?>
		<div id="contact_list">
		<form id="openinviter">
		</form>
		<span id="info_disclaimer">We do not store usernames/passwords</span>
		</div>



<!--
	<form id="invite_form">
	<fieldset>

		<ul id="invite_list">
			<li><input type="text" id="invite_uname"></input></li>
			<li><input type="text" id="invite_pass"></input></li>
			<li><input type="text" id="invite_"></input></li>
			<li><input type="text" id="invite_"></input></li>
		</ul>
	
	</fieldset>
	</form>
-->	
				<a href="#" onclick="window.location = '<?=ROOT?>'; return false; "><button class="sign_up_button">&nbsp;Finish&nbsp;</button></a>
			</fieldset>
			</form>
		
	</div>
	<?=$view_data['second_step'];?>
</div>

