keyspaces:
    - name: circlefy
      replica_placement_strategy: org.apache.cassandra.locator.SimpleStrategy
      replication_factor: 1
      column_families:
        - name: group_members 
          compare_with: LongType
          default_validation_class: LongType
          comment: 'gid = {uid: uid}'

        - name: convo_followers 
          compare_with: LongType
          default_validation_class: LongType
          comment: 'mid = {uid: uid}'        
