<?php
    foreach ($_cl['list'] as $c):
?>
<a href="/circle/<?=$c['symbol']?>" class="circle-thumb" class="circle-thumb" data-tipid="circle-<?=$c['id']?>" data-tiptitle="<img src='/static/images/type_<?=$c['type']?>.png' width='16' height='16' /> <?=$c['name']?>" data-tipcontent="<?=((!empty($c['descr']))?$c['descr']:'&nbsp;')?>">
    <span class="circle"></span>
    <img src="<?=GROUP_PIC_REL . 'medium_' . $c['id'] . '.jpg'?>" />
	<span style="text-align:center;position:absolute;color:black;font-weight:bold;top:26px;vertical-align:middle;width:48px;font-size:11px;left:1px;background:#A1E2F4;">


	<?php
	$str = substr($c['name'],0,6);
	$count =strlen($c['name']);
	echo $str;
	if($count > 7)
		echo '..';
	?>

	</span>

</a>
<?php
    endforeach;
?>
