      <div id="curtain"></div>
                        <div id="connect-signup">
                                <h2>Just one more thing before we log you in..</h2>
                                <p>We're almost there <strong><span id="connect-signup-name"></span></strong>, but first we'll need you to add a few more details to personalize your Tap experience.</p>
                                <input type="text" name="name" style="display:none" />
                                <p class="forms" style="margin-top:30px"><label>Username</label> <input type="text" name="uname" /></p>
                                <p class="guide">This username is already taken.</p>
                                <p class="forms"><label>Email</label> <input type="text" name="email" /></p>
                                <p class="guide">Enter a valid email address.</p>
                                <p class="forms"><label>Password</label> <input type="password" name="pass" /></p>
                                <p class="guide">Passwords must be at least 4 characters.</p>
                                <p style="margin-top: 50px; text-align: right; font-size: 14px; margin-right: 20px">
                                        <span class="indicator">
                                                <img src="/images/spinner.gif" />
                                                <span class="indic-msg">Signing you up...</span>
                                        </span>
                                        <span id="connect-signup-actions">
                                                <button>Start Tapping!</button> or <a id="connect-cancel" href="#">close</a>
                                        </span>
                                </p>
                        </div>

