<h1 class="title feed">
    <span><?=$_f['name']?></span>
    <a href="#" id="pause">Pause Stream</a>
</h1>

<div id="controls" <?=($_f['show_inside'] ? '' : 'class="hidden"')?>>
    <a href="#" data-inside="1" class="tab active">Inside the Circle</a>
    <a href="#" data-inside="2" class="tab">Outside the Circle</a>
    <div class="clear"></div>
</div><!--controls-->
            
<div class="warning hidden">
    <a href="#" class="close">X</a>
    <span></span>
</div><!--warning-->


<? if ($_f['show_reply']): ?>
<form id="reply">
	<a class="anonym" href="#"><img src="/static/images/user.gif" alt="guy" /></a>
    <img src="<?=USER_PIC_REL.'medium_'.$me['id'].'.jpg'?>" alt="It's you" class="avatar" />
    <textarea title="Post a message to this circle"></textarea>
    <input type="submit" value=" " />
    <div class="clear"></div>
</form><!--reply-->
<? endif; ?>


<div id="feed">

    <? if (!empty($_f['feed'])):
            $count = count($_f['feed']);
            $id = 0; //array key doesn't represent real id
            foreach($_f['feed'] as $f):
                $id++;
                $last = $count == $id;
    ?>
    <div class="feed-item<?=($last ? ' last' : '')?><?=(empty($f['responses']) ? ' empty' : '')?>"
         id="global-<?=$f['id']?>"
         data-id="<?=$f['id']?>"
         data-gid="<?=$f['group_id']?>">
    
        <img src="<?=USER_PIC_REL.'medium_'.$f['sender']['id'].'.jpg'?>" alt="<?=$f['sender']['fname']?> <?=$f['sender']['lname']?>" class="avatar-author" />
        <div class="text">
            <h3 class="author"><a href="/user/<?=$f['sender']['uname']?>"><?=$f['sender']['uname']?></a> <small>, <?=$f['sender']['fname']?> <?=$f['sender']['lname']?></small></h3>
            <cite><a href="/convo/<?=$f['id']?>"><?=$f['text']?></a></cite>
            <div class="clear"></div>

            <? if (!empty($f['responses'])): ?>
                <div class="latest-reply">
                    <img src="<?=USER_PIC_REL.'small_'.$f['responses']['user']['id'].'.jpg'?>"
                         alt="<?=$f['responses']['user']['fname']?> <?=$f['responses']['user']['lname']?>" class="avatar-reply" />
                    <a href="/user/<?=$f['responses']['user']['uname']?>" class="reply-author"><?=$f['responses']['user']['uname']?>:</a>
                    <span><?=$f['responses']['text']?></span>
                </div><!--latest-->
            <? else: ?>
                <div class="latest-reply">
                    <img src="" alt="" class="avatar-reply" />
                    <a href="" class="reply-author"></a>
                    <span></span>
                </div><!--latest-->
            <? endif; ?>
           
            <a href="#" alt="Close" def="Reply" class="reply"></a>
            <? if (!empty($f['responses']) && $f['responses']['count'] > 0): ?>
                <a href="#" class="comments"><?=$f['responses']['count']?></a>
            <? else:?>
                <a href="#" class="comments"></a>
            <? endif; ?>

            <div class="replies">
            	<div class="arrow"></div>
                <div class="list">
                    <?php
                        $_r['replies'] = $f['replies'];
                        include(REPLIES);
                    ?>
                </div><!--list-->

                <? if (!$guest): ?>
                <div class="field">
                    <div class="thumb"><img src="<?=USER_PIC_REL.'medium_'.$me['id'].'.jpg'?>" alt="It's you" /></div>
                    <div class="editor">
                        <form>
                            <textarea></textarea>
                            <input type="submit" value=" ">
                        </form>
                        <div class="clear"></div>
                    </div><!--editor-->
                    <div class="clear"></div>
                </div><!--field-->
                <? endif; ?>
            </div><!--replies-->
            <div class="resizer"></div>

            <div class="clear"></div>
                <? if (!$_f['hide_group_icon']): ?>
                <div class="circle">
                    <a href="/circle/<?=$f['group']['symbol']?>">
                        <span></span>
                        <img src="<?=GROUP_PIC_REL.'small_'.$f['group']['id'].'.jpg'?>" alt="<?=$f['group']['name']?>" />
                    </a>
                </div><!--circle-->
                <? endif; ?>
             <div class="icons">
               <!-- there would be icon, selected depending on what type of content message have -->
                <!--<a href="#"><img src="/static/images/feed_type_photo.jpg" alt="tap type" /></a>-->
                <span class="timestamp" data-timestamp="<?=$f['timestamp']?>"><?=$f['time']?></span>
            </div>
            <div class="clear"></div>
        </div><!--text-->
    
    </div><!--feed-item-->
    <?    endforeach;
       endif; 
    ?>
   
    <? if (count($_f['feed']) >= 10): ?>
    <a id="loadmore" class="load" href="#">Older Taps</a>
    <? endif; ?>
    
</div><!--feed-->
