 <div id="header" class="container">
                        <div id="nav">
                                <a href="/">home</a>
                                <a href="/what">what's tap?</a>
                                <a href="/about" class="current">about us</a>
                                <a href="/devs">developers</a>
                                <a href="/contact">contact</a>
                        </div>

                        <div id="logo">
                                <a href="/"></a>
                        </div>

                        <div id="searchbar">
                                <div id="searchover">what are you looking for?</div>
                                <input id="search" type="text" class="basic" autocomplete="off">
                                <div id="searchsuggest">
                                        <ul>
                                        </ul>
                                </div>
                        </div>

                </div>

