  <div id="header" class="container">
                        <div id="nav">
                                <a href="/" class="current">home</a>
                                <a href="/groups">groups</a>
                                <a href="/people">people</a>
                                <a href="/settings">settings</a>
                                <a href="/?logout=true">logout</a>
                        </div>

                        <div id="logo">
                                <a href="/"></a>
                        </div>

                        <div id="searchbar">
                                <div id="searchover">what are you looking for?</div>
                                <input id="search" type="text" class="basic" autocomplete="off">
                                <div id="searchsuggest">
                                        <ul>
                                        </ul>
                                </div>
                        </div>
                </div>

