<?php
// This header will be shown to the GUEST USERS.
$r = $_SERVER['REQUEST_URI'];
$c = 'class="current"';

switch($r){
	case '/':       $home =  $c;break;
	case '/what':   $what =  $c;break;
	case '/about':  $about=  $c;break;
	case '/devs':  $devs =  $c;break;
	case '/contact':$contact=$c;break;
}
		

?>
<div id="header" class="container">
                        <div id="nav">
                                <a href="/" 	   <?=$home?>   >home</a>
                                <a href="/login"       <?=$login?>   >login</a>
                                <a href="/what"	   <?=$what?>   >what's tap?</a>
                                <a href="/about"   <?=$about?>  >about us</a>
								<? /* <a href="/devs"    <?=$devs?>   >developers</a> */ ?>
                                <a href="/contact" <?=$contact?>>contact</a>
                        </div>

                        <div id="logo">
                                <a href="/"></a>
                        </div>

                        <div id="searchbar">
                                <div id="searchover">Start or Join a conversation</div>
                                <input id="search" type="text" class="basic" autocomplete="off">
                                <div id="searchsuggest">
                                        <ul>
                                        </ul>
                                </div>
                        </div>

                </div>

