<?php
	$r = $_SERVER['REQUEST_URI'];
	$c = 'class="current"';

	switch($r){
		        case '/':       $home =  $c;break;
				        case '/groups':   $groups =  $c;break;
						        case '/people':  $people=  $c;break;
								        case '/settings':   $settings =  $c;break;
	}
?>


  <div id="header" class="container">
                        <div id="nav">
                                <a href="/"  	    <?=$home?>    >home</a>
                                <a href="/groups"   <?=$groups?>  >groups</a>
                                <a href="/people"   <?=$people?>  >people</a>
                                <a href="/settings" <?=$settings?>>settings</a>
                                <?php if ($logged): ?>
								<a href="/?logout=true">logout</a> <? echo $_t['ok_user']; ?>
                                <?php else: ?>
                                <a href="/signup">create account</a>
                                <?php endif; ?>
                        </div>

                        <div id="logo">
                                <a href="/"></a>
                        </div>

                        <div id="searchbar">
                                <div id="searchover">Start or Join a conversation</div>
                                <input id="search" type="text" class="basic" autocomplete="off">
                                <div id="searchsuggest">
                                        <ul>
                                        </ul>
                                </div>
                        </div>
                </div>
