<?
$id = 0;
$limit = isset($_f['limit']) ? $_f['limit'] : null;
foreach($_f['members'] as $m):
    $id++;
?>
<a href="/user/<?=$m['uname']?>" class="follower-thumb<?=($id >= $limit && isset($limit) ? ' hidden' : '')?>" data-tiptitle="<?=$m['fname']?> <?=$m['lname']?>" data-tipcontent="&nbsp;" data-tipid="<?=$fk?>-<?=$m['id']?>">
    <img src="<?=USER_PIC_REL.'small_'.$m['id'].'.jpg'?>" />
</a>
<? endforeach;?>
