<? if (!$_f['hide']): ?>
    <div id="footer">
    
    	<div class="copyright">circlefy &copy; 2010</div>
        
        <ul id="footer-navigation">
        	<li><a href="/">home</a></li>
            <? if ($guest): ?>
                <li><a href="#" class="login-signup">login or signup</a></li>
            <? endif; ?>
            <li><a href="/what">what's circlefy?</a></li>
            <li><a href="/about">about us</a></li>
            <li><a href="/devs">developers</a></li>
            <li><a href="/contact">contact</a></li>
        </ul>
        
        <div class="clear"></div>
    
    </div><!--footer-->
<? endif; ?>

<?php
    include(NOTIFICATION_TAB);
    include(JS_TEMPLATES);
    include(TOOLTIP_TEMPLATES);
    include(MODAL_WINDOWS);
    include(FBCONNECT);
?>

</body>
</html>
