    <div id="footer">
    
    	<div class="copyright">circlefy &copy; 2010</div>
        
        <ul id="footer-navigation">
        	<li><a href="#">home</a></li>
            <li><a href="#">login</a></li>
            <li><a href="#">what's circlefy?</a></li>
            <li><a href="#">about us</a></li>
            <li><a href="#">developers</a></li>
            <li><a href="#">contact</a></li>
        </ul>
        
        <div class="clear"></div>
    
    </div><!--footer-->

<?php
    include(JS_TEMPLATES);
    include(MODAL_WINDOWS);
    include(FBCONNECT);
?>

</body>
</html>
