<div id="header">
	<span id="logo">
		<a href="/">TAP</a>
	</span>
	<span id="main-menu">
		<a href="/"><strong>Interface</strong></a> 
		<a href="/profile">Profile</a> 
		<a href="/people">People</a> 
		<a href="/groups">Groups</a> 
		<a href="/settings">Settings</a> 
		<a href="/help">Help</a>
	</span>
	<span id="login-info">
		Logged in as: <strong><?= $_SESSION['uname'] ?></strong><br />
		<a href="/?logout=true">Logout</a>
	</span>
	<div class="clarity"></div>
</div>
