<?php
    extract($_h, EXTR_OVERWRITE | EXTR_REFS);
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="stylesheet" type="text/css" href="/static/css/main.css" />
<?php
    if (isset($styles))
        foreach ($styles as $s)
            echo "<link rel='stylesheet' type='text/css' href='/static/css/$s' />\n";
?>
<script type="text/javascript" src="/static/js/mootools-core.js"></script>
<script type="text/javascript" src="/static/js/mootools-more.js"></script>
<script type="text/javascript" src="http://<?=DOMAIN?>:8000/static/Orbited.js"></script> 
<?php
    if(isset($vars))
        echo "<script type='text/javascript'>\n_vars = ".json_encode($vars)."\n</script>\n";

    if (isset($scripts))
        foreach ($scripts as $s)
            echo "<script type='text/javascript' src='/static/js/$s'></script>\n"; ?>
<title>circlefy - <?=$title?></title>
</head>

<body>

    <div id="header">
    	<div class="wrap">
        	
            <div class="left">
            <a href="#" id="logo">circlefy</a>
            <form>
            	<input type="text" value="Start or join a conversation" />
            </form>
            </div><!--left-->
            
            <a href="#" id="access">create account or login</a>
            
            <div class="clear"></div>
            
        </div><!--wrap-->
    </div><!--header-->
