<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="stylesheet" type="text/css" href="/static/css/main.css" />
<?php
    if (isset($_h['styles']))
        foreach ($_h['styles'] as $s)
            echo "<link rel='stylesheet' type='text/css' href='/static/css/$s' />\n";
?>
<script type="text/javascript" src="/static/js/mootools-core.js"></script>
<script type="text/javascript" src="/static/js/mootools-more.js"></script>
<script type="text/javascript" src="/static/js/libs.js"></script>
<script type="text/javascript" src="/static/js/validators.js"></script>
<script type="text/javascript" src="http://<?=DOMAIN?>:8000/static/Orbited.js"></script> 
<?php
    if(isset($_h['vars']))
        echo "<script type='text/javascript'>\n_vars = ".json_encode($_h['vars'])."\n</script>\n";

    if (isset($_h['scripts']))
        foreach ($_h['scripts'] as $s)
            echo "<script type='text/javascript' src='/static/js/$s'></script>\n";
?>
<? if ($guest):?>
<script type='text/javascript'>
_tap.register({
    init: function() {
        this.publish('modal.show.sign-login', []);
    }
});
</script>
<? endif; ?>
<!-- START GLOBAL JS SCRIPTS -->
<script type="text/javascript" src="/static/js/follow.js"></script>
<!-- END GLOBAL JS SCRIPTS -->

<title>circlefy - <?=$_h['title']?></title>
</head>

<body>

    <div id="header" <?=($_h['fixed'] ? 'style="position: fixed"' : '')?>>
    	<div class="wrap">
        	
            <div class="left">
            <a href="/" id="logo">circlefy</a>
            <form>
            	<input id="group-search" type="text" autocomplete="off" value="" title="Start or join a conversation" />
                <div id="search-results" class="hidden">
                  <ul></ul>
                </div><!--searchresults-->
            </form>
            </div><!--left-->

	    <div class="main-post-button">
		Post
	    </div>

            <? if ($_h['guest']): ?>
            <a href="#" id="access">create account or login</a>
            <? else: ?>
            <div class="right">
            	
                <div class="user">
                	<img src="<?=USER_PIC_REL.'small_'.$me['id'].'.jpg'?>" alt="It's you">
                    <a href="/user/<?=$me['uname']?>" class="name" title="It's you"><?=$me['fname']?></a>
                    <ul class="dropdown">
                    	<li class=""><a href="/?killyourself">Suicide button</a></li>
                    	<li class="settings"><a href="#">Settings</a></li>
                    	<li class="suggestions"><a href="#">Suggestions</a></li>
                        <li class="logout"><a href="/?logout">Log Out</a></li>
                    </ul>
                </div><!--user-->
                
            </div><!--right-->
            <? endif; ?>
            
            <div class="clear"></div>
            
        </div><!--wrap-->
    </div><!--header-->
