<div id="templates">

    <? /*** Search suggestions template ***/ ?>
    <ul id="template-search">
        <# if (this.length > 0): #>
        <# for (var sugg from this): #>
        <li>
           <div class="thumb"><span></span><img src="<?=GROUP_PIC_REL?>small_<#: sugg.id #>.jpg" alt="search" /></div>
           <h3 class="title"><a href="/circle/<#: sugg.symbol #>"><#: sugg.name #></a></h3>
           <small><span><#: sugg.messages_count #> messages received</span><strong><#: sugg.online_count #><em>/<#: sugg.members_count #></em></strong></small>
           <div class="clear"></div>
        </li>
        <# endfor; #>
        <# else: #>
        <li>
            <h3>Nothing found. Create your own circle:</h3>
        </li>
        <# endif; #>

        <li class="create">
            <div class="thumb"><span></span><img src="/static/images/search_create.gif" alt="search" /></div>
            <h3 class="title"><a href="#">Create new conversation circle</a></h3>
            <small>Click here to create a circle on the fly!</small>
            <div class="clear"></div>
        </li>
    </ul>

    <? /*** Placeholder for 'searching' state of group suggestions ***/ ?>
    <ul id="template-search-placeholder">
        <li>
            <h3>Searching...</h3>
        </li>
    </ul>

    <? /*** Replies to tap ***/ ?>
    <ul id="template-replies">
        <# for (var repl from this): #>
        <div class="reply-item">
            <div class="thumb"><img src="<?=USER_PIC_REL?>small_<#: repl.user.id #>.jpg" alt="<#: repl.user.fname #> <#: repl.user.lname #>" /></div>
            <span class="text">
                <h3 class="username">
                    <a href="/user/<#: repl.user.uname #>"><#: repl.user.uname ></a>:
                </h3>
                <#: repl.text #>
                <span class="timestamp"><#: repl.time #></span>
            </span>
            <div class="clear"></div>
        </div><!--item-->
        <# end; #>
    </ul>

</div>
