<div id="left">

		<div id="left_nav">
		
			<ul>
				<li><img src="images/icons/vcard_edit.png" /><a href="<?=ROOT?>profile">Profile</a></li>
				<li><img src="images/icons/connect.png" /><a href="<?=ROOT?>network">Network</a></li>
				<li><img src="images/icons/group.png" /><a href="<?=ROOT?>groups">Groups</a></li>
				<li><img src="images/icons/transmit_go.png" /><a href="<?=ROOT?>relevancy_settings">Relevancy Settings</a></li>
				<li><img src="images/icons/magnifier.png" /><a href="<?=ROOT?>people_search">Search People</a></li>
			</ul>
		
		</div>
		
		
		<div id="alert_nav">
		
		<h4>Alerts:</h4>
		
			<p>
			Hello and welcome to chatapist, every time you login and while you're on the system chatapist checks for alerts
			and makes sure that there are matches to what you know about.  Alerts will show up here if something you know about
			is posted!  Keep an eye out, enjoy!
			</p>
			
		</div>

	
	</div>
	
