<div id="header">
	<div class="holder">
		<span id="logo"><a href="">TAP</a></span>
		<span id="main-menu" style="font-size: 13px; font-weight: normal">
			<a href="/" style="margin-right: 15px"><strong>Home</strong></a> 
			<a href="/what" style="margin-right: 15px">What's Tap?</a> 
			<a href="/about" style="margin-right: 15px">About Us</a> 
			<a href="/contact" style="margin-right: 15px">Contact</a>
			<a href="/devs" style="margin-right: 15px">Developers</a>
			<a href="/help" style="margin-right: 15px">Help</a>
		</span>
	</div>
	<div style="clear:both"></div>
</div>