<div id="header">
	<div class="holder">
		<span id="logo"><a href="">TAP</a></span>
		<span id="main-menu" style="font-size: 13px; font-weight: normal">
			<a href="/" style="margin-right: 15px"><strong>Home</strong></a> 
			<a href="/what" style="margin-right: 15px">What's Tap?</a> 
			<a href="/about" style="margin-right: 15px">About Us</a> 
			<a href="/devs" style="margin-right: 15px">Developers</a>
			<a href="/contact" style="margin-right: 15px">Contact</a>
		</span>
	</div>
	<ul id="right_ul">
		<li><span id="the_only" style="font-size:11px;font-family:;">The only communication engine made with <span id="heart" style="color:red"><3</span></span></li>
	</ul>
	<div style="clear:both"></div>
</div>
