<div id="header">
<script type="text/javascript" charset="utf-8">
  var is_ssl = ("https:" == document.location.protocol);
  var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
  document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript" charset="utf-8">
  var feedback_widget_options = {};

  feedback_widget_options.display = "overlay";
  feedback_widget_options.company = "tap";
  feedback_widget_options.placement = "left";
  feedback_widget_options.color = "#222";
  feedback_widget_options.style = "idea";







  var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
</script>
	<div class="holder">
		<span id="logo"><a href="">TAP</a></span>
		<span id="main-menu" style="font-size: 13px; font-weight: normal">
			<a href="/" style="margin-right: 15px"><strong>Home</strong></a> 
			<a href="/what" style="margin-right: 15px">What's Tap?</a> 
			<a href="/about" style="margin-right: 15px">About Us</a> 
			<a href="/devs" style="margin-right: 15px">Developers</a>
			<a href="/contact" style="margin-right: 15px">Contact</a>
		</span>
	</div>
	<ul id="right_ul">
		<li><span id="the_only" style="font-size:11px;font-family:;">The only communication engine made with <span id="heart" style="color:red"><3</span></span></li>
	</ul>
	<div style="clear:both"></div>
</div>
