<div id="curtain" class="curtain"></div>

<div id="modal-container">

<!-- Signup window for new users -->
    <div id="modal-signup" class="modal-window">
        <h2>Just one more thing before we log you in..<small>We're almost there <strong><span id="modal-signup-name"></span></strong>, but first we'll need you to add a few more details to personalize your Circlefy experience.</small></h2>
    
        <form id="signup-form">
            <p class="forms">
            <label for="i-uname">Username</label>
            <input type="text" id="i-uname"
                   name="uname"
                   class="required validate-alphanum maxLength:20 minLength:4 userDoesNotExists"
                   data-tipid="tip-signup-user"
            />
            </p>

            <p class="forms">
            <label for="i-pass">Password</label>
            <input type="password" id="i-pass"
                   name="pass"
                   class="required minLength:6"
                   data-tipid="tip-signup-pass"
            />
            </p>

            <p class="modal-actions">
                <span class="indicator">
                    <img src="/static/spinner.gif" />
                    <span class="indic-msg">Signing you up...</span>
                </span>
                <span class="modal-actions">
                    <button>Start Circling</button> <a class="modal-cancel" href="#">close</a>
                </span>
            </p>

            <div class="sep"></div>
            <p class="forms" id="fb-button">
                <label for="fb-login-button" style="padding-right: 28px">Facebook</label>
                <span id="fb-signup-faces">
                    <fb:login-button 
                        show-faces="true"
                        width="300"
                        perms="<?=FBPERMISSIONS?>"
                        class="fb-login-button validate-facebook"
                        name="facebook"
                        data-tipid="tip-signup-facebook"
                    ></fb:login-button>
                </span>
            </p>
        </form>
    </div>

<!-- Login -->
    <div id="modal-login" class="modal-window">
        <h2>Join conversation!</h2>
            <form id="taplogin" action="/" method="POST">
                <p class="forms" style="margin-top:30px;">  
                    <label class="inblock">Username</label>
                    <input name="uname" type="text" class="basic" value="<?= $_POST['uname'] ?>" />
                </p>
                <p class="forms">
                    <label class="inblock">Password</label>
                    <input name="pass" type="password" class="basic" value="<?= $_POST['pass'] ?>" />
                </p>

                <span class="modal-actions" style="overflow: hidden; width: 420px; height: 50px;">
                    <button id="login-button" type="submit">Log in with password</button>
                    <button id="facebook-button" type="submit">Log in with Facebook</button>
                </span>
                <div class="sep"></div>
                    <span class="fb" id="fb-faces"><fb:login-button width="300" perms="<?=FBPERMISSIONS?>" show-faces="true"></fb:login-button></span>
                    <span class="fb hidden" id="fb-no-faces"><fb:login-button width="300" perms="<?=FBPERMISSIONS?>"></fb:login-button></span>
            </form>
               
    <span class="modal-actions">
            <a class="modal-cancel" href="#">close</a>
        </span>
    </div>


<!-- Login or signup -->
    <div id="modal-sign-login" class="modal-window">
    <img class="modal-logo-large" src="http://circlefy.com/static/images/logo.png" />
        <div class="text">
        <h2>Hi there!<small>Select an option below</small></h2>
        <span class="modal-actions">
                <button class="signup-button">Sign up</button><button class="login-button">Log in</button>
        </span>
        </div>
	<span class="login-message">Circlefy allows you to create and join social circles that are directly related to your real-world social circles, such as Universities, Companies, and Locations.  It enables true real-time communities on the web.</span>
    </div>

    <!-- facebook -->
    <div id="modal-facebook" class="modal-window">
        <h2>Login to facebook</h2>
        <p class="forms" id="fb-button">
                <label for="fb-login-button" style="padding-right: 28px">Facebook</label>
                <span id="fb-signup-no-faces">
                    <fb:login-button 
                        width="300"
                        perms="<?=FBPERMISSIONS?>"
                        class="fb-login-button validate-facebook"
                        name="facebook"
                        data-tipid="tip-signup-facebook"
                    ></fb:login-button>
                </span>
            </p>
    </div>

<!-- Notification for guests to login or signup -->
    <div id="modal-sign-notify" class="modal-window">
        <h2>You've just posted your first tap</h2>
        <p>In order to make your tap experience better, please, sign up or log in</p>
        <span class="modal-actions">
                <button class="signup-button">Sign up</button><button onClick="javascript: window.location.replace('/login')">Log in</button><a class="modal-cancel" href="#">close</a>
        </span>
    </div>

<!-- Post status on facebook -->
    <div id="modal-facebook-status" class="modal-window">
        <h2>Tap notice</h2>
        <p>Share your tap experience with your friends!</p>
        <input type="hidden" name="link">
        <div id="fb_preview" style="background-color: white; border: 1px solid #CCCCCC; width: 460px; color:#333333; font-family: 'lucida grande', tahoma, verdana, arial; font-weight: normal; text-align: left; overflow: hidden;font-size: 11px; padding: 4px;">
            <div>
                <h3 style="width: 340px; font-size: 13px; margin: 0; padding: 0">
                    <a class="fb_name" style="font-weight: bold; color: #3B5998; cursor: pointer; text-decoration: none"> </a>
                    <span class="fb_message" style="font-weight: normal;"> </span>
                </h3>
            </div>
            <div style="margin-bottom: 5px; margin-top: 6px; padding-right: 10px; overflow: hidden;">
                <div style="padding-right: 10px; float: left; overflow: hidden;">
                    There should be tap image
                </div>
                <div style="display: table;">
                    <div style="display: inline; font-weight: bold; padding-top: 3px">
                        <a style="color: #3B5998; cursor: pointer; text-decoration: none;">Join discussion</a>
                    </div>
                    <div class="caption" style="color: #808080; padding-top: 3px;"> </div>
                    <div style="display:inline; color: #808080; padding: 3px 0;">TAP communication platform</div>
                </div>
            </div>
        </div>
        <p class="forms" style="margin-top:30px"><label>Status</label> <input type="text" name="status" /></p>
        <p class="guide">Wrong story, bro</p>
        <p class="forms" style="margin-top:30px"><label>Message</label> <input type="text" name="message" /></p>
        <p class="guide">Wrong story, bro</p>
        <p class="modal-menu">
                <span class="indicator">
                        <img src="/static/spinner.gif" />
                        <span class="indic-msg">Publishing...</span>
                </span>
                <span class="modal-actions">
                        <button>Publish</button> or <a class="modal-cancel" href="#">close</a>
                </span>
        </p>
    </div>

<!-- Channel suggestion dialog -->
    <div id="modal-channel-suggestion" class="modal-window">
        <h2>Circle suggestions</h2>
        <p>You may be interested in following circles:</p>
        <div id="suggestions">
            <span class="indicator">
                <img src="/static/spinner.gif" />
                <span class="indic-msg">Fetching possible suggestions...</span>
            </span>
            <span class="fail">
                Sorry, no suggestions for you today
            </span>
            <ul>
            </ul>
        </div>
        <p class="modal-menu" style="margin-top: 15px;">
            <span class="indicator">
                <img src="/static/spinner.gif" />
                <span class="indic-msg">Joining...</span>
            </span>
            <span class="modal-actions">
                <button>Join circles</button><a href="#" class="modal-cancel">close</a>
            </span>
        </p>
    </div>

<? if ($circle && $moderator): ?>
<!-- Group edit dialog-->
    <div id="modal-group-edit" class="modal-window">
        <h1 class="wide">Manage circle</h1>
        
        <? if (!empty($pending)): ?>
        	<div id="add" class="add">
            	<label>pending members <small>these members need to be aproved before they can start browsing the circle</small></label>
                
                <?php
                    $_ul = array('users' => $pending);
                    include(USER_LIST);
                ?>

                <input type="submit" class="accept" value="Accept members" />
                <input type="submit" class="reject" value="Reject members" />
                <div class="clear"></div>
            </div><!--add-->
        <? endif; ?>
    	
        <form id="group-edit">
        
            <input type="hidden" name="id" id="edit-id" value="<?=$circle['id']?>">
        	
            <div class="cont">
			<label for="edit-title">title   <small>what will your circle be called?</small></label>
            <input type="text" id="edit-title"
                   name="title" 
                   value="<?=$circle['name']?>"
                   class="required"
                   data-tipid="tip-input-title"
            />
            </div>
            
            <div class="cont second">
            <label for="edit-symbol">symbol   <small>leave it for robots</small></label>
            <input type="text" id="edit-symbol"  disabled=""
                   name="symbol"
                   value="<?=$circle['symbol']?>"
                   class="groupDoesNotExists oldSymbol:'<?=$circle['symbol']?>'"
                   data-tipid="tip-input-symbol"
            />
            </div>
            
            <div class="clear"></div>
            
            <label for="edit-descr">description   <small>a brief explaination what this circle stands for</small></label>
            <textarea name="descr" id="edit-descr" 
                      class="maxLength:250"
                      data-tipid="tip-input-descr"
            /><?=$circle['descr']?></textarea>
			
            <div class="cont">
        	<label for="edit-type">circle type</label>
            <select name="type" id="edit-type">
                <? foreach ($types as $val => $t): ?>
                    <option value="<?=$val?>" <?=($t == $circle['type'] ? ' selected' : '')?>><?=$t?></option>
                <? endforeach; ?>
            </select>
            <div style="width: 250px; height: 50px; padding: 20px 0 0 0;">
                <img src="<?=GROUP_PIC_REL . 'medium_' . $circle['id'] . '.jpg'?>" 
                     id="avatar-changer"
                     data-tipid="tip-avatar-changer">
                     <span class="up">Upload a picture to represent this circle</span>
            </div>
            </div>
            
            <div class="cont second">            
            <label for="edit-auth">authentication type</label>
            <select name="auth" id="edit-auth">
                <? foreach ($auths as $val => $t): ?>
                    <option value="<?=$val?>" <?=($t == $circle['auth'] ? ' selected' : '')?>><?=$t?></option>
                <? endforeach; ?>
            </select>
            <div id="edit-auth-email-cont" class="hidden">
                <label for="edit-auth-email">organization domain</label>
                <input type="text" name="edit-auth-email" id="edit-auth-email" class="required" value="<?=$circle['auth_email']?>" />
            </div>
            </div>
            
            <div class="clear"></div>

            <span>secret <input type="checkbox" name="secret" <?=($circle['secret'] ? ' checked' : '')?>/></span>

            <div class="clear"></div>
            <label for="group-search-link">Parent circle</label>

            <div id="parent-circle" class="circle-thumb <?=(!$parent ? ' hidden' : '')?>" data-tipid="tip-circle-main" data-tiptitle="<?=$parent['name']?>" style="margin-left: 24px">
                <span class="circle" style="margin:0;"></span>
                <img src="<?=GROUP_PIC_REL . 'medium_' . $parent['id'] . '.jpg'?>" class="profile-thumb" alt="thumb" style="opacity: 1" />
            </div>

            <div style="position:relative">
                <input id="group-search-link" class="" type="text" autocomplete="off" value="<?=($parent?$parent['name']:'')?>" title="" rel="" style="width:340px" />
                <div id="link-search-results" class="search-results hidden">
                  <ul></ul>
                </div><!--searchresults-->
            </div>                      

            <input type="submit" class="load" value="Update Circle"/>
                    
        </form>
        <span class="modal-actions">
                <a class="modal-cancel" href="#">close</a>
        </span>
    </div><!--modal-->
<? endif; ?>

<!-- Image preview -->
    <div id="modal-image-display" class="modal-window">
        <div class="img-container"></div>
        <span class="modal-actions">
                <a class="modal-cancel" href="#">close</a>
        </span>
    </div><!--modal-->

<? if (!$guest): ?>
<!-- User edit dialog-->
    <div id="modal-user-edit" class="modal-window" style="position: absolute">
        <h1 class="wide">Your profile settings</h1>
        <form id="user-edit">
            <input type="hidden" name="id" id="edit-user-id" value="<?=$me['id']?>">

            <div class="cont">
			<label for="user-edit-fname">First name</label>
            <input type="text" id="user-edit-fname"
                   name="fname" 
                   value="<?=$me['fname']?>"
                   class="required validate-alphaspace maxLength:24"
                   data-tipid="tip-input-fname"
            />
            </div>

            <div class="cont second">
			<label for="user-edit-lname">Last name</label>
            <input type="text" id="user-edit-lname"
                   name="lname" 
                   value="<?=$me['lname']?>"
                   class="required validate-alphaspace maxLength:24"
                   data-tipid="tip-input-lname"
            />
            </div>  
            
            <div class="clear"></div>         

            <div class="single">
            <label for="user-edit-email">email address<small>you'll receive useful stuff at this address</small></label>
            <input type="text" id="user-edit-email" 
                   name="email"
                   value="<?=$me['email']?>"
                   class="required validate-email emailDoesNotExists oldEmail:'<?=$me['email']?>'"
                   data-tipid="tip-input-email"
            />
            </div>
            
            <div class="clear"></div>
            <div style="width: 500px; height: 50px; padding: 20px 0 0 0;">
                <img src="<?=USER_PIC_REL?>medium_<?=$me['id']?>.jpg" 
                     id="user-avatar-changer"
                     data-tipid="tip-user-avatar-changer">
                     <span class="up">Upload a picture to represents you</span>
            </div>

            <input type="submit" class="load" value="Update your profile"/>
        </form>
        <span class="modal-actions">
                <a class="modal-cancel" href="#">close</a>
        </span>
    </div><!--modal-->
<? endif; ?>


<!-- Group creation dialog-->
    <div id="modal-group-create" class="modal-window">
        <h1 class="wide">Create circle</h1>
        
        <form id="group-create">
        
            <div class="cont">
            <label for="create-title">title   <small>what will your circle be called?</small></label>
            <input type="text" id="create-title"
                   name="title" 
                   value=""
                   class="required"
                   data-tipid="tip-input-title"
            />
            </div>
            
            <div class="cont second">
            <label for="create-symbol">symbol   <small>leave it for robots</small></label>
            <input type="text" id="create-symbol"  disabled=""
                   name="symbol"
                   value=""
                   class="groupDoesNotExists"
                   data-tipid="tip-input-symbol"
            />
            </div>
            
            <div class="clear"></div>
            
            <label for="create-descr">description   <small>a brief explaination what this circle stands for</small></label>
            <textarea name="descr" id="create-descr" 
                      class="maxLength:250"
                      data-tipid="tip-input-descr"
            /></textarea>
			
            <div class="cont">
        	<label for="create-type">circle type</label>
            <select name="type" id="create-type">
                <? foreach ($types as $val => $t): ?>
                    <option value="<?=$val?>"><?=$t?></option>
                <? endforeach; ?>
            </select>
            <!--
            <div id="create-upload" class="hidden">
                <div style="width: 250px; height: 50px; padding: 20px 0 0 0;">
                    <img src="/static/images/medium_group.png" 
                         id="create-avatar-changer"
                         data-tipid="tip-avatar-changer">
                         <span class="up">Upload a picture to represent this circle</span>
                </div>
            </div>-->
            <div id="create-secret">
                <span>secret <input type="checkbox" name="secret" /></span>
            </div>
            </div>
            
            <div class="cont second">
            <label for="create-auth">authentication type</label>
            <select name="auth" id="create-auth">
                <? foreach ($auths as $val => $t): ?>
                    <option value="<?=$val?>"><?=$t?></option>
                <? endforeach; ?>
            </select>
            <div id="auth-email-cont" class="hidden">
                <label for="auth-email">enter your org/edu email</label>
                <input type="text" name="auth-email" id="auth-email" class="required validate-email" value="" />
            </div>
            </div>
            
            <div class="clear"></div>
            
            <input type="submit" class="load" value="Create Circle"/>
                    
        </form>
        <span class="modal-actions">
                <a class="modal-cancel" href="#">close</a>
        </span>
    </div><!--modal-->

<!-- Email Authorization -->
    <div id="modal-email-auth" class="modal-window">
        <h1 class="wide">Enter your circle email</h1>
        <form id="email-auth-form">
            <p>We will send you an email with a link to confirm your email address and join you to this circle.</p>
            <div class="cont">
			<label for="email-auth-email">Email Addres</label>
            <input type="text" id="email-auth-email"
                   name="email" 
                   value=""
                   class="required validate-email"
                   data-tipid="tip-email-auth"
            />
            <input type="hidden" name="gid" value="<?=$circle['id']?>" id="email-auth-gid" />
            <input type="submit" class="load" value="Confirm Email" />
            </div>
        </form>
        <div id="auth-response" class="hidden">
            <p></p>
            <input type="button" name="auth-email-close" value="Close" id="auth-email-close" />
        </div>
    </div><!--modal-->

<!-- First Tap -->
    <div id="modal-first-tap" class="modal-window">
        <h2>How are you related to this circle?</h2>
        <form id="firsttapform" method="POST">
            <input type="hidden" name="gid" value="<?=$circle['id']?>" id="first-tap-gid" />
            <p class="forms" style="margin-top:30px;">  
                <label class="inblock">Enter what's your relation with <?=$circle['name']?></label>
                <input name="circle-context" 
                       id="circle-context" 
                       type="text" 
                       maxlength="50"
                       class="basic required"
                       data-tipid="tip-context"
                />
                <div class="clear"></div>
                <em>Example: Class of 2008, CS Major</em>
            </p>
            <span class="modal-actions"><button id="first-tap-button" type="submit">Post</button></span>
        </form>
        <span class="modal-actions">
                <a class="modal-cancel" href="#">close</a>
        </span>
    </div>

<!-- Post Tap -->
    <div id="modal-post-tap" class="modal-window">
        <h2>Post</h2>
        
        <form id="posttapform" method="POST">
        	<p>Write a message to a circle</p>
            <label for="postmessage">Message</label>
            <textarea name="postmessage" 
                      id="postmessage" 
                      data-tipid="tip-post-message"
                      class="required"
            /></textarea>
            <div class="clear"></div>
            <label for="group-search-post">Circle</label>
            <div style="position:relative">
            <input id="group-search-post" class="required groupSelected" type="text" autocomplete="off" value="" title="" rel="" data-tipid="tip-post-circle" />
            <div id="post-search-results" class="search-results hidden">
              <ul></ul>
            </div><!--searchresults-->
            <a href="#" class="hidden" id="group-search-clear"><img src="/static/images/clear.png" /></a>
            </div>
            
            <div class="clear"></div>
            <div class="media-preview-loading hidden"><img src="/static/images/media-spinner.gif" /><span>Loading...</span></div>
            <div class="media-preview hidden">
                <img src="" alt="thumb" class="thumbnail" id="video-00" />
                <div class="data">
                    <h3 class="title video"><a href="#"></a></h3>
                    <small><a href="#"></a></small>
                    <em></em>
                </div><!--data-->
                <div class="clear"></div>
            </div><!--mediapreview-->                
            
            <span class="modal-actions"><button id="post-tap-button" class="load">Post</button></span>
        </form>
        <span class="modal-actions">
                <a class="modal-cancel" href="#">close</a>
        </span>
    </div>

<? /*** Group members edit dialog ***/ ?>
    <div id="modal-edit-members" class="modal-window">
        <div class="add">
            <label>Circle members <small>feel free to edit user in any way you wish</label>
            
            <?php
                $_ul = array('users' => $members, 'show_actions' => true);
                include(USER_LIST);
            ?>

            <div class="clear"></div>
        </div><!--add-->
        <span class="modal-actions">
                <a class="modal-cancel" href="#">close</a>
        </span>
    </div>

</div>
