<div id="curtain"></div>

<div id="modal-container">
	<div id="modal-signup">
		

		<h2>Just one more thing before we log you in..</h2>
		<p>We're almost there <strong><span id="modal-signup-name"></span></strong>, but first we'll need you to add a few more details to personalize your Tap experience.</p>
        <input type="hidden" name="facebook" value="0">
        <input type="hidden" name="fb_fname" value="">
        <input type="hidden" name="fb_lname" value="">
		<p class="forms" style="margin-top:30px"><label>Username</label> <input type="text" name="uname" /></p>
		<p class="guide">This username is already taken.</p>
		<p class="forms" id="real_name"><label>Real name</label> <input type="text" name="name" /></p>
		<p class="forms"><label>Email</label> <input type="text" name="email" /></p>
		<p class="guide">Enter a valid email address.</p>
		<p class="forms"><label>Password</label> <input type="password" name="pass" /></p>
		<p class="guide">Passwords must be at least 4 characters.</p>
		<p style="margin-top: 50px; text-align: right; font-size: 14px; margin-right: 20px">
				<span class="indicator">
						<img src="/images/spinner.gif" />
						<span class="indic-msg">Signing you up...</span>
				</span>
				<span id="modal-signup-actions">
						<button>Start Tapping!</button> or <a id="modal_signup-cancel" href="#">close</a>
				</span>
		</p>


	</div>
</div>
