<div id="supernav">


 <div id="lists2" class="section container">

    <ul id="panel-groups" class="panel selected"
        data-action="manage"
        data-action-href="/channels"
        data-name="channels">

        <li id="feed" class="<? echo !isset($start_gid) || $start_gid == 'all' ? 'selected ' : ''?>panel-item"
            data-topic="Aggregate feed of everything"
            data-id="feed"
            data-name="Your feed">
            <a href="#" class="names inblock ellipsis">Your feed</a>
        </li>

        <li id="gid_all" class="panel-item"
            data-topic="<?= $all_your_groups_topic ?>"
            data-id="channels"
            data-name="All Your Channels">
            <a href="#" class="names inblock ellipsis">Followed Channels</a>
        </li>

		<li id="users_all" class="panel-item"
            data-id="peoples"
            data-name="All your people"
            data-topic="Aggregate feed of all your friends">
            <a href="#" class="names inblock ellipsis">Followed People</a>
        </li>

        <li id="convos_all" class="panel-item"
            data-id="convos"
            data-name="Inbox"
            data-topic="All your private messages">
            <a href="#" class="names inblock ellipsis">Followed Conversations</a>
        </li>

        <li id="gid_public" class="<? echo isset($start_gid) && $start_gid == 'public' ? 'selected ' : ''?>panel-item"
            data-topic="<?= $public_groups_topic ?>"
            data-id="public"
            data-name="Discover Taps">
            <a href="#" class="names inblock ellipsis">Discover</a>
        </li>

		<li id="private_all" class="panel-item"
            data-id="inbox"
            data-name="Inbox"
            data-topic="All your private messages">
            <a href="#" class="names inblock ellipsis">Inbox</a>
        </li>

    </ul>
</div>
<!--
<div id="filter" class="section">
                <p class="inblock ellipsis">search <span class="title">all your channels</span> <a href="#" class="clear">clear</a></p>
                <input id="filterkey" type="text" class="basic" />
</div>
-->
</div>
