<div id="links">
                        <ul id="left_ul">

                                <li id="this1"><a href="<?=ROOT?>"><img src="images/cimages/tap_logo_beta.gif" /></a></li>
                                <li id="this2"><a href="<?=ROOT?>profile">Profile</a></li>
                                <li id="this3"><a href="<?=ROOT?>relevancy_settings">Filters</a></li>
                                <li id="this5"><a href="<?=ROOT?>channels">Channels</a></li>
                        </ul>

                        <ul id="right_ul">
                                <li><span id="user"> Logged in as <?=$user?></span><span id="sign_out"><a href="<?=ROOT?>?logout=true">Sign Out</a></span></li>
                                <li><span id="tips_toggle"></span></li>
                        </ul>
  </div>
