<div id="header">
<script type="text/javascript" charset="utf-8">
  var is_ssl = ("https:" == document.location.protocol);
  var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
  document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript" charset="utf-8">
  var feedback_widget_options = {};

  feedback_widget_options.display = "overlay";  
  feedback_widget_options.company = "tap";
  feedback_widget_options.placement = "bottom";
  feedback_widget_options.color = "#222";
  feedback_widget_options.style = "idea";
  
  
  
  
  
  

  var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
</script>

	<div class="holder">
		<span id="logo"><a href="">TAP</a></span>
		<span id="main-menu" style="font-size: 13px; font-weight: normal">
			<a href="/" style="margin-right: 15px"><strong>Interface</strong></a> 
			<a href="/profile" style="margin-right: 15px">Profile</a> 
			<a href="/groups" style="margin-right: 15px">Groups</a> 
			<a href="/help" style="margin-right: 15px">Help</a>
		</span>
		<span id="login-info" style="font-size: 12px; font-family: Trebuchet MS, Arial, sans-serif">
			Signed in as: <span style="font-weight: bold; margin-left: 5px;"><?= $_SESSION['uname'] ?></span><br />
			<a href="/?logout=true">Logout</a>
		</span>
	</div>
	<div style="clear:both"></div>
</div>
