<div id="header">
	<div class="holder">
		<span id="logo"><a href="">TAP</a></span>
		<span id="main-menu" style="font-size: 13px; font-weight: normal">
			<a href="/" style="margin-right: 15px"><strong>Interface</strong></a> 
			<a href="/profile" style="margin-right: 15px">Profile</a> 
			<a href="/groups" style="margin-right: 15px">Groups</a> 
			<a href="/help" style="margin-right: 15px">Help</a>
		</span>
		<span id="login-info" style="font-size: 12px; font-family: Trebuchet MS, Arial, sans-serif">
			Signed in as: <span style="font-weight: bold; margin-left: 5px;"><?= $_SESSION['uname'] ?></span><br />
			<a href="/?logout=true">Logout</a>
		</span>
	</div>
	<div style="clear:both"></div>
</div>