<div id="notifications">
    
    <div class="list">
    
    	<div class="controls">
        
        	<a href="#" class="paginate"><strong>&laquo;</strong> Previous</a>
            
            <a href="#" class="paginate">Next <strong>&raquo;</strong></a>
            
            <a href="#" class="close">Close <strong>&times;</strong></a>
        
        </div><!--controls-->
    
    </div><!--list-->

	<a href="#" class="toggle">Notifications</a>

</div><!--notifications-->