<div id="notifications" class="<?=(empty($events) ? 'hidden' : '')?>">
    
    <div class="list">
        <div class="events">
        <? if (!empty($events)): ?>
            <? foreach($events as $e): ?>
            <div id="event-<?=($e['type'] == 2 ? 2 : 1)?>-<?=$e['id']?>" class="event">
                <? if (isset($e['group_id'])): ?>
                    <a href="/circle/<?=$e['group']['symbol']?>">
                        <img src="<?=GROUP_PIC_REL?>small_<?=$e['group_id']?>.jpg" class="group_icon" />
                    </a>
                <? endif; ?>
                <? if (!$e['anonymous']): ?>
                    <a href="/user/<?=$e['sender']['uname']?>">
                        <img src="<?=USER_PIC_REL?>small_<?=$e['sender_id']?>.jpg" class="avatar" />
                    </a>
                <? else: ?>
                    <img src="/static/images/user.gif" class="avatar" />
                <? endif; ?>
                <h3>
                    <? if ($e['type'] == 0): ?>
                    <a href="/convo/<?=$e['id']?>">New message</a>
                    <? elseif ($e['type'] == 1): ?>
                        <a href="/convo/<?=$e['id']?>"><?=$e['new_replies']?> unread repl<?=($e['new_replies'] == 1 ? 'y' : 'ies')?></a>
                    <? elseif ($e['type'] == 2): ?>
                        <a href="/user/<?=$e['sender']['uname']?>">Someone follows you</a>
                    <? endif; ?>
                </h3>
                <p>
                    <? if ($e['type'] == 2): ?>
                    <a href="/user/<?=$e['sender']['uname']?>">
                        <?=$e['sender']['fname']?> <?=$e['sender']['lname']?>
                    </a>
                    <? else: ?>
                    <a href="/convo/<?=$e['id']?>">
                        <?=$e['text']?>
                    </a>
                    <? endif; ?>
                </p>
            </div>
            <? endforeach; ?>
        <? endif; ?>
        </div>
    
    	<div class="controls">
        
        	<button class="paginate" data-type="prev" disabled="true"><strong>&laquo;</strong> Previous</button>
            
            <button class="paginate" data-type="next" <? if (count($events) < 5) :?>disabled="true"<? endif; ?>>Next <strong>&raquo;</strong></button>
            
            <button class="close">Close <strong>&times;</strong></button>
        
        </div><!--controls-->
    
    </div><!--list-->

	<a href="#" class="toggle">Missed Notifications</a>

</div><!--notifications-->
