<div id="notifications">
    
    <div class="list">
    
    	<div class="controls">
        
        	<a href="#" class="previous">Previous</a>
            
            <a href="#" class="next">Next</a>
            
            <a href="#" class="close">Close</a>
        
        </div><!--controls-->
    
    </div><!--list-->

	<a href="#" class="toggle">Notifications</a>

</div><!--notifications-->