<div id="footer">
<div style="padding-top: 10px">
	<strong>tap &copy; 2010</strong>
	<span class="nav">
		<a href="/">home</a>
		<a href="/login">login</a>
		<a href="/what">what's tap?</a>
		<a href="/about">about us</a>
		<a href="/devs">developers</a>
		<a href="/contact">contact</a>
	</span>
</div>
</div>

<script type="text/javascript">
<?php $u = $_SERVER['REQUEST_URI']; ?>
var server_uri = "<?=$u?>";
var join_type = "<?$g = explode('/',$u); $g = $g[1]; echo $g;?>";
var join_value = "<?$g = explode('/',$u); $g = $g[2]; echo $g;?>";
</script>

<script type="text/javascript">
var _gaq = _gaq || [];
 _gaq.push(['_setAccount', 'UA-11153159-1']);
 _gaq.push(['_trackPageview']);

 (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
 })();
</script>
