<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="en-us" />
<meta name="robots" content="noodp" />
<meta name="image-toolbar" content="no" />
<meta name="copyright" content="Copyright (c) 2010 TAP" />
<meta name="description" content="TAP communication platform" />
<meta name="keywords" content="real-time, search, TAP, microblogging, communication platform" />
<meta name="uid" content="<?= $pcid ?>" />
<meta name="uname" content="<?= $_SESSION['uname'] ?>" />
<title>tap - <?=$tpl_title?></title>

<link rel="shortcut icon" href="http://<?=DOMAIN?>/group_pics/default.ico" />
<link rel="stylesheet" href="/views/styles/global.css" type="text/css" />
<link rel="stylesheet" href="/views/styles/public.css" type="text/css" />
<link rel="stylesheet" href="/views/styles/Roar.css" type="text/css" />
<script type="text/javascript" src="http://<?=DOMAIN?>:8000/static/Orbited.js"></script> 
<script type="text/javascript" src="/views/scripts/mootools-core.js"></script>
<script type="text/javascript" src="/views/scripts/mootools-more.js"></script>
<script type="text/javascript" src="/views/scripts/Roar.js"></script>
