<?php
$r = $_SERVER['REQUEST_URI'];
$c = 'class="current"';

switch($r){
        case '/':       $home =  $c;break;
        case '/channels':   $groups =  $c;break;
        case '/people':  $people=  $c;break;
        case '/settings':   $settings =  $c;break;
}
?>


    <div id="searchsuggest" >
        <ul>
        </ul>
    </div>

  <div id="header" class="container">
                        <div id="slim-background"></div>

                        <div id="nav" class="nav-slim">
                                <a href="/"  	    <?=$home?>    >home</a>
                                <a href="/channels"   <?=$groups?>  >channels</a>
                                <a href="/people"   <?=$people?>  >people</a>

                                <?php if ($me['guest']): ?>
    								<a href="#" class="sign-login-button">create account or log in</a>
                                <?php else: ?>
                                    <img src="/user_pics/<?=$me['small_pic']?>">
                                    <a href="/settings" <?=$settings?>><?=$me['real_name']?></a>
    								<a href="/?logout=true">logout</a>
                                <?php endif; ?>
                        </div>

                        <div id="logo" class="logo-slim">
                                <a href="/"></a>
                        </div>

                        <div id="searchbar" class="searchbar-slim"> 
                                <div id="searchover" class="searchover-slim">Start or Join a conversation</div>
                                <input id="search" type="text" class="basic" style="padding: 4px; font-size: 17px; width: 400px;" autocomplete="off">
                        </div>
                </div>


<? /*





<?php
	// This file replaces final_header and final_header_logout

$r = $_SERVER['REQUEST_URI'];
$c = 'class="current"';

// Logged in
switch($r){
	case '/':			$home	= $c; break;
	case '/groups':		$groups	= $c; break;
	case '/people':		$people	= $c; break;
	case '/settings': $settings = $c; break;
}

// Logged out
switch($r){
	case '/':       	$home	= $c; break;
	case '/login':		$login	= $c; break;
	case '/signup': 	$signup	= $c; break;
}
?>

<div id="header" class="container">
	<div id="nav">

	<?php 
	if ($ok_user) { ?>
		<a href="/"  	    <?=$home?>    >home</a>
		<a href="/channels"   <?=$groups?>  >channels</a>
		<a href="/people"   <?=$people?>  >people</a>
		<a href="/settings" <?=$settings?>>settings</a>
		<a href="/?logout=true">logout</a> <? echo $ok_user; ?>
	<? } else { ?>
		<a href="/" 	   <?=$home?>   >home</a>
		<a href="/login"       <?=$login?>   >login</a>
		<a href="/signup"	   <?=$signup?>   >sign up</a>
	<? } ?>

	</div>

	<div id="logo"> <a href="/"></a> </div>

	<div id="searchbar">
		<div id="searchover">Start or Join a conversation</div>
		<input id="search" type="text" class="basic" autocomplete="off">
		<div id="searchsuggest">
			<ul> </ul>
		</div>
	</div>

	</div>

 */ ?>
