<? if (!empty($_r['replies'])):
        $count = count($_r['replies']);
        $id = 0;
        foreach($_r['replies'] as $r):
            $id++;
            $last = $count == $id; ?>
    <div class="reply-item<?=($last ? ' last' : '')?>" id="conversation-<?=$r['id']?>">
        <div class="thumb"><img src="<?=USER_PIC_REL.'medium_'.$r['user']['id'].'.jpg'?>" alt="<?=$r['user']['fname']?> <?=$r['user']['lname']?>" /></div>
        <span class="text">
            <h3 class="username">
                <a href="/user/<?=$r['user']['uname']?>"><?=$r['user']['uname']?></a>:
            </h3>
            <span class="reply-text"><?=$r['text']?></span>
            <span class="timestamp" data-timestamp="<?=$r['timestamp']?>"><?=$r['time']?></span>
        </span>
        <div class="clear"></div>
    </div><!--item-->
<?      endforeach;
   endif;?>

