<div id="sidebar"<?=(isset($_s['convo']) ? 'class="conversation"' : '')?><?=(isset($_s['circle']) ? 'class="side"' : '')?>>
<? if (isset($_s['convo'])): ?>
<div class="wrap">
<? endif; ?>

<? /*** Convo information box ***/ ?>
    <? if (isset($_s['convo'])): 
            $c = $_s['convo']; ?>
        <div class="box">
            
            <h3 class="username">
                <? if(!$c['reciever_id']): ?>
                    <? if (!$c['anonymous']): ?>
                        <img src="<?=USER_PIC_REL.'small_'.$c['sender']['id'].'.jpg'?>" alt="<?=$c['sender']['fname']?> <?=$c['sender']['lname']?>" width="16" />
                    <? else: ?>
                        <img src="/static/images/user.gif"/>
                    <? endif; ?>
                <? else: ?>
                    <img src="/static/images/envelope.png" />
                <? endif; ?>

                <? if (!$c['anonymous']): ?>
                    <?=$c['sender']['uname']?>
                <? else: ?>
                    anonymous
                <? endif; ?>
            </h3>
            <? if ($c['group_id']): ?>
                <a href="/circle/<?=$c['group']['symbol']?>" class="circle-thumb" data-tipid="tip-circle-main" data-tiptitle="<?=$c['group']['name']?>">
                    <span class="circle"></span>
                    <img src="<?=GROUP_PIC_REL . 'medium_' . $c['group']['id'] . '.jpg'?>" alt="<?=$c['group']['name']?>" />
                </a>
            <? elseif ($c['reciever_id']): ?>
                <a href="/user/<?=$c['sender']['id']?>" class="user">
                    <img src="<?=USER_PIC_REL.'medium_'.$c['sender']['id'].'.jpg'?>" alt=""<?=$c['sender']['fname']?> <?=$c['sender']['lname']?> />
                </a>
                <span class="pm-label">Private Message</span>
            <? endif; ?>
            <p>
                <?=$c['text']?>
            </p>
            <? if ($c['media']['id']): ?>
            <div class="media">
                <small><a href="<?=$c['media']['link']?>"><?=$c['media']['link']?></a></small>
                <a href="<?=$c['media']['link']?>" class="thumbnail">
                    <img src="<?=$c['media']['thumbnail_url'] ?>" alt="" class="thumbnail-image media-thumbnail" />
                </a>
                
            </div>
            <? endif; ?>
            
            <div class="clear"></div>
            
            <span class="stats"><span><?=count($c['replies'])?></span><small>responses</small></span>
            <span class="stats"><span><?=count($c['involved'])?></span><small>people involved</small></span>
            
            <div class="clear"></div>
            
            <a href="#" 
             class="follow <?=($_s['state'] ? ' active' : '')?>" 
             data-id="<?=$c['id']?>"
             data-followed="<?=($_s['state'] ? 1 : 0)?>"
             data-type="convo"
             def="Follow conversation"
             alt="Unfollow conversation"></a>       
            
            <div class="clear"></div>
            
        </div><!--box-->
    <? endif; ?>

<? /*** Group information box ***/ ?>
    <? if (isset($_s['circle'])):
            $c = $_s['circle'];
    ?>
    <div class="box circle-title">
      
	<?
	//need to add icon mapping here
	$circle_type = $_s['type'];
	$circle_type = "<span class='type-label'><img src='/static/images/type_{$c['type']}.png' />Type: {$c['type']} </span>";
	?> 

	<h3 class="username"><span class="group-name"><?=$c['name']?></span><? if($circle_type): ?>
	<span class="circle_type" data-tiptitle="blah"><?=$circle_type?></span> 
	<? endif; ?></h3>
        <div href="#" class="circle-thumb" data-tipid="tip-circle-main" data-tiptitle="<?=$c['name']?>">
            <span class="circle"></span>
            <img src="<?=GROUP_PIC_REL . 'medium_' . $c['id'] . '.jpg'?>" class="profile-thumb" alt="thumb" />
        </div>
        <p><?=$c['descr']?></p>
        
        <div class="clear"></div>
        
        <span class="stats"><?=$c['messages_count']?><small>messages<br />sent</small></span>
        <span class="stats"><?=$c['responses_count']?><small>responses<br />received</small></span>
        <span class="stats last"><?=$c['members_count']?><small>users<br />joined</small></span>
        
        <div class="clear"></div>
       
        <?
            $auth = array(
                'email'  => 'email address',
                'manual' => 'moderated',
                'ip'     => 'by ip',
                'geo'    => 'geo location');
            if ($_s['circle']['auth'] == 'manual' && !$_s['moderator']) {
                if ($_s['pending'])
                    $title = 'Waiting Approval';
                else
                    $title = 'Leave circle';
            }
            else $title = 'Leave circle';
        if (array_key_exists($_s['circle']['auth'], $auth)): ?>
            <div class="auth"><span>Authentication type:</span> <?=$auth[$_s['circle']['auth']]?></div>
        <? endif; ?>
        
        <div class="clear"></div>

         <a href="#" 
           class="follow <?=(($_s['state'] || $_s['pending']) ? ' active' : '')?>" 
		   data-id="<?=$c['id']?>"
		   data-followed="<?=(($_s['state'] || $_s['pending']) ? 1 : 0)?>"
           data-type="group"
           data-auth="<?=$_s['circle']['auth']?>"
           def="Join circle"
           alt="<?=$title?>"></a>       
	

	<? if($_s['moderator']): ?>
    	<button id="edit_circle">Edit Circle</button>
    	<button id="edit_members">Edit Members</button>
	<? endif; ?>       
 
        <div class="clear"></div>
        
    </div><!--box-->
    <? endif; ?>
    
<? /*** User information box ***/ ?>
    <? if (isset($_s['user'])):
            $u = $_s['user'];
    ?>
    <div class="box">
        
        <h3 class="username"><span class="<?=($u['online'] ? 'online' : 'offline')?>"><?=$u['uname']?></span>
        <small><?=$u['fname']?> <?=$u['lname']?></small></h3>
        <div href="#" class="user-thumb" data-tipid="tip-circle-user" data-tiptitle="<?=$u['uname']?>">
            <img src="<?=USER_PIC_REL.'medium_'.$u['id'].'.jpg'?>" class="avatar-author profile-thumb" alt="<?=$u['uname']?>'s avatar" /></div>
        <p>Random description of the
        channel. Could be very short</p>
        
        <div class="clear"></div>
        
        <span class="stats"><?=$u['stats']['messages']?><small>messages<br />sent</small></span>
        <span class="stats"><?=$u['stats']['responses']?><small>responses<br />received</small></span>
        <span class="stats last"><?=$u['stats']['groups']?><small>circles<br />joined</small></span>
        
        <div class="clear"></div>
       
        <? if ($u['id'] != $me['id']): ?>
        <a href="#" 
           class="follow <?=($_s['state'] ? ' active' : '')?>" 
		   data-id="<?=$u['id']?>"
		   data-followed="<?=($_s['state'] ? 1 : 0)?>"
           data-type="user"
           def="Follow"
           alt="Unfollow"></a>
        <a href="#" id="sendPMButton" class="pm">Send PM</a>
        <? endif; ?>
        
        <div class="clear"></div>
        
    </div><!--box-->
    <? endif; ?>

<? /*** Navigation menu***/ ?>
    <? if ($_s['show_nav']): ?>
    <ul id="navigation">
        <li <?=($_s['feed_type'] == 'feed' ? 'class="active"' : '')?>
            id="tab-your" 
            data-type="feed">
            <a href="#">Your Feed</a>
        </li>
        <li id="tab-circles"
            data-type="aggr_groups">
            <a href="#">Followed Circles</a>
        </li>
        <li id="tab-people"
            data-type="aggr_friends">
            <a href="#">Followed People</a>
        </li>
        <li id="tab-conversations"
            data-type="aggr_convos">
            <a href="#">Followed Conversations</a>
        </li>
        <li id="tab-discover"
            class="<?=($_s['feed_type'] == 'public' ? 'active ' : '')?>last"
            data-type="public">
            <a href="#">Discover</a>
        </li>
    </ul>
    <? endif; ?>
    
<? /*** Search bar ***/ ?>
    <form>
        <input type="text" id="search" title="Search" value="" />
    </form>

<? /*** Group members ***/ ?>
    <? if (!empty($_s['members'])): ?>
    <div class="box">
    
        <h3 class="title">Circle members 
        <? if (count($_s['members']) >= 14): ?>
            <a class="view-all" href="#"
               data-type="members"
               data-id="<?=$_s['circle']['id']?>">view all...</a>
        <? endif; ?>
        </h3>
        <?php
            $_f['members'] = $_s['members'];
            $fk = 'gmembers';
            include(FOLLOWERS);
        ?>
        <div class="clear"></div>
        
    </div><!--box-->
    <? endif; ?>

 <? /*** Tree ***/ ?>
    <? 
    function place_desired_in_center($list, $did) {
        $desired = null;
        foreach ($list as $e)
            if ($e['id'] == $did) {
                $desired = $e;
                break;
            }

        if (!$desired)
            return $list;

        $newlist = array();
        foreach ($list as $id=>$e) {
            if ($e['id'] != $did)
                $newlist[] = $e;
            if ($id == floor(count($list)/2))
                $newlist[] = $desired;
        }
        
        return $newlist;
    }
    
    if (!empty($_s['parent']) || !empty($_s['siblings']) || !empty($_s['childs'])): 
            $total_width = 240;
            $circle_size = 50;
            $circle_left = floor(($total_width - $circle_size)/2);
            $line_left   = $circle_left + floor($circle_size/2);

            $tree = array();
            if ($_s['parent'])
                $tree[] = array($_s['parent']);

            if ($_s['siblings'])
                $tree[] = $_s['siblings'];

            if ($_s['childs'])
                $tree[] = $_s['childs'];

            //$tree = array(array($_s['parent']), (array)$_s['siblings'], (array)$_s['childs']);
    ?>
    <div class="box">

    
        <h3 class="title">Circles tree</h3>

        <?
        foreach ($tree as $part => $elems):

            if (!empty($elems)): 
                $cells_count = count($elems);
                $cell_width  = floor($total_width/$cells_count);
                $circle_left = floor(($cell_width - $circle_size)/2);
                $line_left   = $circle_left + floor($circle_size/2);
            ?>
            <div class="circles" style="width: <?=$total_width?>px;">

            <?
                $elems = place_desired_in_center($elems, $circle['id']);

                $id = 0; 
                foreach ($elems as $c):
                    $id++;
                    $lineclass = '';
                    if ($cells_count > 1) {
                        if ($id == 1)
                            $lineclass = 'round right';
                        elseif ($id == $cells_count)
                            $lineclass = 'round left';
                        else
                            $lineclass = 'straight horizontal';
                    }
            ?>
                <div class="cell" style="width: <?=$cell_width?>px">
                    <div class="container">
                        <? if ($part): ?>
                            <? if ($lineclass && $lineclass != 'straight horizontal'): ?>
                                <div class="line <?=$lineclass?>" style="left: <?=$line_left?>px; width: <?=$line_left?>px"></div>
                                <div class="line straight" style="left: <?=$line_left?>px"></div>
                            <? else: ?>
                                <? if ($lineclass): ?>
                                    <div class="line <?=$lineclass?>" style="left: 0px; width: <?=$cell_width?>px"></div>
                                <? endif; ?>
                                <div class="line straight long" style="left: <?=$line_left?>px"></div>
                            <? endif; ?>
                        <? endif; ?>

                        <a href="/circle/<?=$c['symbol']?>" 
                           id="tree-<?=$c['id']?>"
                           class="circle-thumb"
                           data-tipid="circle-<?=$c['id']?>" 
                           data-tiptitle="<img src='/static/images/type_<?=$c['type']?>.png' width='16' height='16' /> <?=$c['name']?>" 
                           data-tipcontent="<?=((!empty($c['descr']))?$c['descr']:'&nbsp;')?>"
                           style="left: <?=$circle_left?>px; margin: 0">
                            <span class="circle"></span>
                            <img src="<?=GROUP_PIC_REL . 'medium_' . $c['id'] . '.jpg'?>" />
                            <? if ($c['id'] == $_s['circle']['id']): ?>
                                <span class="circle-title" style="color: red">you here</span>
                            <? else: ?>
                                <span class="circle-title"><?=substr($c['name'],0,6);?></span>
                            <? endif; ?>
                        </a>

                        <? if (($c['id'] == $_s['circle']['id'] || !$part) && $part != count($tree)-1): ?>
                            <div class="line straight" style="left: <?=$line_left?>px; top: <?=$circle_size?>px; margin-bottom: <?=$circle_size?>px"></div>
                        <? endif; ?>
                    </div>
                </div>
            <? endforeach; ?>

            </div>       
            <div class="clear"></div>
        <? endif; 
        endforeach;?>

    </div><!--box-->
    <? endif; ?>

<? /*** Joined groups ***/ ?>
    <? if (!empty($_s['circles'])): ?>
    <div class="box">
    
        <h3 class="title">Circles you're connected to 
        <? if (count($_s['circles']) >= 16): ?>
            <a href="#" class="view-all"
               data-type="groups"
               data-id="<?=$me['id']?>">view all...</a>
        <? endif; ?>
        </h3>
        <div class="circles">
        <?php
            $_cl['list'] = $_s['circles'];
            include(CIRCLE_LIST);
        ?>
        </div>
        <div class="clear"></div>
        
    </div><!--box-->
    <? endif; ?>

<? /*** Followers ***/ ?>
    <? if (!empty($_s['followers'])): ?>
    <div class="box">
   
        <h3 class="title">Followers 
        <? if (count($_s['followers']) >= 14): ?>
            <a class="view-all" href="#"
               data-type="followers"
               data-id="<?=$_s['user']['id']?>">view all...</a>
        <? endif; ?>
        </h3>
        <?php
            $_f['members'] = $_s['followers'];
            $fk = 'follower';
            include(FOLLOWERS);
        ?>
        <div class="clear"></div>
        
    </div><!--box-->
    <? endif; ?>

<? /*** Following ***/ ?>
    <? if (!empty($_s['following'])): ?>
    <div class="box">
    
        <h3 class="title">Following 
        <? if (count($_s['following']) >= 14): ?>
            <a class="view-all" href="#"
               data-type="following"
               data-id="<?=$_s['user']['id']?>">view all...</a>
        <? endif; ?>
        </h3>
        <?php
            $_f['members'] = $_s['following'];
            $fk = 'following';
            include(FOLLOWERS);
        ?>
        <div class="clear"></div>
        
    </div><!--box-->
    <? endif; ?>

<? /*** Involved ***/ ?>
    <? if (!empty($_s['convo']['involved'])): ?>
    <div class="box">
    
        <h3 class="title">Participants... 
        <? if (count($_s['convo']['involved']) >= 16): ?>
            <a class="view-all" href="#"
               data-type="involved"
               data-id="">view all...</a>
        <? endif; ?>
        </h3>
        <?php
            $_f['members'] = $_s['convo']['involved'];
            $_f['limit'] = 16;
            include(FOLLOWERS);
        ?>
        <div class="clear"></div>
        
    </div><!--box-->
    <? endif; ?>

<? if (isset($_s['convo'])): ?>
</div><!--wrap-->
<? endif; ?>
</div><!--sidebar-->

<div class="clear"></div>
