        <div id="sidebar">
        
        	<ul id="navigation">
            	<li class="active" id="tab-your"><a href="#">Your Feed</a></li>
                <li id="tab-circles"><a href="#">Followed Circles</a></li>
                <li id="tab-people"><a href="#">Followed People</a></li>
                <li id="tab-conversations"><a href="#">Followed Conversations</a></li>
                <li id="tab-discover" class="last"><a href="#">Discover</a></li>
            </ul>
            
            <form>
            	<input type="text" id="search" value="Search" />
            </form>
            
            <div class="box">
            
            	<h3 class="title">Circles you're connected to <a href="#" class="view-all">view all...</a></h3>
                
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_01.jpg" alt="circle" /></a>
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_02.jpg" alt="circle" /></a>
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_03.jpg" alt="circle" /></a>
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_04.jpg" alt="circle" /></a>
                
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_02.jpg" alt="circle" /></a>
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_03.jpg" alt="circle" /></a>
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_04.jpg" alt="circle" /></a>
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_01.jpg" alt="circle" /></a>
                
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_01.jpg" alt="circle" /></a>
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_02.jpg" alt="circle" /></a>
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_03.jpg" alt="circle" /></a>
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_04.jpg" alt="circle" /></a>
                
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_02.jpg" alt="circle" /></a>
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_03.jpg" alt="circle" /></a>
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_04.jpg" alt="circle" /></a>
                <a href="#" class="circle-thumb"><span class="circle"></span><img src="/static/images/circles_01.jpg" alt="circle" /></a>
                
                <div class="clear"></div>
                
            </div><!--box-->
        
        </div><!--sidebar-->

        <div class="clear"></div>
