<div id="sidebar"<?=(isset($_s['convo']) ? 'class="conversation"' : '')?><?=(isset($_s['circle']) ? 'class="side"' : '')?>>
<? if (isset($_s['convo'])): ?>
<div class="wrap">
<? endif; ?>

<? /*** Convo information box ***/ ?>
    <? if (isset($_s['convo'])): 
            $c = $_s['convo']; ?>
        <div class="box">
            
            <h3 class="username">
                <img src="<?=USER_PIC_REL.'small_'.$c['sender']['id'].'.jpg'?>" alt="<?=$c['sender']['fname']?> <?=$c['sender']['lname']?>" width="16" />
                <?=$c['sender']['uname']?>
            </h3>
            <a href="/circle/<?=$c['group']['symbol']?>" class="circle-thumb">
                <span class="circle"></span>
                <img src="<?=GROUP_PIC_REL.'medium_'.$c['group']['id'].'.jpg'?>" alt="<?=$c['group']['name']?>" />
            </a>
            <p><?=$c['text']?></p>
            
            <div class="clear"></div>
            
            <span class="stats"><?=count($c['replies'])?><small>responses</small></span>
            <span class="stats"><?=count($c['involved'])?><small>peoples involved</small></span>
            
            <div class="clear"></div>
            
            <a href="#" class="follow">Follow conversation</a>
            <a href="#" class="edit">edit</a>
            
            <div class="clear"></div>
            
        </div><!--box-->
    <? endif; ?>

<? /*** Group information box ***/ ?>
    <? if (isset($_s['circle'])):
            $c = $_s['circle'];
    ?>
    <div class="box">
        <h3 class="username"><?=$c['name']?></h3>
        <div href="#" class="circle-thumb"><span class="circle"></span><img src="<?=GROUP_PIC_REL.'medium_'.$c['id'].'.jpg'?>" class="profile-thumb" alt="thumb" /></div>
        <p><?=$c['descr']?></p>
        
        <div class="clear"></div>
        
        <span class="stats"><?=$c['messages_count']?><small>messages<br />sent</small></span>
        <span class="stats"><?=$c['responses_count']?><small>responses<br />received</small></span>
        <span class="stats"><?=$c['members_count']?><small>users<br />joined</small></span>
        
        <div class="clear"></div>
        
        <a href="#" class="follow">Follow circle</a>
        <a href="#" class="edit">edit</a>
        
        <div class="clear"></div>
        
    </div><!--box-->
    <? endif; ?>
    
<? /*** User information box ***/ ?>
    <? if (isset($_s['user'])):
            $u = $_s['user'];
    ?>
    <div class="box">
        
        <h3 class="username"><span class="<?=($u['online'] ? 'online' : 'offline')?>"><?=$u['uname']?></span>
        <small><?=$u['fname']?> <?=$u['lname']?></small></h3>
        <img src="<?=USER_PIC_REL.'medium_'.$u['id'].'.jpg'?>" class="profile-thumb" alt="<?=$u['uname']?>'s avatar" />
        <p>Random description of the
        channel. Could be very short</p>
        
        <div class="clear"></div>
        
        <span class="stats"><?=$u['stats']['messages']?><small>messages<br />sent</small></span>
        <span class="stats"><?=$u['stats']['responses']?><small>responses<br />received</small></span>
        <span class="stats"><?=$u['stats']['groups']?><small>circles<br />joined</small></span>
        
        <div class="clear"></div>
        
        <a href="#" class="follow">Follow</a>
        <a href="#" class="pm">Send PM</a>
        
        <div class="clear"></div>
        
    </div><!--box-->
    <? endif; ?>

<? /*** Navigation menu***/ ?>
    <? if ($_s['show_nav']): ?>
    <ul id="navigation">
        <li class="active" id="tab-your"><a href="#">Your Feed</a></li>
        <li id="tab-circles"><a href="#">Followed Circles</a></li>
        <li id="tab-people"><a href="#">Followed People</a></li>
        <li id="tab-conversations"><a href="#">Followed Conversations</a></li>
        <li id="tab-discover" class="last"><a href="#">Discover</a></li>
    </ul>
    <? endif; ?>
    
<? /*** Search bar ***/ ?>
    <form>
        <input type="text" id="search" value="Search" />
    </form>

<? /*** Group members ***/ ?>
    <? if (isset($_s['members'])): ?>
    <div class="box">
    
        <h3 class="title">Circle members <a class="view-all" href="#">view all...</a></h3>
        <?php
            $_f['members'] = $_s['members'];
            include(FOLLOWERS);
        ?>
        <div class="clear"></div>
        
    </div><!--box-->
    <? endif; ?>


<? /*** Joined groups ***/ ?>
    <? if (!empty($_s['circles'])): ?>
    <div class="box">
    
        <h3 class="title">Circles you're connected to <a href="#" class="view-all">view all...</a></h3>
        <?php
            $_cl['list'] = $_s['circles'];
            include(CIRCLE_LIST);
        ?>
        <div class="clear"></div>
        
    </div><!--box-->
    <? endif; ?>

<? /*** Followers ***/ ?>
    <? if (!empty($_s['followers'])): ?>
    <div class="box">
   
        <h3 class="title">Followers <a class="view-all" href="#">view all...</a></h3>
        <?php
            $_f['members'] = $_s['followers'];
            include(FOLLOWERS);
        ?>
        <div class="clear"></div>
        
    </div><!--box-->
    <? endif; ?>

<? /*** Following ***/ ?>
    <? if (!empty($_s['following'])): ?>
    <div class="box">
    
        <h3 class="title">Following <a class="view-all" href="#">view all...</a></h3>
        <?php
            $_f['members'] = $_s['following'];
            include(FOLLOWERS);
        ?>
        <div class="clear"></div>
        
    </div><!--box-->
    <? endif; ?>

<? /*** Involved ***/ ?>
    <? if (!empty($_s['convo']['involved'])): ?>
    <div class="box">
    
        <h3 class="title">People invovled in this conversation <a class="view-all" href="#">view all...</a></h3>
        <?php
            $_f['members'] = $_s['convo']['involved'];
            include(FOLLOWERS);
        ?>
        <div class="clear"></div>
        
    </div><!--box-->
    <? endif; ?>

<? /*** Stream actions ***/?>
    <? if (isset($_s['convo'])): ?>
        <div class="latest-reply">
            <img src="/static/images/comments_avatar.jpg" alt="avatar" class="avatar-reply" />
            <a href="#" class="reply-author">Guest209t7</a><span>is typing</span>
            <div class="clear"></div>
        </div><!--latest-->
        
        <div class="latest-reply">
            <img src="/static/images/comments_avatar.jpg" alt="avatar" class="avatar-reply" />
            <a href="#" class="reply-author">Guest209t7</a><span>is yawning</span>
            <div class="clear"></div>
        </div><!--latest-->
        
        <div class="latest-reply">
            <img src="/static/images/comments_avatar.jpg" alt="avatar" class="avatar-reply" />
            <a href="#" class="reply-author">Guest209t7</a><span>is yaying</span>
            <div class="clear"></div>
        </div><!--latest-->
    <? endif; ?>

<? if (isset($_s['convo'])): ?>
</div><!--wrap-->
<? endif; ?>
</div><!--sidebar-->

<div class="clear"></div>
