<?php
$r = $_SERVER['REQUEST_URI'];
$c = 'class="current"';

switch($r){
        case '/':       $home =  $c;break;
        case '/channels':   $groups =  $c;break;
        case '/people':  $people=  $c;break;
        case '/settings':   $settings =  $c;break;
}
?>


  <div id="header" class="container">
                        <div id="slim-background"></div>

                        <div id="nav" class="nav-slim">
                                <a href="/"  	    <?=$home?>    >home</a>
                                <a href="/channels"   <?=$groups?>  >channels</a>
                                <a href="/people"   <?=$people?>  >people</a>
                                <a href="/settings" <?=$settings?>>settings</a>
                                <?php if ($logged): ?>
								<a href="/?logout=true">logout</a> <? echo $_t['ok_user']; ?>
                                <?php else: ?>
                                <a href="/signup">create account</a>
                                <?php endif; ?>
                        </div>

                        <div id="logo" class="logo-slim">
                                <a href="/"></a>
                        </div>

                        <div id="searchbar" class="searchbar-slim"> 
                                <div id="searchover" class="searchover-slim">Start or Join a conversation</div>
                                <input id="search" type="text" class="basic" style="padding: 3px; font-size: 10px; width: 250px;" autocomplete="off">
                                <div id="searchsuggest">
                                        <ul>
                                        </ul>
                                </div>
                        </div>
                </div>

