<ul id="taps" class="stream <?= empty($_taps) ? "empty" : "" ?>">
    <?php if (isset($show_less)): ?>
            <li id="loadless" class="paginator">
                <p>&#9650;</p>
            </li>
    <?php endif; ?>
<?php
if (!empty($_taps)):
    foreach ($_taps as $tap):
        $show_resp = isset($show_responses) && isset($tap['responses']);
?>
        <li id="tid_<?= $tap['cid'] ?>" class="container"
            data-id="<?= $tap['cid'] ?>"
            data-uid="<?= $tap['uid'] ?>"
            data-user="<?= $tap['uname'] ?>"
            data-private="<?= $tap['private'] ?>">
            <a href="/user/<?= $tap['uname'] ?>">
                <img class="avatar" alt="<?= $tap['uname'] ?>"
                     src="/user_pics/<?= $tap['pic_100'] ?>"/>
            </a>

            <p class="tap-from <?= ($tap['user_online'] || $tap['uname'] == $_SESSION['uname']) ? '" title="online"' : 'offline' ?>">
                <a href="/user/<?= $tap['uname'] ?>"><?= trim($tap['uname'])?></a>
                <? if ($tap['private'] == 1): ?>
                    <span style="font-size:16px">&#x279e;</span> <a href="/user/<?= $tap['to_uname'] ?>"><?= $tap['to_uname'] ?></a>
                <? endif; ?>
                ,
                <a href="/tap/<?= $tap['cid'] ?>" class="date"
                   data-timestamp="<?= $tap['chat_timestamp_raw'] ?>">
                <?= $tap['chat_timestamp'] ?>
                </a>

                <? if ($tap['private'] != 1): ?>
                    <a href="/channel/<?= $tap['symbol'] ?>">
                        <img class="aggr-favicons" src="/group_pics/<?= $tap['favicon'] ?>" title="<?= $tap['gname'] ?>" />
                    </a>
                <? else: ?>
                    <a href="/user/<?= $tap['to_uname'] ?>">
                        <img class="aggr-favicons" src="/user_pics/<?= $tap['to_pic_100'] ?>" title="<?= $tap['to_real_name'] ?>" style="height: 30px; width: 30px" />
                    </a>
                <? endif; ?>
            </p>

            <a href="#" class="tap-resp-count" title="view responses">
                <p class="tap-body">
                <?= $tap['chat_text'] ?>
                </p>
            </a>

            <p class="tap-actions">
                <span class="last-resp">
                    <strong><?= (!empty($tap['resp_uname'])) ? $tap['resp_uname'] . ":" : "" ?></strong>
                    <span class="inblock"><?= $tap['last_resp'] ?></span>
                </span>
                <span class="tap-resp">
                    <span class="indicator">Someone's replying..</span>
                </span>
                <a href="#" class="tap-resp-count" title="view responses">
                    <span class="show-resp-count"><?= $tap['count'] ?></span>
                    <span class="follow_button"<? echo ($show_resp ? "style='display: none'" : '') ?>>Reply</span>
                </a>
            </p>

            <div class="responses<? /*echo ($show_resp ? ' open' : '')*/ ?>">
                <ul class="chat"<? echo ($show_resp ? "style='height: 350px'" : '') ?>>
                <?php
                    if ($show_resp):
                        foreach($tap['responses'] as $resp):
                ?>
                    <li>
                        <em data-timestamp="<?= $resp['chat_time_raw'] ?>"><?= $resp['chat_time'] ?></em>
                        <a href="/user/<?= $resp['uname'] ?>" class="user">
        					<img src="/user_pics/<?= $resp['small_pic'] ?>" />
		        			<span class="resp-uname"><?= $resp['uname'] ?>:</span>
                        </a>
				         <span class="resp-text"><?= $resp['chat_text'] ?></span>
                    </li>
                <?php
                        endforeach;
                    endif;
                ?>
                </ul>
                <input class="chatbox" type="text"/>

                <div class="resizer"></div>

                <div class="counter">240</div>
                <div class="overlay">type in your response and press enter.</div>
            </div>
        </li>
<?php endforeach; ?>
    <?php if (!isset($dont_show_more) && count($_taps) >= 10): ?>
            <li id="loadmore" class="paginator">
                <p>&#9660;</p>
            </li>
    <?php endif; ?>
<?php else: ?>
        <li id="no-taps-yet" class="notice">
            <p>Nothing yet! Try tapping this feed...</p>
        </li>
<?php
endif;
?>
</ul>
