<!-- Title + description -->
<div id="title-desc-tooltip">
  <div id="tooltip-<#: this.id #>" class="tooltip-title-desc">
    <h2><#: this.title #></h2>
    <div class="tooltip-content"><#: this.content #></div>
  </div>
</div>

<!-- Follow Tooltip -->
<div id="follow-tooltip">
  <div id="tooltip-<#: this.id #>" class="tooltip-follow">
    <h2><#: this.title #></h2>
  </div>
</div>

<!-- Name Tooltip -->
<div id="name-tooltip">
  <div id="tooltip-<#: this.id #>" class="tooltip-name">
    <h2><#: this.title #></h2>
  </div>
</div>

<!-- Side Tooltip -->
<div id="side-tooltip">
  <div id="tooltip-<#: this.id #>" class="side-follow">
    <h2><#: this.title #></h2>
  </div>
</div>