<div id="you" class="section container">
					<a href="/user/<?= $_SESSION['uname'] ?>">
                                        <img src="/user_pics/<?= $_SESSION['upic'] ?>" class="avatar" />
                                        <span style="font-size:14px;"><p>hello <strong><?= $_SESSION['uname'] ?></strong>!</p></span>
					</a>	
                                        <p class="special">
                                                <a href="/invite" title="Invite your friends to tap">- invite people -</a>
                                        </p>
										<p>
											<? if ($_SESSION['guest'] == 1) { ?>
                                                <a href="/signup">sign up</a>
												<a href="/?logout=true">log in</a>
											<? } else { ?>
                                                <a href="/user/<?= $_SESSION['uname'] ?>">profile</a>
                                                <a href="/settings">settings</a>
												<a href="/?logout=true">logout</a>
											<? } ?>
                                        </p>
                                </div>
