<div id="top">

		<div id="small_logo"><img src="images/chatapist2.gif" alt="logo-small" /></div>
		
		<div id="drop_down"><span id="drop_down_link"><a href="#a">Sign Out</a></span></div>
	
		<div id="top_links">
		
			<ul>
				<li><a href="#">Search/Post</a></li>
				<li><a href="##">Network</a></li>
				<li><a href="#####">Messages</a></li>
				<li><a href="#####">Relevancy Settings</a></li>
			</ul>
			
		
		</div>
	
	</div>
	