<div id="left">

		<div id="left_nav">
		
			<ul>
				<li><a href="#$">Profile</a></li>
				<li><a href="#$">Account</a></li>
				<li><a href="#$###$#">Logs</a></li>
				<li><a href="#$####">Network</a></li>
				<li><a href="#$####">Groups</a></li>
				<li><a href="#$####">Relevancy Settings</a></li>
				<li><a href="#$#">Search People</a></li>
				<li><a href="##">Account Settings</a></li>
			</ul>
		
		</div>
		
		
		<div id="alert_nav">
		
		<h4>Alerts:</h4>
		
			<p>
			Hello and welcome to chatapist, every time you login and while you're on the system chatapist checks for alerts
			and makes sure that there are matches to what you know about.  Alerts will show up here if something you know about
			is posted!  Keep an eye out, enjoy!
			</p>
			
		</div>

	
	</div>
	